objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Externe Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <formula>TEXT(Opportunity__r.Sales_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vertriebstyp</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <formula>Opportunity__r.Vehicle_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fahrzeughersteller</label>
        <type>Text</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Korrespondenzen</relationshipLabel>
        <relationshipName>Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Auftragstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assignment_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auto_Follow_up_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Anzahl Auto-Follow-ups</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Has_Legal_Protection_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rechtsschutzversicherung vorhanden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Versicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Lebensversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Versicherung)</relationshipLabel>
        <relationshipName>Opportunities_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <defaultValue>"Online"</defaultValue>
        <label>Vertriebstyp</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sales_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fahrzeughersteller</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Fahrzeughersteller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Fahrzeughersteller)</relationshipLabel>
        <relationshipName>Opportunities_Fahrzeughersteller</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

globalValueSets/Assignment_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Share</fullName>
    </customValue>
    <customValue>
        <fullName>Direkt</fullName>
    </customValue>
    <customValue>
        <fullName>50%</fullName>
        <isActive>false</isActive>
        <label>50%</label>
    </customValue>
    <customValue>
        <fullName>RSV 20%</fullName>
        <isActive>false</isActive>
        <label>RSV 20%</label>
    </customValue>
    <masterLabel>Assignment Types</masterLabel>
</GlobalValueSet>

globalValueSets/Sales_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
        <default>true</default>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <masterLabel>Sales Types</masterLabel>
</GlobalValueSet>

classes/CorrPerformanceClaimTest.cls
@isTest
public class CorrPerformanceClaimTest {
    public static Opportunity createOpp(Id accountId, String stageName) {
		Account vehicleBrand = new Account(
			Name = 'TestVehicleBrand',
			Type = 'Fahrzeughersteller'
		);
		insert vehicleBrand;
        Opportunity opp = new Opportunity(
            Name = 'TestOpportunity',
            AccountId = accountId,
            CloseDate = System.today(),
            StageName = stageName,
            Sent_Mail_Flag_1__c = true,
            Sent_Mail_Flag_2__c = true,
            Assignment_Type__c = 'RSV',
			Has_Legal_Protection_Insurance__c = true,
            Auto_Follow_up_Count__c = 0,
			Sales_Type__c = 'Online',
			Vehicle_Brand__c = vehicleBrand.Id
        );
        return opp;
    }

    @isTest
    private static void testNoInsurance() {
        Account a = TestData.createAccount();
        a.name = 'Bla';
        insert a;
        Opportunity o = createOpp(a.ID, 'On Hold');
        o.Assignment_Type__c = 'RSV';
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrPerformanceClaim oe = new CorrPerformanceClaim(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(Errors.page('Es muss eine Versicherung auf der Anfrage vorhanden sein.').getUrl(), pr.getUrl());
    }

    @isTest
    private static void testWrongInsurance() {
        Account a = TestData.createAccount();
        a.Type = 'Lebensversicherung';
        a.name = 'Bla';
        insert a;
        Opportunity o = createOpp(a.ID, 'On Hold');
        o.Assignment_Type__c = 'RSV';
        o.Insurance__c = a.Id;
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrPerformanceClaim oe = new CorrPerformanceClaim(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(Errors.page('Diese Aktion kann nur mit der Versicherung "Clerical Medical Investment Group Limited" ausgeführt werden.').getUrl(), pr.getUrl());
    }

    @isTest
    private static void testCorrectInsurance() {
        Account a = TestData.createAccount();
        a.Type = 'Lebensversicherung';
        a.name = 'Bla';
        a.External_Id__c = 'lv004';
        insert a;
        Opportunity o = createOpp(a.ID, 'On Hold');
        o.Assignment_Type__c = 'RSV';
        o.Insurance__c = a.Id;
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrPerformanceClaim oe = new CorrPerformanceClaim(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(Page.SuccessPage.getUrl(), pr.getUrl());
    }
}