objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Externe Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Process_Type__c</fullName>
        <defaultValue>'Internal'</defaultValue>
        <label>Legal Process Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Legal_Process_Types</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Opportunity__r.Account_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unternehmen</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount_In_Dispute__c</fullName>
        <formula>Opportunity__r.Amount_In_Dispute__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aktueller Streitwert</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Form_Hash_1__c</fullName>
        <label>Form Hash 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lawsuit_Date__c</fullName>
        <label>Datum Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for legal process parts.</description>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Legal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <formula>TEXT(Opportunity__r.Sales_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vertriebstyp</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Web Form Token</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Korrespondenzen</relationshipLabel>
        <relationshipName>Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Titel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Partner</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Partners</valueSetName>
        </valueSet>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Rechnungen</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Object for storing and managing invoices towards customers.</description>
    <label>Rechnung</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rechnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_In_Dispute_Clean__c</fullName>
        <label>Amount In Dispute Clean</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount_In_Dispute__c</fullName>
        <formula>IF(RecordTypeId = '0121t000000DzR3',IF(ISPICKVAL(Process_Type__c,'DG_Keep'),Claim_For_Compensation__c,Purchase_Price__c-Compensation_For_Use__c ),IF(RecordTypeId = '0121t000000DzR4',Paid_Installments__c + Advance_Payment__c + Future_Savings__c + Final_Installment__c,Paid_Up_Contributions__c - Amounts_Received__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Streitwert</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Auftragstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assignment_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Callcenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for call center process parts.</description>
        <label>Callcenter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Callcenter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compensation_For_Use_Clean__c</fullName>
        <label>Compensation For Use Clean</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Compensation_For_Use__c</fullName>
        <formula>Purchase_Price__c * ((Current_Mileage__c - Mileage_On_Purchase__c) / Expected_Mileage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nutzungsentschädigung</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Confirmed_Terms_And_Conditions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AGB bestätigt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Form_Hash_1__c</fullName>
        <label>Form Hash 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Has_Legal_Protection_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rechtsschutzversicherung vorhanden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Process_Type__c</fullName>
        <defaultValue>'Internal'</defaultValue>
        <label>Anwaltsprozess</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Legal_Process_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Protection_Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rechtsschutzversicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Rechtsschutzversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Rechtsschutzversicherung)</relationshipLabel>
        <relationshipName>Opportunities_Legal_Protection_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Id__c</fullName>
        <label>Partner Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Partner)</relationshipLabel>
        <relationshipName>Opportunities_Partner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Type__c</fullName>
        <label>Anspruchstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Process_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purchase_Price_Clean__c</fullName>
        <label>Purchase Price Clean</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Price__c</fullName>
        <label>Kaufpreis</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reason_For_Loss__c</fullName>
        <label>Absagegrund</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reasons_For_Loss</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <defaultValue>"Online"</defaultValue>
        <label>Vertriebstyp</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sales_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Set_To_Check_Date__c</fullName>
        <label>Set To Check Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Set_To_Claim_Date__c</fullName>
        <label>Set To Claim Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Set_To_Lost_Date__c</fullName>
        <label>Set To Lost Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Set_To_New_Date__c</fullName>
        <label>Set To New Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Set_To_On_Hold_Date__c</fullName>
        <label>Set To On Hold Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Web form token</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <businessProcess>Finanzierung</businessProcess>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Assignment_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Share</fullName>
    </customValue>
    <customValue>
        <fullName>Direkt</fullName>
    </customValue>
    <customValue>
        <fullName>50%</fullName>
        <isActive>false</isActive>
        <label>50%</label>
    </customValue>
    <customValue>
        <fullName>RSV 20%</fullName>
        <isActive>false</isActive>
        <label>RSV 20%</label>
    </customValue>
    <masterLabel>Assignment Types</masterLabel>
</GlobalValueSet>

globalValueSets/Correspondence_Partners.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Insurance</fullName>
        <label>Versicherung</label>
    </customValue>
    <customValue>
        <fullName>Vehicle Brand</fullName>
        <label>Fahrzeughersteller</label>
    </customValue>
    <customValue>
        <fullName>Bank</fullName>
        <label>Kreditinstitut</label>
    </customValue>
    <customValue>
        <fullName>Legal Protection Insurance</fullName>
        <label>Rechtsschutzversicherung</label>
    </customValue>
    <customValue>
        <fullName>Court</fullName>
        <label>Gericht</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
        <label>Kunde</label>
    </customValue>
    <customValue>
        <fullName>Individuell</fullName>
    </customValue>
    <masterLabel>Correspondence Partners</masterLabel>
</GlobalValueSet>

globalValueSets/Legal_Process_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Internal</fullName>
        <label>Intern</label>
    </customValue>
    <customValue>
        <fullName>External</fullName>
        <label>Extern</label>
    </customValue>
    <masterLabel>Legal Process Types</masterLabel>
</GlobalValueSet>

globalValueSets/Process_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>LV_Opposition</fullName>
        <label>Widerspruch</label>
    </customValue>
    <customValue>
        <fullName>LV_Compensation</fullName>
        <label>Schadenersatz</label>
    </customValue>
    <customValue>
        <fullName>LV_Performance</fullName>
        <label>Erfüllungsanspruch</label>
    </customValue>
    <customValue>
        <fullName>DG_Return</fullName>
        <label>Rückgabe</label>
    </customValue>
    <customValue>
        <fullName>DG_Keep</fullName>
        <label>Behalten</label>
    </customValue>
    <customValue>
        <fullName>DG_Don&apos;t Know</fullName>
        <label>Unentschlossen</label>
    </customValue>
    <masterLabel>Process Types</masterLabel>
</GlobalValueSet>

globalValueSets/Reasons_For_Loss.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Nicht im Zeitraum</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde möchte nicht wegen Preis</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde will nicht</fullName>
    </customValue>
    <customValue>
        <fullName>Widerruf nicht angreifbar</fullName>
    </customValue>
    <customValue>
        <fullName>Potential zu gering</fullName>
    </customValue>
    <customValue>
        <fullName>Kein wirtschaftliches Potential</fullName>
    </customValue>
    <customValue>
        <fullName>Dokumente nicht geschickt</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde hat widerrufen</fullName>
    </customValue>
    <customValue>
        <fullName>Auto verkauft</fullName>
    </customValue>
    <customValue>
        <fullName>Fahrzeug nicht betroffen</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde nicht Käufer</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde nicht erreichbar</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde verstorben</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde hat keine RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Leasing Vertrag</fullName>
    </customValue>
    <customValue>
        <fullName>Keine Widerrufsbelehrung</fullName>
    </customValue>
    <customValue>
        <fullName>BMW EZ nach 01.06.2014</fullName>
    </customValue>
    <customValue>
        <fullName>Darlehensvertrag älter als 2 Jahre</fullName>
    </customValue>
    <customValue>
        <fullName>Nutzungsanteil zu gering</fullName>
    </customValue>
    <customValue>
        <fullName>Kapital zu gering</fullName>
    </customValue>
    <customValue>
        <fullName>Österreich/Schweiz kleiner Motor</fullName>
    </customValue>
    <customValue>
        <fullName>Umrüstung erfolgt</fullName>
    </customValue>
    <customValue>
        <fullName>Mfk nicht bestätigt</fullName>
    </customValue>
    <customValue>
        <fullName>Effektiver Jahreszins 0,00%</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstige Gründe</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstige Gründe (ohne Mail)</fullName>
    </customValue>
    <customValue>
        <fullName>Aussortiert</fullName>
    </customValue>
    <customValue>
        <fullName>Absage wegen Kenntnis</fullName>
    </customValue>
    <masterLabel>Reasons For Loss</masterLabel>
</GlobalValueSet>

globalValueSets/Sales_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
        <default>true</default>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <masterLabel>Sales Types</masterLabel>
</GlobalValueSet>

classes/OpportunitiesTests.cls
@isTest
public class OpportunitiesTests {
    @isTest
    private static void testRecordTypes() {
        System.assert(!Opportunities.isDieselSkandal(null));
        System.assert(!Opportunities.isFinanzierung(null));
        System.assert(!Opportunities.isLebensversicherung(null));
            
        Account a = TestData.createAccount();
        insert a;
        Opportunity o = TestData.createOpportunity(a.ID, 'On Hold');
        
        // DK
        RecordType rt = [
            SELECT ID
            FROM RecordType
            WHERE DeveloperName = 'Dieselskandal' AND SObjectType = 'Opportunity'
        ];
        o.recordTypeId = rt.ID;
        insert o;
        
        o = [SELECT RecordTypeID FROM Opportunity];
        System.assert(Opportunities.isDieselSkandal(o.recordTypeID));
        System.assert(!Opportunities.isFinanzierung(o.recordTypeID));
        System.assert(!Opportunities.isLebensversicherung(o.recordTypeID));
        
        // FZ
        rt = [
            SELECT ID
            FROM RecordType
            WHERE DeveloperName = 'Finanzierung' AND SObjectType = 'Opportunity'
        ];
        o.recordTypeId = rt.ID;
        update o;
        
        o = [SELECT RecordTypeID FROM Opportunity];
        System.assert(!Opportunities.isDieselSkandal(o.recordTypeID));
        System.assert(Opportunities.isFinanzierung(o.recordTypeID));
        System.assert(!Opportunities.isLebensversicherung(o.recordTypeID));
        
        // LV
        rt = [
            SELECT ID
            FROM RecordType
            WHERE DeveloperName = 'Lebensversicherung' AND SObjectType = 'Opportunity'
        ];
        o.recordTypeId = rt.ID;
        update o;
        
        o = [SELECT RecordTypeID FROM Opportunity];
        System.assert(!Opportunities.isDieselSkandal(o.recordTypeID));
        System.assert(!Opportunities.isFinanzierung(o.recordTypeID));
        System.assert(Opportunities.isLebensversicherung(o.recordTypeID));
    }

    @isTest
    private static void testCreateAccountOnInsert() {
        Opportunity o1 = TestData.createOpportunity(null, 'On Hold');
        o1.name = 'o1';
        Opportunity o2 = TestData.createOpportunity(null, 'On Hold');
        o2.name = 'o2';
        insert new Opportunity[]{o1, o2};

		Opportunity[] oo = [SELECT Name, Account.ID, Account.Name FROM Opportunity];
        for (Opportunity o: oo) {
            System.assertEquals(o.name, o.account.name);
            System.assertNotEquals(null, o.account.ID);
        }

        // Opps with the same name are not treated correctly currently, they all use the last account created  
        Opportunity o3 = TestData.createOpportunity(null, 'On Hold');
        o3.name = 'o3';
        Opportunity stillO3 = TestData.createOpportunity(null, 'On Hold');
        stillO3.name = 'o3';
        insert new Opportunity[] { o3, stillO3 };

		oo = [SELECT Name, Account.ID, Account.Name FROM Opportunity WHERE Name = 'o3'];
        String aName = oo[0].account.name;
        for (Opportunity o: oo) {
            System.assertEquals(aName, o.account.name);
            System.assertNotEquals(null, o.account.ID);
        }
    }

    @isTest
    private static void testSetDateStampOnInsertAndUpdate() {
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;    
        }
        Opportunity o1 = TestData.createOpportunity(null, 'On Hold');
        o1.name = 'o1';
        o1.Callcenter__c = u.Id;
        Opportunity o2 = TestData.createOpportunity(null, 'Lost');
        o2.name = 'o2';
        o2.reason_for_loss__c = 'Potential zu gering';
        insert new Opportunity[]{o1, o2};

        Opportunity[] oo = [SELECT Name, Set_To_On_Hold_Date__c, Set_To_Lost_Date__c FROM Opportunity];
        for (Opportunity o: oo) {
            if (o.name == 'o1') {
                System.assertEquals(Date.today(), o.set_To_On_Hold_Date__c);
                continue;
            }
            
            if (o.name == 'o2') {
                System.assertEquals(Date.today(), o.set_To_Lost_Date__c);
                continue;
            }
        }
        
        // Update
        o1.stageName = 'Claim';
        o1.backoffice__c = u.ID;
        o2.stageName = 'Check';
        o2.backoffice__c = u.ID;
        
        Test.startTest();
        update new Opportunity[]{o1, o2};
		Test.stopTest();
        
        oo = [SELECT Name, Set_To_Claim_Date__c, Set_To_Check_Date__c FROM Opportunity];
        for (Opportunity o: oo) {
            if (o.name == 'o1') {
                System.assertEquals(Date.today(), o.set_To_Claim_Date__c);
                continue;
            }
            
            if (o.name == 'o2') {
                System.assertEquals(Date.today(), o.set_To_Check_Date__c);
                continue;
            }
        }
        
        o1.stageName = 'New';
        update o1;
        oo = [SELECT Name, set_To_Check_Date__c, Set_To_New_Date__c FROM Opportunity];
        for (Opportunity o: oo) {
            if (o.name == 'o1') {
                System.assertEquals(Date.today(), o.set_To_New_Date__c);
                continue;
            }
            
            if (o.name == 'o2') {
                System.assertEquals(Date.today(), o.set_To_Check_Date__c);
                continue;
            }
        }        
    }
    
    @isTest
    public static void testSetUniqueID() {
        Opportunity o = TestData.createOpportunity(null, 'On Hold');
        insert o;
        
        o = [SELECT Id, Token__c FROM Opportunity WHERE Id = :o.Id];
        
        System.assert(o.Token__c != null);
    }
    
    @isTest
    private static void testSetAssignmentTypeOnInsertAndUpdate() {
        Opportunity o1 = TestData.createOpportunity(null, 'On Hold');
        o1.name = 'o1';
        Account a = TestData.createLegalProtection();
        insert a;
        o1.assignment_Type__c = null;
        o1.Legal_Protection_Insurance__c = a.ID;

        Opportunity o2 = TestData.createOpportunity(null, 'Lost');
        o2.name = 'o2';
        o2.reason_for_loss__c = 'Potential zu gering';
        o2.confirmed_Terms_And_Conditions__c = true;
        o2.assignment_Type__c = null;
        o2.has_Legal_Protection_Insurance__c = false;

        Opportunity o3 = TestData.createOpportunity(null, 'On Hold');
        o3.name = 'o3';
        o3.legal_Protection_Insurance__c = null;
        o3.confirmed_Terms_And_Conditions__c = true;
        o3.assignment_Type__c = null;
        o3.has_Legal_Protection_Insurance__c = true;
        insert new Opportunity[]{o1, o2, o3};

        Opportunity[] oo = [
            SELECT  Name,
                    Has_Legal_Protection_Insurance__c,
                    Assignment_Type__c 
            FROM Opportunity
        ];
        for (Opportunity o: oo) {
            if (o.name == 'o1') {
                System.assert(o.has_Legal_Protection_Insurance__c);
                System.assertEquals('RSV', o.assignment_Type__c);
                continue;
            }
            if (o.name == 'o2') {
                System.assertEquals('Share', o.assignment_Type__c);
                continue;
            }
            if (o.name == 'o3') {
                System.assertEquals('RSV', o.assignment_Type__c);
                continue;
            }
        }
    }
    
    @isTest
    private static void testSetHashOnInsertAndUpdate() {
        Opportunity o = TestData.createOpportunity(null, 'On Hold');
        insert o;
        
        Opportunity[] oo = [SELECT Form_Hash_1__c FROM Opportunity];
        System.assert(!oo.isEmpty());
        System.assert(String.isNotBlank(oo[0].form_Hash_1__c));
        
        // Updated
        oo[0].form_Hash_1__c = null;
        update oo;
        
        oo = [SELECT Form_Hash_1__c FROM Opportunity];
        System.assert(!oo.isEmpty());
        System.assert(String.isNotBlank(oo[0].form_Hash_1__c));
    }
    
    
    @isTest
    private static void testSetLegalUsersOnInsertAndUpdate() {
        Opportunity o = TestData.createOpportunity(null, 'On Hold');
        o.recordTypeID = Opportunities.finanzierungRecordType();
        o.sales_Type__c = 'Online';
        insert o;

        o = [SELECT Legal__c FROM Opportunity];
        // System.assertEquals(Users.kainzLegal(), o.legal__c);
        
        // Update
        // LV
        o.legal__c = null;
        o.recordTypeId = Opportunities.lebensversicherungRecordType();
        update o;

        o = [SELECT Legal__c FROM Opportunity];
        //System.assertEquals(Users.JHeinrichLegal(), o.legal__c);
        
        // DG
        o.legal__c = null;
        o.recordTypeId = Opportunities.dieselSkandalRecordType();
        update o;

        o = [SELECT Legal__c FROM Opportunity];
        // System.assertEquals(Users.lachmairLegal(), o.legal__c);

        Account a = TestData.createVH24Account();
        insert a;
        o.account__c = a.ID;
        update o;

        o.legal__c = null;
        update o;
        
        o = [SELECT Legal__c FROM Opportunity];
       // System.assertEquals(Users.kainzLegal(), o.legal__c);
    }
    
    
    @isTest
    private static void testSetLegalAccountOnInsertAndUpdate() {
        Account a = TestData.createAccount();
        insert a;

        User u = TestData.legalUser();
        u.account_Id__c = a.ID;
        System.runAs(TestData.bypassUser()) {
            insert u;
        }

        Opportunity o = TestData.createOpportunity(null, 'On Hold');
        o.legal__c = u.ID;
        o.legal_Account__c = null;
        insert o;
        
        o = [SELECT Legal_Account__c FROM Opportunity];
        //System.assertEquals(a.ID, o.legal_Account__c);
        
        // Update
        o.legal__c = null;
        update o;

        // Legal will be set before LegalAccount is
        u = [SELECT Account_Id__c FROM User WHERE ID = :Users.lachmairLegal()];
        o = [SELECT Legal_Account__c FROM Opportunity];
        //System.assertEquals(u.account_Id__c, o.legal_Account__c);
    }
    
    @isTest
    private static void testSetPartnerOnInsert() {
        Account a = TestData.createAccount();
        a.external_Id__c = '119289';
        insert a;

        Opportunity o = TestData.createOpportunity(null, 'On Hold');
        o.partner_Id__c = a.external_Id__c;
        o.partner__c = null;
        insert o;
        
        o = [SELECT Partner__c FROM Opportunity];
        System.assertEquals(a.ID, o.partner__c);
    }
    
    @isTest
    private static void testSetLegalProcessTypeOnInsertAndUpdate() {
        Account a = TestData.createAccount();
        a.legal_Process_Type__c = 'Internal';
        insert a;

        Opportunity o = TestData.createOpportunity(null, 'On Hold');
        o.legal_Account__c = a.ID;
        insert o;
        
        o = [SELECT Legal_Process_Type__c FROM Opportunity];
        System.assertEquals(a.legal_Process_Type__c, o.legal_Process_Type__c);
        
        // Update
        o.legal_Account__c = null;
        update o;
        
        // Changes nothing
        o = [SELECT Legal_Process_Type__c FROM Opportunity];
        System.assertEquals(a.legal_Process_Type__c, o.legal_Process_Type__c);
    }
    
    @isTest
    private static void testSetDecimalFieldsOnInsertAndUpdate() {
        Opportunity o = TestData.createOpportunity(null, 'On Hold');
        // todo: too much setup, a lot of formula fields
        // o.amount_In_Dispute__c = 1200;
        // o.compensation_For_Use__c = 1200;
        o.purchase_Price__c = 1200;
        insert o;
        
        o = [
            SELECT Amount_In_Dispute_Clean__c,
            Compensation_For_Use_Clean__c,
            Purchase_Price_Clean__c
            FROM Opportunity
        ];
        System.assert(!String.isBlank(o.amount_In_Dispute_Clean__c));
        System.assert(!String.isBlank(o.compensation_For_Use_Clean__c));
        System.assertEquals('1.200,00 €', o.purchase_Price_Clean__c);
        
        // Update
        o.purchase_Price__c = 1300;
        update o;
        
        o = [
            SELECT  Amount_In_Dispute_Clean__c,
                    Compensation_For_Use_Clean__c,
                    Purchase_Price_Clean__c
            FROM Opportunity
        ];
        System.assertEquals('1.300,00 €', o.purchase_Price_Clean__c);
    }

    
    @isTest
    private static void testCreateObjectsCorrespondenceKeep() {
	    TriggerConfiguration.allInactive = true;

        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;    
        }
        
        Opportunity o = TestData.createOpportunity(null, 'Check');
        o.backoffice__c = u.ID;
        o.confirmed_Terms_And_Conditions__c = true;
        o.legal__c = u.ID;
        o.assignment_Type__c = 'RSV';
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Lawsuit_Date__c = System.today()
        );
        insert c;

        Correspondence__c[] crr = [
            SELECT ID FROM Correspondence__c
            WHERE Description__c = 'Wechsel Anspruchstyp zu "Behalten"'
        ];
        System.assertEquals(0, crr.size());
        
        // Update
        o.stageName = 'Claim';
        o.Process_Type__c = 'DG_Keep';
        update o;
		TriggerConfiguration.allInactive = false;
        crr = [
            SELECT ID FROM Correspondence__c
            WHERE Description__c = 'Wechsel Anspruchstyp zu "Behalten"'
        ];
        System.assertEquals(0, crr.size());
    }

    @isTest
    private static void testCreateObjectsCorrespondenceReturn() {
	    TriggerConfiguration.allInactive = true;

        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;    
        }
        
        Opportunity o = TestData.createOpportunity(null, 'Check');
        o.backoffice__c = u.ID;
        o.confirmed_Terms_And_Conditions__c = true;
        o.legal__c = u.ID;
        o.assignment_Type__c = 'RSV';
        o.Process_Type__c = 'DG_Keep';
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Lawsuit_Date__c = System.today()
        );
        insert c;

        Correspondence__c[] crr = [
            SELECT ID FROM Correspondence__c
            WHERE Description__c = 'Wechsel Anspruchstyp von "Behalten"'
        ];
        System.assertEquals(0, crr.size());
        
        // Update
        o.stageName = 'Claim';
        o.Process_Type__c = 'DG_Return';
        update o;
        TriggerConfiguration.allInactive = false;

        crr = [
            SELECT ID FROM Correspondence__c
            WHERE Description__c = 'Wechsel Anspruchstyp von "Behalten"'
        ];
        System.assertEquals(0, crr.size());
    }
	
    @isTest
    private static void testCreateObjectsClaimFZ() {
	    TriggerConfiguration.allInactive = true;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;    

            Opportunity o = TestData.createOpportunity(null, 'Check');
            o.backoffice__c = u.ID;
            o.confirmed_Terms_And_Conditions__c = true;
            o.legal__c = u.ID;
            o.assignment_Type__c = 'RSV';
            o.recordTypeId = Opportunities.finanzierungRecordType();
            insert o;
            TriggerConfiguration.allInactive = false;

            Claim__c[] cc = [SELECT ID FROM Claim__c];
            System.assertEquals(0, cc.size());

            // Update
            o.stageName = 'Claim';
            update o;

            cc = [SELECT ID FROM Claim__c];
            System.assertEquals(1, cc.size());
        }
    }
	
    @isTest
    private static void testCreateObjectsInvoice() {
	    TriggerConfiguration.allInactive = true;

        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;    
        }
        
        Opportunity o = TestData.createOpportunity(null, 'Check');
        o.backoffice__c = u.ID;
        o.confirmed_Terms_And_Conditions__c = true;
        o.legal__c = u.ID;
        o.assignment_Type__c = 'RSV';
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Lawsuit_Date__c = System.today()
        );
        insert c;
        TriggerConfiguration.allInactive = false;
        
        // Update
        o.stageName = 'Claim';
        update o;
        
        o.recordTypeId = Opportunities.lebensversicherungRecordType();
        update o;
        
        o.partial_Refund__c = 1000;
        update o;
        Invoice__c[] ii = [SELECT ID FROM Invoice__c];
        System.assertEquals(1, ii.size());
    }
    
    @isTest
    private static void testCalculateRevenueOnInsertAndUpdate() {
        // todo: more thorough
        TriggerConfiguration.allInactive = true;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;

            Opportunity o = TestData.createOpportunity(null, 'On Hold');
            o.potential__c = 1000;
            insert o;

            Product2 p = TestData.createProduct();
            insert p;
            PriceBookEntry pbe = TestData.createPricebookEntry(p.ID);
            insert pbe;

            OpportunityLineItem oli = TestData.createOpportunityLineItem(o.ID, pbe.ID, 1500);
            insert oli;

            // Update
            o.potential__c = 5000;
            update o;

            OpportunityLineItem[] olis = [SELECT TotalPrice FROM OpportunityLineItem];
            // System.assertNotEquals(0, olis[0].totalPrice); // todo: check calculation logic
        }
    }
    
    @isTest
    private static void testProcessLostOnInsertAndUpdate() {
        TriggerConfiguration.allInactive = true;
        User u = TestData.legalUser();
        Claim__c c = ClaimsTests.buildClaim(u, null, 0, null, null);

        Test.startTest();
        insert c;
        Test.stopTest();

		Opportunity o = [SELECT RecordTypeID FROM Opportunity];
        o.stageName = 'Lost';
        o.reason_For_Loss__c = 'Kunde will nicht';
        update o;
    }
    
    @isTest
    private static void testSetContactLastOpportunity() {
        Account a = TestData.createAccount();
        insert a;
        Contact c = TestData.createContact(a.ID);
        insert c;
        
        Opportunity o = TestData.createOpportunity(null, 'On Hold');
        o.contact__c = c.ID;
        insert o;
        
        c = [SELECT Last_Opportunity__c FROM Contact];
        System.assertEquals(o.ID, c.last_Opportunity__c);
        
        o.contact__c = null;
        update o;
        
        // Update
        c = TestData.createContact(a.ID);
        c.firstName = '2';
        insert c;

		Logger.debug('updating');        
        o.contact__c = c.ID;
        update o;
        
        c = [SELECT Last_Opportunity__c FROM Contact WHERE FirstName = '2'];
        System.assertEquals(o.ID, c.last_Opportunity__c);
    }
    
    private static Opportunity createOpp(ID ownerID) {
        Account a = TestData.createAccount();
        insert a;
        Opportunity o = TestData.createOpportunity(a.ID, 'New');
        o.ownerID = ownerID;
        insert o;
        
        return o;
    }
    
	@isTest
    private static void testEmptyDefaultOwner() {
        User u = TestData.createUser();
        u.username = 'reassignIf@bla.com';
        insert u;
        
        // Do not reassign if no DEFAULT_OWNER
        GeneralSettings.DEFAULT_OWNER = null;
        GeneralSettings.REASSIGN_IF_OWNERS = u.ID;
        
        User ou = TestData.createUser();
        ou.username = 'firstOwner@bla.com';
        insert ou;

        Opportunity o;
        Test.startTest();
        System.runAs(TestData.bypassUser()) {
        	o = createOpp(ou.ID);   
        }
        Test.stopTest();
        
        o = [SELECT ID, OwnerID, Owner.username FROM Opportunity WHERE ID = :o.ID];
        System.assertEquals(ou.ID, o.OwnerID);
    }
    
    @isTest
    private static void testUnknownDefaultOwner() {
        User u = TestData.createUser();
        u.username = 'reassignIf@bla.com';
        insert u;
        
        // Do not reassign if no DEFAULT_OWNER
        GeneralSettings.DEFAULT_OWNER = '19281298912';
        GeneralSettings.REASSIGN_IF_OWNERS = u.ID;
        
        User ou = TestData.createUser();
        ou.username = 'firstOwner@bla.com';
        insert ou;

        Opportunity o;
        Test.startTest();
        System.runAs(TestData.bypassUser()) {
        	o = createOpp(ou.ID);   
        }
        Test.stopTest();
        
        o = [SELECT ID, OwnerID, Owner.username FROM Opportunity WHERE ID = :o.ID];
        System.assertEquals(ou.ID, o.OwnerID);
    }
    
    @isTest
    private static void testEmptyReassignIfOwner() {
        User u = TestData.createUser();
        u.username = 'defaultOwner@bla.com';
        insert u;
        
        // Do not reassign if no REASSIGN_IF_OWNERS
        GeneralSettings.DEFAULT_OWNER = u.ID;
        GeneralSettings.REASSIGN_IF_OWNERS = null;
        
        User ou = TestData.createUser();
        ou.username = 'firstOwner@bla.com';
        insert ou;

        Opportunity o;
        Test.startTest();
        System.runAs(TestData.bypassUser()) {
        	o = createOpp(ou.ID);   
        }
        Test.stopTest();
        
        o = [SELECT ID, OwnerID, Owner.username FROM Opportunity WHERE ID = :o.ID];
        System.assertEquals(ou.ID, o.OwnerID);
    }
    
    @isTest
    private static void testInactiveReassignIfOwner() {
        User u = TestData.createUser();
        u.username = 'defaultOwner@bla.com';
        User inactiveu = TestData.createUser();
        u.username = 'inactive@bla.com';
        u.isActive = false;
        insert new User[]{u, inactiveu};
        
        // Do not reassign if REASSIGN_IF_OWNERS is not an active user
        GeneralSettings.DEFAULT_OWNER = u.ID;
        GeneralSettings.REASSIGN_IF_OWNERS = inactiveu.ID;
        
        User ou = TestData.createUser();
        ou.username = 'firstOwner@bla.com';
        insert ou;

        Opportunity o;
        Test.startTest();
        System.runAs(TestData.bypassUser()) {
        	o = createOpp(ou.ID);   
        }
        Test.stopTest();
        
        o = [SELECT ID, OwnerID, Owner.username FROM Opportunity WHERE ID = :o.ID];
        System.assertEquals(ou.ID, o.OwnerID);
    }

    @isTest
    private static void testNoReassignmentWhenNoMatchingOwner() {
        User dou = TestData.createUser();
        dou.username = 'defaultOwner@bla.com';

        User fou = TestData.createUser();
        fou.username = 'firstOwner@bla.com';
        
        User lou = TestData.createUser();
        lou.username = 'oppOwner@bla.com';

        insert new User[]{dou, fou, lou};

        // Do _not_ reassign opp if the current opp owner if not the one set in REASSIGN_IF_OWNERS.
        GeneralSettings.DEFAULT_OWNER = dou.username;
        GeneralSettings.REASSIGN_IF_OWNERS = fou.username + ';alkslaks@lakslk.com';

        Opportunity o;
        Test.startTest();
        System.runAs(TestData.bypassUser()) {
        	o = createOpp(lou.ID);   
        }
        Test.stopTest();
        
        o = [SELECT ID, OwnerID, Owner.username FROM Opportunity WHERE ID = :o.ID];
        System.assertEquals(lou.ID, o.OwnerID);
    }

    @isTest
    private static void testReassignment() {
        User du = TestData.createUser();
        du.username = 'defaultOwner@bla.com';

        User ou = TestData.createUser();
        ou.username = 'firstOwner@bla.com';

        insert new User[]{du, ou};

        // Reassign opp to DEFAULT_OWNER if REASSIGN_IF_OWNERS is the current owner of the opp
        // and DEFAULT_OWNER is a valid user.
        GeneralSettings.DEFAULT_OWNER = du.username;
        GeneralSettings.REASSIGN_IF_OWNERS = 'alkslaks@lakslk.com;' + ou.username;

        Opportunity o;
        Test.startTest();
        System.runAs(TestData.bypassUser()) {
        	o = createOpp(ou.ID);   
        }
        Test.stopTest();
        
        o = [SELECT ID, OwnerID, Owner.username FROM Opportunity WHERE ID = :o.ID];
        System.assertEquals(du.ID, o.OwnerID);
    }
}