objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Holder__c</fullName>
        <label>Kontoinhaber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BIC__c</fullName>
        <label>BIC</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bankname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_Date_Old_Org__c</fullName>
        <label>Created Date Old Org</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>IBAN__c</fullName>
        <label>IBAN</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ich_bin_damIit_einverstanden_dass_im_Rah__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ich bin damit einverstanden, dass im Rah</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ich_stimme_hiermit_dem_SEPA_Einzugsverfa__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ich stimme hiermit dem SEPA-Einzugsverfa</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ich_stimme_hiermit_dem_VH24_Partnervertr__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ich stimme hiermit dem VH24-Partnervertr</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Leitung__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Projektverantwortlicher/Portalassistent</inlineHelpText>
        <label>Leitung</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Unternehmen</relationshipLabel>
        <relationshipName>Unternehmen</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vermittler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vermittler</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Unternehmen</relationshipLabel>
        <relationshipName>Unternehmen</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Holder__c</fullName>
        <label>Kontoinhaber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Anwalt__c</fullName>
        <formula>Last_Opportunity__r.Legal__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Anwalt</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auftragstyp__c</fullName>
        <formula>TEXT(Last_Opportunity__r.Assignment_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Auftragstyp</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auto_Follow_up_Count__c</fullName>
        <label>Anzahl Auto-Follow-ups</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Auto_Follow_up_Date__c</fullName>
        <label>Nächstes Auto-Follow-up</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Autostart_Auto_Follow_up_Journeys__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Follow-up Journeys automatisch starten</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BIC__c</fullName>
        <label>BIC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bankname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bearbeitungsnummer__c</fullName>
        <formula>Last_Opportunity__r.Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bearbeitungsnummer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BypassProcessBuilder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BypassProcessBuilder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContactImpID__c</fullName>
        <externalId>true</externalId>
        <label>ContactImpID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_Date_Old_Org__c</fullName>
        <label>Created Date Old Org</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Document_Count__c</fullName>
        <formula>Last_Opportunity__r.Document_Count__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document_Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IBAN__c</fullName>
        <label>IBAN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invalid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ungültig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pro__c</fullName>
        <formula>Last_Opportunity__r.Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Produkt</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <formula>IF(Title = "Herr" || TEXT(Salutation) = "Herr","Sehr geehrter Herr " + LastName,IF(Title = "Frau"|| TEXT(Salutation) = "Frau","Sehr geehrte Frau " + LastName,"Hallo " + FirstName + " " + LastName))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Salutation</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unternehmen__c</fullName>
        <formula>Last_Opportunity__r.Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unternehmen</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invitation__c.object
<CustomObject>
    <fields>
        <fullName>Invitation_URL__c</fullName>
        <formula>'https://vh24customers.force.com/VH24/Registration?Id='+Id+'&amp;PartnerId='+ Contact__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invitation URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invitee_Id__c</fullName>
        <formula>CreatedBy.Contact.AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invitee Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unternehmen__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unternehmen</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vermittler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vermittler</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Invitations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Einladung</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invitation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invitations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>BIC__c</fullName>
        <label>BIC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IBAN__c</fullName>
        <label>IBAN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PartnerCommunityManager.cls
public without sharing class PartnerCommunityManager{

    public static id getProfile(string profileName){
    
        return [Select id from Profile where Name =:profileName limit 1].id;
    
    }
    
    public static Invitation__c getInv(string invId){
    
        return [Select OwnerId,Invitee_Id__c ,id,Status__c,Invitation_URL__c from Invitation__c where Id =:invId limit 1];
    
    }
    
    public static Contact getcontact(id contactId){
    
        return [Select ownerId,MailingCity,MailingCountry,MailingCountryCode,MailingPostalCode,MailingStreet, AccountId,Account_Holder__c,Anwalt__c,Auftragstyp__c,Autostart_Auto_Follow_up_Journeys__c,Auto_Follow_up_Count__c,Auto_Follow_up_Date__c,Bank_Name__c,Bearbeitungsnummer__c,BIC__c,Birthdate,BypassProcessBuilder__c,ContactImpID__c,Created_Date_Old_Org__c,Department,Description,Document_Count__c,Email,FirstName,HomePhone,IBAN__c,Id,Invalid__c,LastName,MiddleName,Phone,Primary__c,Pro__c,Salutation,Salutation__c,Unternehmen__c FROM Contact where id=: contactId];
    }
    
    public static Account getAccount(id accountId){
        
        return [select ParentId,ownerId,name,Leitung__c,BIC__c,IBAN__c,Ich_bin_damIit_einverstanden_dass_im_Rah__c,Ich_stimme_hiermit_dem_SEPA_Einzugsverfa__c,Ich_stimme_hiermit_dem_VH24_Partnervertr__c,Id,Vermittler__c from Account where id=: accountId];
        
    }
    
    public static string createPartnerUser(string profileId, string email, string lastName, string firstName, string contactId){
        
        try{
            User user  = new User(
                 Username          = email+'.'+lastName,
                 ContactId         = contactId,
                 ProfileId         = profileId,
                 Alias             = lastName.left(4),
                 Email             = email,
                 EmailEncodingKey  = 'UTF-8',
                 LastName          = lastName,
                 CommunityNickname = lastName,
                 TimeZoneSidKey    = 'Europe/Berlin',
                 LocaleSidKey      = 'de_DE',
                 LanguageLocaleKey = 'de'
            );
            Database.insert(user);
            return 'true';
        }catch(Exception e){
            return e.getMessage();
        }
    
    }

}