objects/Account.object
<CustomObject>
    <fields>
        <fullName>Test__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Accounting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for accounting process parts.</description>
        <label>Accounting</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Invoices_Accounting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <description>Invoice number.</description>
        <label>Rechnungsnummer</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <description>Object for storing and managing invoices towards customers.</description>
    <label>Rechnung</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rechnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice_Reminder__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Invoice__r.Opportunity__r.Account_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Rechnung</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Mahnungen</relationshipLabel>
        <relationshipName>Invoice_Reminders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mahnung</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mahnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Bearbeitungsnummer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/InvoiceReminderTriggerHandlerTests.cls
@isTest
public class InvoiceReminderTriggerHandlerTests {
	@isTest
	static void testNotTestVR24() {

		// Testsetup
		TriggerConfiguration.allInactive = true;

		Account account = TestData.createVR24Account();
        insert account;
        Opportunity opportunity = TestData.createOpportunity(null,'New');
        opportunity.Account__c = account.ID;
		opportunity.Test__c = false;
		insert opportunity;
        User user = TestData.createUser();
		insert user;
		Invoice__c invoice = TestData.createInvoice(opportunity.Id);
		invoice.Accounting__c = user.Id;
		insert invoice;
		Invoice_Reminder__c oldInvoiceReminder = TestData.createInvoiceReminder(invoice.Id,'Draft');
		oldInvoiceReminder.Number__c = '2017000001/IRVR';
		List<Invoice_Reminder__c> invoiceReminders = new List<Invoice_Reminder__c>();
		for (Integer i=0;i<20;i++){
			invoiceReminders.add(TestData.createInvoiceReminder(invoice.Id,'Draft'));
		}

		TriggerConfiguration.allInactive = false;

		// Test
		Test.startTest();

		insert oldInvoiceReminder;

		TriggerConfiguration.allInactive = false;
		insert invoiceReminders;
		Test.stopTest();

		// Assertion
		invoiceReminders = [select Id,Number__c from Invoice_Reminder__c where Id IN :invoiceReminders];

		Integer i = 1;
		for (Invoice_Reminder__c invoiceReminder : invoiceReminders){
			System.assert(invoiceReminder.Number__c.endsWith(String.valueOf(i+1) + '/IRVR'));
			i++;
		}
	}

	@isTest
	static void testNotTestVH24() {

		// Testsetup
		TriggerConfiguration.allInactive = true;

		Account account = TestData.createVH24Account();
        insert account;
        Opportunity opportunity = TestData.createOpportunity(null,'New');
        opportunity.Account__c = account.ID;
		opportunity.Test__c = false;
		insert opportunity;
        User user = TestData.createUser();
		insert user;
		Invoice__c invoice = TestData.createInvoice(opportunity.Id);
		invoice.Accounting__c = user.Id;
		insert invoice;
		Invoice_Reminder__c oldInvoiceReminder = TestData.createInvoiceReminder(invoice.Id,'Draft');
		oldInvoiceReminder.Number__c = '2017000001/IRVH';
		List<Invoice_Reminder__c> invoiceReminders = new List<Invoice_Reminder__c>();
		for (Integer i=0;i<20;i++){
			invoiceReminders.add(TestData.createInvoiceReminder(invoice.Id,'Draft'));
		}

		TriggerConfiguration.allInactive = false;

		// Test
		Test.startTest();

		insert oldInvoiceReminder;

		TriggerConfiguration.allInactive = false;
		insert invoiceReminders;
		Test.stopTest();

		// Assertion
		invoiceReminders = [select Id,Number__c from Invoice_Reminder__c where Id IN :invoiceReminders];

		Integer i = 1;
		for (Invoice_Reminder__c invoiceReminder : invoiceReminders){
			System.assert(invoiceReminder.Number__c.endsWith(String.valueOf(i+1) + '/IRVH'));
			i++;
		}
	}

	@isTest
	static void testTest() {

		// Testsetup
		TriggerConfiguration.allInactive = true;

		Account account = TestData.createVH24Account();
        insert account;
        Opportunity opportunity = TestData.createOpportunity(null,'New');
        opportunity.Account__c = account.ID;
		opportunity.Test__c = true;
		insert opportunity;
        User user = TestData.createUser();
		insert user;
		Invoice__c invoice = TestData.createInvoice(opportunity.Id);
		invoice.Accounting__c = user.Id;
		insert invoice;
		Invoice_Reminder__c oldInvoiceReminder = TestData.createInvoiceReminder(invoice.Id,'Draft');
		oldInvoiceReminder.Number__c = '2017000001/IRVH';
		List<Invoice_Reminder__c> invoiceReminders = new List<Invoice_Reminder__c>();
		for (Integer i=0;i<20;i++){
			invoiceReminders.add(TestData.createInvoiceReminder(invoice.Id,'Draft'));
		}

		TriggerConfiguration.allInactive = false;

		// Test
		Test.startTest();

		insert oldInvoiceReminder;

		TriggerConfiguration.allInactive = false;
		insert invoiceReminders;
		Test.stopTest();

		// Assertion
		invoiceReminders = [select Id,Number__c from Invoice_Reminder__c where Id IN :invoiceReminders];

		for (Invoice_Reminder__c invoiceReminder : invoiceReminders){
			System.assert(invoiceReminder.Number__c.endsWith('00/Test'));
		}
	}
}