objects/Account.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Abteilung</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Canceled_Next_Court_Date__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gerichtstermin abgesagt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Clerk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sachbearbeiter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Clerk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cover_Note_Scope__c</fullName>
        <label>Deckungsumfang</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Cover_Note_Scopes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cover_Note__c</fullName>
        <label>Deckungszusage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Cover_Note_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for legal process parts.</description>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Legal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response_Insurance_Claim_Letter__c</fullName>
        <label>Antwort Deckungsanfrage Anspruchsschr.</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Insurance_Lawsuit__c</fullName>
        <label>Antwort Deckungsanfrage für Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Insurance_Legal_Opposition__c</fullName>
        <label>Antwort Deckungsanfrage Anwaltswiderspr.</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Ergebnis</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Date_Before_Claim_Statement__c</fullName>
        <label>Übermittlung vor Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submission_Date_Before_Lawsuit_Date__c</fullName>
        <label>Übermittlung vor Gerichtstermin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submitter_Before_Claim_Statement__c</fullName>
        <label>Übermittler vor Klage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Transmitters</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitter_Before_Lawsuit_Date__c</fullName>
        <label>Übermittler vor Gerichtstermin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Transmitters</valueSetName>
        </valueSet>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <label>Finanzierung</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <formula>TEXT(Last_Opportunity__r.StageName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 1</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <businessProcess>Finanzierung</businessProcess>
        <label>Finanzierung</label>
    </recordTypes>
</CustomObject>

globalValueSets/Claim_Cover_Note_Scopes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Extrajudicial</fullName>
        <label>Außergerichtlich</label>
    </customValue>
    <customValue>
        <fullName>Judicial</fullName>
        <label>Gerichtlich</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Without Appeal</fullName>
        <label>Ohne Berufung</label>
    </customValue>
    <customValue>
        <fullName>Arrangement</fullName>
        <label>Vergleich</label>
    </customValue>
    <masterLabel>Claim Cover Note Scopes</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Cover_Note_Statuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Issued</fullName>
        <label>Erteilt</label>
    </customValue>
    <customValue>
        <fullName>Refused</fullName>
        <label>Abgelehnt</label>
    </customValue>
    <masterLabel>Claim Cover Note Statuses</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Results.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accepted</fullName>
        <label>Angenommen</label>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
        <label>Abgelehnt</label>
    </customValue>
    <customValue>
        <fullName>Partial</fullName>
        <label>Teilzahlung</label>
    </customValue>
    <customValue>
        <fullName>Arrangement</fullName>
        <label>Vergleich</label>
    </customValue>
    <customValue>
        <fullName>No Response</fullName>
        <label>Keine Antwort</label>
    </customValue>
    <customValue>
        <fullName>Partially won</fullName>
        <label>Teilweise gewonnen</label>
    </customValue>
    <masterLabel>Claim Results</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Entwurf</label>
    </customValue>
    <customValue>
        <fullName>Customers Opposition</fullName>
        <label>Kundenwiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Legal Opposition</fullName>
        <label>Anwaltswiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Claim Letter</fullName>
        <label>Anspruchsschreiben</label>
    </customValue>
    <customValue>
        <fullName>Lawsuit</fullName>
        <label>Klage</label>
    </customValue>
    <customValue>
        <fullName>Class Action</fullName>
        <label>Sammelklage</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
        <label>Abwicklung</label>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
        <label>Abgeschlossen</label>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <label>Warten auf Grundsatzurteil</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>Abbruch</label>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Examination</fullName>
        <isActive>false</isActive>
        <label>Examination</label>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
        <isActive>false</isActive>
        <label>Success</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
        <isActive>false</isActive>
        <label>Failure</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <isActive>false</isActive>
        <label>Open</label>
    </customValue>
    <description>Claim stages.</description>
    <masterLabel>Claim Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Transmitters.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Kunde</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <masterLabel>Claim Transmitters</masterLabel>
</GlobalValueSet>

classes/ClaimMailTest.cls
@isTest
public class ClaimMailTest {
    @testSetup
    public static void SetupTheThings() {
        TriggerConfiguration.allInactive = true;
        Test.startTest();
        Account a = new Account(Name = 'VH24');
        insert a;
        Contact con = new Contact(
            LastName = 'bar',
            Email = 'foo@bar.baz'
        );
        insert con;
        Opportunity o = TestData.createOpportunity(a.Id, 'On Hold');
        o.Contact__c = con.Id;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;
        }
        o.Legal__c = u.Id;
        o.Backoffice__c = u.Id;
        insert o;
        Test.stopTest();
    }

	private static id setLegal(string legalName, string department) {
        return setLegalX(legalName, department);
    }

    private static id setLegal(string legalName) {
        return setLegalX(legalName, 'Heinrich Jäger - DG & FZ');
    }

    private static id setLegalX(string legalName, string department) {
        TriggerConfiguration.allInactive = true;
        opportunity o = [SELECT ID, Legal__c FROM Opportunity][0];
        Account a = new Account(
            name = legalName,
            Department__c = department
        );
        insert a;
        o.Legal_Account__c = a.Id;
        update o;
        return o.Legal__c;
    }

    /* * * * * * * * *
     * Dieselskandal *
     * * * * * * * * */

    // == On Hold ==

    // Issued

    @isTest
    public static void testDGOnHoldIssuedJCLegal() {
        id uId = setLegal('J & C Anwälte');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Issued',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Clerk__c = uID
        );
        insert c;
        c.RecordTypeId = Claims.dieselskandalRecordType();
        c.Response_Insurance_Claim_Letter__c = System.today();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testDGOnHoldIssued21Legal() {
        id uId = setLegal('21Legal GmbH');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Issued',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Clerk__c = uid
        );
        insert c;
        c.RecordTypeId = Claims.dieselskandalRecordType();
        c.Response_Insurance_Claim_Letter__c = System.today();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testDGOnHoldIssuedKainz() {
        id uId = setLegal('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Issued',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.dieselskandalRecordType();
        c.Response_Insurance_Claim_Letter__c = System.today();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testDGOnHoldIssuedLeCom() {
        id uId = setLegal('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Issued',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Clerk__c = uid
        );
        insert c;
        c.RecordTypeId = Claims.dieselskandalRecordType();
        c.Response_Insurance_Claim_Letter__c = System.today();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testDGOnHoldIssuedLachmair() {
        id uId = setLegal('Rechtsanwälte Lachmair & Kollegen');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Issued',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.dieselskandalRecordType();
        c.Response_Insurance_Claim_Letter__c = System.today();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }

    // Refused

    @isTest
    public static void testDGOnHoldRefusedJCLegal() {
        id uId = setLegal('J & C Anwälte');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Refused',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.dieselskandalRecordType();
        c.Response_Insurance_Claim_Letter__c = System.today();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testDGOnHoldRefused21Legal() {
        id uId = setLegal('21Legal GmbH');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Refused',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.dieselskandalRecordType();
        c.Response_Insurance_Claim_Letter__c = System.today();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testDGOnHoldRefusedKainz() {
        id uId = setLegal('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Refused',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.dieselskandalRecordType();
        c.Response_Insurance_Claim_Letter__c = System.today();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testDGOnHoldRefusedLeCom() {
        id uId = setLegal('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Refused',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.dieselskandalRecordType();
        c.Response_Insurance_Claim_Letter__c = System.today();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testDGOnHoldRefusedLachmair() {
        id uId = setLegal('Rechtsanwälte Lachmair & Kollegen');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Refused',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.dieselskandalRecordType();
        c.Response_Insurance_Claim_Letter__c = System.today();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }

    // == Lawsuit ==

    /*
    // TODO: comment this out and fix soql101 in production
    @isTest
    public static void testDGLawsuitIssuedJCLegal() {
        setLegal('J & C Anwälte');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Issued',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Sent_Mail_Flag_1__c = false
        );
        insert c;
        c.RecordTypeId = Claims.dieselskandalRecordType();
        c.Response_Insurance_Claim_Letter__c = System.today();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Submission_Date_Before_Claim_Statement__c = System.today();
        c.Submission_Date_Before_Lawsuit_Date__c = System.today();
        c.Submitter_Before_Claim_Statement__c = 'System';
        c.Submitter_Before_Lawsuit_Date__c = 'System';
        c.Stage__c = 'Lawsuit';
        c.Canceled_Next_Court_Date__c = true;
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testDGLawsuitIssued21Legal() {
        setLegal('21Legal GmbH');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Issued',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Sent_Mail_Flag_1__c = false
        );
        insert c;
        c.RecordTypeId = Claims.dieselskandalRecordType();
        c.Response_Insurance_Claim_Letter__c = System.today();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Submission_Date_Before_Claim_Statement__c = System.today();
        c.Submission_Date_Before_Lawsuit_Date__c = System.today();
        c.Submitter_Before_Claim_Statement__c = 'System';
        c.Submitter_Before_Lawsuit_Date__c = 'System';
        c.Stage__c = 'Lawsuit';
        c.Canceled_Next_Court_Date__c = true;
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testDGLawsuitIssuedKainz() {
        setLegal('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Issued',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Sent_Mail_Flag_1__c = false
        );
        insert c;
        c.RecordTypeId = Claims.dieselskandalRecordType();
        c.Response_Insurance_Claim_Letter__c = System.today();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Submission_Date_Before_Claim_Statement__c = System.today();
        c.Submission_Date_Before_Lawsuit_Date__c = System.today();
        c.Submitter_Before_Claim_Statement__c = 'System';
        c.Submitter_Before_Lawsuit_Date__c = 'System';
        c.Stage__c = 'Lawsuit';
        c.Canceled_Next_Court_Date__c = true;
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testDGLawsuitIssuedLeCom() {
        setLegal('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Issued',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Sent_Mail_Flag_1__c = false
        );
        insert c;
        c.RecordTypeId = Claims.dieselskandalRecordType();
        c.Response_Insurance_Claim_Letter__c = System.today();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Submission_Date_Before_Claim_Statement__c = System.today();
        c.Submission_Date_Before_Lawsuit_Date__c = System.today();
        c.Submitter_Before_Claim_Statement__c = 'System';
        c.Submitter_Before_Lawsuit_Date__c = 'System';
        c.Stage__c = 'Lawsuit';
        c.Canceled_Next_Court_Date__c = true;
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testDGLawsuitIssuedLachmair() {
        setLegal('Rechtsanwälte Lachmair & Kollegen');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Issued',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Sent_Mail_Flag_1__c = false
        );
        insert c;
        c.RecordTypeId = Claims.dieselskandalRecordType();
        c.Response_Insurance_Claim_Letter__c = System.today();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Submission_Date_Before_Claim_Statement__c = System.today();
        c.Submission_Date_Before_Lawsuit_Date__c = System.today();
        c.Submitter_Before_Claim_Statement__c = 'System';
        c.Submitter_Before_Lawsuit_Date__c = 'System';
		c.Stage__c = 'Lawsuit';
		c.Canceled_Next_Court_Date__c = true;
        TriggerConfiguration.allInactive = false;

        update c;
    }
	*/

    /* * * * * * * * *
     * Finanzierung  *
     * * * * * * * * */

    // Issued
/*
    @isTest
    public static void testFZLawsuitIssuedJCLegal() {
        id uId = setLegal('J & C Anwälte');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Issued',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Result__c = 'No Response',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.finanzierungRecordType();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Response_Insurance_Legal_Opposition__c = System.today();
        c.Submitter_Before_Claim_Statement__c = 'System';
        c.Submitter_Before_Lawsuit_Date__c = 'System';
		c.Stage__c = 'Lawsuit';
		c.Canceled_Next_Court_Date__c = true;
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testFZLawsuitIssuedLeCom() {
        id uId = setLegal('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Issued',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Result__c = 'No Response',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.finanzierungRecordType();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Response_Insurance_Legal_Opposition__c = System.today();
        c.Submitter_Before_Claim_Statement__c = 'System';
        c.Submitter_Before_Lawsuit_Date__c = 'System';
		c.Stage__c = 'Lawsuit';
		c.Canceled_Next_Court_Date__c = true;
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testFZLawsuitIssuedKainz() {
        id uId = setLegal('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Issued',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Result__c = 'No Response',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.finanzierungRecordType();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Response_Insurance_Legal_Opposition__c = System.today();
        c.Submitter_Before_Claim_Statement__c = 'System';
        c.Submitter_Before_Lawsuit_Date__c = 'System';
		c.Stage__c = 'Lawsuit';
		c.Canceled_Next_Court_Date__c = true;
        TriggerConfiguration.allInactive = false;

        update c;
    }

    // Refused

    @isTest
    public static void testFZLawsuitRefusedJCLegal() {
        id uId = setLegal('J & C Anwälte');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Refused',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Result__c = 'No Response',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.finanzierungRecordType();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Response_Insurance_Legal_Opposition__c = System.today();
        c.Submitter_Before_Claim_Statement__c = 'System';
        c.Submitter_Before_Lawsuit_Date__c = 'System';
		c.Stage__c = 'Lawsuit';
		c.Canceled_Next_Court_Date__c = true;
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testFZLawsuitRefusedLeCom() {
        id uId = setLegal('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Refused',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Result__c = 'No Response',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.finanzierungRecordType();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Response_Insurance_Legal_Opposition__c = System.today();
        c.Submitter_Before_Claim_Statement__c = 'System';
        c.Submitter_Before_Lawsuit_Date__c = 'System';
		c.Stage__c = 'Lawsuit';
		c.Canceled_Next_Court_Date__c = true;
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testFZLawsuitefusedKainz() {
        id uId = setLegal('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Refused',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Result__c = 'No Response',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.finanzierungRecordType();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Response_Insurance_Legal_Opposition__c = System.today();
        c.Submitter_Before_Claim_Statement__c = 'System';
        c.Submitter_Before_Lawsuit_Date__c = 'System';
		c.Stage__c = 'Lawsuit';
		c.Canceled_Next_Court_Date__c = true;
        TriggerConfiguration.allInactive = false;

        update c;
    }
	*/
    /* * * * * * * * * * * *
     * Lebenesversicherung *
     * * * * * * * * * * * */

    // Issued

    @isTest
    public static void testLVOnHoldIssuedJaeger() {
        id uId = setLegal('J & C Anwälte', 'Heinrich Jäger - LV');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Issued',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Result__c = 'No Response',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.lebensversicherungRecordType();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Response_Insurance_Legal_Opposition__c = System.today();
		c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testLVOnHoldIssued21Legal() {
        id uId = setLegal('21Legal GmbH');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Issued',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Result__c = 'No Response',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.lebensversicherungRecordType();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Response_Insurance_Legal_Opposition__c = System.today();
		c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testLVOnHoldIssuedLeCom() {
        id uId = setLegal('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Issued',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Result__c = 'No Response',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.lebensversicherungRecordType();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Response_Insurance_Legal_Opposition__c = System.today();
		c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testLVOnHoldIssuedKainz() {
        id uId = setLegal('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Issued',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Result__c = 'No Response',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.lebensversicherungRecordType();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Response_Insurance_Legal_Opposition__c = System.today();
		c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }

    // Refused

    @isTest
    public static void testLVOnHoldRefusedJaeger() {
        id uId = setLegal('J & C Anwälte', 'Heinrich Jäger - LV');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Refused',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Result__c = 'No Response',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.lebensversicherungRecordType();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Response_Insurance_Legal_Opposition__c = System.today();
		c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testLVOnHoldRefused21Legal() {
        id uId = setLegal('21Legal GmbH');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Refused',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Result__c = 'No Response',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.lebensversicherungRecordType();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Response_Insurance_Legal_Opposition__c = System.today();
		c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testLVOnHoldRefusedLeCom() {
        id uId = setLegal('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Refused',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Result__c = 'No Response',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.lebensversicherungRecordType();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Response_Insurance_Legal_Opposition__c = System.today();
		c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }

    @isTest
    public static void testLVOnHoldRefusedKainz() {
        id uId = setLegal('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        Claim__c c = new Claim__c(
            Opportunity__c = [SELECT ID FROM Opportunity][0].id,
            Cover_Note__c = 'Refused',
            Cover_Note_Scope__c = 'Extrajudicial;Judicial',
            Result__c = 'No Response',
            Clerk__c = uId
        );
        insert c;
        c.RecordTypeId = Claims.lebensversicherungRecordType();
        c.Response_Insurance_Lawsuit__c = System.today();
        c.Response_Insurance_Legal_Opposition__c = System.today();
		c.Stage__c = 'On Hold';
        TriggerConfiguration.allInactive = false;

        update c;
    }
}