objects/Account.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Betrag</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Stages</valueSetName>
        </valueSet>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <formula>TEXT(Last_Opportunity__r.StageName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>ROUND(Total_Price__c + Total_VAT__c,2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Summe</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipName>Cost_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <label>Empfänger</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Recipients</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Uploaded_To_Dropbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hochgeladen</label>
        <type>Checkbox</type>
    </fields>
    <label>Kostennote</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostennoten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Note__c</fullName>
        <label>Kostennote</label>
        <referenceTo>Cost_Note__c</referenceTo>
        <relationshipLabel>Kostenpunkte</relationshipLabel>
        <relationshipName>Cost_Note_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Kostenpunkt</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostenpunkte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Credit_Note__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>Total_Price__c + Total_VAT__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Summe</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipName>Credit_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credit_Note_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Uploaded_To_Dropbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hochgeladen</label>
        <type>Checkbox</type>
    </fields>
    <label>Gutschrift</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gutschriften</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Credit_Note_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Credit_Note__c</fullName>
        <label>Gutschrift</label>
        <referenceTo>Credit_Note__c</referenceTo>
        <relationshipLabel>Gutschriftspositionen</relationshipLabel>
        <relationshipName>Credit_Note_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Gutschriftsposition</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gutschriftspositionen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Bruttosumme</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Invoice_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Uploaded_To_Dropbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hochgeladen</label>
        <type>Checkbox</type>
    </fields>
    <description>Object for storing and managing invoices towards customers.</description>
    <label>Rechnung</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rechnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

globalValueSets/Claim_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Entwurf</label>
    </customValue>
    <customValue>
        <fullName>Customers Opposition</fullName>
        <label>Kundenwiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Legal Opposition</fullName>
        <label>Anwaltswiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Claim Letter</fullName>
        <label>Anspruchsschreiben</label>
    </customValue>
    <customValue>
        <fullName>Lawsuit</fullName>
        <label>Klage</label>
    </customValue>
    <customValue>
        <fullName>Class Action</fullName>
        <label>Sammelklage</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
        <label>Abwicklung</label>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
        <label>Abgeschlossen</label>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <label>Warten auf Grundsatzurteil</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>Abbruch</label>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Examination</fullName>
        <isActive>false</isActive>
        <label>Examination</label>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
        <isActive>false</isActive>
        <label>Success</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
        <isActive>false</isActive>
        <label>Failure</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <isActive>false</isActive>
        <label>Open</label>
    </customValue>
    <description>Claim stages.</description>
    <masterLabel>Claim Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Recipients.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Customer</fullName>
        <default>true</default>
        <label>Kunde</label>
    </customValue>
    <customValue>
        <fullName>Legal Protection Insurance</fullName>
        <label>Rechtsschutzversicherung</label>
    </customValue>
    <masterLabel>Cost Note Recipients</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Replaced</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Cost Note Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Credit_Note_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Credit Note Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Invoice_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <description>Invoice stages.</description>
    <masterLabel>Invoice Stages</masterLabel>
</GlobalValueSet>

classes/IntegrateDropboxTest.cls
@IsTest
private class IntegrateDropboxTest {

	public static Integer testcase;

	private class MockHttpResponseGenerator implements HttpCalloutMock {
		public HTTPResponse respond(HTTPRequest req) {
			HttpResponse res = new HttpResponse();
			if(testcase == 1){
				res.setBody('{"name": "cost_note_cn20160810020.pdf", "path_lower": "/test/cost_note_cn20160810020.pdf", "path_display": "/Test/cost_note_cn20160810020.pdf", "id": "id:b1-3Lzp3mDQAAAAAAABR2A", "client_modified": "2016-08-10T14:40:27Z", "server_modified": "2016-08-10T14:40:27Z", "rev": "1c0470bd6ed24", "size": 84310}');
			} else if (testcase == 2) {
				res.setBody('{"error" : "Testfehler"}');
			}
			res.setStatusCode(200);

			return res;
		}
	}

	@isTest
	static void testUploadFromCreditNoteSuccess() {
		// Testsetup
		Utilities.deactivateTriggers();

		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id,'New');
		opportunity.Legal_Account__c = account.Id;
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id,'Draft');
		insert claim;
		Credit_Note__c creditNote = TestData.createCreditNote(claim.Id,'Draft');
		creditNote.Uploaded_To_Dropbox__c = false;
		insert creditNote;
		Credit_Note_Line_Item__c creditNoteLineItem = TestData.createCreditNoteLineItem(creditNote.Id,10000);
		insert creditNoteLineItem;
		Attachment attachment = TestData.createAttachment(creditNote.Id);
		insert attachment;

		Utilities.activateTriggers();

		// Test
		test.StartTest();

		testcase = 1;
		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		IntegrateDropbox.uploadFileToDropboxAsync('/Test/',attachment.Id,account.Id);

		test.StopTest();

		// Assertion
		creditNote = [select Id,Uploaded_To_Dropbox__c, (select Id,Subject from Tasks) from Credit_Note__c where Id = :creditNote.Id];

		Integer i = 0;
		for (Task task : creditNote.Tasks){
			if (task.Subject.contains('Uploaded to')){
				i++;
			}
		}

		System.assert(i == 1);
		System.assert(creditNote.Uploaded_To_Dropbox__c == true);
	}

	@isTest
	static void testUploadFromCostNoteSuccess() {
		// Testsetup
		Utilities.deactivateTriggers();

		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id, 'New');
        opportunity.RecordTypeId = Opportunities.dieselSkandalRecordType();
		opportunity.Legal_Account__c = account.Id;
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
		insert claim;
		Cost_Note__c costNote = TestData.createCostNote(claim.Id, 'Draft');
		costNote.Recipient__c = 'Legal Protection Insurance';
		costNote.Uploaded_To_Dropbox__c = false;
		insert costNote;
		Cost_Note_Line_Item__c costNoteLineItem = TestData.createCostNoteLineItem(costNote.Id,10000);
		insert costNoteLineItem;
		Attachment attachment = TestData.createAttachment(costNote.Id);
		insert attachment;

		Utilities.activateTriggers();

		// Test
		test.StartTest();

		testcase = 1;
		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		IntegrateDropbox.uploadFileToDropboxAsync('/Test/',attachment.Id,account.Id);

		test.StopTest();

		// Assertion
		costNote = [select Id,Uploaded_To_Dropbox__c, (select Id,Subject from Tasks) from Cost_Note__c where Id = :costNote.Id];

		Integer i = 0;
		for (Task task : costNote.Tasks){
			if (task.Subject.contains('Uploaded to')){
				i++;
			}
		}

		System.assert(i == 1);
		System.assert(costNote.Uploaded_To_Dropbox__c == true);
	}

	@isTest
	static void testUploadFromInvoiceSuccess() {
		// Testsetup
		Utilities.deactivateTriggers();

		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id,'New');
		insert opportunity;
		Invoice__c invoice = TestData.createInvoice(opportunity.Id);
		invoice.Stage__c = 'Draft';
		invoice.Amount__c = 1000;
		insert invoice;
		Attachment attachment = TestData.createAttachment(invoice.Id);
		insert attachment;

		Utilities.activateTriggers();

		// Test
		test.StartTest();

		testcase = 1;
		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		IntegrateDropbox.uploadFileToDropboxAsync('/Test/',attachment.Id,account.Id);

		test.StopTest();

		// Assertion
		invoice = [select Id,Uploaded_To_Dropbox__c, (select Id,Subject from Tasks) from Invoice__c where Id = :invoice.Id];

		Integer i = 0;
		for (Task task : invoice.Tasks){
			if (task.Subject.contains('Uploaded to')){
				i++;
			}
		}

		System.assert(i == 1);
		System.assert(invoice.Uploaded_To_Dropbox__c == true);
	}

	@isTest
	static void testBadResponse() {
		// Testsetup
		Utilities.deactivateTriggers();

		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id,'New');
		opportunity.Legal_Account__c = account.Id;
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id,'Draft');
		insert claim;
		Credit_Note__c creditNote = TestData.createCreditNote(claim.Id,'Draft');
		creditNote.Uploaded_To_Dropbox__c = false;
		insert creditNote;
		Credit_Note_Line_Item__c creditNoteLineItem = TestData.createCreditNoteLineItem(creditNote.Id,10000);
		insert creditNoteLineItem;
		Attachment attachment = TestData.createAttachment(creditNote.Id);
		insert attachment;

		Utilities.activateTriggers();

		// Test
		test.StartTest();

		testcase = 2;
		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		IntegrateDropbox.uploadFileToDropboxAsync('/Test/',attachment.Id,account.Id);

		test.StopTest();

		// Assertion
		creditNote = [select Id,Uploaded_To_Dropbox__c, (select Id,Subject from Tasks) from Credit_Note__c where Id = :creditNote.Id];

		Integer i = 0;
		for (Task task : creditNote.Tasks){
			if (task.Subject.contains('Uploaded to')){
				i++;
			}
		}

		System.assert(i == 0);
		System.assert(creditNote.Uploaded_To_Dropbox__c == false);
	}

	@isTest
	static void testUploadToDropboxDeactivated() {
		// Testsetup
		Utilities.deactivateTriggers();

		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id,'New');
		opportunity.Legal_Account__c = account.Id;
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id,'Draft');
		insert claim;
		Credit_Note__c creditNote = TestData.createCreditNote(claim.Id,'Draft');
		creditNote.Uploaded_To_Dropbox__c = false;
		insert creditNote;
		Credit_Note_Line_Item__c creditNoteLineItem = TestData.createCreditNoteLineItem(creditNote.Id,10000);
		insert creditNoteLineItem;
		Attachment attachment = TestData.createAttachment(creditNote.Id);
		insert attachment;

		Utilities.deactivateDropboxUpload = true;

		Utilities.activateTriggers();

		// Test
		test.StartTest();

		testcase = 2;
		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		IntegrateDropbox.uploadFileToDropboxAsync('/Test/',attachment.Id,account.Id);

		test.StopTest();

		// Assertion
		creditNote = [select Id,Uploaded_To_Dropbox__c, (select Id,Subject from Tasks) from Credit_Note__c where Id = :creditNote.Id];

		Integer i = 0;
		for (Task task : creditNote.Tasks){
			if (task.Subject.contains('Uploaded to')){
				i++;
			}
		}

		System.assert(i == 0);
		System.assert(creditNote.Uploaded_To_Dropbox__c == false);
	}
}