objects/Account.object
<CustomObject>
    <fields>
        <fullName>Test__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Test__c</fullName>
        <formula>Opportunity__r.Test__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Credit_Note__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipName>Credit_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Nummer</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <formula>Claim__r.Opportunity__r.Test__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <label>Gutschrift</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gutschriften</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Date__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Termine</relationshipLabel>
        <relationshipName>Termine</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Termin</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Termine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Callcenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for call center process parts.</description>
        <label>Callcenter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Callcenter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Bearbeitungsnummer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CreditNotesTests.cls
// Adapted from legacy code, todo: refactor
@isTest
public class CreditNotesTests {
    @isTest
    static void testDgInsert() {
        // Testsetup
        TriggerConfiguration.allInactive = true;

        /*Account account = TestData.createAccount();
        insert account;*/

        Opportunity opportunity = TestData.createOpportunity(null, 'New');
        opportunity.RecordTypeId = Opportunities.dieselSkandalRecordType();
        insert opportunity;
        Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
        insert claim;
        Credit_Note__c creditNote = TestData.createCreditNote(claim.Id, 'Draft');

        TriggerConfiguration.allInactive = false;

        // Test
        Test.startTest();

        insert creditNote;

        Test.stopTest();

        // Assertion
        creditNote = [select Id, Number__c from Credit_Note__c where Id = :creditNote.Id];
        System.assert(creditNote.Number__c.contains('000001/CNDG'));
    }

    @isTest
    static void testDgUpdate() {
        // Testsetup
        TriggerConfiguration.allInactive = true;

        /*Account account = TestData.createAccount();
        insert account;*/

        Opportunity opportunity = TestData.createOpportunity(null, 'New');
        opportunity.RecordTypeId = Opportunities.dieselSkandalRecordType();
        insert opportunity;
        Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
        insert claim;
        Credit_Note__c creditNote = TestData.createCreditNote(claim.Id, 'Draft');
        creditNote.Date__c = null;
        insert creditNote;

        TriggerConfiguration.allInactive = false;

        // Test
        Test.startTest();

        creditNote.Date__c = System.today();
        update creditNote;

        Test.stopTest();

        // Assertion
        creditNote = [select Id, Number__c from Credit_Note__c where Id = :creditNote.Id];
        System.assert(creditNote.Number__c.contains('000001/CNDG'));
    }

    @isTest
    static void testFzInsert() {
        // Testsetup
        TriggerConfiguration.allInactive = true;

        Account account = TestData.createVR24Account();
        insert account;
        Opportunity opportunity = TestData.createOpportunity(account.Id, 'New');
        opportunity.RecordTypeId = Opportunities.finanzierungRecordType();
        insert opportunity;
        Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
        insert claim;
        Credit_Note__c creditNote = TestData.createCreditNote(claim.Id, 'Draft');

        TriggerConfiguration.allInactive = false;

        // Test
        Test.startTest();

        insert creditNote;

        Test.stopTest();

        // Assertion
        creditNote = [select Id, Number__c from Credit_Note__c where Id = :creditNote.Id];
        System.assert(creditNote.Number__c.contains('000001/CNCVRFZ'));
    }

    @isTest
    static void testFzUpdate() {
        // Testsetup
        TriggerConfiguration.allInactive = true;

        Account account = TestData.createVR24Account();
        insert account;
        Opportunity opportunity = TestData.createOpportunity(account.Id, 'New');
        opportunity.RecordTypeId = Opportunities.finanzierungRecordType();
        insert opportunity;
        Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
        insert claim;
        Credit_Note__c creditNote = TestData.createCreditNote(claim.Id, 'Draft');
        creditNote.Date__c = null;
        insert creditNote;

        TriggerConfiguration.allInactive = false;

        // Test
        Test.startTest();

        creditNote.Date__c = System.today();
        update creditNote;

        Test.stopTest();

        // Assertion
        creditNote = [select Id, Number__c from Credit_Note__c where Id = :creditNote.Id];
        System.assert(creditNote.Number__c.contains('000001/CNCVRFZ'));
    }

    @isTest
    static void testLvInsert() {
        // Testsetup
        TriggerConfiguration.allInactive = true;

        User user = TestData.createUser();
        insert user;
        Account account = TestData.createVR24Account();
        insert account;
        Opportunity opportunity = TestData.createOpportunity(account.Id, 'New');
        opportunity.RecordTypeId = Opportunities.lebensversicherungRecordType();
        opportunity.Callcenter__c = user.Id;
        insert opportunity;
        Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
        insert claim;
        Credit_Note__c creditNote = TestData.createCreditNote(claim.Id, 'Draft');

        TriggerConfiguration.allInactive = false;

        // Test
        Test.startTest();

        insert creditNote;

        Test.stopTest();

        // Assertion
        creditNote = [select Id, Number__c from Credit_Note__c where Id = :creditNote.Id];
        System.assert(creditNote.Number__c.contains('000001/CN21VRLV'));
    }

    @isTest
    static void testTestInsert() {
        // Testsetup
        TriggerConfiguration.allInactive = true;

        Opportunity opportunity = TestData.createOpportunity(null, 'New');
        opportunity.Test__c = true;
        insert opportunity;
        Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
        insert claim;
        Credit_Note__c creditNote = TestData.createCreditNote(claim.Id, 'Draft');

        TriggerConfiguration.allInactive = false;

        // Test
        Test.startTest();

        insert creditNote;

        Test.stopTest();

        // Assertion
        creditNote = [select Id, Number__c from Credit_Note__c where Id = :creditNote.Id];
        System.assert(creditNote.Number__c.contains('000001/Test'));
    }
}