objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Externe Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Clerk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sachbearbeiter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Clerk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cover_Note_Scope__c</fullName>
        <label>Deckungsumfang</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Cover_Note_Scopes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cover_Note__c</fullName>
        <label>Deckungszusage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Cover_Note_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Ergebnis</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Stages</valueSetName>
        </valueSet>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Korrespondenzen</relationshipLabel>
        <relationshipName>Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Auftragstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assignment_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Versicherungsende</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Has_Legal_Protection_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rechtsschutzversicherung vorhanden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Versicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Lebensversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Versicherung)</relationshipLabel>
        <relationshipName>Opportunities_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <label>Kündigungsdatum</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

globalValueSets/Assignment_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Share</fullName>
    </customValue>
    <customValue>
        <fullName>Direkt</fullName>
    </customValue>
    <customValue>
        <fullName>50%</fullName>
        <isActive>false</isActive>
        <label>50%</label>
    </customValue>
    <customValue>
        <fullName>RSV 20%</fullName>
        <isActive>false</isActive>
        <label>RSV 20%</label>
    </customValue>
    <masterLabel>Assignment Types</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Cover_Note_Scopes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Extrajudicial</fullName>
        <label>Außergerichtlich</label>
    </customValue>
    <customValue>
        <fullName>Judicial</fullName>
        <label>Gerichtlich</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Without Appeal</fullName>
        <label>Ohne Berufung</label>
    </customValue>
    <customValue>
        <fullName>Arrangement</fullName>
        <label>Vergleich</label>
    </customValue>
    <masterLabel>Claim Cover Note Scopes</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Cover_Note_Statuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Issued</fullName>
        <label>Erteilt</label>
    </customValue>
    <customValue>
        <fullName>Refused</fullName>
        <label>Abgelehnt</label>
    </customValue>
    <masterLabel>Claim Cover Note Statuses</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Results.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accepted</fullName>
        <label>Angenommen</label>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
        <label>Abgelehnt</label>
    </customValue>
    <customValue>
        <fullName>Partial</fullName>
        <label>Teilzahlung</label>
    </customValue>
    <customValue>
        <fullName>Arrangement</fullName>
        <label>Vergleich</label>
    </customValue>
    <customValue>
        <fullName>No Response</fullName>
        <label>Keine Antwort</label>
    </customValue>
    <customValue>
        <fullName>Partially won</fullName>
        <label>Teilweise gewonnen</label>
    </customValue>
    <masterLabel>Claim Results</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Entwurf</label>
    </customValue>
    <customValue>
        <fullName>Customers Opposition</fullName>
        <label>Kundenwiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Legal Opposition</fullName>
        <label>Anwaltswiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Claim Letter</fullName>
        <label>Anspruchsschreiben</label>
    </customValue>
    <customValue>
        <fullName>Lawsuit</fullName>
        <label>Klage</label>
    </customValue>
    <customValue>
        <fullName>Class Action</fullName>
        <label>Sammelklage</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
        <label>Abwicklung</label>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
        <label>Abgeschlossen</label>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <label>Warten auf Grundsatzurteil</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>Abbruch</label>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Examination</fullName>
        <isActive>false</isActive>
        <label>Examination</label>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
        <isActive>false</isActive>
        <label>Success</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
        <isActive>false</isActive>
        <label>Failure</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <isActive>false</isActive>
        <label>Open</label>
    </customValue>
    <description>Claim stages.</description>
    <masterLabel>Claim Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Correspondence_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Correspondence Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Correspondence_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Widerspruch durch Kunden</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Widerspruch</fullName>
    </customValue>
    <customValue>
        <fullName>Widerspruch durch Anwalt</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Anspruchsschreiben</fullName>
    </customValue>
    <customValue>
        <fullName>Anspruchsschreiben</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Klage</fullName>
    </customValue>
    <customValue>
        <fullName>Klageschrift</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungsschrift</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungsbegründung</fullName>
    </customValue>
    <customValue>
        <fullName>Gerichtskostenrechnung</fullName>
    </customValue>
    <customValue>
        <fullName>Replik</fullName>
    </customValue>
    <customValue>
        <fullName>Vollmacht §141 ZPO</fullName>
    </customValue>
    <customValue>
        <fullName>Eingehend</fullName>
    </customValue>
    <customValue>
        <fullName>Fristverlängerung</fullName>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungserwiderung</fullName>
    </customValue>
    <customValue>
        <fullName>Einspruch</fullName>
        <isActive>false</isActive>
        <label>Einspruch</label>
    </customValue>
    <masterLabel>Correspondence Types</masterLabel>
</GlobalValueSet>

classes/ClaimCorrespondencesTest.cls
@isTest
public class ClaimCorrespondencesTest {
    private static Map<ID, Claim__c> oldMapFromNewList(Claim__c[] cc) {
        Map<ID, Claim__c> oldMap = new Map<ID, Claim__c>();
        for (Claim__c c : cc) {
            Claim__c oldC = new Claim__c(
                Opportunity__c = c.Opportunity__c,
                Stage__c = c.Stage__c,
                Result__c = c.Result__c,
                Cover_Note_Scope__c = c.Cover_Note_Scope__c,
                Cover_Note__c = c.Cover_Note__c
            );
            oldMap.put(c.Id, oldC);
        }
        return oldMap;
    }

    /* * * * * * * * * * * *
     *                     *
     *  Integration tests  *
     *                     *
     * * * * * * * * * * * */

    /*
    // SOQL 101 LIMIT
    @isTest
    public static void testChangeResultIntegration() {
        TriggerConfiguration.allInactive = true;
        Account a = new Account(Name = 'foo');
        insert a;
        Opportunity o = new Opportunity(
            Name = 'foo',
            AccountId = a.Id,
            CloseDate = System.today(),
            StageName = 'On Hold',
            Assignment_Type__c = 'RSV',
            Has_Legal_Protection_Insurance__c = false,
            RecordTypeId = Opportunities.lebensversicherungRecordType()
        );
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Stage__c = 'Appeal',
            Result__c = 'Accepted',
            Cover_Note_Scope__c = 'Appeal',
            Cover_Note__c = 'Issued'
        );
        insert c;

        List<Correspondence__c> corrs;
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Berufungsbegründung'];
        System.assertEquals(0, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Berufungsschrift'];
        System.assertEquals(0, corrs.size());

        TriggerConfiguration.allInactive = false;
        c.Result__c = 'Declined';
        update c;

        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Berufungsbegründung'];
        System.assertEquals(1, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Berufungsschrift'];
        System.assertEquals(1, corrs.size());
    }

    @isTest
    public static void testLegalOppositionLVNoLegalIntegration() {
        TriggerConfiguration.allInactive = true;
        Account a = new Account(Name = 'foo');
        insert a;
        Opportunity o = new Opportunity(
            Name = 'foo',
            AccountId = a.Id,
            CloseDate = System.today(),
            StageName = 'On Hold',
            Assignment_Type__c = 'RSV',
            Has_Legal_Protection_Insurance__c = false,
            RecordTypeId = Opportunities.lebensversicherungRecordType()
        );
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Stage__c = 'Legal Opposition',
            Result__c = 'Accepted',
            Cover_Note_Scope__c = 'Appeal',
            Cover_Note__c = 'Issued'
        );
        insert c;

        List<Correspondence__c> corrs;
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Klageschrift'];
        System.assertEquals(0, corrs.size());

        TriggerConfiguration.allInactive = false;
        c.Result__c = 'Declined';
        update c;

        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Klageschrift'];
        System.assertEquals(0, corrs.size());
    }
	*/

    /* * * * * * * * * * * *
     *                     *
     *      Unit tests     *
     *                     *
     * * * * * * * * * * * */

    @isTest
    public static void testChangeResult() {
        TriggerConfiguration.allInactive = true;
        List<Claim__c> cls = new List<Claim__c>();
        Account a = new Account(Name = 'foo');
        insert a;
        Opportunity o = new Opportunity(
            Name = 'foo',
            AccountId = a.Id,
            CloseDate = System.today(),
            StageName = 'On Hold',
            Assignment_Type__c = 'RSV',
            Has_Legal_Protection_Insurance__c = true,
            RecordTypeId = Opportunities.lebensversicherungRecordType()
        );
        insert o;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;
        }
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Stage__c = 'Appeal',
            Result__c = 'Declined',
            Cover_Note_Scope__c = 'Appeal',
            Cover_Note__c = 'Issued',
            Clerk__c = u.Id
        );
        insert c;
        cls.add(c);
        Claim__c oldC = new Claim__c(
            Opportunity__c = o.Id,
            Stage__c = 'Appeal',
            Result__c = 'Accepted',
            Cover_Note_Scope__c = 'Appeal',
            Cover_Note__c = 'Issued',
            Clerk__c = u.Id
        );
        Map<ID, Claim__c> oldMap = new Map<ID, Claim__c>();
        oldMap.put(c.Id, oldC);

        List<Correspondence__c> corrs;
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Berufungsbegründung'];
        System.assertEquals(0, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Berufungsschrift'];
        System.assertEquals(0, corrs.size());

        ClaimCorrespondences.create(cls, oldMap);

        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Berufungsbegründung'];
        System.assertEquals(1, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Berufungsschrift'];
        System.assertEquals(1, corrs.size());
    }

    @isTest
    public static void testNoChangeResult() {
        TriggerConfiguration.allInactive = true;
        List<Claim__c> cls = new List<Claim__c>();
        Account a = new Account(Name = 'foo');
        insert a;
        Opportunity o = new Opportunity(
            Name = 'foo',
            AccountId = a.Id,
            CloseDate = System.today(),
            StageName = 'On Hold',
            Assignment_Type__c = 'RSV',
            Has_Legal_Protection_Insurance__c = true,
            RecordTypeId = Opportunities.lebensversicherungRecordType()
        );
        insert o;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;
        }
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Stage__c = 'Appeal',
            Result__c = 'Declined',
            Cover_Note_Scope__c = 'Appeal',
            Cover_Note__c = 'Issued',
            Clerk__c = u.Id
        );
        insert c;
        cls.add(c);
        Map<ID, Claim__c> oldMap = oldMapFromNewList(cls);

        List<Correspondence__c> corrs;
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Berufungsbegründung'];
        System.assertEquals(0, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Berufungsschrift'];
        System.assertEquals(0, corrs.size());

        ClaimCorrespondences.create(cls, oldMap);

        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Berufungsbegründung'];
        System.assertEquals(1, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Berufungsschrift'];
        System.assertEquals(1, corrs.size());
    }

    // TODO: this suddenly started to fail on restricted picklist
    @isTest
    public static void testVerteidigungsanzeige() {
        TriggerConfiguration.allInactive = true;
        List<Claim__c> cls = new List<Claim__c>();
        Account a = new Account(Name = 'foo');
        insert a;
        Opportunity o = new Opportunity(
            Name = 'foo',
            AccountId = a.Id,
            CloseDate = System.today(),
            StageName = 'On Hold',
            Assignment_Type__c = 'RSV',
            Has_Legal_Protection_Insurance__c = true
        );
        insert o;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;
        }
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Stage__c = 'Verteidigungsanzeige',
            Result__c = 'Accepted',
            Cover_Note_Scope__c = 'Appeal',
            Cover_Note__c = 'Issued',
            Clerk__c = u.Id
        );
        insert c;
        cls.add(c);
        Map<ID, Claim__c> oldMap = oldMapFromNewList(cls);

        List<Correspondence__c> corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Deckungsanfrage Verteidigungsanzeige'];
        System.assertEquals(0, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Verteidigungsanzeige'];
        System.assertEquals(0, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Fristverlängerung'];
        System.assertEquals(0, corrs.size());

        ClaimCorrespondences.create(cls, oldMap);

        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Deckungsanfrage Verteidigungsanzeige'];
        System.assertEquals(1, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Verteidigungsanzeige'];
        System.assertEquals(1, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Fristverlängerung'];
        System.assertEquals(1, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Berufungserwiderung'];
        System.assertEquals(1, corrs.size());
    }

    @isTest
    public static void testCustomersOppositionFZ() {
        TriggerConfiguration.allInactive = true;
        List<Claim__c> cls = new List<Claim__c>();
        Account a = new Account(Name = 'foo');
        insert a;
        Opportunity o = new Opportunity(
            Name = 'foo',
            AccountId = a.Id,
            CloseDate = System.today(),
            StageName = 'On Hold',
            Assignment_Type__c = 'RSV',
            Has_Legal_Protection_Insurance__c = true,
            RecordTypeId = Opportunities.finanzierungRecordType()
        );
        insert o;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;
        }
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Stage__c = 'Customers Opposition',
            Result__c = 'Accepted',
            Cover_Note_Scope__c = 'Appeal',
            Cover_Note__c = 'Issued',
            Clerk__c = u.Id
        );
        insert c;
        cls.add(c);
        Map<ID, Claim__c> oldMap = oldMapFromNewList(cls);

        List<Correspondence__c> corrs;
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Widerspruch durch Kunden'];
        System.assertEquals(0, corrs.size());

        ClaimCorrespondences.create(cls, oldMap);

        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Widerspruch durch Kunden'];
        System.assertEquals(1, corrs.size());
    }

    @isTest
    public static void testCustomersOppositionLV() {
        TriggerConfiguration.allInactive = true;
        List<Claim__c> cls = new List<Claim__c>();
        Account a = new Account(Name = 'foo');
        a.Type = 'Lebensversicherung';
        a.External_Id__c = 'lv999'; // prio III
        insert a;
        Opportunity o = new Opportunity(
            Name = 'foo',
            AccountId = a.Id,
            CloseDate = System.today(),
            StageName = 'On Hold',
            Assignment_Type__c = 'RSV',
            Has_Legal_Protection_Insurance__c = true,
            RecordTypeId = Opportunities.lebensversicherungRecordType(),
            Termination_Date__c = System.today().addDays(2),
            Expiration_Date__c = System.today().addDays(4),
            Insurance__c = a.Id
        );
        insert o;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;
        }
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Stage__c = 'Customers Opposition',
            Result__c = 'Accepted',
            Cover_Note_Scope__c = 'Appeal',
            Cover_Note__c = 'Issued',
            Clerk__c = u.Id
        );
        insert c;
        cls.add(c);
        Map<ID, Claim__c> oldMap = oldMapFromNewList(cls);

        List<Correspondence__c> corrs;
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Widerspruch durch Kunden'];
        System.assertEquals(0, corrs.size());

        ClaimCorrespondences.create(cls, oldMap);

        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Widerspruch durch Kunden'];
        System.assertEquals(1, corrs.size());
    }

    @isTest
    public static void testLegalOppositionFZ() {
        TriggerConfiguration.allInactive = true;
        List<Claim__c> cls = new List<Claim__c>();
        Account a = new Account(Name = 'foo');
        insert a;
        Opportunity o = new Opportunity(
            Name = 'foo',
            AccountId = a.Id,
            CloseDate = System.today(),
            StageName = 'On Hold',
            Assignment_Type__c = 'RSV',
            Has_Legal_Protection_Insurance__c = true,
            RecordTypeId = Opportunities.finanzierungRecordType()
        );
        insert o;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;
        }
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Stage__c = 'Legal Opposition',
            Result__c = 'Accepted',
            Cover_Note_Scope__c = 'Appeal',
            Cover_Note__c = 'Issued',
            Clerk__c = u.Id
        );
        insert c;
        cls.add(c);
        Map<ID, Claim__c> oldMap = oldMapFromNewList(cls);

        List<Correspondence__c> corrs;
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Deckungsanfrage für Widerspruch'];
        System.assertEquals(0, corrs.size());

        ClaimCorrespondences.create(cls, oldMap);

        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Deckungsanfrage für Widerspruch'];
        System.assertEquals(1, corrs.size());
    }

    @isTest
    public static void testLegalOppositionLV() {
        TriggerConfiguration.allInactive = true;
        List<Claim__c> cls = new List<Claim__c>();
        Account a = new Account(Name = 'foo');
        insert a;
        Opportunity o = new Opportunity(
            Name = 'foo',
            AccountId = a.Id,
            CloseDate = System.today(),
            StageName = 'On Hold',
            Assignment_Type__c = 'RSV',
            Has_Legal_Protection_Insurance__c = true,
            RecordTypeId = Opportunities.lebensversicherungRecordType()
        );
        insert o;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;
        }
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Stage__c = 'Legal Opposition',
            Result__c = 'Declined',
            Cover_Note_Scope__c = 'Appeal',
            Cover_Note__c = 'Issued',
            Clerk__c = u.Id
        );
        insert c;
        cls.add(c);
        Map<ID, Claim__c> oldMap = oldMapFromNewList(cls);

        List<Correspondence__c> corrs;
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Widerspruch durch Anwalt'];
        System.assertEquals(0, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Deckungsanfrage für Widerspruch'];
        System.assertEquals(0, corrs.size());

        ClaimCorrespondences.create(cls, oldMap);

        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Widerspruch durch Anwalt'];
        System.assertEquals(1, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Deckungsanfrage für Widerspruch'];
        System.assertEquals(1, corrs.size());
    }

    @isTest
    public static void testLegalOppositionLVNoLegal() {
        TriggerConfiguration.allInactive = true;
        List<Claim__c> cls = new List<Claim__c>();
        Account a = new Account(Name = 'foo');
        insert a;
        Opportunity o = new Opportunity(
            Name = 'foo',
            AccountId = a.Id,
            CloseDate = System.today(),
            StageName = 'On Hold',
            Assignment_Type__c = 'Share',
            Has_Legal_Protection_Insurance__c = false,
            RecordTypeId = Opportunities.lebensversicherungRecordType()
        );
        insert o;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;
        }
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Stage__c = 'Legal Opposition',
            Result__c = 'Declined',
            Cover_Note_Scope__c = 'Appeal',
            Cover_Note__c = 'Issued',
            Clerk__c = u.Id
        );
        insert c;
        cls.add(c);
        Map<ID, Claim__c> oldMap = oldMapFromNewList(cls);

        List<Correspondence__c> corrs;
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Klageschrift'];
        System.assertEquals(0, corrs.size());

        ClaimCorrespondences.create(cls, oldMap);

        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Klageschrift'];
        System.assertEquals(0, corrs.size());
    }

    @isTest
    public static void testClaimLetter() {
        TriggerConfiguration.allInactive = true;
        List<Claim__c> cls = new List<Claim__c>();
        Account a = new Account(Name = 'foo');
        insert a;
        Opportunity o = new Opportunity(
            Name = 'foo',
            AccountId = a.Id,
            CloseDate = System.today(),
            StageName = 'On Hold',
            Assignment_Type__c = 'RSV',
            Has_Legal_Protection_Insurance__c = true,
            RecordTypeId = Opportunities.lebensversicherungRecordType()
        );
        insert o;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;
        }
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Stage__c = 'Claim Letter',
            Result__c = 'Declined',
            Cover_Note_Scope__c = 'Appeal',
            Cover_Note__c = 'Issued',
            Clerk__c = u.Id
        );
        insert c;
        cls.add(c);
        Map<ID, Claim__c> oldMap = oldMapFromNewList(cls);

        List<Correspondence__c> corrs;
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Deckungsanfrage für Anspruchsschreiben'];
        System.assertEquals(0, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Anspruchsschreiben'];
        System.assertEquals(0, corrs.size());

        ClaimCorrespondences.create(cls, oldMap);

        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Deckungsanfrage für Anspruchsschreiben'];
        System.assertEquals(1, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Anspruchsschreiben'];
        System.assertEquals(1, corrs.size());
    }

    @isTest
    public static void testLawsuit() {
        TriggerConfiguration.allInactive = true;
        List<Claim__c> cls = new List<Claim__c>();
        Account a = new Account(Name = 'foo');
        insert a;
        Opportunity o = new Opportunity(
            Name = 'foo',
            AccountId = a.Id,
            CloseDate = System.today(),
            StageName = 'On Hold',
            Assignment_Type__c = 'RSV',
            Has_Legal_Protection_Insurance__c = true,
            RecordTypeId = Opportunities.lebensversicherungRecordType()
        );
        insert o;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;
        }
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Stage__c = 'Lawsuit',
            Result__c = 'Declined',
            Cover_Note_Scope__c = 'Appeal',
            Cover_Note__c = 'Issued',
            Clerk__c = u.Id
        );
        insert c;
        cls.add(c);
        Map<ID, Claim__c> oldMap = oldMapFromNewList(cls);

        List<Correspondence__c> corrs;
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Klageschrift'];
        System.assertEquals(0, corrs.size());

        ClaimCorrespondences.create(cls, oldMap);

        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Klageschrift'];
        System.assertEquals(1, corrs.size());
    }

    @isTest
    public static void testAppeal() {
        TriggerConfiguration.allInactive = true;
        List<Claim__c> cls = new List<Claim__c>();
        Account a = new Account(Name = 'foo');
        insert a;
        Opportunity o = new Opportunity(
            Name = 'foo',
            AccountId = a.Id,
            CloseDate = System.today(),
            StageName = 'On Hold',
            Assignment_Type__c = 'RSV',
            Has_Legal_Protection_Insurance__c = true,
            RecordTypeId = Opportunities.lebensversicherungRecordType()
        );
        insert o;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;
        }
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Stage__c = 'Appeal',
            Result__c = 'Declined',
            Cover_Note_Scope__c = 'Appeal',
            Cover_Note__c = 'Issued',
            Clerk__c = u.ID
        );
        insert c;
        cls.add(c);
        Map<ID, Claim__c> oldMap = oldMapFromNewList(cls);

        List<Correspondence__c> corrs;
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Replik'];
        System.assertEquals(0, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Deckungsanfrage für Berufung'];
        System.assertEquals(0, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Berufungsschrift'];
        System.assertEquals(0, corrs.size());

        ClaimCorrespondences.create(cls, oldMap);

        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Replik'];
        System.assertEquals(1, corrs.size());
        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Deckungsanfrage für Berufung'];
        System.assertEquals(1, corrs.size());

        corrs = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Berufungsschrift'];
        System.assertEquals(1, corrs.size());
    }
    
    @isTest
    public static void testHackCoverage() {
        new ClaimCorrespondences().HackCoverage();
    }
}