objects/Account.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Abteilung</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Clerk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sachbearbeiter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Clerk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for legal process parts.</description>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Legal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Korrespondenzen</relationshipLabel>
        <relationshipName>Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
</CustomObject>

globalValueSets/Correspondence_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Widerspruch durch Kunden</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Widerspruch</fullName>
    </customValue>
    <customValue>
        <fullName>Widerspruch durch Anwalt</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Anspruchsschreiben</fullName>
    </customValue>
    <customValue>
        <fullName>Anspruchsschreiben</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Klage</fullName>
    </customValue>
    <customValue>
        <fullName>Klageschrift</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungsschrift</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungsbegründung</fullName>
    </customValue>
    <customValue>
        <fullName>Gerichtskostenrechnung</fullName>
    </customValue>
    <customValue>
        <fullName>Replik</fullName>
    </customValue>
    <customValue>
        <fullName>Vollmacht §141 ZPO</fullName>
    </customValue>
    <customValue>
        <fullName>Eingehend</fullName>
    </customValue>
    <customValue>
        <fullName>Fristverlängerung</fullName>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungserwiderung</fullName>
    </customValue>
    <customValue>
        <fullName>Einspruch</fullName>
        <isActive>false</isActive>
        <label>Einspruch</label>
    </customValue>
    <masterLabel>Correspondence Types</masterLabel>
</GlobalValueSet>

classes/ClaimRequestDeductibleTest.cls
@isTest
public class ClaimRequestDeductibleTest {
    private static Claim__c createClaim(string accname) {
        Account a = TestData.createAccount();
        a.name = accname;
        a.Department__c = 'Heinrich Jäger - DG & FZ';
        insert a;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;
        }
        Contact co = new Contact(LastName = 'foo');
        insert co;
        Opportunity o = TestData.createOpportunity(a.ID, 'On Hold');
        o.Backoffice__c = u.Id;
        o.Legal_Account__c = a.Id;
        o.Contact__c = co.Id;
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Clerk__c = u.Id,
            legal__c = u.Id
        );
        return c;
    }

    @isTest
    private static void testNoContact() {
		TriggerConfiguration.allInactive = true;
        Account a = TestData.createAccount();
        a.name = 'J & C Anwälte';
        a.Department__c = 'Heinrich Jäger - DG & FZ';
        insert a;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;
        }
        Opportunity o = TestData.createOpportunity(a.ID, 'On Hold');
        o.Backoffice__c = u.Id;
        o.Legal_Account__c = a.Id;
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Clerk__c = u.Id,
            legal__c = u.Id
        );
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Sonstiges'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ClaimRequestDeductible oe = new ClaimRequestDeductible(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(Errors.page('Bitte hinterlegen Sie einen Kunden auf der Anfrage').getUrl(), pr.getUrl());
    }

    @isTest
    private static void testJC() {
		TriggerConfiguration.allInactive = true;
        Claim__c c = createClaim('J & C Anwälte');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Sonstiges'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ClaimRequestDeductible oe = new ClaimRequestDeductible(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.name.DieselJaegerLegalClaimRequestDeductible)));
    }

    @isTest
    private static void testLegal21() {
		TriggerConfiguration.allInactive = true;
        Claim__c c = createClaim('21Legal GmbH');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Sonstiges'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ClaimRequestDeductible oe = new ClaimRequestDeductible(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.name.Diesel21LegalLegalClaimRequestDeductible)));
    }

    @isTest
    private static void testCLLB() {
		TriggerConfiguration.allInactive = true;
        Claim__c c = createClaim('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Sonstiges'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ClaimRequestDeductible oe = new ClaimRequestDeductible(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.name.DieselKainzLegalClaimRequestDeductible)));
    }

    @isTest
    private static void testElse() {
		TriggerConfiguration.allInactive = true;
        Claim__c c = createClaim('VH24');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Sonstiges'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ClaimRequestDeductible oe = new ClaimRequestDeductible(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.name.DieselLachmairLegalClaimRequestDeductible)));
    }
}