objects/Account.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Abteilung</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Opportunity__r.Account_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unternehmen</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <formula>TEXT(Opportunity__r.Sales_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vertriebstyp</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <formula>Opportunity__r.Vehicle_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fahrzeughersteller</label>
        <type>Text</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Auto_Follow_up_Count__c</fullName>
        <label>Anzahl Auto-Follow-ups</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Date__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Termine</relationshipLabel>
        <relationshipName>Termine</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Representative__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Terminsvertreter</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Termine</relationshipLabel>
        <relationshipName>Termine</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Bezeichnung</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Termin</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Termine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Date_Record__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Termin</label>
        <referenceTo>Date__c</referenceTo>
        <relationshipLabel>Terminprotokolle</relationshipLabel>
        <relationshipName>Date_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Terminprotokoll</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terminprotokolle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Auftragstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assignment_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auto_Follow_up_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Anzahl Auto-Follow-ups</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Has_Legal_Protection_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rechtsschutzversicherung vorhanden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <defaultValue>"Online"</defaultValue>
        <label>Vertriebstyp</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sales_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fahrzeughersteller</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Fahrzeughersteller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Fahrzeughersteller)</relationshipLabel>
        <relationshipName>Opportunities_Fahrzeughersteller</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <businessProcess>Finanzierung</businessProcess>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

globalValueSets/Assignment_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Share</fullName>
    </customValue>
    <customValue>
        <fullName>Direkt</fullName>
    </customValue>
    <customValue>
        <fullName>50%</fullName>
        <isActive>false</isActive>
        <label>50%</label>
    </customValue>
    <customValue>
        <fullName>RSV 20%</fullName>
        <isActive>false</isActive>
        <label>RSV 20%</label>
    </customValue>
    <masterLabel>Assignment Types</masterLabel>
</GlobalValueSet>

globalValueSets/Sales_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
        <default>true</default>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <masterLabel>Sales Types</masterLabel>
</GlobalValueSet>

classes/DateRecordSendMailTest.cls
@isTest
public class DateRecordSendMailTest {
    private static Opportunity createOpp(string legalname) {
        Account la = TestData.createAccount();
        la.name = legalname;
        la.Department__c = 'Heinrich Jäger - DG & FZ';
        insert la;
        Account a = TestData.createAccount();
        a.name = 'VH24';
        insert a;
        Account vehicleBrand = new Account(
            Name = 'TestVehicleBrand',
            Type = 'Fahrzeughersteller'
        );
        insert vehicleBrand;
        Opportunity o = new Opportunity(
            Name = 'TestOpportunity',
            AccountId = a.Id,
            CloseDate = System.today(),
            StageName = 'On Hold',
            Sent_Mail_Flag_1__c = true,
            Sent_Mail_Flag_2__c = true,
            Assignment_Type__c = 'RSV',
            Has_Legal_Protection_Insurance__c = true,
            Auto_Follow_up_Count__c = 0,
            Sales_Type__c = 'Online',
            Vehicle_Brand__c = vehicleBrand.Id
        );
        o.Account__c = a.Id;
        o.Legal_Account__c = la.Id;
        Contact c = new Contact(FirstName = 'foo', LastName = 'bar', Email = 'baz@de.de');
        insert c;
        o.Contact__c = c.Id;
        return o;
    }

    /* * * * * * * * *
     * Dieselskandal *
     * * * * * * * * */

    @isTest
    private static void testDieselSkandalJCLegalNoRec() {
        TriggerConfiguration.allInactive = true;
        Opportunity o = createOpp('J & C Anwälte');
        o.recordTypeId = Opportunities.dieselSkandalRecordType();
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id
        );
        insert c;
        Date__c d = new Date__c(
            Claim__c = c.Id,
            Date__c = System.today().addDays(2),
            Subject__c = 'foo',
            Representative__c = null
        );
        insert d;
        Date_Record__c dr = new Date_Record__c(
            Date__c = d.Id
        );
        insert dr;

        Apexpages.StandardController sc = new Apexpages.standardController(dr);
        DateRecordSendMail oe = new DateRecordSendMail(sc);

        PageReference pr = oe.renderPage();

        System.assertEquals(pr, null);
        System.assertEquals('einen "Terminsvertreter" auf dem Termin', oe.errorMsg);
    }

    @isTest
    private static void testDieselSkandalJCLegal() {
        TriggerConfiguration.allInactive = true;
        Opportunity o = createOpp('J & C Anwälte');
        o.recordTypeId = Opportunities.dieselSkandalRecordType();
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id
        );
        insert c;
        Date__c d = new Date__c(
            Claim__c = c.Id,
            Date__c = System.today().addDays(2),
            Subject__c = 'foo',
            Representative__c = o.Contact__c
        );
        insert d;
        Date_Record__c dr = new Date_Record__c(
            Date__c = d.Id
        );
        insert dr;

        Apexpages.StandardController sc = new Apexpages.standardController(dr);
        DateRecordSendMail oe = new DateRecordSendMail(sc);

        PageReference pr = oe.renderPage();

        System.assertNotEquals(pr, null);
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.LegalDate.DieselJaegerLegalDateRecord)), 'template not found');
        System.assertNotEquals('einen "Terminsvertreter" auf dem Termin', oe.errorMsg);

        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }

    @isTest
    private static void testDieselSkandalLeCom() {
        TriggerConfiguration.allInactive = true;
        Opportunity o = createOpp('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        o.recordTypeId = Opportunities.dieselSkandalRecordType();
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id
        );
        insert c;
        Date__c d = new Date__c(
            Claim__c = c.Id,
            Date__c = System.today().addDays(2),
            Subject__c = 'foo',
            Representative__c = o.Contact__c
        );
        insert d;
        Date_Record__c dr = new Date_Record__c(
            Date__c = d.Id
        );
        insert dr;

        Apexpages.StandardController sc = new Apexpages.standardController(dr);
        DateRecordSendMail oe = new DateRecordSendMail(sc);

        PageReference pr = oe.renderPage();

        System.assertNotEquals(pr, null);
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.LegalDate.DieselLeComLegalDateRecord)), 'template not found');
        System.assertNotEquals('einen "Terminsvertreter" auf dem Termin', oe.errorMsg);

        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }

    @isTest
    private static void testDieselSkandalCllb() {
        TriggerConfiguration.allInactive = true;
        Opportunity o = createOpp('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        o.recordTypeId = Opportunities.dieselSkandalRecordType();
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id
        );
        insert c;
        Date__c d = new Date__c(
            Claim__c = c.Id,
            Date__c = System.today().addDays(2),
            Subject__c = 'foo',
            Representative__c = o.Contact__c
        );
        insert d;
        Date_Record__c dr = new Date_Record__c(
            Date__c = d.Id
        );
        insert dr;

        Apexpages.StandardController sc = new Apexpages.standardController(dr);
        DateRecordSendMail oe = new DateRecordSendMail(sc);

        PageReference pr = oe.renderPage();

        System.assertNotEquals(pr, null);
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.LegalDate.DieselKainzLegalDateRecord)), 'template not found');
        System.assertNotEquals('einen "Terminsvertreter" auf dem Termin', oe.errorMsg);

        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }

    /* * * * * * * * *
     * Finanzierung  *
     * * * * * * * * */

    @isTest
    private static void testFinanzierungJCLegal() {
        TriggerConfiguration.allInactive = true;
        Opportunity o = createOpp('J & C Anwälte');
        o.recordTypeId = Opportunities.FinanzierungRecordType();
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id
        );
        insert c;
        Date__c d = new Date__c(
            Claim__c = c.Id,
            Date__c = System.today().addDays(2),
            Subject__c = 'foo',
            Representative__c = o.Contact__c
        );
        insert d;
        Date_Record__c dr = new Date_Record__c(
            Date__c = d.Id
        );
        insert dr;

        Apexpages.StandardController sc = new Apexpages.standardController(dr);
        DateRecordSendMail oe = new DateRecordSendMail(sc);

        PageReference pr = oe.renderPage();

        System.assertNotEquals(pr, null);
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.LegalDate.FzJaegerLegalDateRecord)), 'template not found');
        System.assertNotEquals('einen "Terminsvertreter" auf dem Termin', oe.errorMsg);

        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }

    @isTest
    private static void testFinanzierungLeCom() {
        TriggerConfiguration.allInactive = true;
        Opportunity o = createOpp('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        o.recordTypeId = Opportunities.FinanzierungRecordType();
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id
        );
        insert c;
        Date__c d = new Date__c(
            Claim__c = c.Id,
            Date__c = System.today().addDays(2),
            Subject__c = 'foo',
            Representative__c = o.Contact__c
        );
        insert d;
        Date_Record__c dr = new Date_Record__c(
            Date__c = d.Id
        );
        insert dr;

        Apexpages.StandardController sc = new Apexpages.standardController(dr);
        DateRecordSendMail oe = new DateRecordSendMail(sc);

        PageReference pr = oe.renderPage();

        System.assertNotEquals(pr, null);
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.LegalDate.FzLeComLegalDateRecord)), 'template not found');
        System.assertNotEquals('einen "Terminsvertreter" auf dem Termin', oe.errorMsg);

        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }

    @isTest
    private static void testFinanzierungCllb() {
        TriggerConfiguration.allInactive = true;
        Opportunity o = createOpp('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        o.recordTypeId = Opportunities.FinanzierungRecordType();
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id
        );
        insert c;
        Date__c d = new Date__c(
            Claim__c = c.Id,
            Date__c = System.today().addDays(2),
            Subject__c = 'foo',
            Representative__c = o.Contact__c
        );
        insert d;
        Date_Record__c dr = new Date_Record__c(
            Date__c = d.Id
        );
        insert dr;

        Apexpages.StandardController sc = new Apexpages.standardController(dr);
        DateRecordSendMail oe = new DateRecordSendMail(sc);

        PageReference pr = oe.renderPage();

        System.assertNotEquals(pr, null);
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.LegalDate.FzKainzLegalDateRecord)), 'template not found');
        System.assertNotEquals('einen "Terminsvertreter" auf dem Termin', oe.errorMsg);

        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }

    /* * * * * * * * * * * *
     * Lebensversicherung  *
     * * * * * * * * * * * */

    @isTest
    private static void testLebensversicherungJCLegal() {
        TriggerConfiguration.allInactive = true;
        Opportunity o = createOpp('J & C Anwälte');
        o.recordTypeId = Opportunities.LebensversicherungRecordType();
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id
        );
        insert c;
        Date__c d = new Date__c(
            Claim__c = c.Id,
            Date__c = System.today().addDays(2),
            Subject__c = 'foo',
            Representative__c = o.Contact__c
        );
        insert d;
        Date_Record__c dr = new Date_Record__c(
            Date__c = d.Id
        );
        insert dr;

        Apexpages.StandardController sc = new Apexpages.standardController(dr);
        DateRecordSendMail oe = new DateRecordSendMail(sc);

        PageReference pr = oe.renderPage();

        System.assertNotEquals(pr, null);
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.LegalDate.LvJaegerLegalDateRecord)), 'template not found');
        System.assertNotEquals('einen "Terminsvertreter" auf dem Termin', oe.errorMsg);

        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }

    @isTest
    private static void testLebensversicherungLeCom() {
        TriggerConfiguration.allInactive = true;
        Opportunity o = createOpp('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        o.recordTypeId = Opportunities.LebensversicherungRecordType();
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id
        );
        insert c;
        Date__c d = new Date__c(
            Claim__c = c.Id,
            Date__c = System.today().addDays(2),
            Subject__c = 'foo',
            Representative__c = o.Contact__c
        );
        insert d;
        Date_Record__c dr = new Date_Record__c(
            Date__c = d.Id
        );
        insert dr;

        Apexpages.StandardController sc = new Apexpages.standardController(dr);
        DateRecordSendMail oe = new DateRecordSendMail(sc);

        PageReference pr = oe.renderPage();

        System.assertNotEquals(pr, null);
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.LegalDate.LvLeComLegalDateRecord)), 'template not found');
        System.assertNotEquals('einen "Terminsvertreter" auf dem Termin', oe.errorMsg);

        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }

    @isTest
    private static void testLebensversicherungCllb() {
        TriggerConfiguration.allInactive = true;
        Opportunity o = createOpp('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        o.recordTypeId = Opportunities.LebensversicherungRecordType();
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id
        );
        insert c;
        Date__c d = new Date__c(
            Claim__c = c.Id,
            Date__c = System.today().addDays(2),
            Subject__c = 'foo',
            Representative__c = o.Contact__c
        );
        insert d;
        Date_Record__c dr = new Date_Record__c(
            Date__c = d.Id
        );
        insert dr;

        Apexpages.StandardController sc = new Apexpages.standardController(dr);
        DateRecordSendMail oe = new DateRecordSendMail(sc);

        PageReference pr = oe.renderPage();

        System.assertNotEquals(pr, null);
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.LegalDate.LvKainzLegalDateRecord)), 'template not found');
        System.assertNotEquals('einen "Terminsvertreter" auf dem Termin', oe.errorMsg);

        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }
}