objects/Account.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Abteilung</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <formula>TEXT(Opportunity__r.Sales_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vertriebstyp</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <formula>Opportunity__r.Vehicle_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fahrzeughersteller</label>
        <type>Text</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Auto_Follow_up_Count__c</fullName>
        <label>Anzahl Auto-Follow-ups</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipName>Cost_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <label>Empfänger</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Recipients</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Betreff</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Kostennote</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostennoten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Auftragstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assignment_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auto_Follow_up_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Anzahl Auto-Follow-ups</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Has_Legal_Protection_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rechtsschutzversicherung vorhanden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Protection_Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rechtsschutzversicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Rechtsschutzversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Rechtsschutzversicherung)</relationshipLabel>
        <relationshipName>Opportunities_Legal_Protection_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <defaultValue>"Online"</defaultValue>
        <label>Vertriebstyp</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sales_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fahrzeughersteller</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Fahrzeughersteller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Fahrzeughersteller)</relationshipLabel>
        <relationshipName>Opportunities_Fahrzeughersteller</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <businessProcess>Finanzierung</businessProcess>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

globalValueSets/Assignment_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Share</fullName>
    </customValue>
    <customValue>
        <fullName>Direkt</fullName>
    </customValue>
    <customValue>
        <fullName>50%</fullName>
        <isActive>false</isActive>
        <label>50%</label>
    </customValue>
    <customValue>
        <fullName>RSV 20%</fullName>
        <isActive>false</isActive>
        <label>RSV 20%</label>
    </customValue>
    <masterLabel>Assignment Types</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Recipients.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Customer</fullName>
        <default>true</default>
        <label>Kunde</label>
    </customValue>
    <customValue>
        <fullName>Legal Protection Insurance</fullName>
        <label>Rechtsschutzversicherung</label>
    </customValue>
    <masterLabel>Cost Note Recipients</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Außergerichtlich</fullName>
    </customValue>
    <customValue>
        <fullName>I. Instanz</fullName>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Selbstbehalt</fullName>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Abschluss</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Cost Note Types</masterLabel>
</GlobalValueSet>

globalValueSets/Sales_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
        <default>true</default>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <masterLabel>Sales Types</masterLabel>
</GlobalValueSet>

classes/SendCostNoteTest.cls
@isTest
public class SendCostNoteTest {
    public static Opportunity createOpp(string legalName) {
        TriggerConfiguration.allInactive = true;
        Account vehicleBrand = new Account(
            Name = 'TestVehicleBrand',
            Type = 'Fahrzeughersteller'
        );
        insert vehicleBrand;
        Account a = new Account(Name = legalName, Department__c = 'Heinrich Jäger - DG & FZ', Type = 'Rechtsschutzversicherung');
        insert a;
        Contact con = new Contact(
            FirstName = 'Foo',
            LastName = 'Bar'
        );
        insert con;
        Opportunity opp = new Opportunity(
            Name = 'TestOpportunity',
            AccountId = a.Id,
            Legal_Account__c = a.Id,
            CloseDate = System.today(),
            StageName = 'On Hold',
            Sent_Mail_Flag_1__c = true,
            Sent_Mail_Flag_2__c = true,
            Contact__c = con.Id,
            Assignment_Type__c = 'RSV',
            Has_Legal_Protection_Insurance__c = true,
            Auto_Follow_up_Count__c = 0,
            Sales_Type__c = 'Online',
            Vehicle_Brand__c = vehicleBrand.Id,
            Legal_Protection_Insurance__c = a.Id
        );
        return opp;
    }

    @isTest
    private static void testErrorContact() {
        Opportunity o = createOpp('foo');
        o.Contact__c = null;
        insert o;
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();
        System.assertEquals(Errors.page('Bitte tragen Sie ein Kontakt auf dem Feld "Kunde" ein.').getUrl(), pr.getUrl());
    }

    /* * * * * * * * *
     * Dieselskandal *
	 * * * * * * * * */

    @isTest
    private static void testDGCustomerJC() {
        Opportunity o = createOpp('J & C Anwälte');
        insert o;
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Customer'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.DieselJaegerLegalCostNoteCustomer) +
            '&recipient=' + o.Contact__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }

    @isTest
    private static void testDGInsuranceJC() {
        Opportunity o = createOpp('J & C Anwälte');
        insert o;
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Legal Protection Insurance'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.DieselJaegerLegalCostNoteInsurance) +
            '&recipient=' + o.Legal_Protection_Insurance__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }

    @isTest
    private static void testDGCustomerLeCom() {
        Opportunity o = createOpp('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        insert o;
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Customer'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.DieselLeComLegalCostNoteCustomer) +
            '&recipient=' + o.Contact__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }

    @isTest
    private static void testDGInsuranceLeCom() {
        Opportunity o = createOpp('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        insert o;
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Legal Protection Insurance'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.DieselLeComLegalCostNoteInsurance) +
            '&recipient=' + o.Legal_Protection_Insurance__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }

    @isTest
    private static void testDGCustomerCllb() {
        Opportunity o = createOpp('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        insert o;
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Customer'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.DieselKainzLegalCostNoteCustomer) +
            '&recipient=' + o.Contact__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }

    @isTest
    private static void testDGInsuranceCllb() {
        Opportunity o = createOpp('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        insert o;
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Legal Protection Insurance'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.DieselKainzLegalCostNoteInsurance) +
            '&recipient=' + o.Legal_Protection_Insurance__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }

    /* * * * * * * * *
     * Finanzierung  *
	 * * * * * * * * */

    @isTest
    private static void testFZCustomerJC() {
        Opportunity o = createOpp('J & C Anwälte');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Finanzierung' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.Id;
        insert o;
        rt = [SELECT ID FROM RecordType WHERE Name='Finanzierung' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Customer'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.FZJaegerLegalCostNoteCustomer) +
            '&recipient=' + o.Contact__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }

    @isTest
    private static void testFZInsuranceJC() {
        Opportunity o = createOpp('J & C Anwälte');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Finanzierung' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.Id;
        insert o;
        rt = [SELECT ID FROM RecordType WHERE Name='Finanzierung' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Legal Protection Insurance'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.FZJaegerLegalCostNoteInsurance) +
            '&recipient=' + o.Legal_Protection_Insurance__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }

    @isTest
    private static void testFZCustomerLeCom() {
        Opportunity o = createOpp('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Finanzierung' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.Id;
        insert o;
        rt = [SELECT ID FROM RecordType WHERE Name='Finanzierung' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Customer'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.FZLeComLegalCostNoteCustomer) +
            '&recipient=' + o.Contact__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }

    @isTest
    private static void testFZInsuranceLeCom() {
        Opportunity o = createOpp('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Finanzierung' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.Id;
        insert o;
        rt = [SELECT ID FROM RecordType WHERE Name='Finanzierung' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Legal Protection Insurance'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.FZLeComLegalCostNoteInsurance) +
            '&recipient=' + o.Legal_Protection_Insurance__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }

    @isTest
    private static void testFZCustomerCllb() {
        Opportunity o = createOpp('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Finanzierung' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.Id;
        insert o;
        rt = [SELECT ID FROM RecordType WHERE Name='Finanzierung' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Customer'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.FZKainzLegalCostNoteCustomer) +
            '&recipient=' + o.Contact__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }

    @isTest
    private static void testFZInsuranceCllb() {
        Opportunity o = createOpp('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Finanzierung' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.Id;
        insert o;
        rt = [SELECT ID FROM RecordType WHERE Name='Finanzierung' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Legal Protection Insurance'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.FZKainzLegalCostNoteInsurance) +
            '&recipient=' + o.Legal_Protection_Insurance__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }

    /* * * * * * * * * * * *
     * Finanzierung  *
	 * * * * * * * * * * * */

    @isTest
    private static void testLVNoInsurance() {
        Opportunity o = createOpp('J & C Anwälte');
        o.Legal_Protection_Insurance__c = null;
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Lebensversicherung' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.Id;
        insert o;
        rt = [SELECT ID FROM RecordType WHERE Name='Lebensversicherung' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Customer'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();
        System.assertEquals(Errors.page('Bitte tragen Sie eine "Rechtsschutzversicherung" auf der Anfrage ein.').getUrl(), pr.getUrl());
    }

    @isTest
    private static void testLVCustomerJC() {
        Opportunity o = createOpp('J & C Anwälte');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Lebensversicherung' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.Id;
        insert o;
        rt = [SELECT ID FROM RecordType WHERE Name='Lebensversicherung' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Customer'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.LvJaegerLegalCostNoteCustomer) +
            '&recipient=' + o.Contact__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }

    @isTest
    private static void testLVInsuranceJC() {
        Opportunity o = createOpp('J & C Anwälte');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Lebensversicherung' AND sObjectType = 'Opportunity'];
				o.recordTypeId = rt.Id;
        insert o;
        rt = [SELECT ID FROM RecordType WHERE Name='Lebensversicherung' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Legal Protection Insurance'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.LvJaegerLegalCostNoteInsurance) +
            '&recipient=' + o.Legal_Protection_Insurance__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }

    @isTest
    private static void testLVCustomerLeCom() {
        Opportunity o = createOpp('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Lebensversicherung' AND sObjectType = 'Opportunity'];
				o.recordTypeId = rt.Id;
        insert o;
        rt = [SELECT ID FROM RecordType WHERE Name='Lebensversicherung' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Customer'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.LvLeComLegalCostNoteCustomer) +
            '&recipient=' + o.Contact__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }

    @isTest
    private static void testLVInsuranceLeCom() {
        Opportunity o = createOpp('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Lebensversicherung' AND sObjectType = 'Opportunity'];
				o.recordTypeId = rt.Id;
        insert o;
        rt = [SELECT ID FROM RecordType WHERE Name='Lebensversicherung' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Legal Protection Insurance'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.LvLeComLegalCostNoteInsurance) +
            '&recipient=' + o.Legal_Protection_Insurance__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }

    @isTest
    private static void testLVCustomerCllb() {
        Opportunity o = createOpp('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Lebensversicherung' AND sObjectType = 'Opportunity'];
				o.recordTypeId = rt.Id;
        insert o;
        rt = [SELECT ID FROM RecordType WHERE Name='Lebensversicherung' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Customer'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.LvKainzLegalCostNoteCustomer) +
            '&recipient=' + o.Contact__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }

    @isTest
    private static void testLVInsuranceCllb() {
        Opportunity o = createOpp('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Lebensversicherung' AND sObjectType = 'Opportunity'];
				o.recordTypeId = rt.Id;
        insert o;
        rt = [SELECT ID FROM RecordType WHERE Name='Lebensversicherung' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
            Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
            Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges',
            Recipient__c = 'Legal Protection Insurance'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendCostNote oe = new SendCostNote(sc);

        PageReference pr = oe.renderPage();

        string url = page.sendMail.getUrl() +
            '?id=' + c.Id +
            '&tpl=' + EmailTemplates.idOf(EmailTemplates.CostNote.LvKainzLegalCostNoteInsurance) +
            '&recipient=' + o.Legal_Protection_Insurance__c +
            '&hdl=Kostennote versenden' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
        System.assertEquals(new PageReference(url).getUrl(), pr.getUrl());
    }
}