objects/Account.object
<CustomObject>
    <fields>
        <fullName>Test__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Extrajudicial_Cost_Note_Number__c</fullName>
        <label>Nummer der ag. Kostennote</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <formula>Opportunity__r.Test__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <formula>TEXT(Last_Opportunity__r.StageName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipName>Cost_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Nummer</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <label>Empfänger</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Recipients</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <formula>Claim__r.Opportunity__r.Test__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Kostennote</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostennoten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Note__c</fullName>
        <label>Kostennote</label>
        <referenceTo>Cost_Note__c</referenceTo>
        <relationshipLabel>Kostenpunkte</relationshipLabel>
        <relationshipName>Cost_Note_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Line_Item_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Kostenpunkt</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostenpunkte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note_Reminder__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Note__c</fullName>
        <label>Kostennote</label>
        <referenceTo>Cost_Note__c</referenceTo>
        <relationshipLabel>Mahnungen</relationshipLabel>
        <relationshipName>Cost_Note_Reminders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <label>Empfänger</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Recipients</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reminder_Stages</valueSetName>
        </valueSet>
    </fields>
    <label>Mahnung</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mahnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Date__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Termine</relationshipLabel>
        <relationshipName>Termine</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Date_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Date_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Termin</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Termine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Callcenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for call center process parts.</description>
        <label>Callcenter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Callcenter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Bearbeitungsnummer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Claim_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Entwurf</label>
    </customValue>
    <customValue>
        <fullName>Customers Opposition</fullName>
        <label>Kundenwiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Legal Opposition</fullName>
        <label>Anwaltswiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Claim Letter</fullName>
        <label>Anspruchsschreiben</label>
    </customValue>
    <customValue>
        <fullName>Lawsuit</fullName>
        <label>Klage</label>
    </customValue>
    <customValue>
        <fullName>Class Action</fullName>
        <label>Sammelklage</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
        <label>Abwicklung</label>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
        <label>Abgeschlossen</label>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <label>Warten auf Grundsatzurteil</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>Abbruch</label>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Examination</fullName>
        <isActive>false</isActive>
        <label>Examination</label>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
        <isActive>false</isActive>
        <label>Success</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
        <isActive>false</isActive>
        <label>Failure</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <isActive>false</isActive>
        <label>Open</label>
    </customValue>
    <description>Claim stages.</description>
    <masterLabel>Claim Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Line_Item_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Außergerichtlich</fullName>
    </customValue>
    <customValue>
        <fullName>I. Instanz</fullName>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Cost Note Line Item Types</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Recipients.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Customer</fullName>
        <default>true</default>
        <label>Kunde</label>
    </customValue>
    <customValue>
        <fullName>Legal Protection Insurance</fullName>
        <label>Rechtsschutzversicherung</label>
    </customValue>
    <masterLabel>Cost Note Recipients</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Replaced</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Cost Note Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Außergerichtlich</fullName>
    </customValue>
    <customValue>
        <fullName>I. Instanz</fullName>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Selbstbehalt</fullName>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Abschluss</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Cost Note Types</masterLabel>
</GlobalValueSet>

globalValueSets/Date_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Open</fullName>
        <default>true</default>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Date Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Date_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Gerichtstermin</fullName>
        <default>true</default>
        <label>Gerichtstermin</label>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Date Types</masterLabel>
</GlobalValueSet>

globalValueSets/Reminder_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Reminder Stages</masterLabel>
</GlobalValueSet>

classes/CostNoteTriggerHandlerTests.cls
@isTest
public class CostNoteTriggerHandlerTests {
	// todo:
	@isTest
    private static void testSetClaimExtrajudicialCostNoteNumber() {
         ClaimTriggerhandler.Deactivate = true;
        User u = TestData.legalUser();
        Claim__c c = ClaimsTests.buildClaim(u, null, 0, null, null);
        c.extrajudicial_Cost_Note_Number__c = null;
        insert c;

    	Cost_Note__c cn = TestData.createCostNote(c.ID, 'Draft');
        cn.type__c = 'Außergerichtlich';
        cn.number__c = '12345';
        insert cn;

        Test.startTest();
        cn.stage__c = 'Sent';
        update cn;
        Test.stopTest();

        c = [SELECT Extrajudicial_Cost_Note_Number__c FROM Claim__c];
        System.assertEquals('12345', c.extrajudicial_Cost_Note_Number__c);
    }

    /*******************
     * setNumber tests *
     *******************/

	@isTest
	static void testNotCustomerDgInsert() {
		// Testsetup
		TriggerConfiguration.allInactive = true;
        ClaimTriggerhandler.Deactivate = true;

		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id, 'New');
		opportunity.RecordTypeId = Opportunities.dieselSkandalRecordType();
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
		insert claim;
		Cost_Note__c costNote = TestData.createCostNote(claim.Id, 'Draft');
        costNote.Type__c = 'Sonstiges';
		costNote.Recipient__c = 'Legal Protection Insurance';

		TriggerConfiguration.allInactive = false;

		// Test
		Test.startTest();

		insert costNote;

		Test.stopTest();

		// Assertion
		costNote = [select Id, Number__c from Cost_Note__c where Id = :costNote.Id];
        System.assertEquals(String.valueOf(System.now().date().year()) + '000001/DG', costNote.Number__c);
	}

	@isTest
	static void testNotCustomerDgUpdate() {
		// Testsetup
		TriggerConfiguration.allInactive = true;
		ClaimTriggerhandler.Deactivate = true;
		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id, 'New');
		opportunity.RecordTypeId = Opportunities.dieselSkandalRecordType();
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
		insert claim;
		Cost_Note__c costNote = TestData.createCostNote(claim.Id, 'Draft');
		costNote.Recipient__c = 'Legal Protection Insurance';
		costNote.Date__c = null;
        costNote.Type__c = 'Sonstiges';
		insert costNote;

		TriggerConfiguration.allInactive = false;

		// Test
		Test.startTest();

		costNote.Date__c = System.today();
		update costNote;

		Test.stopTest();

		// Assertion
		costNote = [select Id, Number__c from Cost_Note__c where Id = :costNote.Id];
		System.assertEquals(String.valueOf(System.now().date().year()) + '000001/DG', costNote.Number__c);
	}

	@isTest
	static void testNotCustomerFzInsert() {
		// Testsetup
		TriggerConfiguration.allInactive = true;
		ClaimTriggerhandler.Deactivate = true;
		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id, 'New');
		opportunity.RecordTypeId = Opportunities.finanzierungRecordType();
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
		insert claim;
		Cost_Note__c costNote = TestData.createCostNote(claim.Id, 'Draft');
		costNote.Recipient__c = 'Legal Protection Insurance';
        costNote.Type__c = 'Sonstiges';

		TriggerConfiguration.allInactive = false;

		// Test
		Test.startTest();

		insert costNote;

		Test.stopTest();

		// Assertion
		costNote = [select Id, Number__c from Cost_Note__c where Id = :costNote.Id];
		System.assertEquals(String.valueOf(System.now().date().year()) + '000001/CVRFZ', costNote.Number__c);
	}

	@isTest
	static void testNotCustomerFzUpdate() {
		// Testsetup
		TriggerConfiguration.allInactive = true;
		ClaimTriggerhandler.Deactivate = true;
		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id, 'New');
		opportunity.RecordTypeId = Opportunities.finanzierungRecordType();
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
		insert claim;
		Cost_Note__c costNote = TestData.createCostNote(claim.Id, 'Draft');
		costNote.Recipient__c = 'Legal Protection Insurance';
		costNote.Date__c = null;
        costNote.Type__c = 'Sonstiges';
		insert costNote;

		TriggerConfiguration.allInactive = false;

		// Test
		Test.startTest();

		costNote.Date__c = System.today();
		update costNote;

		Test.stopTest();

		// Assertion
		costNote = [select Id, Number__c from Cost_Note__c where Id = :costNote.Id];
		System.assertEquals(String.valueOf(System.now().date().year()) + '000001/CVRFZ', costNote.Number__c);
	}

	@isTest
	static void testNotCustomerLvInsert() {
		// Testsetup
		TriggerConfiguration.allInactive = true;
		ClaimTriggerhandler.Deactivate = true;
        User user = TestData.createUser();
        insert user;
		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id, 'New');
        opportunity.RecordTypeID = Opportunities.lebensversicherungRecordType();
        opportunity.Callcenter__c = user.Id;
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
		insert claim;
		Cost_Note__c costNote = TestData.createCostNote(claim.Id, 'Draft');
		costNote.Recipient__c = 'Legal Protection Insurance';
        costNote.Type__c = 'Sonstiges';

		TriggerConfiguration.allInactive = false;

		// Test
		Test.startTest();

		insert costNote;

		Test.stopTest();

		// Assertion
		costNote = [select Id, Number__c from Cost_Note__c where Id = :costNote.Id];
		System.assertEquals(String.valueOf(System.now().date().year()) + '000001/21VRLV', costNote.Number__c);
	}

	@isTest
	static void testCustomerInsert() {
		// Testsetup
		TriggerConfiguration.allInactive = true;
		ClaimTriggerhandler.Deactivate = true;

		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id, 'New');
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
		insert claim;
		Cost_Note__c costNote = TestData.createCostNote(claim.Id, 'Draft');
		costNote.Recipient__c = 'Customer';
        costNote.Type__c = 'Sonstiges';

		TriggerConfiguration.allInactive = false;

		// Test
		Test.startTest();

		insert costNote;

		Test.stopTest();

		// Assertion
		costNote = [select Id, Number__c from Cost_Note__c where Id = :costNote.Id];
		System.assert(costNote.Number__c == null);
	}

	@isTest
	static void testTestInsert() {
		// Testsetup
		TriggerConfiguration.allInactive = true;
		ClaimTriggerhandler.Deactivate = true;

		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id, 'New');
		opportunity.Test__c = true;
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
		insert claim;
		Cost_Note__c costNote = TestData.createCostNote(claim.Id, 'Draft');
		costNote.Recipient__c = 'Legal Protection Insurance';
        costNote.Type__c = 'Sonstiges';

		TriggerConfiguration.allInactive = false;

		// Test
		Test.startTest();

		insert costNote;

		Test.stopTest();

		// Assertion
		costNote = [select Id, Number__c from Cost_Note__c where Id = :costNote.Id];
        System.assertEquals(String.valueOf(System.now().date().year()) + '000001/Test', costNote.Number__c);
	}

    /******************************
     * setRemindersCanceled tests *
     ******************************/

	@isTest
	static void testDraft(){
		// Testsetup
		TriggerConfiguration.allInactive = true;
		ClaimTriggerhandler.Deactivate = true;

		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id, 'New');
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
		insert claim;
		Cost_Note__c costNote = TestData.createCostNote(claim.Id, 'Sent');
        costNote.Type__c = 'Sonstiges';
        costNote.stage__c = 'Sent';
		insert costNote;
		Cost_Note_Line_Item__c costNoteLineItem = TestData.createCostNoteLineItem(costNote.Id, 10000);
        costNoteLineItem.Type__c = 'Sonstiges';
		insert costNoteLineItem;
		Cost_Note_Reminder__c costNoteReminder = TestData.createCostNoteReminder(costNote.Id, 'Draft');
		insert costNoteReminder;

        costNote = [SELECT Id, (SELECT ID, Stage__c FROM Cost_Note_Reminders__r) FROM Cost_Note__c WHERE Id = :costNote.Id];
        TriggerConfiguration.allInactive = false;
        costNote.stage__c = 'Sent';
        update costNote;
		// Test
		Test.startTest();

		costNote.Stage__c = 'Paid';
		update costNote;

		Test.stopTest();

		// Assertion
		costNoteReminder = [SELECT Id, Stage__c FROM Cost_Note_Reminder__c WHERE Id = :costNoteReminder.Id];
		System.AssertEquals('Canceled', costNoteReminder.Stage__c);
	}
}