objects/Account.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Abteilung</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auto_Follow_up_Date__c</fullName>
        <label>Nächstes Auto-Follow-up</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Callcenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for call center process parts.</description>
        <label>Callcenter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Callcenter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

classes/OppStartAutoFollowUpTest.cls
@isTest
public class OppStartAutoFollowUpTest {
    private static Opportunity createOpp(string accname, string legalname, boolean isCallcenter) {
        Account la = TestData.createAccount();
        la.name = legalname;
        la.Department__c = 'Heinrich Jäger - DG & FZ';
        insert la;

		User u = TestData.createUser();
        insert u;
        Account a = TestData.createAccount();
        a.name = accname;
        insert a;
        Opportunity o = TestData.createOpportunity(a.ID, 'On Hold');
        o.Account__c = a.Id;
        o.Legal_Account__c = la.Id;
        o.Backoffice__c = u.Id;
        if (isCallcenter == true) {
            o.Callcenter__c = u.Id;
            o.Callcenter__r = u;
        }
        return o;
    }

    @isTest
    private static void testNoCallcenter() {
        Opportunity o = createOpp('VH24', 'J & C Anwälte', false);
        o.RecordTypeId = Opportunities.lebensversicherungRecordType();
        insert o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        OppStartAutoFollowUp oe = new OppStartAutoFollowUp(sc);

        // Act
        PageReference pr = oe.renderPage();

        // should not create a task when the callcenter is missing
        List<Task> ts = [SELECT Id FROM Task];
        System.assertEquals(0, ts.size());
    }

    @isTest
    private static void testStageNew() {
        Opportunity o = createOpp('VR24', 'J & C Anwälte', true);
        o.recordTypeId = Opportunities.lebensversicherungRecordType();
        o.StageName = 'New';
        insert o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        OppStartAutoFollowUp oe = new OppStartAutoFollowUp(sc);

        // Act
        PageReference pr = oe.renderPage();
        o = [SELECT Id, Auto_Follow_up_Date__c FROM Opportunity WHERE Id = :o.Id];
        Datetime nowDate = System.now();
        Datetime resDate = o.Auto_Follow_up_Date__c;
        System.assertEquals(nowDate.year(), resDate.year());
        System.assertEquals(nowDate.month(), resDate.month());
        System.assertEquals(nowDate.day(), resDate.day());
        System.assertEquals(nowDate.hour(), resDate.hour());
    }

    @isTest
    private static void testStageCheck() {
        Opportunity o = createOpp('VR24', 'J & C Anwälte', true);
        o.recordTypeId = Opportunities.lebensversicherungRecordType();
        o.StageName = 'Check';
        insert o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        OppStartAutoFollowUp oe = new OppStartAutoFollowUp(sc);

        // Act
        PageReference pr = oe.renderPage();
        o = [SELECT Id, Auto_Follow_up_Date__c FROM Opportunity WHERE Id = :o.Id];
        Datetime nowDate = System.now();
        Datetime resDate = o.Auto_Follow_up_Date__c;
        System.assertEquals(nowDate.year(), resDate.year());
        System.assertEquals(nowDate.month(), resDate.month());
        System.assertEquals(nowDate.day(), resDate.day());
        System.assertEquals(nowDate.hour(), resDate.hour());
    }

    @isTest
    private static void testSendMail() {
        Opportunity o = createOpp('VR24', 'J & C Anwälte', true);
        o.recordTypeId = Opportunities.lebensversicherungRecordType();
        insert o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        OppStartAutoFollowUp oe = new OppStartAutoFollowUp(sc);

        // Act
        PageReference pr = oe.renderPage();

        // send mail
        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }
}