objects/Account.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Abteilung</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Callcenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for call center process parts.</description>
        <label>Callcenter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Callcenter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Confirmed_Terms_And_Conditions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AGB bestätigt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Follow_up_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Anzahl Follow-ups</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Follow_up_Period__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Zeit bis Follow-up</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Follow_up_Variant__c</fullName>
        <label>Follow-up Variant</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <fields>
        <fullName>Email</fullName>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <label>Email</label>
    </recordTypes>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

classes/IncreaseFollowUpCountDocTest.cls
@isTest
public class IncreaseFollowUpCountDocTest {
    private static Opportunity createOpp() {
        Account la = TestData.createAccount();
        la.name = 'J & C Anwälte';
        la.Department__c = 'Heinrich Jäger - DG & FZ';
        insert la;
        Account a = TestData.createAccount();
        a.name = 'VH24';
        insert a;
        Opportunity o = TestData.createOpportunity(a.ID, 'On Hold');
        o.Account__c = a.Id;
        o.Legal_Account__c = la.Id;
        Contact c = new Contact(FirstName = 'foo', LastName = 'bar', Email = 'baz@de.de');
        insert c;
        o.Contact__c = c.Id;
        return o;
    }

    /*@isTest
    private static void testVarNull() {
        Opportunity o = createOpp();
        o.RecordTypeId = Opportunities.dieselSkandalRecordType();
        insert o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        IncreaseFollowUpCountDoc oe = new IncreaseFollowUpCountDoc(sc);

        // Act
        PageReference pr = oe.renderPage();
        o = [SELECT Id, Follow_up_Count__c FROM Opportunity WHERE Id = :o.Id];
        System.assertEquals(1, o.Follow_up_Count__c);
        System.assertEquals(new PageReference('/' + o.Id).getUrl(), pr.getUrl());
    }*/

    /*@isTest
    private static void testVar3() {
        Opportunity o = createOpp();
        o.RecordTypeId = Opportunities.dieselSkandalRecordType();
        o.Follow_up_Variant__c = '3';
        o.Follow_up_Count__c = 44;
        insert o;
        o = [SELECT Id FROM Opportunity WHERE Id = :o.Id];
        o.StageName = 'New';
        upsert o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        IncreaseFollowUpCountDoc oe = new IncreaseFollowUpCountDoc(sc);

        // Act
        PageReference pr = oe.renderPage();
        o = [SELECT Id, Follow_up_Count__c, Follow_up_Period__c FROM Opportunity WHERE Id = :o.Id];
        System.assertEquals(1, o.Follow_up_Count__c);
        System.assertEquals(5, o.Follow_up_Period__c);
        System.assertEquals(new PageReference('/' + o.Id).getUrl(), pr.getUrl());
    }*/

    @isTest
    private static void testCreateTask() {
        User u = TestData.createUser();
        insert u;
        Opportunity o = createOpp();
        o.RecordTypeId = Opportunities.lebensversicherungRecordType();
        o.StageName = 'New';
        o.Callcenter__c = u.Id;
        o.Confirmed_Terms_And_Conditions__c = false;
        o.Follow_up_Variant__c = '2';
        o.Follow_up_Count__c = 44;
        insert o;
        o = [SELECT Id FROM Opportunity WHERE Id = :o.Id];
        o.StageName = 'New';
        upsert o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        IncreaseFollowUpCountDoc oe = new IncreaseFollowUpCountDoc(sc);

        // Act
        Test.startTest();
        PageReference pr = oe.renderPage();
        Test.stopTest();

        o = [SELECT Id, Follow_up_Count__c FROM Opportunity WHERE Id = :o.Id];
        System.assertEquals(45, o.Follow_up_Count__c);
        System.assertEquals(new PageReference('/' + o.Id).getUrl(), pr.getUrl());

        Task[] ts = [
            SELECT ID,
            Subject,
            Description,
            Follow_Up_Task__c,
            ActivityDate,
            Status
            FROM Task
            WHERE OwnerId = :u.ID
        ];
        System.assertEquals(2, ts.size());
        Task t = ts[0];
        //System.assertEquals('AGB/Dokumentenerhalt prüfen #45', t.subject);
        //System.assertEquals(true, t.follow_Up_Task__c);
        //System.assertEquals(Date.today() + 5, t.activityDate);
        //System.assertNotEquals('Completed', t.status);
    }

    @isTest
    private static void testCloseTask() {
        User u = TestData.createUser();
        insert u;
        Opportunity o = createOpp();
        o.RecordTypeId = Opportunities.lebensversicherungRecordType();
        o.StageName = 'New';
        o.Callcenter__c = u.Id;
        o.Confirmed_Terms_And_Conditions__c = false;
        o.Follow_up_Variant__c = '3';
        o.Follow_up_Count__c = 44;
        insert o;
        o = [SELECT Id, Follow_up_Count__c FROM Opportunity WHERE Id = :o.Id];
        o.StageName = 'New';
        upsert o;
        Task closeTask = Tasks.build(
            'AGB/Dokumentenerhalt prüfen #' + o.Follow_up_Count__c, // subject
            null, // description
            o, // parentObj
            u, // owner
            Date.today() + 3, // due date
            true, // noDuplicates
            o.Follow_up_Count__c > 0 // isFollowUpTask
        );
        insert closeTask;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        IncreaseFollowUpCountDoc oe = new IncreaseFollowUpCountDoc(sc);

        // Act
        Test.startTest();
        PageReference pr = oe.renderPage();
        Test.stopTest();

        Task[] ts = [
            SELECT ID
            FROM Task
            WHERE OwnerId = :u.ID
        ];
        System.assertEquals(3, ts.size());
        ts = [
            SELECT ID,
            Subject,
            Description,
            Follow_Up_Task__c,
            ActivityDate,
            Status
            FROM Task
            WHERE OwnerId = :u.ID
            AND Status <> 'Completed'
        ];
        System.assertEquals(2, ts.size());
        Task t = ts[0];
        //System.assertEquals('AGB/Dokumentenerhalt prüfen #1', t.subject);
        //System.assertEquals(true, t.follow_Up_Task__c);
        //System.assertEquals(Date.today() + 5, t.activityDate);
        //System.assertNotEquals('Completed', t.status);
    }
}