objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Externe Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Process_Type__c</fullName>
        <defaultValue>'Internal'</defaultValue>
        <label>Legal Process Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Legal_Process_Types</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Auftragstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assignment_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Confirmed_Terms_And_Conditions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AGB bestätigt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Versicherungsende</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Insurance_Status__c</fullName>
        <formula>IF(Termination_Date__c &lt; Today(),"bereits gekündigt",IF(Expiration_Date__c &lt; Today(),"regulär abgelaufen",IF(Active_Non_contributory_Periods__c &gt; 0,"beitragsfrei gestellt","noch aktiv")))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Versicherungsstatus</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Versicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Lebensversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Versicherung)</relationshipLabel>
        <relationshipName>Opportunities_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Process_Type__c</fullName>
        <defaultValue>'Internal'</defaultValue>
        <label>Anwaltsprozess</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Legal_Process_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partial_Refund__c</fullName>
        <label>Teilerstattungsbetrag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Priority_Level__c</fullName>
        <formula>IF(Insurance__c = null,'',CASE(Insurance__r.External_Id__c,'lv001','I','lv002','I','lv104','I','lv003','I','lv106','I','lv032','I','lv039','I','lv031','I','lv046','I','lv071','I','lv047','I','lv053','I','lv008','I','lv005','I','lv067','I', 'lv068','I', 'lv089','I','lv054','I','lv048','I', 'lv049','I', 'lv045','I', 'lv035','I', 'lv098','I', 'lv016','I', 'lv027','I', 'lv078','I', 'lv009','I', 'lv034','I','lv777','I','lv004','II','III'))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prioritätsstufe</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_Type__c</fullName>
        <label>Anspruchstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Process_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Aktenzeichen</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refund__c</fullName>
        <label>Erstattungsbetrag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <defaultValue>"Online"</defaultValue>
        <label>Vertriebstyp</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sales_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <label>Kündigungsdatum</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fahrzeughersteller</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Fahrzeughersteller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Fahrzeughersteller)</relationshipLabel>
        <relationshipName>Opportunities_Fahrzeughersteller</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Assignment_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Share</fullName>
    </customValue>
    <customValue>
        <fullName>Direkt</fullName>
    </customValue>
    <customValue>
        <fullName>50%</fullName>
        <isActive>false</isActive>
        <label>50%</label>
    </customValue>
    <customValue>
        <fullName>RSV 20%</fullName>
        <isActive>false</isActive>
        <label>RSV 20%</label>
    </customValue>
    <masterLabel>Assignment Types</masterLabel>
</GlobalValueSet>

globalValueSets/Legal_Process_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Internal</fullName>
        <label>Intern</label>
    </customValue>
    <customValue>
        <fullName>External</fullName>
        <label>Extern</label>
    </customValue>
    <masterLabel>Legal Process Types</masterLabel>
</GlobalValueSet>

globalValueSets/Process_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>LV_Opposition</fullName>
        <label>Widerspruch</label>
    </customValue>
    <customValue>
        <fullName>LV_Compensation</fullName>
        <label>Schadenersatz</label>
    </customValue>
    <customValue>
        <fullName>LV_Performance</fullName>
        <label>Erfüllungsanspruch</label>
    </customValue>
    <customValue>
        <fullName>DG_Return</fullName>
        <label>Rückgabe</label>
    </customValue>
    <customValue>
        <fullName>DG_Keep</fullName>
        <label>Behalten</label>
    </customValue>
    <customValue>
        <fullName>DG_Don&apos;t Know</fullName>
        <label>Unentschlossen</label>
    </customValue>
    <masterLabel>Process Types</masterLabel>
</GlobalValueSet>

globalValueSets/Sales_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
        <default>true</default>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <masterLabel>Sales Types</masterLabel>
</GlobalValueSet>

classes/OpportunitiesStage.cls
public class OpportunitiesStage {
    public static Opportunity[] setStage(Opportunity[] oo, Map<ID,Opportunity> oldOo) {
        Map<Id, Opportunity> ooQ = new Map<Id, Opportunity>([
            select Id,
            Priority_Level__c,
            Vehicle_Brand__c,
            Process_Type__c,
            Account_Id__c,
            Sales_Type__c,
            Reference__c,
            RecordTypeId,
            Confirmed_Terms_And_Conditions__c,
            StageName,
            Legal_Process_Type__c,
            Legal__c,
            Assignment_Type__c,
            Partial_Refund__c,
            Refund__c,
            Backoffice__c,
            Termination_Date__c,
            Expiration_Date__c,
            Insurance_Status__c,
            Insurance__c,
            Insurance__r.External_Id__c
            from Opportunity
            where Id IN :oo
        ]);
        for (Opportunity o : oo) {
            OpportunitiesStage.setClaim(o, oldOo.get(o.Id), ooQ.get(o.Id));
        }
        return oo;
    }

    private static Opportunity setClaim(Opportunity opp, Opportunity oldOpp, Opportunity oQ) {
        if (Opportunities.isLebensversicherung(opp.RecordTypeId)) {
            if (oQ.priority_Level__c == 'I' || oQ.priority_Level__c == 'II') {
                if (oQ.Insurance_Status__c == 'bereits gekündigt') {
                    if (opp.Confirmed_Terms_And_Conditions__c == true) {
                        if (oldOpp.Confirmed_Terms_And_Conditions__c != opp.Confirmed_Terms_And_Conditions__c) {
                            opp.StageName = 'Claim';
                            System.debug('OpportunitiesStage :: setClaim :: opp: ' + opp);
                        }
                    }
                }
            }
        }
        return opp;
    }
}