objects/Account.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Abteilung</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Auto_Follow_up_Count__c</fullName>
        <label>Anzahl Auto-Follow-ups</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Auftragstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assignment_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auto_Follow_up_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Anzahl Auto-Follow-ups</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Kreditinstitut</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Kreditinstitut)</relationshipLabel>
        <relationshipName>Opportunities_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Has_Legal_Protection_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rechtsschutzversicherung vorhanden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Versicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Lebensversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Versicherung)</relationshipLabel>
        <relationshipName>Opportunities_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Protection_Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rechtsschutzversicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Rechtsschutzversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Rechtsschutzversicherung)</relationshipLabel>
        <relationshipName>Opportunities_Legal_Protection_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Partner)</relationshipLabel>
        <relationshipName>Opportunities_Partner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <defaultValue>"Online"</defaultValue>
        <label>Vertriebstyp</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sales_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fahrzeughersteller</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Fahrzeughersteller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Fahrzeughersteller)</relationshipLabel>
        <relationshipName>Opportunities_Fahrzeughersteller</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <businessProcess>Finanzierung</businessProcess>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Opportunity_Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Korrespondenz</relationshipLabel>
        <relationshipName>Opportunity_Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Partner</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Opportunity_Correspondence_Partners</valueSetName>
        </valueSet>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

globalValueSets/Assignment_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Share</fullName>
    </customValue>
    <customValue>
        <fullName>Direkt</fullName>
    </customValue>
    <customValue>
        <fullName>50%</fullName>
        <isActive>false</isActive>
        <label>50%</label>
    </customValue>
    <customValue>
        <fullName>RSV 20%</fullName>
        <isActive>false</isActive>
        <label>RSV 20%</label>
    </customValue>
    <masterLabel>Assignment Types</masterLabel>
</GlobalValueSet>

globalValueSets/Opportunity_Correspondence_Partners.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Insurance</fullName>
        <label>Versicherung</label>
    </customValue>
    <customValue>
        <fullName>Vehicle Brand</fullName>
        <label>Fahrzeughersteller</label>
    </customValue>
    <customValue>
        <fullName>Bank</fullName>
        <label>Kreditinstitut</label>
    </customValue>
    <customValue>
        <fullName>Legal Protection Insurance</fullName>
        <label>Rechtsschutzversicherung</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
        <label>Kunde</label>
    </customValue>
    <customValue>
        <fullName>Individuell</fullName>
    </customValue>
    <masterLabel>Opportunity Correspondence Partners</masterLabel>
</GlobalValueSet>

globalValueSets/Sales_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
        <default>true</default>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <masterLabel>Sales Types</masterLabel>
</GlobalValueSet>

classes/OppCorrSendDocToPartnerTest.cls
@isTest
public class OppCorrSendDocToPartnerTest {
    private static Opportunity createOpp(string legalname) {
        Account la = TestData.createAccount();
        la.name = legalname;
        la.Department__c = 'Heinrich Jäger - DG & FZ';
        insert la;

        Account a = TestData.createAccount();
        a.name = 'VH24';
        a.Type = 'Rechtsschutzversicherung';
        insert a;
        Account insuranceAcc = TestData.createAccount();
        insuranceAcc.Type = 'Lebensversicherung';
        insert insuranceAcc;
        Account vehicleBrand = new Account(
            Name = 'TestVehicleBrand',
            Type = 'Fahrzeughersteller'
        );
        insert vehicleBrand;
        Contact con = new Contact(LastName = 'Bar');
        insert con;
        Opportunity o = new Opportunity(
            Name = 'TestOpportunity',
            AccountId = a.Id,
            CloseDate = System.today(),
            StageName = 'On Hold',
            Sent_Mail_Flag_1__c = true,
            Sent_Mail_Flag_2__c = true,
            Assignment_Type__c = 'RSV',
            Has_Legal_Protection_Insurance__c = true,
            Auto_Follow_up_Count__c = 0,
            Sales_Type__c = 'Online',
            Vehicle_Brand__c = vehicleBrand.Id,
            Bank__c = a.Id,
            Legal_Protection_Insurance__c = a.Id,
            Contact__c = con.Id,
            Insurance__c = insuranceAcc.Id
        );
        o.Account__c = a.Id;
        o.Legal_Account__c = la.Id;
        return o;
    }

    /* * * * * * * * *
     * DIESELSKANDAL *
     * * * * * * * * */

    @isTest
    private static void testDieselSkandalJCVehicle() {
        Opportunity o = createOpp('J & C Anwälte');
        o.recordTypeId = Opportunities.dieselSkandalRecordType();
        insert o;
        Opportunity_Correspondence__c corr = new Opportunity_Correspondence__c(
            Opportunity__c = o.Id,
            Partner__c = 'Vehicle Brand'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(corr);
        OppCorrSendDocToPartner oe = new OppCorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.name.DieselJaegerLegalAnfrageKorrespondenz)));
        System.assertEquals(true, pr.getUrl().contains(o.Vehicle_Brand__c));

        // send mail
        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }

    @isTest
    private static void testDieselSkandalCLLBBank() {
        Opportunity o = createOpp('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        o.recordTypeId = Opportunities.dieselSkandalRecordType();
        insert o;
        Opportunity_Correspondence__c corr = new Opportunity_Correspondence__c(
            Opportunity__c = o.Id,
            Partner__c = 'Bank'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(corr);
        OppCorrSendDocToPartner oe = new OppCorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.name.DieselKainzLegalAnfrageKorrespondenz)));
        System.assertEquals(true, pr.getUrl().contains(o.Bank__c));

        // send mail
        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }

    @isTest
    private static void testDieselSkandalLeComRSV() {
        Opportunity o = createOpp('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        o.recordTypeId = Opportunities.dieselSkandalRecordType();
        insert o;
        Opportunity_Correspondence__c corr = new Opportunity_Correspondence__c(
            Opportunity__c = o.Id,
            Partner__c = 'Legal Protection Insurance'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(corr);
        OppCorrSendDocToPartner oe = new OppCorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.name.DieselLeComLegalAnfrageKorrespondenz)));
        System.assertEquals(true, pr.getUrl().contains(o.Legal_Protection_Insurance__c));

        // send mail
        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }

    /* * * * * * * * *
     * FINANZIERUNG  *
     * * * * * * * * */

    @isTest
    private static void testFinanzierungJCInsurance() {
        Opportunity o = createOpp('J & C Anwälte');
        o.recordTypeId = Opportunities.FinanzierungRecordType();
        insert o;
        Opportunity_Correspondence__c corr = new Opportunity_Correspondence__c(
            Opportunity__c = o.Id,
            Partner__c = 'Insurance'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(corr);
        OppCorrSendDocToPartner oe = new OppCorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.name.FzJaegerLegalAnfrageKorrespondenz)));
        System.assertEquals(true, pr.getUrl().contains(o.Insurance__c));

        // send mail
        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }

    @isTest
    private static void testFinanzierungCLLBCustomer() {
        Opportunity o = createOpp('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        o.recordTypeId = Opportunities.FinanzierungRecordType();
        insert o;
        Opportunity_Correspondence__c corr = new Opportunity_Correspondence__c(
            Opportunity__c = o.Id,
            Partner__c = 'Customer'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(corr);
        OppCorrSendDocToPartner oe = new OppCorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.name.FzKainzLegalAnfrageKorrespondenz)));
        System.assertEquals(true, pr.getUrl().contains(o.Contact__c));

        // send mail
        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }

    @isTest
    private static void testFinanzierungLeComRSV() {
        Opportunity o = createOpp('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        o.recordTypeId = Opportunities.FinanzierungRecordType();
        insert o;
        Opportunity_Correspondence__c corr = new Opportunity_Correspondence__c(
            Opportunity__c = o.Id,
            Partner__c = 'Legal Protection Insurance'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(corr);
        OppCorrSendDocToPartner oe = new OppCorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.name.FzLeComLegalAnfrageKorrespondenz)));
        System.assertEquals(true, pr.getUrl().contains(o.Legal_Protection_Insurance__c));

        // send mail
        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }

    /* * * * * * * * * * * *
     * LEBENSVERSICHERUNG  *
     * * * * * * * * * * * */

    @isTest
    private static void testLebensversicherungJCInsurance() {
        Opportunity o = createOpp('J & C Anwälte');
        Account la = TestData.createAccount();
        la.name = 'J & C Anwälte';
        la.Department__c = 'Heinrich Jäger - LV';
        insert la;
        o.Legal_Account__c = la.Id;
        o.recordTypeId = Opportunities.LebensversicherungRecordType();
        insert o;
        Opportunity_Correspondence__c corr = new Opportunity_Correspondence__c(
            Opportunity__c = o.Id,
            Partner__c = 'Insurance'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(corr);
        OppCorrSendDocToPartner oe = new OppCorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.name.LvJaegerLegalAnfrageKorrespondenz)));
        System.assertEquals(true, pr.getUrl().contains(o.Insurance__c));

        // send mail
        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }

    @isTest
    private static void testLebensversicherungCLLBCustomer() {
        Opportunity o = createOpp('CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB');
        o.recordTypeId = Opportunities.LebensversicherungRecordType();
        insert o;
        Opportunity_Correspondence__c corr = new Opportunity_Correspondence__c(
            Opportunity__c = o.Id,
            Partner__c = 'Customer'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(corr);
        OppCorrSendDocToPartner oe = new OppCorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.name.LvKainzLegalAnfrageKorrespondenz)));
        System.assertEquals(true, pr.getUrl().contains(o.Contact__c));

        // send mail
        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }

    @isTest
    private static void testLebensversicherungLeComRSV() {
        Opportunity o = createOpp('LeCom - Legal & Compliance Rechtsanwaltsgesellschaft mbH');
        o.recordTypeId = Opportunities.LebensversicherungRecordType();
        insert o;
        Opportunity_Correspondence__c corr = new Opportunity_Correspondence__c(
            Opportunity__c = o.Id,
            Partner__c = 'Legal Protection Insurance'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(corr);
        OppCorrSendDocToPartner oe = new OppCorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.name.LvLeComLegalAnfrageKorrespondenz)));
        System.assertEquals(true, pr.getUrl().contains(o.Legal_Protection_Insurance__c));

        // send mail
        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }
}