objects/Analysis__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Potentialberechnungen</relationshipLabel>
        <relationshipName>Potentialanalysen</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Object for storing and managing potential analysis.</description>
    <label>Potentialberechnung</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potentialberechnungen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <type>Date</type>
    </fields>
    <label>Kostennote</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostennoten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Date__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Termin</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Termine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Checklist_Information_Complete__c</fullName>
        <formula>AND(TEXT(Payment_Term__c) != '',NOT(ISNULL(Insured_Person_1_Date_Of_Birth__c)),NOT(ISNULL(Inception_Date__c)),NOT(ISNULL(Expiration_Date__c)),NOT(ISNULL(Contribution_Life_Insurance__c)),NOT(ISNULL(Valuation_Date__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Checklist Information Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Potential__c</fullName>
        <label>Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CreateDocController.cls
// Legacy code, to be refactored
// WIP for docgen
// As we discover the requirements remove as much old code as possible.
public class CreateDocController {
    private final ID objID;
    
	public CreateDocController() {
        this.objID = ApexPages.currentPage().getParameters().get('id');
    }
    
	public PageReference createDoc() {
        System.debug('>> CreateDocExtension :: createDoc');
        
        // todo: extract to some class or have the same extension for all doc gen buttons
        // This comes form Legacy PageButtonAction

        Boolean parPreserveMergefields;
        if (ApexPages.currentPage().getParameters().get('preserveMergeFields') != null){
	        parPreserveMergefields = Boolean.valueOf(ApexPages.currentPage().getParameters().get('preserveMergeFields'));
        } else {
            parPreserveMergefields = false;
        }
        
        String parOutput;
        if (ApexPages.currentPage().getParameters().get('output') != null){
	        parOutput = ApexPages.currentPage().getParameters().get('output');
        } else {
            parOutput = 'pdf';
        }
        
        String parVariant;
        if (ApexPages.currentPage().getParameters().get('variant') != null){
	        parVariant = ApexPages.currentPage().getParameters().get('variant');
        }
        //--
        
        PageReference r;
        try {
        	String error = DocumentCreationAction.autoCreateDocument(this.objID, parPreserveMergefields, parOutput, parVariant, null/*parDocumentAttachment - only for correspondences*/);   
            r = String.isBlank(error) ? Page.SuccessPage : Errors.page('Unable to create doc: ' + error);
        } catch (Exception e) { 
        	System.debug('CreateDocExtension :: createDoc :: e: '+ e.getMessage());   
            r = Errors.page('Unable to create doc', e.getMessage());
        }
        r.setRedirect(true);
        return r;

        /*PageReference red;
        if (parentObject.Id.getSObjectType() == Schema.SObjectType.Analysis__c.getSObjectType()){
	        Analysis__c analysis = [select Id,Opportunity__c from Analysis__c where Id = :parentObject.Id];
            Opportunity opportunity = [select Id, Checklist_Information_Complete__c, Potential__c from Opportunity where Id = :analysis.Opportunity__c];

	        if (parVariant == '1'){
                if (opportunity.Checklist_Information_Complete__c == false){
		            red = Page.ChecklistInformationIncomplete;
                }                    
            } else if (parVariant == '2') {
                if (opportunity.Potential__c == null) {
		            red = Page.CalculationIncomplete;
                }
            }
        }

		if (parentObject.Id.getSObjectType() == Schema.SObjectType.Correspondence__c.getSObjectType()){
			for (EmailUtilities.CAttachmentListItem parentAttachmentListItem : parParentAttachments){
				if (parentAttachmentListItem.selected == true){
					parDocumentAttachments.add(parentAttachmentListItem.record.Id + ';0;internal');
				}
			}
			for (EmailUtilities.CDocumentListItem documentListItem : parDocuments){
				if (documentListItem.selected == true){
					parDocumentAttachments.add(documentListItem.record.Link__c + ';0;external');
				}
			}
			for (EmailUtilities.CCorrespondenceAttachmentListItem correspondenceAttachmentListItem : parCorrespondencies){
				if (correspondenceAttachmentListItem.selected == true){
					parDocumentAttachments.add(correspondenceAttachmentListItem.attachment.Id + ';0;internal');
				}
			}
			for (EmailUtilities.CAttachmentListItem opportunityAttachmentListItem : parOpportunityAttachments){
				if (opportunityAttachmentListItem.selected == true){
					parDocumentAttachments.add(opportunityAttachmentListItem.record.Id + ';0;internal');
				}
			}
			for (EmailUtilities.CAuthorizationAttachmentListItem authorizationAttachmentListItem : parAuthorizations){
				if (authorizationAttachmentListItem.selected == true){
					parDocumentAttachments.add(authorizationAttachmentListItem.attachment.Id + ';0;internal');
				}
			}
		}

		if (parentObject.Id.getSObjectType() == Schema.SObjectType.Cost_Note__c.getSObjectType()){
			Cost_Note__c costNote = [select Id from Cost_Note__c where Id = :parentObject.Id];
			costNote.Date__c = System.today();
			update costNote;
		}

        if (red == null){
            DocumentCreationAction.autoCreateDocument(parentObject.Id,parPreserveMergefields,parOutput,parVariant,parDocumentAttachments);
            red = Page.SuccessPage;
        }
        red.setRedirect(true);
        return red;*/
    }
}