objects/Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Authorization_Stages</valueSetName>
        </valueSet>
    </fields>
    <description>Object for storing the customers written authorization.</description>
    <label>Vollmacht</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vollmachten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Cancellation__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cancellation_Stages</valueSetName>
        </valueSet>
    </fields>
    <label>Stornierung</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stornierungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Stages</valueSetName>
        </valueSet>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <formula>TEXT(Last_Opportunity__r.StageName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contract_Stages</valueSetName>
        </valueSet>
    </fields>
    <description>Object for storing contract with customer.</description>
    <label>Vertrag</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verträge</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Stages</valueSetName>
        </valueSet>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Stages</valueSetName>
        </valueSet>
    </fields>
    <label>Kostennote</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostennoten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note_Reminder__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reminder_Stages</valueSetName>
        </valueSet>
    </fields>
    <label>Mahnung</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mahnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Credit_Note__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credit_Note_Stages</valueSetName>
        </valueSet>
    </fields>
    <label>Gutschrift</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gutschriften</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Date__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Date_Stages</valueSetName>
        </valueSet>
    </fields>
    <label>Termin</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Termine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Fund__c.object
<CustomObject>
    <fields>
        <fullName>Default_Trend__c</fullName>
        <label>Standardentwicklung</label>
        <precision>18</precision>
        <scale>17</scale>
        <type>Percent</type>
    </fields>
    <label>Fonds</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fonds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Fund_Reference__c.object
<CustomObject>
    <fields>
        <fullName>Fund__c</fullName>
        <label>Fonds</label>
        <referenceTo>Fund__c</referenceTo>
        <relationshipLabel>Fondsreferenzen</relationshipLabel>
        <relationshipName>Fund_References</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fondsreferenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fondsreferenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Auftragstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assignment_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Has_Legal_Protection_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rechtsschutzversicherung vorhanden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Versicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Lebensversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Versicherung)</relationshipLabel>
        <relationshipName>Opportunities_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Protection_Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rechtsschutzversicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Rechtsschutzversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Rechtsschutzversicherung)</relationshipLabel>
        <relationshipName>Opportunities_Legal_Protection_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Rate__c.object
<CustomObject>
    <fields>
        <fullName>Fund__c</fullName>
        <label>Fonds</label>
        <referenceTo>Fund__c</referenceTo>
        <relationshipLabel>Kurse</relationshipLabel>
        <relationshipName>Rates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Kurs</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kurse</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Assignment_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Share</fullName>
    </customValue>
    <customValue>
        <fullName>Direkt</fullName>
    </customValue>
    <customValue>
        <fullName>50%</fullName>
        <isActive>false</isActive>
        <label>50%</label>
    </customValue>
    <customValue>
        <fullName>RSV 20%</fullName>
        <isActive>false</isActive>
        <label>RSV 20%</label>
    </customValue>
    <masterLabel>Assignment Types</masterLabel>
</GlobalValueSet>

globalValueSets/Authorization_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Signed</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <description>Authorization stages.</description>
    <masterLabel>Authorization Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Cancellation_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Cancellation Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Entwurf</label>
    </customValue>
    <customValue>
        <fullName>Customers Opposition</fullName>
        <label>Kundenwiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Legal Opposition</fullName>
        <label>Anwaltswiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Claim Letter</fullName>
        <label>Anspruchsschreiben</label>
    </customValue>
    <customValue>
        <fullName>Lawsuit</fullName>
        <label>Klage</label>
    </customValue>
    <customValue>
        <fullName>Class Action</fullName>
        <label>Sammelklage</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
        <label>Abwicklung</label>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
        <label>Abgeschlossen</label>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <label>Warten auf Grundsatzurteil</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>Abbruch</label>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Examination</fullName>
        <isActive>false</isActive>
        <label>Examination</label>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
        <isActive>false</isActive>
        <label>Success</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
        <isActive>false</isActive>
        <label>Failure</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <isActive>false</isActive>
        <label>Open</label>
    </customValue>
    <description>Claim stages.</description>
    <masterLabel>Claim Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Contract_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Signed</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <description>Contract stages.</description>
    <masterLabel>Contract Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Correspondence_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Correspondence Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Replaced</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Cost Note Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Credit_Note_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Credit Note Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Date_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Open</fullName>
        <default>true</default>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Date Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Reminder_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Reminder Stages</masterLabel>
</GlobalValueSet>

classes/DocumentCreationActionTest.cls
@isTest (seeAllData=true)
public class DocumentCreationActionTest {

    private class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            if(req.getEndpoint().contains('documents')){
                res.setBody('{"file":"Testfile","extension":"pdf","calculated_fields":{"Ergebnis!B46":"13410,93 €"}}');
            }
            res.setStatusCode(200);
            return res;
        }
	}

    private class MockHttpErrorResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(400);
            return res;
        }
	}

    @isTest
    static void hackCoverage() {
        DocumentCreationAction.hackCoverage();
    }
                            
    @isTest
	static void testAnalysisSuccess(){
		// Testsetup
        TriggerConfiguration.allInactive = true;

		// Create test data
        Account account = TestData.createAccount();
        insert account;
        Account insurance = TestData.createAccount();
        insurance.Type = 'Lebensversicherung';
        insert insurance;
        Contact contact = TestData.createContact(account.Id);
        insert contact;
		Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
        opportunity.Contact__c = contact.Id;
        opportunity.Insurance__c = insurance.Id;
        insert opportunity;
        Fund__c fund = TestData.createFund('Testfund','99999');
        fund.Default_Trend__c = 0.35;
		insert fund;
        Rate__c rate = TestData.createRate(fund.Id,0.3,100.45,Date.valueOf('2000-10-15'));
		insert rate;
        Rate__c rate2 = TestData.createRate(fund.Id,null,100.45,Date.valueOf('2000-10-15'));
		insert rate2;
        Fund_Reference__c fundReference = TestData.createFundReference(opportunity.Id,fund.Id,100);
		insert fundReference;
	    Analysis__c analysis = TestData.createAnalysis(opportunity.Id);
	    insert analysis;

        // Test
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        DocumentCreationAction.autoCreateDocument(analysis.Id,false,'sameAsInput',null,null);

        Test.stopTest();

        // Assertion impossible
    }
    
    @isTest
    static void testContract50Success(){
		// Testsetup
        TriggerConfiguration.allInactive = true;

		// Create test data
        Account account = TestData.createAccount();
        account.Type = 'Lebensversicherung';
        insert account;
        Contact contact = TestData.createContact(account.Id);
        insert contact;
		Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
        opportunity.Insurance__c = account.Id;
		opportunity.Assignment_Type__c = 'Share';
        opportunity.Has_Legal_Protection_Insurance__c = false;
        opportunity.Contact__c = contact.Id;
        insert opportunity;
        Contract__c contract = TestData.createContract(opportunity.Id);
        insert contract;

        // Test
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        DocumentCreationAction.autoCreateDocument(contract.Id,false,'pdf',null,null);

        Test.stopTest();

        // Assertion impossible
    }

    @isTest
    static void testContract20Success(){
		// Testsetup
        TriggerConfiguration.allInactive = true;

		// Create test data
        Account account = TestData.createAccount();
        account.Type = 'Lebensversicherung';
        insert account;
        Contact contact = TestData.createContact(account.Id);
        insert contact;
		Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
        opportunity.Insurance__c = account.Id;
		opportunity.Assignment_Type__c = 'RSV';
        opportunity.Contact__c = contact.Id;
        insert opportunity;
        Contract__c contract = TestData.createContract(opportunity.Id);
        insert contract;

        // Test
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        DocumentCreationAction.autoCreateDocument(contract.Id,false,'pdf',null,null);

        Test.stopTest();

        // Assertion impossible
    }

    @isTest
    static void testContractDirektSuccess(){
		// Testsetup
        TriggerConfiguration.allInactive = true;

		// Create test data
        Account account = TestData.createAccount();
        account.Type = 'Lebensversicherung';
        insert account;
        Contact contact = TestData.createContact(account.Id);
        insert contact;
		Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
        opportunity.Insurance__c = account.Id;
		opportunity.Assignment_Type__c = 'Direkt';
        opportunity.Contact__c = contact.Id;
        insert opportunity;
        Contract__c contract = TestData.createContract(opportunity.Id);
        insert contract;

        // Test
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        DocumentCreationAction.autoCreateDocument(contract.Id,false,'pdf',null,null);

        Test.stopTest();

        // Assertion impossible
    }

	@isTest
	static void testInvoiceSuccess(){
		// Testsetup
		TriggerConfiguration.allInactive = true;

		// Create test data
		User user = TestData.createUser();
		insert user;
		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id,'New');
		insert opportunity;
		Invoice__c invoice = TestData.createInvoice(opportunity.Id);
		invoice.Stage__c = 'Draft';
		invoice.Amount__c = 15000;
		invoice.Accounting__c = user.Id;
		insert invoice;

		// Test
		Test.startTest();

		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		DocumentCreationAction.autoCreateDocument(invoice.Id,false,'pdf',null,null);

		Test.stopTest();

		// Assertion impossible
	}

	@isTest
    static void testWelcomeLetterRSVSuccess(){
        // Testsetup
        TriggerConfiguration.allInactive = true;

        // Create admin user to update roles on other users
        User adminUser = TestData.createUser();
        adminUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
        insert adminUser;

        // Create test users and set their roles with admin user
        User legalUser = TestData.createUser();
        legalUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
        legalUser.Username = 'legalUser@cloudworx.agency';
        insert legalUser;

        System.runAs(adminUser) {
            legalUser.UserRoleId = UserRoles.LegalID; // 00E0Y000000Hvm7
            update legalUser;
        }

        // Create test data
        Account account = TestData.createAccount();
        insert account;
        Contact contact = TestData.createContact(account.Id);
        insert contact;
        Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
        opportunity.Assignment_Type__c = 'RSV';
        opportunity.Contact__c = contact.Id;
        opportunity.Legal__c = legalUser.Id;
        insert opportunity;
		Welcome_Letter__c welcomeLetter = TestData.createWelcomeLetter(opportunity.Id);
		insert welcomeLetter;

        // Test
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        DocumentCreationAction.autoCreateDocument(welcomeLetter.Id,false,'pdf',null,null);

        Test.stopTest();

        // Assertion impossible
    }

	@isTest
	static void testWelcomeLetterShareSuccess(){
		// Testsetup
		TriggerConfiguration.allInactive = true;

		// Create admin user to update roles on other users
		User adminUser = TestData.createUser();
		adminUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
		insert adminUser;

		// Create test users and set their roles with admin user
		User legalUser = TestData.createUser();
		legalUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
		legalUser.Username = 'legalUser@cloudworx.agency';
		insert legalUser;

		System.runAs(adminUser) {
			legalUser.UserRoleId = UserRoles.LegalID; // 00E0Y000000Hvm7
			update legalUser;
		}

		// Create test data
		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
		opportunity.Assignment_Type__c = 'Direkt'; // TODO: was Share but validation rule
		opportunity.Contact__c = contact.Id;
		opportunity.Legal__c = legalUser.Id;
		insert opportunity;
		Welcome_Letter__c welcomeLetter = TestData.createWelcomeLetter(opportunity.Id);
		insert welcomeLetter;

		// Test
		Test.startTest();

		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		DocumentCreationAction.autoCreateDocument(welcomeLetter.Id,false,'pdf',null,null);

		Test.stopTest();

		// Assertion impossible
	}

	@isTest
	static void testAuthorizationSuccess(){
		// Testsetup
        TriggerConfiguration.allInactive = true;

        // Create admin user to update roles on other users
        User adminUser = TestData.createUser();
        adminUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
        insert adminUser;

        // Create test users and set their roles with admin user
        User legalUser = TestData.createUser();
        legalUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
        legalUser.Username = 'legalUser@cloudworx.agency';
        insert legalUser;

        System.runAs(adminUser) {
            legalUser.UserRoleId = UserRoles.LegalID; // 00E0Y000000Hvm7
            update legalUser;
        }

		// Create test data
        Account account = TestData.createAccount();
        account.Type = 'Lebensversicherung';
        insert account;
        Contact contact = TestData.createContact(account.Id);
        insert contact;
		Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
        opportunity.Insurance__c = account.Id;
        opportunity.Contact__c = contact.Id;
        opportunity.Legal__c = legalUser.Id;
        insert opportunity;
        Authorization__c authorization = TestData.createAuthorization(opportunity.Id);
        insert authorization;

        // Test
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        DocumentCreationAction.autoCreateDocument(authorization.Id,false,'pdf',null,null);

        Test.stopTest();

        // Assertion impossible
    }
    
    @isTest
	static void testCorrespondenceLVSuccess(){
		// Testsetup
        TriggerConfiguration.allInactive = true;

        // Create admin user to update roles on other users
        User adminUser = TestData.createUser();
        adminUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
        insert adminUser;

        // Create test users and set their roles with admin user
        User legalUser = TestData.createUser();
        legalUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
        legalUser.Username = 'legalUser@cloudworx.agency';
        insert legalUser;

        System.runAs(adminUser) {
            legalUser.UserRoleId = UserRoles.LegalID; // 00E0Y000000Hvm7
            update legalUser;
        }

		// Create test data
        Account account = TestData.createAccount();
        insert account;
        Account districtCourt = TestData.createAccount();
        districtCourt.Type = 'Gericht';
        insert districtCourt;
        Account insurance = TestData.createAccount();
        insurance.Type = 'Lebensversicherung';
        insert insurance;
        Account legalInsurance = TestData.createAccount();
        legalInsurance.Type = 'Rechtsschutzversicherung';
        insert legalInsurance;
        Contact contact = TestData.createContact(account.Id);
        insert contact;
		Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
        opportunity.Insurance__c = insurance.Id;
        opportunity.Legal_Protection_Insurance__c = legalInsurance.Id;
        opportunity.Contact__c = contact.Id;
        opportunity.Legal__c = legalUser.Id;
        insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id,'Draft');
        claim.Court__c = districtCourt.Id;
        claim.Legal__c = legalUser.Id;
        insert claim;
		Correspondence__c correspondence = TestData.createCorrespondence(claim.Id,'Insurance','Widerspruch durch Kunden','Draft');
		insert correspondence;

        // Test
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        DocumentCreationAction.autoCreateDocument(correspondence.Id,false,'sameAsInput',null,null);

        Test.stopTest();

        // Assertion impossible
    }

	@isTest
	static void testCorrespondenceFZSuccess(){
		// Testsetup
		TriggerConfiguration.allInactive = true;

		// Create admin user to update roles on other users
		User adminUser = TestData.createUser();
		adminUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
		insert adminUser;

		// Create test users and set their roles with admin user
		User legalUser = TestData.createUser();
		legalUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
		legalUser.Username = 'legalUser@cloudworx.agency';
		insert legalUser;

		System.runAs(adminUser) {
			legalUser.UserRoleId = UserRoles.LegalID; // 00E0Y000000Hvm7
			update legalUser;
		}

		// Create test data
		Account account = TestData.createAccount();
		insert account;
		Account districtCourt = TestData.createAccount();
		districtCourt.Type = 'Gericht';
		insert districtCourt;
		Account legalInsurance = TestData.createAccount();
		legalInsurance.Type = 'Rechtsschutzversicherung';
		insert legalInsurance;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
		opportunity.RecordTypeId = Opportunities.finanzierungRecordType();
		opportunity.Bank__c = account.Id;
		opportunity.Legal_Protection_Insurance__c = legalInsurance.Id;
		opportunity.Contact__c = contact.Id;
		opportunity.Legal__c = legalUser.Id;
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id,'Draft');
		claim.Court__c = districtCourt.Id;
		claim.Legal__c = legalUser.Id;
		insert claim;
		Correspondence__c correspondence = TestData.createCorrespondence(claim.Id,'Bank','Widerspruch durch Kunden','Draft');
		insert correspondence;

		// Test
		Test.startTest();

		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		DocumentCreationAction.autoCreateDocument(correspondence.Id,false,'sameAsInput',null,null);

		Test.stopTest();

		// Assertion impossible
	}

	@isTest
	static void testCorrespondenceDGSuccess(){
		// Testsetup
		TriggerConfiguration.allInactive = true;

		// Create admin user to update roles on other users
		User adminUser = TestData.createUser();
		adminUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
		insert adminUser;

		// Create test users and set their roles with admin user
		User legalUser = TestData.createUser();
		legalUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
		legalUser.Username = 'legalUser@cloudworx.agency';
		insert legalUser;

		System.runAs(adminUser) {
			legalUser.UserRoleId = UserRoles.LegalID; // 00E0Y000000Hvm7
			update legalUser;
		}

		// Create test data
		Account account = TestData.createAccount();
		insert account;
		Account districtCourt = TestData.createAccount();
		districtCourt.Type = 'Gericht';
		insert districtCourt;
		Account insurance = TestData.createAccount();
		insurance.Type = 'Lebensversicherung';
		insert insurance;
		Account legalInsurance = TestData.createAccount();
		legalInsurance.Type = 'Rechtsschutzversicherung';
		insert legalInsurance;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
		opportunity.RecordTypeId = Opportunities.dieselSkandalRecordType();
		opportunity.Insurance__c = insurance.Id;
		opportunity.Legal_Protection_Insurance__c = legalInsurance.Id;
		opportunity.Contact__c = contact.Id;
		opportunity.Legal__c = legalUser.Id;
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id,'Draft');
		claim.Court__c = districtCourt.Id;
		claim.Legal__c = legalUser.Id;
		insert claim;
		Correspondence__c correspondence = TestData.createCorrespondence(claim.Id,'Insurance','Widerspruch durch Kunden','Draft');
		insert correspondence;

		// Test
		Test.startTest();

		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		DocumentCreationAction.autoCreateDocument(correspondence.Id,false,'sameAsInput',null,null);

		Test.stopTest();

		// Assertion impossible
	}

	@isTest
	static void testCostNoteSuccess(){
		// Testsetup
        TriggerConfiguration.allInactive = true;

        // Create admin user to update roles on other users
        User adminUser = TestData.createUser();
        adminUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
        insert adminUser;

        // Create test users and set their roles with admin user
        User legalUser = TestData.createUser();
        legalUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
        legalUser.Username = 'legalUser@cloudworx.agency';
        insert legalUser;

        System.runAs(adminUser) {
            legalUser.UserRoleId = UserRoles.LegalID; // 00E0Y000000Hvm7
            update legalUser;
        }

		// Create test data
        Account account = TestData.createAccount();
        insert account;
        Account legalInsurance = TestData.createAccount();
        legalInsurance.Type = 'Rechtsschutzversicherung';
        insert legalInsurance;
        Contact contact = TestData.createContact(account.Id);
        insert contact;
		Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
        opportunity.Legal_Protection_Insurance__c = legalInsurance.Id;
        opportunity.Contact__c = contact.Id;
        insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id,'Draft');
        claim.Legal__c = legalUser.Id;
        insert claim;
		Cost_Note__c costNote = TestData.createCostNote(claim.Id,'Draft');
		insert costNote;

        // Test
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        DocumentCreationAction.autoCreateDocument(costNote.Id,false,'pdf',null,null);

        Test.stopTest();

        // Assertion impossible
    }

	@isTest
	static void testCancellationSuccess(){
		// Testsetup
		TriggerConfiguration.allInactive = true;

		// Create admin user to update roles on other users
		User adminUser = TestData.createUser();
		adminUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
		insert adminUser;

		// Create test users and set their roles with admin user
		User legalUser = TestData.createUser();
		legalUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
		legalUser.Username = 'legalUser@cloudworx.agency';
		insert legalUser;

		System.runAs(adminUser) {
			legalUser.UserRoleId = UserRoles.LegalID; // 00E0Y000000Hvm7
			update legalUser;
		}

		// Create test data
		Account account = TestData.createAccount();
		insert account;
		Account legalInsurance = TestData.createAccount();
		legalInsurance.Type = 'Rechtsschutzversicherung';
		insert legalInsurance;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
		opportunity.Legal_Protection_Insurance__c = legalInsurance.Id;
		opportunity.Contact__c = contact.Id;
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id,'Draft');
		claim.Legal__c = legalUser.Id;
		insert claim;
		Cost_Note__c costNote = TestData.createCostNote(claim.Id,'Draft');
		insert costNote;
		Cancellation__c cancellation = TestData.createCancellation(costNote.Id,'Draft');
		insert cancellation;

		// Test
		Test.startTest();

		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		DocumentCreationAction.autoCreateDocument(cancellation.Id,false,'pdf',null,null);

		Test.stopTest();

		// Assertion impossible
	}

	@isTest
	static void testCreditNoteSuccess(){
		// Testsetup
		TriggerConfiguration.allInactive = true;

		// Create admin user to update roles on other users
		User adminUser = TestData.createUser();
		adminUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
		insert adminUser;

		// Create test users and set their roles with admin user
		User legalUser = TestData.createUser();
		legalUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
		legalUser.Username = 'legalUser@cloudworx.agency';
		insert legalUser;

		System.runAs(adminUser) {
			legalUser.UserRoleId = UserRoles.LegalID; // 00E0Y000000Hvm7
			update legalUser;
		}

		// Create test data
		Account account = TestData.createAccount();
		insert account;
		Account legalInsurance = TestData.createAccount();
		legalInsurance.Type = 'Rechtsschutzversicherung';
		insert legalInsurance;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
		opportunity.Legal_Protection_Insurance__c = legalInsurance.Id;
		opportunity.Contact__c = contact.Id;
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id,'Draft');
		claim.Legal__c = legalUser.Id;
		insert claim;
		Credit_Note__c creditNote = TestData.createCreditNote(claim.Id,'Draft');
		insert creditNote;

		// Test
		Test.startTest();

		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		DocumentCreationAction.autoCreateDocument(creditNote.Id,false,'pdf',null,null);

		Test.stopTest();

		// Assertion impossible
	}

	@isTest
	static void testCostNoteReminderSuccess(){
		// Testsetup
		TriggerConfiguration.allInactive = true;

		// Create admin user to update roles on other users
		User adminUser = TestData.createUser();
		adminUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
		insert adminUser;

		// Create test users and set their roles with admin user
		User legalUser = TestData.createUser();
		legalUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
		legalUser.Username = 'legalUser@cloudworx.agency';
		insert legalUser;

		System.runAs(adminUser) {
			legalUser.UserRoleId = UserRoles.LegalID; // 00E0Y000000Hvm7
			update legalUser;
		}

		// Create test data
		Account account = TestData.createAccount();
		insert account;
		Account legalInsurance = TestData.createAccount();
		legalInsurance.Type = 'Rechtsschutzversicherung';
		insert legalInsurance;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
		opportunity.Legal_Protection_Insurance__c = legalInsurance.Id;
		opportunity.Contact__c = contact.Id;
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id,'Draft');
		claim.Legal__c = legalUser.Id;
		insert claim;
		Cost_Note__c costNote = TestData.createCostNote(claim.Id,'Draft');
		insert costNote;
		Cost_Note_Reminder__c costNoteReminder = TestData.createCostNoteReminder(costNote.Id,'Draft');
		insert costNoteReminder;

		// Test
		Test.startTest();

		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		DocumentCreationAction.autoCreateDocument(costNoteReminder.Id,false,'pdf',null,null);

		Test.stopTest();

		// Assertion impossible
	}

	@isTest
	static void testCommissionSuccess(){
		// Testsetup
		TriggerConfiguration.allInactive = true;

		// Create admin user to update roles on other users
		User adminUser = TestData.createUser();
		adminUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
		insert adminUser;

		// Create test users and set their roles with admin user
		User legalUser = TestData.createUser();
		legalUser.ProfileId = [SELECT Id FROM Profile WHERE Name='System Administrator'].Id;
		legalUser.Username = 'legalUser@cloudworx.agency';
		insert legalUser;

		System.runAs(adminUser) {
			legalUser.UserRoleId = UserRoles.LegalID; // 00E0Y000000Hvm7
			update legalUser;
		}

		// Create test data
		Account account = TestData.createAccount();
		insert account;
		Account legalInsurance = TestData.createAccount();
		legalInsurance.Type = 'Rechtsschutzversicherung';
		insert legalInsurance;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
		opportunity.Legal_Protection_Insurance__c = legalInsurance.Id;
		opportunity.Contact__c = contact.Id;
		opportunity.RecordTypeId = Opportunities.dieselSkandalRecordType(); // 0120Y000000W0CY
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id,'Draft');
		claim.Legal__c = legalUser.Id;
		insert claim;
		Cost_Note__c costNote = TestData.createCostNote(claim.Id,'Draft');
		insert costNote;
		Cost_Note_Reminder__c costNoteReminder = TestData.createCostNoteReminder(costNote.Id,'Draft');
		insert costNoteReminder;
		Commission__c commission = TestData.createCommission(account.Id,legalInsurance.Id,20,30,System.today() - 1,System.today());
		insert commission;
		Cost_Note_Payment__c costNotePayment1 = TestData.createCostNotePayment(costNote.Id,100);
		costNotePayment1.Commission__c = commission.Id;
		insert costNotePayment1;
		Cost_Note_Payment__c costNotePayment2 = TestData.createCostNotePayment(costNote.Id,100);
		costNotePayment2.Commission__c = commission.Id;
		insert costNotePayment2;

		TriggerConfiguration.allInactive = false;
		// Test
		Test.startTest();

		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		DocumentCreationAction.autoCreateDocument(commission.Id,false,'pdf',null,null);
		TriggerConfiguration.allInactive = false;
		DocumentCreationAction.autoCreateDocument(commission.Id,false,'sameAsInput',null,null);
		Test.stopTest();

		// Assertion impossible
	}

	@isTest
    static void testError(){
		// Testsetup
        TriggerConfiguration.allInactive = true;

		// Create test data
        Account account = TestData.createAccount();
        account.Type = 'Lebensversicherung';
        insert account;
        Contact contact = TestData.createContact(account.Id);
        insert contact;
		Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
        opportunity.Insurance__c = account.Id;
        opportunity.Contact__c = contact.Id;
        insert opportunity;
        Contract__c contract = TestData.createContract(opportunity.Id);
        insert contract;

        // Test
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpErrorResponseGenerator());
        DocumentCreationAction.autoCreateDocument(contract.Id,false,'pdf',null,null);

        Test.stopTest();

        // Assertion impossible
    }

	@isTest
	static void testTestCaseSuccess(){
		// Testsetup
		TriggerConfiguration.allInactive = true;

		// Create test data
		Account account = TestData.createAccount();
		account.Type = 'Lebensversicherung';
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
		opportunity.Contact__c = contact.Id;
		insert opportunity;
		Test_Case__c testCase = TestData.createTestCase(opportunity.Id);
		insert testCase;

		// Test
		Test.startTest();

		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		DocumentCreationAction.autoCreateDocument(testCase.Id,false,'pdf',null,null);

		Test.stopTest();

		// Assertion impossible
	}

	@isTest
	static void testOpportunityCorrespondenceSuccess(){
		// Testsetup
		TriggerConfiguration.allInactive = true;

		// Create test data
		Account account = TestData.createAccount();
		account.Type = 'Lebensversicherung';
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.CreateOpportunity(account.Id,'New');
		opportunity.Contact__c = contact.Id;
		insert opportunity;
		Opportunity_Correspondence__c opportunityCorrespondence = TestData.createOpportunityCorrespondence(opportunity.Id,'Customer','Draft');
		insert opportunityCorrespondence;

		// Test
		Test.startTest();

		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		DocumentCreationAction.autoCreateDocument(opportunityCorrespondence.Id,false,'pdf',null,null);

		Test.stopTest();

		// Assertion impossible
	}

	@isTest
	static void testDateNotificationSuccess(){
		// Testsetup
		TriggerConfiguration.allInactive = true;

		// Create test data
		User user = TestData.createUser();
		insert user;
		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id,'New');
        opportunity.Contact__c = contact.Id;
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id,'Draft');
		insert claim;
		Date__c thisDate = TestData.createDate(claim.Id);
		insert thisDate;
        Date_Notification__c dateNotification = new Date_Notification__c(
            Date__c = thisDate.Id
        );
		insert dateNotification;

		// Test
		Test.startTest();

		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		DocumentCreationAction.autoCreateDocument(dateNotification.Id,false,'pdf',null,null);

		Test.stopTest();

		// Assertion impossible
	}

	@isTest
	static void testDateRecordSuccess(){
		// Testsetup
		TriggerConfiguration.allInactive = true;

		// Create test data
		User user = TestData.createUser();
		insert user;
		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id,'New');
        opportunity.Contact__c = contact.Id;
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id,'Draft');
		insert claim;
		Date__c thisDate = TestData.createDate(claim.Id);
		insert thisDate;
        Date_Record__c dateRecord = new Date_Record__c(
            Date__c = thisDate.Id
        );
		insert dateRecord;

		// Test
		Test.startTest();

		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		DocumentCreationAction.autoCreateDocument(dateRecord.Id,false,'pdf',null,null);

		Test.stopTest();

		// Assertion impossible
	}

	@isTest
	static void testDateAuthorizationSuccess(){
		// Testsetup
		TriggerConfiguration.allInactive = true;

		// Create test data
		User user = TestData.createUser();
		insert user;
		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id,'New');
        opportunity.Contact__c = contact.Id;
		insert opportunity;
		Claim__c claim = TestData.createClaim(opportunity.Id,'Draft');
		insert claim;
		Date__c thisDate = TestData.createDate(claim.Id);
		insert thisDate;
		Date_Authorization__c dateAuthorization = new Date_Authorization__c(
            date__c = thisDate.Id
        );
		insert dateAuthorization;

		// Test
		Test.startTest();

		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		DocumentCreationAction.autoCreateDocument(dateAuthorization.Id,false,'pdf',null,null);

		Test.stopTest();

		// Assertion impossible
	}
}