objects/Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Authorization_Stages</valueSetName>
        </valueSet>
    </fields>
    <description>Object for storing the customers written authorization.</description>
    <label>Vollmacht</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vollmachten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

globalValueSets/Authorization_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Signed</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <description>Authorization stages.</description>
    <masterLabel>Authorization Stages</masterLabel>
</GlobalValueSet>

classes/SetAuthorizationSigned.cls
// Authorization__c "Unterschrift erhalten" Button
// Vollmacht "Unterschrift erhalten" Button
public class SetAuthorizationSigned {
    private final Authorization__c auth;

    public SetAuthorizationSigned(ApexPages.Standardcontroller stdCtl) {
        this.auth = [
            SELECT Id,
            Stage__c,
            (SELECT Id, Status, Subject, IsClosed FROM Tasks) 
            FROM Authorization__c
            WHERE ID = :stdCtl.getId()
        ];
    }

    public PageReference renderPage() {
        PageReference pageRef;

        if (this.auth.Stage__c != 'Signed'){
            this.auth.Stage__c = 'Signed';
            update this.auth;
        }
        List<Task> updateTasks = Tasks.markAsClosed('Unterschriebene Vollmacht hochladen und Erhalt bestätigen', this.auth);
        if (updateTasks.size() > 0) {
            update updateTasks;
        }

        pageRef = Page.SuccessPage;
        pageRef.setRedirect(true);
        return pageRef;
    }
}