objects/Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vollmachten</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Object for storing the customers written authorization.</description>
    <label>Vollmacht</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vollmachten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

classes/SendAuthorization.cls
// Authorization__c "Vollmacht versenden" Button
public class SendAuthorization {
    private final Authorization__c auth;
    private final Opportunity opp;
    public string errorMsg {get; set;}

    public SendAuthorization(ApexPages.Standardcontroller stdCtl) {
        errorMsg = '';
        this.auth = [
            SELECT ID,
            Opportunity__c
            FROM Authorization__c
            WHERE ID = :stdCtl.getId()
        ];
        this.opp = [
            SELECT ID,
            RecordTypeId,
            Legal_Account__c,
            Account__c,
            Contact__c
            FROM Opportunity
            WHERE ID = :this.auth.Opportunity__c
        ];
    }

    public PageReference renderPage() {
        if (this.opp.Contact__c == null) {
            errorMsg = 'einen Kontakt auf dem Feld "Kunde" der Anfrage';
        }
        if (errorMsg != '') {
            return Null;
        }
        string url = page.SendMail.getUrl() + createUrl();
        System.debug('url: ' +  url);
        return new PageReference(url);
    }

    private string getTpl() {
        // these templates are copied over from ResendAuthorization.apxc
        // https://trello.com/c/9Uydt17V/531-button-vollmacht-versenden
        if (Opportunities.isDieselSkandal(this.opp.RecordTypeId)) { // 0120Y000000W0CY
            if (Accounts.isJCLegal(this.opp.Legal_Account__c)) { // 0010Y000011MYHW
                return EmailTemplates.idOf(EmailTemplates.name.DieselskandalBackofficeResendAuthorizationJaeger); // 00X0Y000001awdy
            }
            if (Accounts.isVH24(this.opp.Account__c)) { // 0010Y00000eCUS9
                return EmailTemplates.idOf(EmailTemplates.name.DieselskandalBackofficeResendAuthorizationVh24); // 00X0Y000000y7Ta
            }
            return EmailTemplates.idOf(EmailTemplates.name.DieselskandalBackofficeResendAuthorizationVr24); // 00X0Y000000y7Tf
        }
        if (Accounts.isJCLegal(this.opp.Legal_Account__c)) { // 0010Y000011MYHW
            return EmailTemplates.idOf(EmailTemplates.name.FzBackofficeResendAuthorizationJaeger); // 00X1v000000SMx9
        }
        if (Accounts.isVH24(this.opp.Account__c)) { // 0010Y00000eCUS9
            return EmailTemplates.idOf(EmailTemplates.name.FzBackofficeResendAuthorizationVh24); // 00X1v000000SMvh
        }
        return EmailTemplates.idOf(EmailTemplates.name.FzBackofficeResendAuthorizationVr24); // 00X1v000000SMvm
        /*
        // these commented out tpls were used in the old code
        // but got replaced by ResendAuthorization tpls
        // https://trello.com/c/9Uydt17V/531-button-vollmacht-versenden
        // Dieselskandal
        if (Opportunities.isDieselSkandal(this.opp.RecordTypeId)) { // 0120Y000000W0CY
            if (Accounts.isJCLegal(this.opp.Legal_Account__c)) { // 0010Y000011MYHW
                return EmailTemplates.idOf(EmailTemplates.LegalAuthorization.DieselJaegerLegalAuthorization);
            }
            if (Accounts.isLegalLeCom(this.opp.Legal_Account__c)) {
                return EmailTemplates.idOf(EmailTemplates.LegalAuthorization.DieselLeComLegalAuthorization);
            }
            if (Accounts.isLegal21(this.opp.Legal_Account__c)) { // 0010Y000013yLnP
                return EmailTemplates.idOf(EmailTemplates.LegalAuthorization.Diesel21LegalLegalAuthorization);
            }
            if (Accounts.isCLLBLegal(this.opp.Legal_Account__c)) { // 0010Y000010COcm
                return EmailTemplates.idOf(EmailTemplates.LegalAuthorization.DieselKainzLegalAuthorization);
            }
            return EmailTemplates.idOf(EmailTemplates.LegalAuthorization.DieselLachmairLegalAuthorization);
        }
        // Lebensversicherung
        if (Accounts.isLegal21(this.opp.Legal_Account__c)) { // 0010Y000013yLnP
            return EmailTemplates.idOf(EmailTemplates.LegalAuthorization.Lv21LegalLegalAuthorization);
        }
        if (Accounts.isLegalLeCom(this.opp.Legal_Account__c)) {
            return EmailTemplates.idOf(EmailTemplates.LegalAuthorization.LvLeComLegalAuthorization);
        }
        if (Accounts.isCLLBLegal(this.opp.Legal_Account__c)) { // 0010Y000010COcm
            return EmailTemplates.idOf(EmailTemplates.LegalAuthorization.LvKainzLegalAuthorization);
        }
        return EmailTemplates.idOf(EmailTemplates.LegalAuthorization.LvJaegerLegalAuthorization);
		*/
    }

    private string createUrl() {
        return
            '?id=' + auth.Id +
            '&recipient=' + this.opp.Contact__c +
            '&tpl=' + getTpl() +
            '&hdl="Vollmacht anfordern."' +
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showCreateFollowUpCheckbox=true' +
            '&attreq=true';
    }
}

// /apex/SendMail?id={!Authorization__c.Id}
// &recipient={!Opportunity.ContactId__c}
// &tpl={!IF(Opportunity.RecordTypeId = '0120Y000000W0CY',IF(Opportunity.Legal_AccountId__c = '0010Y000011MYHW','00X0Y000000dmVP',IF(Opportunity.Legal_AccountId__c = '0010Y000013yLnP','00X0Y000000yAcT',IF(Opportunity.Legal_AccountId__c = '0010Y000010COcm','00X0Y000001ab0t','00X0Y000000sJaE'))),IF(Opportunity.Legal_AccountId__c = '0010Y000013yLnP','00X0Y000000yAWb',IF(Opportunity.Legal_AccountId__c = '0010Y000010COcm','00X0Y000000yAWB','00X0Y000000m8AH')))}
// &hdl="Vollmacht anfordern."
// &showDocumentsList=true
// &showCorrespondenciesList=true
// &showOpportunityAttachmentsList=true
// &showCreateFollowUpCheckbox=true
// &attreq=true