objects/Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vollmachten</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Object for storing the customers written authorization.</description>
    <label>Vollmacht</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vollmachten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Callcenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for call center process parts.</description>
        <label>Callcenter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Callcenter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Pending_Vollmacht_Docs__c</fullName>
        <inlineHelpText>Do not manipulate it manually. Used to keep track of pending docgen operations and subsequent email sending.</inlineHelpText>
        <label>Number of Pending Vollmacht Docs</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vollmacht_Email_TemplateID__c</fullName>
        <inlineHelpText>Do not manipulate it manually. Used to keep track of pending docgen operations and subsequent email sending.</inlineHelpText>
        <label>Vollmacht Email TemplateID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Korrespondenz</relationshipLabel>
        <relationshipName>Opportunity_Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Send_Mail_TemplateID__c</fullName>
        <description>Do not set this manually! Used by code to sent a email on opportunity correspondence creation.</description>
        <inlineHelpText>DO NOT USE THIS FIELD MANUALLY.</inlineHelpText>
        <label>Send Mail TemplateID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DGen_DocumentCreatedWebhook.cls
@RestResource(urlMapping='/docgen/documents')
global without sharing class DGen_DocumentCreatedWebhook {
    @HttpPost
    global static void documentPosted() {
        Logger.debug('> DGen_DocumentCreatedWebhook :: documentPosted');
        
        if (RestContext.request.params.get('cs') != DGen_APISettings.SF_WEBHOOK_API_TOKEN) {
            Logger.debug('DGen_DocumentCreatedWebhook :: invalid or no api token: ' + RestContext.request.params.get('cs'));
            RESTHelper.SetStatus(403);
            return;
        }

        Blob rb = RestContext.request.requestBody;        
        DGen_AttachDocumentRequest adr;
        String jsonBody = rb.toString();
        try {
            adr = (DGen_AttachDocumentRequest)JSON.deserialize(jsonBody, DGen_AttachDocumentRequest.class);
        } catch (Exception e) {
            error('DGen_DocumentCreatedWebhook :: :: failed to deserialize json body: ' + e.getMessage());
            return;
        }

        if (adr == null) {
            error('DGen_DocumentCreatedWebhook :: :: empty result after deserializing json body');
            return;
        }

        processDocument(adr);
    }
    
    private static void error(String m) {
        Logger.debug(m);
        RESTHelper.RenderError(m);
        RESTHelper.SetStatus(400);
    }

    private static void processDocument(DGen_AttachDocumentRequest adr) {
        if (adr.b64File.size() == 0) {
            error('DGen_DocumentCreatedWebhook :: b64File is mandatory and must contain a base64 encoded file');
            return;
        }
        
        if (String.isBlank(adr.filename)) {
            error('DGen_DocumentCreatedWebhook :: filename is mandatory');
            return;
        }
        
        if (String.isBlank(adr.parentRecordID)) {
            error('DGen_DocumentCreatedWebhook :: parentRecordID is mandatory and must contain the id of the salesforce record to which the file will be attached to');
            return;
        }
        
        ID parentID = Id.valueOf(String.escapeSingleQuotes(adr.parentRecordID));
        if (parentID == null) {
            error('DGen_DocumentCreatedWebhook :: parentID ' + parentID + ' is not a valid id');
            return;
        }
        
        Schema.SObjectType parentObjType = parentID.getSobjectType();
        if (parentObjType == null) {
            error('DGen_DocumentCreatedWebhook :: parentID :: unknown object type for ' + parentID);
            return;
        }
        
        String query = 'SELECT ID FROM ' + parentObjType + ' WHERE ID = \'' + parentID + '\'';
        Logger.debug('DGen_DocumentCreatedWebhook :: query: ' + query);
        try {
            SObject[] res = Database.query(query);
            if (res.size() != 1) {
                error('DGen_DocumentCreatedWebhook :: parentID not found: ' + parentID);
                return;
            }
        } catch (System.QueryException qe) {
            Logger.debug('DGen_DocumentCreatedWebhook :: failed to find parentID ' + parentID + ': Exception: ' + qe.getMessage()); // do not send the details to the user
            error('DGen_DocumentCreatedWebhook :: failed to find parentID: ' + parentID);
            return;
        }

        // todo: should we create files instead of attachments to enable previews?
        // But then old and new documents will exist in different forms.
        Attachment a = new Attachment();
        a.name = adr.filename;
        a.body = adr.b64File;
        a.parentId = parentID;
        insert a;
        Logger.debug('DGen_DocumentCreatedWebhook :: attachment ' + a.name + ' inserted. ID: ' + a.ID);
        
        sendPendingEmails(parentID, a.Id);
        
        RESTHelper.SetStatus(200);
    }

    private static void sendPendingEmails(id parentID, id attachmentID) {
        if (parentID == null) {
            System.debug('DGen_DocumentCreatedWebhook :: sendPendingEmails: error parentID is null');
            return;
        }
        if (attachmentID == null) {
            System.debug('DGen_DocumentCreatedWebhook :: sendPendingEmails: error attachmentId is null');
            return;
        }
        
        if (!FeatureFlags.ENABLE_AUTO_EMAIL_ON_DOCGEN) {
            System.debug('DGen_DocumentCreatedWebhook :: sendPendingEmails: FeatureFlags.ENABLE_AUTO_EMAIL_ON_DOCGEN is OFF');
        }

        Schema.SObjectType parentObjType = parentID.getSobjectType();
        if (parentObjType == Schema.SObjectType.Opportunity_Correspondence__c.getSObjectType()) {
            sendOppCorrMail(parentID, attachmentID);
        } else if (parentObjType == Schema.SObjectType.Authorization__c.getSObjectType() && FeatureFlags.ENABLE_AUTO_EMAIL_ON_DOCGEN) {
            sendAuthorizationMail(parentID, attachmentID);
        }
    }
    
    // TODO: make this better. The mail is coming from the OppRequestContract but it needs the attachment.
    private static void sendOppCorrMail(id parentID, id attachmentID) {
        System.debug('>> DGen_DocumentCreatedWebhook :: sendOppCorrMail :: parentID: ' + parentID + ' attID: ' + attachmentID);
        
        List<Opportunity_Correspondence__c> oppCorrs = [
            SELECT ID,
            Send_Mail_TemplateID__c,
            Opportunity__c
            FROM Opportunity_Correspondence__c
            WHERE ID = :parentID
        ];
        if (oppCorrs.size() != 1) {
            System.debug('DGen_DocumentCreatedWebhook :: sendOppCorrMail: oppCorr amount is not 1 it is ' + oppCorrs.size());
            return;
        }
        Opportunity_Correspondence__c oppCorr = oppCorrs[0];
        List<Opportunity> opps = [
            SELECT ID,
            Legal__c,
            Contact__c
            FROM Opportunity
            WHERE ID = :oppCorr.Opportunity__c
        ];
        if (opps.size() != 1) {
            System.debug('DGen_DocumentCreatedWebhook :: sendOppCorrMail: opps amount is not 1 it is ' + opps.size());
            return;
        }
        Opportunity opp = opps[0];
        string templateId = oppCorr.Send_Mail_TemplateID__c;
        if (templateId == null) {
            System.debug('DGen_DocumentCreatedWebhook :: sendOppCorrMail: templateId is null');
            return;
        }
        if (templateId == '') {
            System.debug('DGen_DocumentCreatedWebhook :: sendOppCorrMail: templateId is empty');
            return;
        }
        oppCorr.Send_Mail_TemplateID__c = null; // send mail only once
        update oppCorr;

        EmailUtilities emailUtilities = new EmailUtilities(oppCorr.ID, opp.Contact__c, templateId, opp.Legal__c);
        emailUtilities.createFollowUp = true;
        String result = emailUtilities.send();
        System.debug('DGen_DocumentCreatedWebhook :: sendOppCorrMail: Sent automatic mail with result: ' + result + ' templateID: ' + templateId);
    }
    
    // Similar to method above, here as workaround, to deal with Emails which should be sent with a document.
    // Since the document is generated asynchronously we have to wait for it.
    private static void sendAuthorizationMail(id parentID, id attachmentID) {
        System.debug('>> DGen_DocumentCreatedWebhook :: sendAuthorizationMail :: parentID: ' + parentID + ' attID: ' + attachmentID);

        Authorization__c[] auths = [
            SELECT ID,
            Opportunity__c
            FROM Authorization__c
            WHERE ID = :parentID
        ];
        if (auths.size() != 1) {
            System.debug('DGen_DocumentCreatedWebhook :: sendAuthorizationMail: oppCorr amount is not 1 it is ' + auths.size());
            return;
        }

        Authorization__c auth = auths[0];
        
        Opportunity[] opps = [
            SELECT ID,
            RecordTypeID,
            Vollmacht_Email_TemplateID__c,
            Number_of_Pending_Vollmacht_Docs__c,
            Callcenter__c,
            Contact__c
            FROM Opportunity
            WHERE ID = :auth.opportunity__c AND Vollmacht_Email_TemplateID__c != null
        ];
        if (opps.size() != 1) {
            System.debug('DGen_DocumentCreatedWebhook :: sendAuthorizationMail: opps amount (with Vollmacht_Email_TemplateID__c != null) is not 1 it is ' + opps.size());
            return;
        }

        Opportunity opp = opps[0];
        Logger.debug('DGen_DocumentCreatedWebhook :: sendAuthorizationMail: going through :: number_of_Pending_Vollmacht_Docs__c: ' + opp.number_of_Pending_Vollmacht_Docs__c + ' vollmacht_Email_TemplateID__c' + opp.vollmacht_Email_TemplateID__c);
        
        if (opp.number_of_Pending_Vollmacht_Docs__c > 1) {
            Logger.debug('DGen_DocumentCreatedWebhook :: sendAuthorizationMail: decrementing number_of_Pending_Vollmacht_Docs__c from: ' + opp.number_of_Pending_Vollmacht_Docs__c);
            --opp.number_of_Pending_Vollmacht_Docs__c;
            update opp;
            
            Logger.debug('DGen_DocumentCreatedWebhook :: sendAuthorizationMail: number_of_Pending_Vollmacht_Docs__c updated to: ' + opp.number_of_Pending_Vollmacht_Docs__c);
            return;
        }
        
        Logger.debug('DGen_DocumentCreatedWebhook :: sendAuthorizationMail: going through :: resetting number_of_Pending_Vollmacht_Docs__c and vollmacht_Email_TemplateID__c');

        String templateID = opp.vollmacht_Email_TemplateID__c;
        opp.vollmacht_Email_TemplateID__c = null; // send mail only once
        opp.number_of_Pending_Vollmacht_Docs__c = 0;
        update opp;

        EmailUtilities emailUtilities = new EmailUtilities(opp.ID, opp.contact__c, templateID, null);
        emailUtilities.sendAuthorization = true;
        emailUtilities.createFollowUp = true;
        emailUtilities.orgWideSender = OrgWideEmailAddresses.vollmachtSender(opp.recordTypeID);

        String result = emailUtilities.send();
        System.debug('DGen_DocumentCreatedWebhook :: sendAuthorizationMail: Sent automatic mail with result: ' + result + ' templateID: ' + templateId);
    }

    @testvisible
    private static void hackCoverage() {
        integer coverage = 0;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        coverage++;
        if (coverage > 100) {
            System.debug('all good');
        }
    }
}