objects/Cancellation__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Note__c</fullName>
        <label>Kostennote</label>
        <referenceTo>Cost_Note__c</referenceTo>
        <relationshipLabel>Stornierungen</relationshipLabel>
        <relationshipName>Cancellations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Datum</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Nummer</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Stornierung</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stornierungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Claim__c.object
<CustomObject>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipName>Cost_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Nummer</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Kostennote</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostennoten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Date__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Termine</relationshipLabel>
        <relationshipName>Termine</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Date_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Termin</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Termine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Callcenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for call center process parts.</description>
        <label>Callcenter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Callcenter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Bearbeitungsnummer</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Bypass_process_builder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass process builder</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Cost_Note_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Außergerichtlich</fullName>
    </customValue>
    <customValue>
        <fullName>I. Instanz</fullName>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Selbstbehalt</fullName>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Abschluss</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Cost Note Types</masterLabel>
</GlobalValueSet>

globalValueSets/Date_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Gerichtstermin</fullName>
        <default>true</default>
        <label>Gerichtstermin</label>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Date Types</masterLabel>
</GlobalValueSet>

classes/CancellationsTest.cls
@isTest
public class CancellationsTest {
    @isTest
    static void testUpdateLV() {
        // Testsetup
        TriggerConfiguration.allInactive = true;

        User u = user();
        u.bypass_process_builder__c = true;
        insert u;
        Account account = TestData.createAccount();
        insert account;
        Contact contact = TestData.createContact(account.Id);
        insert contact;
        Opportunity opp = TestData.createOpportunity(account.Id, 'New');
        opp.RecordTypeId = Opportunities.lebensversicherungRecordType();
        opp.Callcenter__c = u.Id;
        insert opp;
        Claim__c claim = TestData.createClaim(opp.Id, 'Draft');
        insert claim;
        Cost_Note__c costNote = TestData.createCostNote(claim.Id, 'Draft');
        costNote.Type__c = 'Sonstiges';
        insert costNote;
        Cancellation__c cancellation = TestData.createCancellation(costNote.Id,'Draft');
        cancellation.Date__c = null;
        insert cancellation;

        TriggerConfiguration.allInactive = false;

        // Test
        Test.startTest();

        cancellation.Date__c = System.today();
        update cancellation;

        Test.stopTest();

        // Assertion
        cancellation = [SELECT Id, Number__c FROM Cancellation__c WHERE Id = :cancellation.Id];
        System.assert(cancellation.Number__c.contains('000001/21VRLV'));
    }

    @isTest
    static void testInsertLV() {
        // Testsetup
        TriggerConfiguration.allInactive = true;

        User u = user();
        u.bypass_process_builder__c = true;
        insert u;
        Account account = TestData.createAccount();
        insert account;
        Contact contact = TestData.createContact(account.Id);
        insert contact;
        Opportunity opp = TestData.createOpportunity(account.Id, 'New');
        opp.RecordTypeId = Opportunities.lebensversicherungRecordType();
        opp.Callcenter__c = u.Id;
        insert opp;
        Claim__c claim = TestData.createClaim(opp.Id, 'Draft');
        insert claim;
        Cost_Note__c costNote = TestData.createCostNote(claim.Id, 'Draft');
        costNote.Type__c = 'Sonstiges';
        insert costNote;
        Cancellation__c cancellation = TestData.createCancellation(costNote.Id,'Draft');

        TriggerConfiguration.allInactive = false;

        // Test
        Test.startTest();

        insert cancellation;

        Test.stopTest();

        // Assertion
        cancellation = [SELECT Id, Number__c FROM Cancellation__c WHERE Id = :cancellation.Id];
        System.assertEquals(String.valueOf(System.now().date().year()) + '1000001/21VRLV', cancellation.Number__c);
    }

    @isTest
    static void testUpdateDG() {
        // Testsetup
        TriggerConfiguration.allInactive = true;

        Account account = TestData.createAccount();
        insert account;
        Contact contact = TestData.createContact(account.Id);
        insert contact;
        Opportunity opportunity = TestData.createOpportunity(account.Id, 'New');
        opportunity.RecordTypeId = Opportunities.dieselSkandalRecordType();
        insert opportunity;
        Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
        insert claim;
        Cost_Note__c costNote = TestData.createCostNote(claim.Id, 'Draft');
        costNote.Type__c = 'Sonstiges';
        insert costNote;
        Cancellation__c cancellation = TestData.createCancellation(costNote.Id,'Draft');
        cancellation.Date__c = null;
        insert cancellation;

        TriggerConfiguration.allInactive = false;

        // Test
        Test.startTest();

        cancellation.Date__c = System.today();
        update cancellation;

        Test.stopTest();

        // Assertion
        cancellation = [SELECT Id, Number__c FROM Cancellation__c WHERE Id = :cancellation.Id];
        System.assertEquals(String.valueOf(System.now().date().year()) + '1000001/DG', cancellation.Number__c);
    }

    @isTest
    static void testInsertDG() {
        // Testsetup
        TriggerConfiguration.allInactive = true;

        Account account = TestData.createAccount();
        insert account;
        Contact contact = TestData.createContact(account.Id);
        insert contact;
        Opportunity opportunity = TestData.createOpportunity(account.Id, 'New');
        opportunity.RecordTypeId = Opportunities.dieselSkandalRecordType();
        insert opportunity;
        Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
        insert claim;
        Cost_Note__c costNote = TestData.createCostNote(claim.Id, 'Draft');
        costNote.Type__c = 'Sonstiges';
        insert costNote;
        Cancellation__c cancellation = TestData.createCancellation(costNote.Id,'Draft');

        TriggerConfiguration.allInactive = false;

        // Test
        Test.startTest();

        insert cancellation;

        Test.stopTest();

        // Assertion
        cancellation = [SELECT Id, Number__c FROM Cancellation__c WHERE Id = :cancellation.Id];
        System.assertEquals(String.valueOf(System.now().date().year()) + '1000001/DG', cancellation.Number__c);
    }

    @isTest
    static void testUpdateFZ() {
        // Testsetup
        TriggerConfiguration.allInactive = true;

        Account account = TestData.createAccount();
        insert account;
        Contact contact = TestData.createContact(account.Id);
        insert contact;
        Opportunity opportunity = TestData.createOpportunity(account.Id, 'New');
        opportunity.RecordTypeId = Opportunities.finanzierungRecordType();
        insert opportunity;
        Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
        insert claim;
        Cost_Note__c costNote = TestData.createCostNote(claim.Id, 'Draft');
        costNote.Type__c = 'Sonstiges';
        insert costNote;
        Cancellation__c cancellation = TestData.createCancellation(costNote.Id,'Draft');
        cancellation.Date__c = null;
        insert cancellation;

        TriggerConfiguration.allInactive = false;

        // Test
        Test.startTest();

        cancellation.Date__c = System.today();
        update cancellation;

        Test.stopTest();

        // Assertion
        cancellation = [SELECT Id, Number__c FROM Cancellation__c WHERE Id = :cancellation.Id];
        System.assertEquals(String.valueOf(System.now().date().year()) + '1000001/CVRFZ', cancellation.Number__c);
    }

    @isTest
    static void testInsertFZ() {
        // Testsetup
        TriggerConfiguration.allInactive = true;

        Account account = TestData.createAccount();
        insert account;
        Contact contact = TestData.createContact(account.Id);
        insert contact;
        Opportunity opportunity = TestData.createOpportunity(account.Id, 'New');
        opportunity.RecordTypeId = Opportunities.finanzierungRecordType();
        insert opportunity;
        Claim__c claim = TestData.createClaim(opportunity.Id, 'Draft');
        insert claim;
        Cost_Note__c costNote = TestData.createCostNote(claim.Id, 'Draft');
        costNote.Type__c = 'Sonstiges';
        insert costNote;
        Cancellation__c cancellation = TestData.createCancellation(costNote.Id,'Draft');

        TriggerConfiguration.allInactive = false;

        // Test
        Test.startTest();

        insert cancellation;

        Test.stopTest();

        // Assertion
        cancellation = [SELECT Id, Number__c FROM Cancellation__c WHERE Id = :cancellation.Id];
        System.assertEquals(String.valueOf(System.now().date().year()) + '1000001/CVRFZ', cancellation.Number__c);
    }

    private static User user() {
        Profile testProfile = [
            SELECT ID 
            FROM Profile
            WHERE Name = 'System Administrator' 
            LIMIT 1
        ];
        return new User(
            LastName = 'Test u1', 
            Username = 'testu1@test.com', 
            Email = 'testu1@test.com', 
            Alias = 'u1', 
            TimeZoneSidKey = 'GMT', 
            LocaleSidKey = 'en_GB', 
            EmailEncodingKey = 'ISO-8859-1', 
            ProfileId = testProfile.Id, 
            LanguageLocaleKey = 'en_US',
            IsActive = true
        );
    }
}