objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Opportunity__r.Account_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unternehmen</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clerk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sachbearbeiter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Clerk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cover_Note_Scope__c</fullName>
        <label>Deckungsumfang</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Cover_Note_Scopes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cover_Note__c</fullName>
        <label>Deckungszusage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Cover_Note_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Protection_Insurance_Case_Number__c</fullName>
        <label>Schadensnummer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for legal process parts.</description>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Legal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason_For_Cover_Note_Refusal__c</fullName>
        <label>Ablehnungsgrund für Deckungszusage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cover_Note_Refusal_Reasons</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Response_Claim_Letter__c</fullName>
        <label>Antwort Anspruchsschreiben</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Insurance_Claim_Letter__c</fullName>
        <label>Antwort Deckungsanfrage Anspruchsschr.</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Insurance_Lawsuit__c</fullName>
        <label>Antwort Deckungsanfrage für Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Insurance_Legal_Opposition__c</fullName>
        <label>Antwort Deckungsanfrage Anwaltswiderspr.</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Lawsuit__c</fullName>
        <label>Antwort Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Legal_Opposition__c</fullName>
        <label>Antwort Anwaltswiderspruch</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Ergebnis</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Stages</valueSetName>
        </valueSet>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Korrespondenzen</relationshipLabel>
        <relationshipName>Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Legal_Protection_Insurance_Case_Number__c</fullName>
        <formula>Claim__r.Legal_Protection_Insurance_Case_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Schadensnummer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Protection_Deductible__c</fullName>
        <label>Selbstbehalt für Rechtsschutz</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
</CustomObject>

globalValueSets/Claim_Cover_Note_Scopes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Extrajudicial</fullName>
        <label>Außergerichtlich</label>
    </customValue>
    <customValue>
        <fullName>Judicial</fullName>
        <label>Gerichtlich</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Without Appeal</fullName>
        <label>Ohne Berufung</label>
    </customValue>
    <customValue>
        <fullName>Arrangement</fullName>
        <label>Vergleich</label>
    </customValue>
    <masterLabel>Claim Cover Note Scopes</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Cover_Note_Statuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Issued</fullName>
        <label>Erteilt</label>
    </customValue>
    <customValue>
        <fullName>Refused</fullName>
        <label>Abgelehnt</label>
    </customValue>
    <masterLabel>Claim Cover Note Statuses</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Results.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accepted</fullName>
        <label>Angenommen</label>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
        <label>Abgelehnt</label>
    </customValue>
    <customValue>
        <fullName>Partial</fullName>
        <label>Teilzahlung</label>
    </customValue>
    <customValue>
        <fullName>Arrangement</fullName>
        <label>Vergleich</label>
    </customValue>
    <customValue>
        <fullName>No Response</fullName>
        <label>Keine Antwort</label>
    </customValue>
    <customValue>
        <fullName>Partially won</fullName>
        <label>Teilweise gewonnen</label>
    </customValue>
    <masterLabel>Claim Results</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Entwurf</label>
    </customValue>
    <customValue>
        <fullName>Customers Opposition</fullName>
        <label>Kundenwiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Legal Opposition</fullName>
        <label>Anwaltswiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Claim Letter</fullName>
        <label>Anspruchsschreiben</label>
    </customValue>
    <customValue>
        <fullName>Lawsuit</fullName>
        <label>Klage</label>
    </customValue>
    <customValue>
        <fullName>Class Action</fullName>
        <label>Sammelklage</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
        <label>Abwicklung</label>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
        <label>Abgeschlossen</label>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <label>Warten auf Grundsatzurteil</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>Abbruch</label>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Examination</fullName>
        <isActive>false</isActive>
        <label>Examination</label>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
        <isActive>false</isActive>
        <label>Success</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
        <isActive>false</isActive>
        <label>Failure</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <isActive>false</isActive>
        <label>Open</label>
    </customValue>
    <description>Claim stages.</description>
    <masterLabel>Claim Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Correspondence_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Correspondence Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Correspondence_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Widerspruch durch Kunden</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Widerspruch</fullName>
    </customValue>
    <customValue>
        <fullName>Widerspruch durch Anwalt</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Anspruchsschreiben</fullName>
    </customValue>
    <customValue>
        <fullName>Anspruchsschreiben</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Klage</fullName>
    </customValue>
    <customValue>
        <fullName>Klageschrift</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungsschrift</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungsbegründung</fullName>
    </customValue>
    <customValue>
        <fullName>Gerichtskostenrechnung</fullName>
    </customValue>
    <customValue>
        <fullName>Replik</fullName>
    </customValue>
    <customValue>
        <fullName>Vollmacht §141 ZPO</fullName>
    </customValue>
    <customValue>
        <fullName>Eingehend</fullName>
    </customValue>
    <customValue>
        <fullName>Fristverlängerung</fullName>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungserwiderung</fullName>
    </customValue>
    <customValue>
        <fullName>Einspruch</fullName>
        <isActive>false</isActive>
        <label>Einspruch</label>
    </customValue>
    <masterLabel>Correspondence Types</masterLabel>
</GlobalValueSet>

globalValueSets/Cover_Note_Refusal_Reasons.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Vorvertraglichkeit</fullName>
    </customValue>
    <customValue>
        <fullName>Nachvertraglichkeit</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Cover Note Refusal Reasons</masterLabel>
</GlobalValueSet>

classes/SetClaimCoverNoteTest.cls
@isTest
public class SetClaimCoverNoteTest {
    private static Claim__c createClaim(string accname) {
        Account a = TestData.createAccount();
        a.name = accname;
        insert a;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;
        }
        Opportunity o = TestData.createOpportunity(a.ID, 'On Hold');
        o.Account__c = a.Id;
        o.Backoffice__c = u.Id;
        insert o;
        Claim__c c = new Claim__c(
            Opportunity__c = o.Id,
            Clerk__c = u.Id,
            Legal__c = u.Id
        );
        return c;
    }

    @isTest
    private static void testAppendScope() {
        ClaimTriggerhandler.Deactivate = true;
        Claim__c c = createClaim('VH24');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Stage__c = 'Claim Letter';
        c.Result__c = 'Declined';
        c.Cover_Note_Scope__c = 'Appeal';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Verteidigungsanzeige'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SetClaimCoverNote oe = new SetClaimCoverNote(sc);

        // Act
        oe.parDescription = 'foo bar world';
        oe.parClaim.Cover_Note__c = 'Refused';
        oe.parClaim.Cover_Note_Scope__c = 'Extrajudicial';
        oe.parClaim.Reason_For_Cover_Note_Refusal__c = 'Sonstiges';
        oe.parOpportunity.Legal_Protection_Deductible__c = 2;
        oe.parClaim.Legal_Protection_Insurance_Case_Number__c = '22';
        PageReference pr = oe.renderPage();

        // test
        Claim__c res = [SELECT Id, Cover_Note_Scope__c FROM Claim__c WHERE Id = :c.Id];
        System.assertNotEquals('Extrajudicial', res.Cover_Note_Scope__c); // don't overwrite
        System.assertEquals(true, res.Cover_Note_Scope__c.contains('Extrajudicial')); // but append
        System.assertEquals(true, res.Cover_Note_Scope__c.contains('Appeal')); // and keep the old
    }

    @isTest
    private static void testLetterDeclined() {
        ClaimTriggerhandler.Deactivate = true;
        Claim__c c = createClaim('VH24');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Stage__c = 'Claim Letter';
        c.Result__c = 'Declined';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Verteidigungsanzeige'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SetClaimCoverNote oe = new SetClaimCoverNote(sc);

        // Act
        oe.parDescription = 'foo bar world';
        oe.parClaim.Cover_Note__c = 'Refused';
        oe.parClaim.Cover_Note_Scope__c = 'Extrajudicial';
        oe.parClaim.Reason_For_Cover_Note_Refusal__c = 'Sonstiges';
        oe.parOpportunity.Legal_Protection_Deductible__c = 2;
        oe.parClaim.Legal_Protection_Insurance_Case_Number__c = '22';
        PageReference pr = oe.renderPage();

        // test
        Claim__c res = [SELECT Id, Stage__c, Response_Insurance_Claim_Letter__c FROM Claim__c WHERE Id = :c.Id];
        // System.assertEquals('On Hold', res.Stage__c);
        System.assertEquals(res.Response_Insurance_Claim_Letter__c, oe.parClaim.Response_Lawsuit__c);
    }

    @isTest
    private static void testLegalAccepted() {
        ClaimTriggerhandler.Deactivate = true;
        Claim__c c = createClaim('VH24');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Stage__c = 'Legal Opposition';
        c.Result__c = 'Accepted';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Verteidigungsanzeige'
        );
        insert corr;
        

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SetClaimCoverNote oe = new SetClaimCoverNote(sc);

        // Act
        oe.parDescription = 'foo bar world';
        oe.parClaim.Cover_Note__c = 'Refused';
        PageReference pr = oe.renderPage();

        // test
        Claim__c res = [SELECT Id, Stage__c, Response_Insurance_Legal_Opposition__c FROM Claim__c WHERE Id = :c.Id];
        System.debug('Claim=' + res.Id + ' Stage=' + res.Stage__c);
        // System.assertEquals('Processing', res.Stage__c); // TODO: probably updated by a trigger process what ever
        System.assertEquals(res.Response_Insurance_Legal_Opposition__c, oe.parClaim.Response_Lawsuit__c);
    }

    @isTest
    private static void testLawsuit() {
        ClaimTriggerhandler.Deactivate = true;
        Claim__c c = createClaim('VH24');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Stage__c = 'Lawsuit';
        // c.Result__c = 'Arrangement';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Verteidigungsanzeige'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SetClaimCoverNote oe = new SetClaimCoverNote(sc);

        // Act
        oe.parDescription = 'foo bar world';
        oe.parClaim.Cover_Note__c = 'Refused';
        PageReference pr = oe.renderPage();

        // test
        Claim__c res = [SELECT Id, Stage__c, Response_Insurance_Lawsuit__c FROM Claim__c WHERE Id = :c.Id];
        System.assertEquals(res.Response_Insurance_Lawsuit__c, oe.parClaim.Response_Lawsuit__c);
    }

    @isTest
    private static void testAppealIssued() {
        ClaimTriggerhandler.Deactivate = true;
        Claim__c c = createClaim('VH24');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Stage__c = 'Appeal';
        // c.Result__c = 'Arrangement';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Verteidigungsanzeige'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SetClaimCoverNote oe = new SetClaimCoverNote(sc);

        // Act
        oe.parDescription = 'foo bar world';
        oe.parClaim.Cover_Note__c = 'Issued';
        PageReference pr = oe.renderPage();

        // test
        Claim__c res = [SELECT Id, Stage__c, Response_Insurance_Lawsuit__c, Cover_Note_Scope__c FROM Claim__c WHERE Id = :c.Id];
        System.assertEquals(res.Response_Insurance_Lawsuit__c, oe.parClaim.Response_Lawsuit__c);
        System.assertEquals(true, res.Cover_Note_Scope__c.contains('Appeal'));
    }

    @isTest
    private static void testLetterDeclinedDate() { // TODO: might be duplicated
        ClaimTriggerhandler.Deactivate = true;
        Claim__c c = createClaim('VH24');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Stage__c = 'Claim Letter';
        c.Response_Claim_Letter__c = System.today();
        c.Result__c = 'Declined';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Verteidigungsanzeige'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SetClaimCoverNote oe = new SetClaimCoverNote(sc);

        // Act
        oe.parDescription = 'foo bar world';
        oe.parClaim.Cover_Note__c = 'Issued';
        PageReference pr = oe.renderPage();

        // test
        Claim__c res = [SELECT Id, Stage__c FROM Claim__c WHERE Id = :c.Id];
        System.assertEquals('Lawsuit', res.Stage__c);
    }

    @isTest
    private static void testLetterAccepted() {
        ClaimTriggerhandler.Deactivate = true;
        Claim__c c = createClaim('VH24');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Stage__c = 'Claim Letter';
        c.Response_Claim_Letter__c = System.today();
        c.Result__c = 'Accepted';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Verteidigungsanzeige'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SetClaimCoverNote oe = new SetClaimCoverNote(sc);

        // Act
        oe.parDescription = 'foo bar world';
        oe.parClaim.Cover_Note__c = 'Issued';
        PageReference pr = oe.renderPage();

        // test
        Claim__c res = [SELECT Id, Stage__c FROM Claim__c WHERE Id = :c.Id];
        System.assertEquals('Processing', res.Stage__c);
    }

    @isTest
    private static void testLegalOppositionDeclined() {
        ClaimTriggerhandler.Deactivate = true;
        Claim__c c = createClaim('VH24');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Stage__c = 'Legal Opposition';
        c.Result__c = 'Declined';
        c.Cover_Note_Scope__c = 'Extrajudicial';
        c.Response_Legal_Opposition__c = System.today();
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Verteidigungsanzeige'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SetClaimCoverNote oe = new SetClaimCoverNote(sc);

        // Act
        oe.parDescription = 'foo bar world';
        oe.parClaim.Cover_Note__c = 'Issued';
        PageReference pr = oe.renderPage();

        // test
        Claim__c res = [SELECT Id, Stage__c FROM Claim__c WHERE Id = :c.Id];
        System.assertEquals('Lawsuit', res.Stage__c);
    }

    @isTest
    private static void testLegalOppositionAccepted() {
        ClaimTriggerhandler.Deactivate = true;
        Claim__c c = createClaim('VH24');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Stage__c = 'Legal Opposition';
        c.Result__c = 'Accepted';
        c.Response_Legal_Opposition__c = System.today();
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Verteidigungsanzeige'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SetClaimCoverNote oe = new SetClaimCoverNote(sc);

        // Act
        oe.parDescription = 'foo bar world';
        oe.parClaim.Cover_Note__c = 'Issued';
        PageReference pr = oe.renderPage();

        // test
        Claim__c res = [SELECT Id, Stage__c FROM Claim__c WHERE Id = :c.Id];
        System.assertEquals('Processing', res.Stage__c);
    }

    @isTest
    private static void testLawsuitIssuedDeclined() {
        ClaimTriggerhandler.Deactivate = true;
        Claim__c c = createClaim('VH24');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Stage__c = 'Lawsuit';
        c.Result__c = 'Declined';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Verteidigungsanzeige'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SetClaimCoverNote oe = new SetClaimCoverNote(sc);

        // Act
        oe.parDescription = 'foo bar world';
        oe.parClaim.Cover_Note__c = 'Issued';
        PageReference pr = oe.renderPage();

        // test
        Claim__c res = [SELECT Id, Stage__c FROM Claim__c WHERE Id = :c.Id];
        System.assertEquals('Lawsuit', res.Stage__c);
    }
}