objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Clerk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sachbearbeiter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Clerk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for legal process parts.</description>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Legal</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Callcenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for call center process parts.</description>
        <label>Callcenter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Callcenter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Insurance_Rate__c</fullName>
        <label>Tarifbezeichnung</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Insurance_Type__c</fullName>
        <label>Versicherungstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Insurance_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Versicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Lebensversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Versicherung)</relationshipLabel>
        <relationshipName>Opportunities_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <businessProcess>Finanzierung</businessProcess>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/SendMail__e.object
<CustomObject>
    <description>SendMailEvent to decouple VH24MailManager</description>
    <label>SendMail</label>
    <pluralLabel>SendMails</pluralLabel>
</CustomObject>

globalValueSets/Insurance_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Kapital-LV</fullName>
    </customValue>
    <customValue>
        <fullName>Rentenversicherung</fullName>
    </customValue>
    <customValue>
        <fullName>fondsgebundene LV</fullName>
    </customValue>
    <customValue>
        <fullName>fondsgebundene RV</fullName>
    </customValue>
    <customValue>
        <fullName>Unfallversicherung</fullName>
    </customValue>
    <customValue>
        <fullName>betriebliche Altersvorsorge</fullName>
    </customValue>
    <customValue>
        <fullName>Nutzung</fullName>
    </customValue>
    <customValue>
        <fullName>sonstiges</fullName>
    </customValue>
    <masterLabel>Insurance Types</masterLabel>
</GlobalValueSet>

classes/MandateMailControllerTest.cls
@isTest
public class MandateMailControllerTest {
    
    @isTest
    private static void testInitDisabled(){
        Account accountInsurance = TestData.createInsurance('123456789');
		insert accountInsurance;
        Account account = TestData.createAccount();
		insert account;
        User backoffice = Testdata.createUser();
        insert backoffice;
        Opportunity opp = TestData.createOpportunity(account.Id, 'check');
        opp.RecordTypeId = [select Id from RecordType where Name = 'Finanzierung' and SobjectType = 'Opportunity'][0].Id;
        opp.Insurance__c = accountInsurance.Id;
        opp.Insurance_Type__c = 'Rentenversicherung';
        opp.Insurance_Rate__c = 'Dummy-Tarifbezeichnung';
        opp.Backoffice__c= backoffice.Id;
        //opp.Legal__c = legal.Id;
        insert opp;
        Claim__c claim = TestData.createClaim(opp.Id,'Customers Opposition');
        claim.Clerk__c = backoffice.Id;
 		insert claim;
		String returnValue = MandateMailController.init(claim.Id);
        System.assertEquals('disabled', returnValue);
    }
    
    @isTest
    private static void testInitEnabled01(){
        Account accountInsurance = TestData.createInsurance('123456789');
		insert accountInsurance;
        Account account = TestData.createAccount();
		insert account;
        User backoffice = Testdata.createUser();
        insert backoffice;
        Opportunity opp = TestData.createOpportunity(account.Id, 'check');
        opp.Insurance__c = accountInsurance.Id;
        opp.Insurance_Type__c = 'Rentenversicherung';
        opp.Insurance_Rate__c = 'Dummy-Tarifbezeichnung';
        opp.Backoffice__c= backoffice.Id;
        //opp.Legal__c = legal.Id;
        insert opp;
        Claim__c claim = TestData.createClaim(opp.Id,'Legal Opposition');
        claim.Clerk__c = backoffice.Id;
 		insert claim;
		String returnValue = MandateMailController.init(claim.Id);
        System.assertEquals(null, returnValue);
    }
    /*
    @isTest
    private static void testInitEnabled02(){
        Account accountInsurance = TestData.createInsurance('12345678');
		insert accountInsurance;
        Account account = TestData.createAccount();
		insert account;
        User backoffice = Testdata.createUser();
        insert backoffice;
        Opportunity opp = TestData.createOpportunity(account.Id, 'check');
        opp.RecordTypeId = [select Id from RecordType where Name = 'Finanzierung' and SobjectType = 'Opportunity'][0].Id;
        opp.Insurance__c = accountInsurance.Id;
        opp.Insurance_Type__c = 'Rentenversicherung';
        opp.Insurance_Rate__c = 'Dummy-Tarifbezeichnung';
        opp.Backoffice__c= backoffice.Id;
        //opp.Legal__c = legal.Id;
        insert opp;
        Claim__c claim = TestData.createClaim(opp.Id,'Legal Opposition');
        claim.Clerk__c = backoffice.Id;
 		insert claim;
		String returnValue = MandateMailController.init(claim.Id);
        System.assertEquals(null, returnValue);
    }
    */
    @isTest
    private static void testInitEnabled03(){
        Account accountInsurance = TestData.createInsurance('123456789');
		insert accountInsurance;
        Account account = TestData.createAccount();
		insert account;
        User backoffice = Testdata.createUser();
        insert backoffice;
        Opportunity opp = TestData.createOpportunity(account.Id, 'check');
        opp.RecordTypeId = [select Id from RecordType where Name = 'Lebensversicherung' and SobjectType = 'Opportunity'][0].Id;
        opp.Insurance__c = accountInsurance.Id;
        opp.Insurance_Type__c = 'Rentenversicherung';
        opp.Insurance_Rate__c = 'Dummy-Tarifbezeichnung';
        opp.Backoffice__c= backoffice.Id;
        opp.Callcenter__c =backoffice.Id;
        //opp.Legal__c = legal.Id;
        insert opp;
        Claim__c claim = TestData.createClaim(opp.Id,'Legal Opposition');
        claim.Clerk__c = backoffice.Id;
 		insert claim;
		String returnValue = MandateMailController.init(claim.Id);
        System.assertEquals(null, returnValue);
    }
 
    @isTest
    private static void testTriggerEvent(){  
        Test.startTest();
        Account accountInsurance = TestData.createInsurance('123456789');
		insert accountInsurance;
        Account account = TestData.createAccount();
		insert account;
        User backoffice = Testdata.createUser();
        insert backoffice;
        Opportunity opp = TestData.createOpportunity(account.Id, 'check');
        opp.Insurance__c = accountInsurance.Id;
        opp.Insurance_Type__c = 'Rentenversicherung';
        opp.Insurance_Rate__c = 'Dummy-Tarifbezeichnung';
        opp.Backoffice__c= backoffice.Id;
        insert opp;
        Claim__c claim = TestData.createClaim(opp.Id,'Legal Opposition');
        claim.Clerk__c = backoffice.Id;
 		insert claim;
        
        String uuid = MandateMailController.retrieveMailUuid();
        MandateMailController.sendMail(opp.Id, 'testmail@test.de', uuid);
        Test.getEventBus().deliver();
    	List<EventBusSubscriber> subscribers = [SELECT Name, Position, Retries, LastError 
			FROM EventBusSubscriber WHERE Topic='SendMail__e' AND Type='ApexTrigger'];
       
        System.assertNotEquals(null, subscribers);
        Test.stopTest();
    }
    
}