objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Refund__c</fullName>
        <formula>Opportunity__r.Refund__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Erstattungsbetrag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Refund__c</fullName>
        <label>Erstattungsbetrag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SetOppRefund.cls
// Claim "Erstattungsbetrag hinterlegen" Button
public class SetOppRefund {
    private final Opportunity opp;
    public Opportunity parOpportunity {get; set;}

    public SetOppRefund(ApexPages.StandardController stdCtl) {
        parOpportunity = new Opportunity();
        Claim__c claim;
        claim = [
            SELECT Id, Opportunity__c
            FROM Claim__c
            WHERE Id = :stdCtl.getId()
        ];

        this.opp = [
            SELECT Id, Refund__c
            FROM Opportunity
            WHERE Id = :claim.Opportunity__c
        ];
    }

    public pageReference renderPage() {
        PageReference pageRef;
        this.opp.Refund__c = parOpportunity.Refund__c;
        update this.opp;

        pageRef = Page.SuccessPage;
        pageRef.setRedirect(true);
        return pageRef;
    }
}