objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Cover_Note_Scope__c</fullName>
        <label>Deckungsumfang</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Cover_Note_Scopes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for legal process parts.</description>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Legal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Korrespondenzen</relationshipLabel>
        <relationshipName>Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

globalValueSets/Claim_Cover_Note_Scopes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Extrajudicial</fullName>
        <label>Außergerichtlich</label>
    </customValue>
    <customValue>
        <fullName>Judicial</fullName>
        <label>Gerichtlich</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Without Appeal</fullName>
        <label>Ohne Berufung</label>
    </customValue>
    <customValue>
        <fullName>Arrangement</fullName>
        <label>Vergleich</label>
    </customValue>
    <masterLabel>Claim Cover Note Scopes</masterLabel>
</GlobalValueSet>

classes/CorrLegalDocumentsComplete.cls
public class CorrLegalDocumentsComplete {
    private final Correspondence__c corr;
    public boolean errorClaim {get; set;}
    public boolean errorLegal {get; set;}

    public CorrLegalDocumentsComplete(ApexPages.StandardController stdCtl) {
        errorClaim = false;
        errorLegal = false;
        this.corr = [
            SELECT Id, Claim__r.Legal__c, Claim__r.Legal__r.isActive, Claim__r.Opportunity__r.Assignment_Type__c, Claim__r.Cover_Note_Scope__c, Claim__r.Opportunity__c,
            (SELECT Id, Status, Subject, IsClosed FROM Tasks)
            FROM Correspondence__c
            WHERE Id = :stdCtl.getId()
        ];
    }

    public PageReference renderPage() {
		PageReference pageRef;
		Correspondence__c newCorrespondence;
        /*
        // claim is mandatory for inserting
        if (this.corr.Claim__r == null) {
            errorClaim = true;
            return null;
        }
		*/
        if (this.corr.Claim__r.Legal__r == null) {
            errorLegal = true;
            return null;
        }

		// Close task
		update Tasks.markAsClosed('Klagedokumente prüfen', this.corr);

		// Create task & correspondence
		if ((this.corr.Claim__r.Opportunity__r.Assignment_Type__c == 'RSV') && ((this.corr.Claim__r.Cover_Note_Scope__c == null) || (this.corr.Claim__r.Cover_Note_Scope__c.contains('Judicial') == false))) {
			newCorrespondence = Correspondences.build(this.corr.Claim__r, 'Legal Protection Insurance', 'Deckungsanfrage für Klage', 'Draft', null);
			if (newCorrespondence != null) {
				insert newCorrespondence;
			}
		} else {
			Task task = Tasks.build('Klageschrift versenden', null, this.corr, this.corr.Claim__r.Legal__r, System.today(), true, false, this.corr.claim__r.Opportunity__c);
			if (task != null) {
				insert task;
			}
		}

		pageRef = Page.SuccessPage;
		pageRef.setRedirect(true);
		return pageRef;
    }
}