objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Court_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gericht des Kunden</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Nur Gerichte dürfen hier ausgewählt werden.</errorMessage>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Gericht</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fälle (Gericht des Kunden)</relationshipLabel>
        <relationshipName>Claims_Court_Customer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Court__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Gericht des Gegners</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Nur Gerichte dürfen hier ausgewählt werden.</errorMessage>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Gericht</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fälle (Gericht)</relationshipLabel>
        <relationshipName>Claims_Court</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Record_Type_Id__c</fullName>
        <formula>Opportunity__r.RecordTypeId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Record Type Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opposing_Counsel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Korrespondenzanwalt</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Faelle_Korrespondenzanwalt</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <formula>Opportunity__r.Vehicle_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fahrzeughersteller</label>
        <type>Text</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Claim_Competent_Court__c</fullName>
        <formula>TEXT(Claim__r.Competent_Court__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Claim Competent Court</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Korrespondenzen</relationshipLabel>
        <relationshipName>Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity_Record_Type_Id__c</fullName>
        <formula>Claim__r.Opportunity__r.RecordTypeId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Record Type Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Partner</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Partners</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Kreditinstitut</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Kreditinstitut)</relationshipLabel>
        <relationshipName>Opportunities_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Versicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Lebensversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Versicherung)</relationshipLabel>
        <relationshipName>Opportunities_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Protection_Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rechtsschutzversicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Rechtsschutzversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Rechtsschutzversicherung)</relationshipLabel>
        <relationshipName>Opportunities_Legal_Protection_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Partner)</relationshipLabel>
        <relationshipName>Opportunities_Partner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fahrzeughersteller</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Fahrzeughersteller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Fahrzeughersteller)</relationshipLabel>
        <relationshipName>Opportunities_Fahrzeughersteller</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Correspondence_Partners.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Insurance</fullName>
        <label>Versicherung</label>
    </customValue>
    <customValue>
        <fullName>Vehicle Brand</fullName>
        <label>Fahrzeughersteller</label>
    </customValue>
    <customValue>
        <fullName>Bank</fullName>
        <label>Kreditinstitut</label>
    </customValue>
    <customValue>
        <fullName>Legal Protection Insurance</fullName>
        <label>Rechtsschutzversicherung</label>
    </customValue>
    <customValue>
        <fullName>Court</fullName>
        <label>Gericht</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
        <label>Kunde</label>
    </customValue>
    <customValue>
        <fullName>Individuell</fullName>
    </customValue>
    <masterLabel>Correspondence Partners</masterLabel>
</GlobalValueSet>

globalValueSets/Correspondence_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Widerspruch durch Kunden</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Widerspruch</fullName>
    </customValue>
    <customValue>
        <fullName>Widerspruch durch Anwalt</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Anspruchsschreiben</fullName>
    </customValue>
    <customValue>
        <fullName>Anspruchsschreiben</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Klage</fullName>
    </customValue>
    <customValue>
        <fullName>Klageschrift</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungsschrift</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungsbegründung</fullName>
    </customValue>
    <customValue>
        <fullName>Gerichtskostenrechnung</fullName>
    </customValue>
    <customValue>
        <fullName>Replik</fullName>
    </customValue>
    <customValue>
        <fullName>Vollmacht §141 ZPO</fullName>
    </customValue>
    <customValue>
        <fullName>Eingehend</fullName>
    </customValue>
    <customValue>
        <fullName>Fristverlängerung</fullName>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungserwiderung</fullName>
    </customValue>
    <customValue>
        <fullName>Einspruch</fullName>
        <isActive>false</isActive>
        <label>Einspruch</label>
    </customValue>
    <masterLabel>Correspondence Types</masterLabel>
</GlobalValueSet>

classes/SendDocViaLetterOrFax.cls
// Correspondence__c "Per Brief oder Fax versenden" Button
// Korrespondenz "Per Brief oder Fax versenden" Button
public class SendDocViaLetterOrFax {
    private final Correspondence__c corr;
    private final Claim__c claim;
    private final Opportunity opp;
    public string errorMsg {get; set;}
    private string recipient;

    public SendDocViaLetterOrFax(ApexPages.Standardcontroller stdCtl) {
        errorMsg = '';
        this.corr = [
            SELECT ID,
            Claim__c,
            Type__c,
            Partner__c,
            Claim_Competent_Court__c
            FROM Correspondence__c
            WHERE ID = :stdCtl.getId()
        ];
        this.claim = [
            SELECT Id,
            Opportunity__c,
            RecordTypeId,
            Opposing_Counsel__c,
            Court_Customer__c,
            Court__c,
            Vehicle_Brand__c
            FROM Claim__c
            WHERE Id = :this.corr.Claim__c
        ];
        this.opp = [
            SELECT Id,
            Contact__c,
            Insurance__c,
            Bank__c,
            RecordTypeId,
            Vehicle_Brand__c,
            Legal_Protection_Insurance__c
            FROM Opportunity
            WHERE Id = :this.claim.Opportunity__c
        ];
    }

    public PageReference renderPage() {
        this.recipient = getRec();
        if (errorMsg != '') {
            return Null;
        }
        string url = page.SendLetterOrFax.getUrl() + createUrl();
        System.debug('url: ' +  url);
        return new PageReference(url);
    }

    private string getHdl() {
        if (this.corr.Type__c == 'Widerspruch durch Kunden') {
            return 'Widerspruch durch Kunden versenden.';
        }
        if (this.corr.Type__c == 'Deckungsanfrage für Widerspruch') {
            return 'Deckungsanfrage für Widerspruch versenden.';
        }
        if (this.corr.Type__c == 'Widerspruch durch Anwalt') {
            return 'Widerspruch durch Anwalt versenden.';
        }
        if (this.corr.Type__c == 'Deckungsanfrage für Klage') {
            return 'Deckungsanfrage für Klage versenden.';
        }
        if (this.corr.Type__c == 'Klageschrift') {
            return 'Klageschrift versenden.';
        }
        return 'Dokument versenden.';
    }

    private string getRec() {
        if (this.corr.Partner__c == 'Court') {
            if (this.corr.Claim_Competent_Court__c == 'Opponent') {
                if (this.claim.Court__c != null) {
                    return this.claim.Court__c;
                }
                errorMsg = 'ein Gericht des Gegners auf dem Fall';
                return null;
            }
            if (this.claim.Court_Customer__c != null) {
                return this.claim.Court_Customer__c;
            }
            errorMsg = 'ein Gericht des Kunden auf dem Fall';
            return null;
        }
        if (this.corr.Partner__c == 'Insurance') {
            if (this.claim.Opposing_Counsel__c != null) {
                return this.claim.Opposing_Counsel__c;
            }
            errorMsg = 'einen Korrespondenzanwalt auf dem Fall';
            return this.opp.Insurance__c;
        }
        if (this.corr.Partner__c == 'Vehicle Brand') {
            if (this.claim.Vehicle_Brand__c != null) {
                return this.claim.Vehicle_Brand__c;
            }
            errorMsg = 'einen Fahrzeughersteller auf dem Fall';
            return this.opp.Vehicle_Brand__c;
        }
        if (this.corr.Partner__c == 'Bank') {
            if (this.opp.Bank__c != null) {
                return this.opp.Bank__c;
            }
            errorMsg = 'ein Kreditinstitut auf der Anfrage';
            return null;
        }
        if (this.corr.Partner__c == 'Legal Protection Insurance') {
            if (this.opp.Legal_Protection_Insurance__c != null) {
                return this.opp.Legal_Protection_Insurance__c;
            }
            errorMsg = 'eine RSV auf der Anfrage';
            return null;
        }
        if (this.corr.Partner__c == 'Customer') {
            if (this.opp.Contact__c != null) {
                return this.opp.Contact__c;
            }
            errorMsg = 'einen Kunden auf der Anfrage';
            return null;
        }
        errorMsg = 'den wert "Gericht", "Versicherung", "Fahrzeughersteller", "Kreditinstitut", "Rechtsschutzversicherung" oder "Kunde" als Partner auf der Anfrage';
        return null;
    }

    private string getBcc() {
        if (Opportunities.isDieselSkandal(this.opp.RecordTypeId)) {
            return 'RA-abgas@verbraucherhilfe24.de';
        }
        return '';
    }

    private string createUrl() {
        return
            '?id=' + corr.Id +
            '&recipient=' + this.recipient +
            '&hdl=' + getHdl() + 
            '&showDocumentsList=true' +
            '&showCorrespondenciesList=true' +
            '&showOpportunityAttachmentsList=true' +
            '&showAuthorizationsList=true' +
            '&showCostNotesList' +
            '&showReceiptsList=true' +
            '&showDatesList=true' +
            '&restrictFileTypes=true' +
            '&bcc=' + getBcc();
    }
}

// /apex/SendLetterOrFax?id={!Correspondence__c.Id}
// &recipient={!IF(TEXT(Correspondence__c.Partner__c) = 'Court',IF(Correspondence__c.Claim_Competent_Court__c = 'Opponent',IF(Claim__c.Court__c != null,Claim__c.CourtId__c,null),IF(Claim__c.Court_Customer__c != null,Claim__c.Court_CustomerId__c,null)),IF(TEXT(Correspondence__c.Partner__c) = 'Insurance',IF(Claim__c.Opposing_Counsel__c != null,Claim__c.Opposing_CounselId__c,Opportunity.InsuranceId__c),IF(TEXT(Correspondence__c.Partner__c) = 'Vehicle Brand',IF(Claim__c.Opposing_Counsel__c != null,Claim__c.Opposing_CounselId__c,Opportunity.Vehicle_BrandId__c),IF(TEXT(Correspondence__c.Partner__c) = 'Bank',IF(Opportunity.Bank__c != null,Opportunity.BankId__c,null),IF(TEXT(Correspondence__c.Partner__c) = 'Legal Protection Insurance',IF(Opportunity.Legal_Protection_Insurance__c != null,Opportunity.Legal_Protection_InsuranceId__c,null),IF(TEXT(Correspondence__c.Partner__c) = 'Customer',IF(Opportunity.Contact__c != null,Opportunity.ContactId__c,null),null))))))}
// &hdl={!IF(TEXT(Correspondence__c.Type__c) = 'Widerspruch durch Kunden','Widerspruch durch Kunden versenden.',IF(TEXT(Correspondence__c.Type__c) = 'Deckungsanfrage für Widerspruch','Deckungsanfrage für Widerspruch versenden.',IF(TEXT(Correspondence__c.Type__c) = 'Widerspruch durch Anwalt','Widerspruch durch Anwalt versenden.',IF(TEXT(Correspondence__c.Type__c) = 'Deckungsanfrage für Klage','Deckungsanfrage für Klage versenden.',IF(TEXT(Correspondence__c.Type__c) = 'Klageschrift','Klageschrift versenden.','Dokument versenden.')))))}
// &showDocumentsList=true
// &showCorrespondenciesList=true
// &showOpportunityAttachmentsList=true
// &showAuthorizationsList=true
// &showCostNotesList
// &showReceiptsList=true
// &showDatesList=true
// &restrictFileTypes=true
// &bcc={!IF(Correspondence__c.Opportunity_Record_Type_Id__c = '0120Y000000W0CY','RA-abgas@verbraucherhilfe24.de','')}