objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Extrajudicial_Cost_Note_Number__c</fullName>
        <label>Nummer der ag. Kostennote</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Open__c</fullName>
        <formula>Amount__c - Cost_Note_Payment_Sum__c - Advance_Payment_By_Legal_Prot_Insurance__c - Advance_Payment_By_Customer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Offene Summe</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipName>Cost_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Nummer</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Kostennote</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostennoten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Open__c</fullName>
        <formula>Amount__c - Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Offene Summe</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <description>Invoice number.</description>
        <label>Rechnungsnummer</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <description>Object for storing and managing invoices towards customers.</description>
    <label>Rechnung</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rechnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Number__c</fullName>
        <label>Bearbeitungsnummer</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Transaction__c.object
<CustomObject>
    <label>Transaktion</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaktionen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Cost_Note_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Außergerichtlich</fullName>
    </customValue>
    <customValue>
        <fullName>I. Instanz</fullName>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Selbstbehalt</fullName>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Abschluss</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Cost Note Types</masterLabel>
</GlobalValueSet>

classes/FinAPITransactionsTests.cls
@isTest
public class FinAPITransactionsTests {
    @isTest
    private static void testFetchAndStorePagination() {
        Test.setMock(HTTPCalloutMock.class, new FinAPIMock());
        
        FinAPISettings ss = new FinAPISettings();
        FinAPI f = new DefaultFinAPI(ss, new DefaultLogger());
        Transaction__c[] tt = f.fetchTransactions(Date.today()-5, 1, 3);
        
        System.assertEquals(4, tt.size());
    }

    // Transaction.purpose is what carries the number which we will search for in invoices, costnotes, etc.
    // Create and test mapping to Opp, Claim, Invoices, CostNotes, CreditNotes, and Receipts.
    //
    // WIP: for now we're using an adapted version of the legacy tests - FinAPITransactionsLegacyTests
    /*
    @isTest
    private static void testMappingInvoice() { 
        // Note that we look for mapping via Opp Number or Invoice Number
        Account a = TestData.createAccount();
        insert a;
        
        Opportunity o = TestData.createOpportunity(a.ID, 'Draft');
        o.number__c = 'numberOpp';
        System.runAs(TestData.bypassUser()) {
			insert o;
        }

        Invoice__c inv = TestData.createInvoice(o.ID);
        inv.number__c = 'numberInv';
        //inv.amount_Open__c = 1000;
        insert inv;
        
        FinAPIMock mock = new FinAPIMock();
		Test.setMock(HTTPCalloutMock.class, mock);
        DefaultFinAPI.CFinApiGetTransactionsResponse resp = new DefaultFinAPI.CFinApiGetTransactionsResponse();
        //resp.amount = 1000;
        mock.response = resp;

        TransactionImportRunnable r = buildRunnable();

        Test.startTest();
        GenericQueueable.enqueue(r);
        Test.stopTest();
        
        
        
        // Test that we have an error margin on the amount, e.g, 1eur.
		
        // todo:
        // - test already mapped payments but transaction not mapped
        // - test no mapping
        // - test no amount matching
        // - test amount with difference below error margin
    }
    
    @isTest
    private static void testMappingClaim() { 
		User u = TestData.legalUser();        
        Claim__c c = ClaimsTests.buildClaim(u, null, 0, null, null);
        c.extrajudicial_Cost_Note_Number__c = null;
        insert c;

        Cost_Note__c cn = TestData.createCostNote(c.ID, 'Draft');
        cn.type__c = 'Außergerichtlich';
        cn.number__c = '12345';
        insert cn;

        FinAPIMock mock = new FinAPIMock();
		Test.setMock(HTTPCalloutMock.class, mock);
        DefaultFinAPI.CFinApiGetTransactionsResponse resp = new DefaultFinAPI.CFinApiGetTransactionsResponse();
        // todo:
        // 
        mock.response = resp;

        TransactionImportRunnable r = buildRunnable();

        Test.startTest();
        GenericQueueable.enqueue(r);
        Test.stopTest();
        
        
        
        // Test that we have an error margin on the amount, e.g, 1eur.
		
    }
    
    private static TransactionImportRunnable buildRunnable() {
        FinAPISettings s = new FinAPISettings();
        FinAPI api = new DefaultFinAPI(s);
        FinAPITransactionMapper m = new FinAPITransactionPurposeMapper();
        return new TransactionImportRunnable(s, api, m);
    }
	*/
}