objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Opportunity__r.Account_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unternehmen</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Canceled_Next_Court_Date__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gerichtstermin abgesagt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cover_Note_Scope__c</fullName>
        <label>Deckungsumfang</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Cover_Note_Scopes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cover_Note__c</fullName>
        <label>Deckungszusage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Cover_Note_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for legal process parts.</description>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Legal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Court_Date__c</fullName>
        <label>Nächster Gerichtstermin</label>
        <summarizedField>Date__c.Date__c</summarizedField>
        <summaryFilterItems>
            <field>Date__c.Type__c</field>
            <operation>equals</operation>
            <value>Gerichtstermin</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Date__c.Stage__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </summaryFilterItems>
        <summaryForeignKey>Date__c.Claim__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason_For_Cover_Note_Refusal__c</fullName>
        <label>Ablehnungsgrund für Deckungszusage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cover_Note_Refusal_Reasons</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Response_Claim_Letter__c</fullName>
        <label>Antwort Anspruchsschreiben</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Insurance_Claim_Letter__c</fullName>
        <label>Antwort Deckungsanfrage Anspruchsschr.</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Insurance_Lawsuit__c</fullName>
        <label>Antwort Deckungsanfrage für Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Insurance_Legal_Opposition__c</fullName>
        <label>Antwort Deckungsanfrage Anwaltswiderspr.</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Ergebnis</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Date_Before_Claim_Statement__c</fullName>
        <label>Übermittlung vor Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submission_Date_Before_Lawsuit_Date__c</fullName>
        <label>Übermittlung vor Gerichtstermin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submitter_Before_Claim_Statement__c</fullName>
        <label>Übermittler vor Klage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Transmitters</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitter_Before_Lawsuit_Date__c</fullName>
        <label>Übermittler vor Gerichtstermin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Transmitters</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <formula>Opportunity__r.Vehicle_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fahrzeughersteller</label>
        <type>Text</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Kreditinstitut</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Kreditinstitut)</relationshipLabel>
        <relationshipName>Opportunities_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Protection_Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rechtsschutzversicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Rechtsschutzversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Rechtsschutzversicherung)</relationshipLabel>
        <relationshipName>Opportunities_Legal_Protection_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fahrzeughersteller</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Fahrzeughersteller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Fahrzeughersteller)</relationshipLabel>
        <relationshipName>Opportunities_Fahrzeughersteller</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <businessProcess>Finanzierung</businessProcess>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

globalValueSets/Claim_Cover_Note_Scopes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Extrajudicial</fullName>
        <label>Außergerichtlich</label>
    </customValue>
    <customValue>
        <fullName>Judicial</fullName>
        <label>Gerichtlich</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Without Appeal</fullName>
        <label>Ohne Berufung</label>
    </customValue>
    <customValue>
        <fullName>Arrangement</fullName>
        <label>Vergleich</label>
    </customValue>
    <masterLabel>Claim Cover Note Scopes</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Cover_Note_Statuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Issued</fullName>
        <label>Erteilt</label>
    </customValue>
    <customValue>
        <fullName>Refused</fullName>
        <label>Abgelehnt</label>
    </customValue>
    <masterLabel>Claim Cover Note Statuses</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Results.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accepted</fullName>
        <label>Angenommen</label>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
        <label>Abgelehnt</label>
    </customValue>
    <customValue>
        <fullName>Partial</fullName>
        <label>Teilzahlung</label>
    </customValue>
    <customValue>
        <fullName>Arrangement</fullName>
        <label>Vergleich</label>
    </customValue>
    <customValue>
        <fullName>No Response</fullName>
        <label>Keine Antwort</label>
    </customValue>
    <customValue>
        <fullName>Partially won</fullName>
        <label>Teilweise gewonnen</label>
    </customValue>
    <masterLabel>Claim Results</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Entwurf</label>
    </customValue>
    <customValue>
        <fullName>Customers Opposition</fullName>
        <label>Kundenwiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Legal Opposition</fullName>
        <label>Anwaltswiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Claim Letter</fullName>
        <label>Anspruchsschreiben</label>
    </customValue>
    <customValue>
        <fullName>Lawsuit</fullName>
        <label>Klage</label>
    </customValue>
    <customValue>
        <fullName>Class Action</fullName>
        <label>Sammelklage</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
        <label>Abwicklung</label>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
        <label>Abgeschlossen</label>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <label>Warten auf Grundsatzurteil</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>Abbruch</label>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Examination</fullName>
        <isActive>false</isActive>
        <label>Examination</label>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
        <isActive>false</isActive>
        <label>Success</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
        <isActive>false</isActive>
        <label>Failure</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <isActive>false</isActive>
        <label>Open</label>
    </customValue>
    <description>Claim stages.</description>
    <masterLabel>Claim Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Transmitters.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Kunde</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <masterLabel>Claim Transmitters</masterLabel>
</GlobalValueSet>

globalValueSets/Cover_Note_Refusal_Reasons.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Vorvertraglichkeit</fullName>
    </customValue>
    <customValue>
        <fullName>Nachvertraglichkeit</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Cover Note Refusal Reasons</masterLabel>
</GlobalValueSet>

classes/ClaimMail.cls
public class ClaimMail {
    // Legacy code, adjusted to remove the hardcoded ids.
    // todo: refactor the if/else mess
    public static void send(Claim__c[] cc, Map<ID, Claim__c> oldClaims) {
        
        cc = [
            SELECT Id,
            Legal__c,
            Stage__c,
            Cover_Note__c,
            Cover_Note_Scope__c,
            Sent_Mail_Flag_1__c,
            Result__c,
            Submission_Date_Before_Claim_Statement__c,
            Submitter_Before_Claim_Statement__c,
            Submission_Date_Before_Lawsuit_Date__c,
            Submitter_Before_Lawsuit_Date__c,
            Response_Claim_Letter__c,
            Next_Court_Date__c,
            Canceled_Next_Court_Date__c,
            Account__c,
            Reason_For_Cover_Note_Refusal__c,
            Response_Insurance_Legal_Opposition__c,
            Response_Insurance_Claim_Letter__c,
            Response_Insurance_Lawsuit__c,
            RecordTypeId,
            Opportunity__c,
            Opportunity__r.Contact__c,
            Opportunity__r.Vehicle_Brand__c,
            Opportunity__r.Legal_Account__c,
            Opportunity__r.Bank__c,
            Opportunity__r.Legal_Protection_Insurance__c
            FROM Claim__c
            WHERE Id IN :cc
        ];
        
        for (Claim__c claim : cc) {
            Logger.debug('>> ClaimMail :: send :: loop claim=' + claim.id + ' recordtype=' + claim.RecordTypeId);

            if (Claims.isDieselSkandal(claim.RecordTypeId)) {
                // DG
                Logger.debug('ClaimMail :: Dieselskandal');
                // Benachrichtigung über Dokumentation Deckungszusage außergerichtlich
                if ((claim.Cover_Note__c != null) && (claim.Response_Insurance_Claim_Letter__c != null) && (claim.Response_Insurance_Claim_Letter__c != oldClaims.get(claim.Id).Response_Insurance_Claim_Letter__c)) {
                    Id templateId;
                    if (claim.Cover_Note__c == 'Issued') {
                        if ((claim.Cover_Note_Scope__c != null) && (claim.Cover_Note_Scope__c.contains('Extrajudicial'))) {
                            if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) {
                                // Jäger
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselJaegerLegalClaimCoverNoteIssuedClaimLetter));
                            } else if (Accounts.isLegal21(claim.Opportunity__r.Legal_Account__c)) {
                                // 21Legal
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.Diesel21LegalLegalClaimCoverNoteIssuedClaimLetter));
                            } else if (Accounts.isCLLBLegal(claim.Opportunity__r.Legal_Account__c)) {
                                // Kainz
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselKainzLegalClaimCoverNoteIssuedClaimLetter));
                            } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                                // LeCom
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselLeComLegalClaimCoverNoteIssuedClaimLetter));
                            } else {
                                // Lachmair
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselLachmairLegalClaimCoverNoteIssuedClaimLetter));
                            }
                        }
                    } else {
                        if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) {
                            // Jäger
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselJaegerLegalClaimCoverNoteRefusedClaimLetter));
                        } else if (Accounts.isLegal21(claim.Opportunity__r.Legal_Account__c)) {
                            // 21Legal
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.Diesel21LegalLegalClaimCoverNoteRefusedClaimLetter));
                        } else if (Accounts.isCLLBLegal(claim.Opportunity__r.Legal_Account__c)) {
                            // Kainz
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselKainzLegalClaimCoverNoteRefusedClaimLetter));
                        } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                            // LeCom
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselLeComLegalClaimCoverNoteRefusedClaimLetter));
                        } else {
                            // Lachmair
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselLachmairLegalClaimCoverNoteRefusedClaimLetter));
                        }
                    }
                    if (templateId != null) {
                        EmailUtilities emailUtilities = new EmailUtilities(claim.Id, claim.Opportunity__r.Contact__c, templateId, claim.Legal__c);
                        String result = emailUtilities.send();
                        System.debug('Sent automatic mail with result: ' + result);
                    }
                }
                
                // Benachrichtigung über Dokumentation Deckungszusage gerichtlich
                if ((claim.Cover_Note__c != null) && (claim.Response_Insurance_Lawsuit__c != null) && (claim.Response_Insurance_Lawsuit__c != oldClaims.get(claim.Id).Response_Insurance_Lawsuit__c)) {
                    Id templateId;
                    if (claim.Cover_Note__c == 'Issued') {
                        if ((claim.Cover_Note_Scope__c != null) && (claim.Cover_Note_Scope__c.contains('Judicial'))) {
                            if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) {
                                // Jäger
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselJaegerLegalClaimCoverNoteIssuedLawsuit));
                            } else if (Accounts.isLegal21(claim.Opportunity__r.Legal_Account__c)) {
                                // 21Legal
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.Diesel21LegalLegalClaimCoverNoteIssuedLawsuit));
                            } else if (Accounts.isCLLBLegal(claim.Opportunity__r.Legal_Account__c)) {
                                // Kainz
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselKainzLegalClaimCoverNoteIssuedLawsuit));
                            } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                                // LeCom
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselLeComLegalClaimCoverNoteIssuedLawsuit));
                            } else {
                                // Lachmair
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselLachmairLegalClaimCoverNoteIssuedLawsuit));
                            }
                        }
                    } else {
                        if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) {
                            // Jäger
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselJaegerLegalClaimCoverNoteRefusedLawsuit));
                        } else if (Accounts.isLegal21(claim.Opportunity__r.Legal_Account__c)) {
                            // 21Legal
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.Diesel21LegalLegalClaimCoverNoteRefusedLawsuit));
                        } else if (Accounts.isCLLBLegal(claim.Opportunity__r.Legal_Account__c)) {
                            // Kainz
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselKainzLegalClaimCoverNoteRefusedLawsuit));
                        } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                            // LeCom
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselLeComLegalClaimCoverNoteRefusedLawsuit));
                        } else {
                            // Lachmair
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselLachmairLegalClaimCoverNoteRefusedLawsuit));
                        }
                    }
                    if (templateId != null) {
                        EmailUtilities emailUtilities = new EmailUtilities(claim.Id, claim.Opportunity__r.Contact__c, templateId, claim.Legal__c);
                        String result = emailUtilities.send();
                        System.debug('Sent automatic mail with result: ' + result);
                    }
                }
                
                // Benachrichtigung über Warten auf Grundsatzurteil
                if ((claim.Stage__c == 'On Hold') && (claim.Stage__c != oldClaims.get(claim.Id).Stage__c)) {
                    Id templateId;
                    if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) {
                        // Jäger
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselJaegerLegalOnHold));
                    } else if (Accounts.isLegal21(claim.Opportunity__r.Legal_Account__c)) {
                        // 21Legal
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.Diesel21LegalLegalOnHold));
                    } else if (Accounts.isCLLBLegal(claim.Opportunity__r.Legal_Account__c)) {
                        // Kainz
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselKainzLegalOnHold));
                    } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                        // LeCom
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselLeComLegalOnHold));
                    } else {
                        // Lachmair
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselLachmairLegalOnHold));
                    }
                    EmailUtilities emailUtilities = new EmailUtilities(claim.Id, claim.Opportunity__r.Contact__c, templateId, claim.Legal__c);
                    String result = emailUtilities.send();
                    System.debug('Sent automatic mail with result: ' + result);
                }
                
                // Benachrichtigung über Absage des Gerichtstermins
                if ((claim.Stage__c == 'Lawsuit') && (claim.Canceled_Next_Court_Date__c == true) && (claim.Canceled_Next_Court_Date__c != oldClaims.get(claim.Id).Canceled_Next_Court_Date__c) && (claim.Sent_Mail_Flag_1__c == false)) {
                    Id templateId;
                    if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) {
                        // Jäger
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselJaegerLegalClaimCanceledNexCourtDate));
                    } else if (Accounts.isLegal21(claim.Opportunity__r.Legal_Account__c)) {
                        // 21Legal
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.Diesel21LegalLegalClaimCanceledNexCourtDate));
                    } else if (Accounts.isCLLBLegal(claim.Opportunity__r.Legal_Account__c)) {
                        // Kainz
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselKainzLegalClaimCanceledNexCourtDate));
                    } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                        // LeCom
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselLeComLegalClaimCanceledNexCourtDate));
                    } else {
                        // Lachmair
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselLachmairLegalClaimCanceledNexCourtDate));
                    }
                    EmailUtilities emailUtilities = new EmailUtilities(claim.Id, claim.Opportunity__r.Contact__c, templateId, claim.Legal__c);
                    String result = emailUtilities.send();
                    System.debug('Sent automatic mail with result: ' + result);
                }
                
                // Email zur Information über automatische Annahme der Eigentümerschaft vor Klage
                if ((claim.Stage__c == 'Lawsuit') && (claim.Submission_Date_Before_Claim_Statement__c != null) && (claim.Submission_Date_Before_Claim_Statement__c != oldClaims.get(claim.Id).Submission_Date_Before_Claim_Statement__c) && (claim.Submitter_Before_Claim_Statement__c == 'System')) {
                    Id templateId;
                    if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) {
                        // Jäger
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselJaegerLegalClaimNoResponseClaimStatement));
                    } else if (Accounts.isLegal21(claim.Opportunity__r.Legal_Account__c)) {
                        // 21Legal
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.Diesel21LegalLegalClaimNoResponseClaimStatement));
                    } else if (Accounts.isCLLBLegal(claim.Opportunity__r.Legal_Account__c)) {
                        // Kainz
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselKainzLegalClaimNoResponseClaimStatement));
                    } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                        // LeCom
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselLeComLegalClaimNoResponseClaimStatement));
                    } else {
                        // Lachmair
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselLachmairLegalClaimNoResponseClaimStatement));
                    }
                    EmailUtilities emailUtilities = new EmailUtilities(claim.Id, claim.Opportunity__r.Contact__c, templateId, claim.Legal__c);
                    String result = emailUtilities.send();
                    System.debug('Sent automatic mail with result: ' + result);
                }
                
                // Email zur Information über automatische Annahme der Eigentümerschaft vor Gerichtstermin
                if ((claim.Stage__c == 'Lawsuit') && (claim.Submission_Date_Before_Lawsuit_Date__c != null) && (claim.Submission_Date_Before_Lawsuit_Date__c != oldClaims.get(claim.Id).Submission_Date_Before_Lawsuit_Date__c) && (claim.Submitter_Before_Lawsuit_Date__c == 'System')) {
                    Id templateId;
                    if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) {
                        // Jäger
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselJaegerLegalClaimNoResponseLawsuitDate));
                    } else if (Accounts.isLegal21(claim.Opportunity__r.Legal_Account__c)) {
                        // 21Legal
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.Diesel21LegalLegalClaimNoResponseLawsuitDate));
                    } else if (Accounts.isCLLBLegal(claim.Opportunity__r.Legal_Account__c)) {
                        // Kainz
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselKainzLegalClaimNoResponseLawsuitDate));
                    } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                        // LeCom
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselLeComLegalClaimNoResponseLawsuitDate));
                    } else {
                        // Lachmair
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.DieselLachmairLegalClaimNoResponseLawsuitDate));
                    }
                    EmailUtilities emailUtilities = new EmailUtilities(claim.Id, claim.Opportunity__r.Contact__c, templateId, claim.Legal__c);
                    String result = emailUtilities.send();
                    System.debug('Sent automatic mail with result: ' + result);
                }
            } else if (claims.isFinanzierung(claim.RecordTypeId)) { // 0121v00000032Pe
                // FZ
                Logger.debug('ClaimMail :: Finanzierung');
                if (
                    (claim.Result__c == 'Accepted' && claim.Stage__c == 'Finished') ||
                    (claim.Result__c == 'Declined' && claim.Stage__c == 'Legal Opposition') ||
                    (claim.Result__c == 'No Response')
                ) {
                    System.debug('ClaimMail :: Finanzierung :: ResultMatch');
                    Id templateId;
                    if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) {
                        // Jäger
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.name.FzJaegerLegalCorrespondenceDeckungsanfrageFuerWiderspruch));
                    } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                        // LeCom
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.name.FzLeComLegalCorrespondenceDeckungsanfrageFuerWiderspruch));
                    } else {
                        // Kainz
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.name.FzKainzLegalCorrespondenceDeckungsanfrageFuerWiderspruch));
                    }
                    if (templateId != null) {
                        //if (claim.Result__c == 'No Response') {
                            if (claim.Opportunity__r.Legal_Protection_Insurance__c == null) {
                                Logger.error('ClaimMail :: error: Failed to send automatic mail Legal_Protection_Insurance__c is null (claim=' + claim.id + ')');
                            } else {
                                EmailUtilities emailUtilities = new EmailUtilities(claim.Id, claim.Opportunity__r.Legal_Protection_Insurance__c, templateId, claim.Legal__c);
                                String result = emailUtilities.send();
                                System.debug('Sent automatic mail to Legal_Protection_Insurance__c with templateid: ' + templateId + ' result: ' + result);
                            }
                        //} else {
                            if (claim.Opportunity__r.Bank__c == null) {
                                Logger.error('ClaimMail :: error: Failed to send automatic mail Bank__c is null (claim=' + claim.id + ')');
                            } else {
                                EmailUtilities emailUtilities = new EmailUtilities(claim.Id, claim.Opportunity__r.Bank__c, templateId, claim.Legal__c);
                                String result = emailUtilities.send();
                                System.debug('Sent automatic mail to Bank__c with templateid: ' + templateId + ' result: ' + result);
                            }
                        // }
                    }
                }
                // Benachrichtigung über Dokumentation Deckungszusage außergerichtlich
                if ((claim.Cover_Note__c != null) && (claim.Response_Insurance_Legal_Opposition__c != null) && (claim.Response_Insurance_Legal_Opposition__c != oldClaims.get(claim.Id).Response_Insurance_Legal_Opposition__c)){
                    Id templateId;
                    if (claim.Cover_Note__c == 'Issued') {
                        if ((claim.Cover_Note_Scope__c != null) && (claim.Cover_Note_Scope__c.contains('Extrajudicial'))){
                            if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) { // 0010Y000011MYHW
                                // Jäger
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.FzJaegerLegalClaimCoverNoteIssuedClaimLetter));
                            } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                                // LeCom
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.FzLeComLegalClaimCoverNoteIssuedClaimLetter));
                            } else {
                                // Kainz
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.FzKainzLegalClaimCoverNoteIssuedClaimLetter));
                            }
                        }
                    } else {
                        if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) {
                            // Jäger
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.FzJaegerLegalClaimCoverNoteRefusedClaimLetter));
                        } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                            // LeCom
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.FzLeComLegalClaimCoverNoteRefusedClaimLetter));
                        } else {
                            // Kainz
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.FzKainzLegalClaimCoverNoteRefusedClaimLetter));
                        }
                    }
                    if (templateId != null) {
                        EmailUtilities emailUtilities = new EmailUtilities(claim.Id, claim.Opportunity__r.Contact__c, templateId, claim.Legal__c);
                        String result = emailUtilities.send();
                        System.debug('Sent automatic mail with result: ' + result);
                    }
                }
                
                // Benachrichtigung über Dokumentation Deckungszusage gerichtlich
                if ((claim.Cover_Note__c != null) && (claim.Response_Insurance_Lawsuit__c != null) && (claim.Response_Insurance_Lawsuit__c != oldClaims.get(claim.Id).Response_Insurance_Lawsuit__c)) {
                    Id templateId;
                    if (claim.Cover_Note__c == 'Issued') {
                        if ((claim.Cover_Note_Scope__c != null) && (claim.Cover_Note_Scope__c.contains('Judicial'))) {
                            if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) {
                                // Jäger
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.FzJaegerLegalClaimCoverNoteIssuedLawsuit));
                            } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                                // LeCom
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.FzLeComLegalClaimCoverNoteIssuedLawsuit));
                            } else {
                                // Kainz
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.FzKainzLegalClaimCoverNoteIssuedLawsuit));
                            }
                        }
                    } else {
                        if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) {
                            // Jäger
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.FzJaegerLegalClaimCoverNoteRefusedLawsuit));
                        } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                            // LeCom
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.FzLeComLegalClaimCoverNoteRefusedLawsuit));
                        } else {
                            // Kainz
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.FzKainzLegalClaimCoverNoteRefusedLawsuit));
                        }
                    }
                    if (templateId != null){
                        EmailUtilities emailUtilities = new EmailUtilities(claim.Id, claim.Opportunity__r.Contact__c, templateId, claim.Legal__c);
                        String result = emailUtilities.send();
                        System.debug('Sent automatic mail with result: ' + result);
                    }
                }
            } else {
                // LV
                Logger.debug('ClaimMail :: Lebensversicherung');

                // Benachrichtigung über Dokumentation Deckungszusage außergerichtlich
                if ((claim.Cover_Note__c != null) && (claim.Response_Insurance_Legal_Opposition__c != null) && (claim.Response_Insurance_Legal_Opposition__c != oldClaims.get(claim.Id).Response_Insurance_Legal_Opposition__c)){
                    Id templateId;
                    if (claim.Cover_Note__c == 'Issued') {
                        if ((claim.Cover_Note_Scope__c != null) && (claim.Cover_Note_Scope__c.contains('Extrajudicial'))) {
                            if (Accounts.isJCLegalLv(claim.Opportunity__r.Legal_Account__c)) {
                                // Jäger
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.LvJaegerLegalClaimCoverNoteIssuedClaimLetter));
                            } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                                // LeCom
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.LvLeComLegalClaimCoverNoteIssuedClaimLetter));
                            } else {
                                // Kainz
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.LvKainzLegalClaimCoverNoteIssuedClaimLetter));
                            }
                        }
                    } else {
                        if (Accounts.isJCLegalLv(claim.Opportunity__r.Legal_Account__c)) {
                            // Jäger
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.LvJaegerLegalClaimCoverNoteRefusedClaimLetter));
                        } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                            // LeCom
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.LvLeComLegalClaimCoverNoteIssuedClaimLetter));
                        } else {
                            // Kainz
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.LvKainzLegalClaimCoverNoteRefusedClaimLetter));
                        }
                    }
                    if (templateId != null){
                        EmailUtilities emailUtilities = new EmailUtilities(claim.Id, claim.Opportunity__r.Contact__c, templateId, claim.Legal__c);
                        String result = emailUtilities.send();
                        System.debug('Sent automatic mail with result: ' + result);
                    }
                }
                
                // Benachrichtigung über Dokumentation Deckungszusage gerichtlich
                if ((claim.Cover_Note__c != null) && (claim.Response_Insurance_Lawsuit__c != null) && (claim.Response_Insurance_Lawsuit__c != oldClaims.get(claim.Id).Response_Insurance_Lawsuit__c)){
                    Id templateId;
                    if (claim.Cover_Note__c == 'Issued'){
                        if ((claim.Cover_Note_Scope__c != null) && (claim.Cover_Note_Scope__c.contains('Judicial'))) {
                            if (Accounts.isJCLegalLv(claim.Opportunity__r.Legal_Account__c)) {
                                // Jäger
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.LvJaegerLegalClaimCoverNoteIssuedLawsuit));
                            } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                                // LeCom
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.LvLeComLegalClaimCoverNoteIssuedLawsuit));
                            } else {
                                // Kainz
                                templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.LvKainzLegalClaimCoverNoteIssuedLawsuit));
                            }
                        }
                    } else {
                        if (Accounts.isJCLegalLv(claim.Opportunity__r.Legal_Account__c)) {
                            // Jäger
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.LvJaegerLegalClaimCoverNoteRefusedLawsuit));
                        } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                            // LeCom
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.LvLeComLegalClaimCoverNoteRefusedLawsuit));
                        } else {
                            // Kainz
                            templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.LvKainzLegalClaimCoverNoteRefusedLawsuit));
                        }
                    }
                    if (templateId != null){
                        EmailUtilities emailUtilities = new EmailUtilities(claim.Id, claim.Opportunity__r.Contact__c, templateId, claim.Legal__c);
                        String result = emailUtilities.send();
                        System.debug('Sent automatic mail with result: ' + result);
                    }
                }
                
                if ((claim.Stage__c == 'On Hold') && (claim.Stage__c != oldClaims.get(claim.Id).Stage__c)) {
                    Id templateId;
                    if (Accounts.isLegal21(claim.Opportunity__r.Legal_Account__c)) {
                        // 21Legal
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.Lv21LegalLegalOnHold));
                    } else if (Accounts.isCLLBLegal(claim.Opportunity__r.Legal_Account__c)) {
                        // Kainz
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.LvKainzLegalOnHold));
                    } else if (Accounts.isLegalLeCom(claim.Opportunity__r.Legal_Account__c)) {
                        // LeCom
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.LvLeComLegalOnHold));
                    } else {
                        // Jäger
                        templateId = Id.valueOf(EmailTemplates.idOf(EmailTemplates.Claims.LvJaegerLegalOnHold));
                    }
                    EmailUtilities emailUtilities = new EmailUtilities(claim.Id, claim.Opportunity__r.Contact__c, templateId, claim.Legal__c);
                    String result = emailUtilities.send();
                    System.debug('Sent automatic mail with result: ' + result);
                }
            }
            Logger.debug('<< ClaimMail :: send');
        }
    }
}