objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Opportunity__r.Account_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unternehmen</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clerk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sachbearbeiter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Clerk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <formula>TEXT(Opportunity__r.Sales_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vertriebstyp</label>
        <type>Text</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_For_Loss__c</fullName>
        <label>Absagegrund</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reasons_For_Loss</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <defaultValue>"Online"</defaultValue>
        <label>Vertriebstyp</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sales_Types</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
</CustomObject>

globalValueSets/Reasons_For_Loss.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Nicht im Zeitraum</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde möchte nicht wegen Preis</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde will nicht</fullName>
    </customValue>
    <customValue>
        <fullName>Widerruf nicht angreifbar</fullName>
    </customValue>
    <customValue>
        <fullName>Potential zu gering</fullName>
    </customValue>
    <customValue>
        <fullName>Kein wirtschaftliches Potential</fullName>
    </customValue>
    <customValue>
        <fullName>Dokumente nicht geschickt</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde hat widerrufen</fullName>
    </customValue>
    <customValue>
        <fullName>Auto verkauft</fullName>
    </customValue>
    <customValue>
        <fullName>Fahrzeug nicht betroffen</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde nicht Käufer</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde nicht erreichbar</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde verstorben</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde hat keine RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Leasing Vertrag</fullName>
    </customValue>
    <customValue>
        <fullName>Keine Widerrufsbelehrung</fullName>
    </customValue>
    <customValue>
        <fullName>BMW EZ nach 01.06.2014</fullName>
    </customValue>
    <customValue>
        <fullName>Darlehensvertrag älter als 2 Jahre</fullName>
    </customValue>
    <customValue>
        <fullName>Nutzungsanteil zu gering</fullName>
    </customValue>
    <customValue>
        <fullName>Kapital zu gering</fullName>
    </customValue>
    <customValue>
        <fullName>Österreich/Schweiz kleiner Motor</fullName>
    </customValue>
    <customValue>
        <fullName>Umrüstung erfolgt</fullName>
    </customValue>
    <customValue>
        <fullName>Mfk nicht bestätigt</fullName>
    </customValue>
    <customValue>
        <fullName>Effektiver Jahreszins 0,00%</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstige Gründe</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstige Gründe (ohne Mail)</fullName>
    </customValue>
    <customValue>
        <fullName>Aussortiert</fullName>
    </customValue>
    <customValue>
        <fullName>Absage wegen Kenntnis</fullName>
    </customValue>
    <masterLabel>Reasons For Loss</masterLabel>
</GlobalValueSet>

globalValueSets/Sales_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
        <default>true</default>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <masterLabel>Sales Types</masterLabel>
</GlobalValueSet>

classes/SetOpportunityLostTest.cls
@isTest
public class SetOpportunityLostTest {
    private static Opportunity createOpp(string accname, string salestype) {
        PageReference p = Page.SetOpportunityLost;
        Test.setCurrentPage(p);

        Account a = TestData.createAccount();
        a.name = accname;
        insert a;
        Opportunity o = TestData.createOpportunity(a.ID, 'On Hold');
        o.Account__c = a.ID;
        o.Sales_Type__c = salestype;
        return o;
    }

    @isTest
    private static void testVH24() {
        Opportunity o = createOpp('VH24', 'Online');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        insert o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        SetOpportunityLost oe = new SetOpportunityLost(sc);

        // Act
        oe.parOpportunity.Reason_For_Loss__c = 'Auto verkauft';
        PageReference pr = oe.renderPage();

        System.assertNotEquals(null, pr);
    }

    @isTest
    private static void testClaimNoClerk() {
        Opportunity o = createOpp('VH24', 'Online');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        insert o;
        Claim__c cl = new Claim__c(
            Opportunity__c = o.id
        );
        insert cl;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        SetOpportunityLost oe = new SetOpportunityLost(sc);

        // Act
        oe.parOpportunity.Reason_For_Loss__c = 'Auto verkauft';
        PageReference pr = oe.renderPage();

        System.assertEquals(null, pr);
    }

    @isTest
    private static void testClaimClerk() {
        TriggerConfiguration.allInactive = true;
        Opportunity o = createOpp('VH24', 'Online');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        insert o;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;
        }
        Claim__c cl = new Claim__c(
            Opportunity__c = o.id,
            Clerk__c = u.Id
        );
        insert cl;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        SetOpportunityLost oe = new SetOpportunityLost(sc);

        // Act
        oe.parOpportunity.Reason_For_Loss__c = 'Auto verkauft';
        PageReference pr = oe.renderPage();

        System.assertNotEquals(null, pr);
    }
}