objects/Claim__c.object
<CustomObject>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipName>Cost_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <defaultValue>14</defaultValue>
        <label>Zahlungsfrist</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Betreff</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Kostennote</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostennoten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Calculate_Vat__c</fullName>
        <defaultValue>true</defaultValue>
        <label>USt. berechnen</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cost_Note__c</fullName>
        <label>Kostennote</label>
        <referenceTo>Cost_Note__c</referenceTo>
        <relationshipLabel>Kostenpunkte</relationshipLabel>
        <relationshipName>Cost_Note_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Beschreibung</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Honorar</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Bezeichnung</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Line_Item_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Kostenpunkt</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostenpunkte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Credit_Note__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipName>Credit_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <defaultValue>14</defaultValue>
        <label>Zahlungsfrist</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Betreff</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Gutschrift</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gutschriften</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Credit_Note_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Calculate_Vat__c</fullName>
        <defaultValue>true</defaultValue>
        <label>USt. berechnen</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Credit_Note__c</fullName>
        <label>Gutschrift</label>
        <referenceTo>Credit_Note__c</referenceTo>
        <relationshipLabel>Gutschriftspositionen</relationshipLabel>
        <relationshipName>Credit_Note_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Beschreibung</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Honorar</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Bezeichnung</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Gutschriftsposition</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gutschriftspositionen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Date__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Termine</relationshipLabel>
        <relationshipName>Termine</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Bezeichnung</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Date_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Termin</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Termine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Cost_Note_Line_Item_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Außergerichtlich</fullName>
    </customValue>
    <customValue>
        <fullName>I. Instanz</fullName>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Cost Note Line Item Types</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Außergerichtlich</fullName>
    </customValue>
    <customValue>
        <fullName>I. Instanz</fullName>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Selbstbehalt</fullName>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Abschluss</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Cost Note Types</masterLabel>
</GlobalValueSet>

globalValueSets/Date_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Gerichtstermin</fullName>
        <default>true</default>
        <label>Gerichtstermin</label>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Date Types</masterLabel>
</GlobalValueSet>

classes/CreateCreditNoteFromCostNote.cls
public class CreateCreditNoteFromCostNote {
    public Credit_Note__c parCreditNote {get; set;}
    public List<CCostNoteLineItem> parCostNoteLineItems {get; set;}
    private final Cost_Note__c note;

    public CreateCreditNoteFromCostNote(ApexPages.StandardController stdCtl) {
        this.note = [
            SELECT Id, Claim__c
            FROM Cost_Note__c
            WHERE Id = :stdCtl.getId()
        ];
        parCreditNote = new Credit_Note__c();
        parCreditNote.Claim__c = note.Claim__c;
        parCostNoteLineItems = new List<CCostNoteLineItem>();

        Cost_Note__c costNote = [select Id,Claim__c,Type__c,Payment_Term__c,(select Id, Description__c, Subject__c, Price__c, Calculate_Vat__c from Cost_Note_Line_Items__r) from Cost_Note__c where Id = :stdCtl.getId()];
        for (Cost_Note_Line_Item__c costNoteLineItem : costNote.Cost_Note_Line_Items__r){
            parCostNoteLineItems.add(new CCostNoteLineItem(costNoteLineItem));
        }
        parCreditNote.Date__c = System.today();
        parCreditNote.Subject__c = 'Gutschrift zu Kostennote mit Typ \"' + costNote.Type__c + '\"';
        parCreditNote.Payment_Term__c = costNote.Payment_Term__c;
        parCreditNote.Claim__c = costNote.Claim__c;
        
    }

    public pageReference renderPage() {
        PageReference pageRef;
        insert parCreditNote;

        List<Credit_Note_Line_Item__c> creditNoteLineItems = new List<Credit_Note_Line_Item__c>();
        for (CCostNoteLineItem costNoteLineItem : parCostNoteLineItems) {
            if (costNoteLineItem.selected == true) {
                Credit_Note_Line_Item__c creditNoteLineItem = new Credit_Note_Line_Item__c(
                    Credit_Note__c = parCreditNote.Id,
                    Description__c = costNoteLineItem.record.Description__c,
                    Subject__c = costNoteLineItem.record.Subject__c,
                    Price__c = costNoteLineItem.record.Price__c,
                    Calculate_Vat__c = costNoteLineItem.record.Calculate_Vat__c
                );
                creditNoteLineItems.add(creditNoteLineItem);
            }
        }
        insert creditNoteLineItems;

        pageRef = new PageReference('/' + parCreditNote.Id);
        pageRef.setRedirect(true);
        return pageRef;
    }

    // TODO: is this a good place?
    public class CCostNoteLineItem {
        public Cost_Note_Line_Item__c record {get; set;}
        public Boolean selected {get; set;}

        public CCostNoteLineItem(Cost_Note_Line_Item__c record) {
            this.record = record;
            selected = true;
        }
    }
}