objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Appeal_Date__c</fullName>
        <label>Datum Berufung</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Appeal_Insurance_Date__c</fullName>
        <label>Datum Deckungsanfrage Berufung</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Claim_Letter_Date__c</fullName>
        <label>Datum Anspruchsschreiben</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Claim_Letter_Insurance_Date__c</fullName>
        <label>Datum Deckungsanfrage Anspruchsschreiben</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer_Opposition_Date__c</fullName>
        <label>Datum Kundenwiderspruch</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Follow_up_Period__c</fullName>
        <defaultValue>14</defaultValue>
        <label>Zeit bis Wiedervorlage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lawsuit_Date__c</fullName>
        <label>Datum Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lawsuit_Insurance_Date__c</fullName>
        <label>Datum Deckungsanfrage Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal_Opposition_Date__c</fullName>
        <label>Datum Anwaltswiderspruch</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal_Opposition_Insurance_Date__c</fullName>
        <label>Datum Deckungsanfrage Anwaltswiderspruch</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for legal process parts.</description>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Legal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Stages</valueSetName>
        </valueSet>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Korrespondenzen</relationshipLabel>
        <relationshipName>Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Follow_up_Period__c</fullName>
        <defaultValue>14</defaultValue>
        <label>Zeit bis Wiedervorlage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wiedervorlage_erstellen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wiedervorlage erstellen</label>
        <type>Checkbox</type>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Date__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Termine</relationshipLabel>
        <relationshipName>Termine</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Follow_up_Period__c</fullName>
        <defaultValue>14</defaultValue>
        <label>Warnzeitraum vor Termin</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Termine</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Date_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Date_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Termin</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Termine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

globalValueSets/Claim_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Entwurf</label>
    </customValue>
    <customValue>
        <fullName>Customers Opposition</fullName>
        <label>Kundenwiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Legal Opposition</fullName>
        <label>Anwaltswiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Claim Letter</fullName>
        <label>Anspruchsschreiben</label>
    </customValue>
    <customValue>
        <fullName>Lawsuit</fullName>
        <label>Klage</label>
    </customValue>
    <customValue>
        <fullName>Class Action</fullName>
        <label>Sammelklage</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
        <label>Abwicklung</label>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
        <label>Abgeschlossen</label>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <label>Warten auf Grundsatzurteil</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>Abbruch</label>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Examination</fullName>
        <isActive>false</isActive>
        <label>Examination</label>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
        <isActive>false</isActive>
        <label>Success</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
        <isActive>false</isActive>
        <label>Failure</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <isActive>false</isActive>
        <label>Open</label>
    </customValue>
    <description>Claim stages.</description>
    <masterLabel>Claim Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Correspondence_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Correspondence Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Correspondence_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Widerspruch durch Kunden</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Widerspruch</fullName>
    </customValue>
    <customValue>
        <fullName>Widerspruch durch Anwalt</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Anspruchsschreiben</fullName>
    </customValue>
    <customValue>
        <fullName>Anspruchsschreiben</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Klage</fullName>
    </customValue>
    <customValue>
        <fullName>Klageschrift</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungsschrift</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungsbegründung</fullName>
    </customValue>
    <customValue>
        <fullName>Gerichtskostenrechnung</fullName>
    </customValue>
    <customValue>
        <fullName>Replik</fullName>
    </customValue>
    <customValue>
        <fullName>Vollmacht §141 ZPO</fullName>
    </customValue>
    <customValue>
        <fullName>Eingehend</fullName>
    </customValue>
    <customValue>
        <fullName>Fristverlängerung</fullName>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungserwiderung</fullName>
    </customValue>
    <customValue>
        <fullName>Einspruch</fullName>
        <isActive>false</isActive>
        <label>Einspruch</label>
    </customValue>
    <masterLabel>Correspondence Types</masterLabel>
</GlobalValueSet>

globalValueSets/Date_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Open</fullName>
        <default>true</default>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Date Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Date_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Gerichtstermin</fullName>
        <default>true</default>
        <label>Gerichtstermin</label>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Date Types</masterLabel>
</GlobalValueSet>

classes/SetCorrespondenceSent.cls
// Correspondence__c "Als versendet markieren" Button
// Korrespondenz "Als versendet markieren" Button
public class SetCorrespondenceSent {
    private final Correspondence__c corr;
    private final Claim__c claim;
    public boolean parCreateFollowUp {get; set;}
    public boolean errorClaim {get; set;}
    public boolean errorLegal {get; set;}

    public SetCorrespondenceSent(ApexPages.StandardController stdCtl) {
        errorClaim = false;
        errorLegal = false;
        this.corr = [
            SELECT Id, Date__c, Claim__c, Stage__c, Type__c, Follow_up_Period__c, Wiedervorlage_erstellen__c,
            (SELECT Id, Status, Subject FROM Tasks)
            FROM Correspondence__c
            WHERE Id = :stdCtl.getId()
        ];
        this.claim = [
            SELECT Id, Stage__c, Follow_up_Period__c, Legal__c, Legal__r.isActive
            FROM Claim__c
            WHERE Id = :this.corr.Claim__c
        ];
        parCreateFollowUp = this.corr.Wiedervorlage_erstellen__c;
    }

    public PageReference renderPage() {
 		PageReference pageRef;

		if (this.corr.Stage__c != 'Sent'){
			this.corr.Stage__c = 'Sent';

			if (this.corr.Type__c == 'Widerspruch durch Kunden') {
				claim.Customer_Opposition_Date__c = this.corr.Date__c;
				update claim;
			} else if (this.corr.Type__c == 'Deckungsanfrage für Anspruchsschreiben') {
				claim.Claim_Letter_Insurance_Date__c = this.corr.Date__c;
				update claim;
			} else if (this.corr.Type__c == 'Anspruchsschreiben') {
				claim.Claim_Letter_Date__c = this.corr.Date__c;
				update claim;
			} else if (this.corr.Type__c == 'Deckungsanfrage für Widerspruch') {
				claim.Legal_Opposition_Insurance_Date__c = this.corr.Date__c;
				update claim;
			} else if (this.corr.Type__c == 'Widerspruch durch Anwalt') {
				claim.Legal_Opposition_Date__c = this.corr.Date__c;
				update claim;
			} else if (this.corr.Type__c == 'Deckungsanfrage für Klage') {
				claim.Lawsuit_Insurance_Date__c = this.corr.Date__c;
				update claim;
			} else if (this.corr.Type__c == 'Klageschrift') {
				claim.Lawsuit_Date__c = this.corr.Date__c;
				update claim;
			} else if (this.corr.Type__c == 'Deckungsanfrage für Berufung') {
				claim.Appeal_Insurance_Date__c = this.corr.Date__c;
				update claim;
			} else if ((this.corr.Type__c == 'Replik') && (claim.Stage__c == 'Appeal')) {
				claim.Appeal_Date__c = this.corr.Date__c;
				update claim;
			}
		}

		// Close Task
		update Utilities.closeTasks('Wiedervorlage', this.corr);
		update Utilities.closeTasks('versenden', this.corr);

        this.corr.Wiedervorlage_erstellen__c = parCreateFollowUp;
        update this.corr;
		// Create Follow-up
		// Created by ProcessBuilder
		/*
		if (parCreateFollowUp == true){
			User usr = [select Id, isActive from User where Id = :UserInfo.getUserId()];
			Task task;
            Date activityDate = System.today() + Integer.valueOf(this.corr.Follow_up_Period__c);
			if (this.corr.Type__c == 'Widerspruch durch Kunden') {
				task = Utilities.createTask('Wiedervorlage bzgl. Kundenwiderspruch', null, this.corr, usr, activityDate, false, true);
			} else if (this.corr.Type__c == 'Widerspruch durch Anwalt') {
				task = Utilities.createTask('Wiedervorlage bzgl. Anwaltswiderspruch', null, this.corr, usr, activityDate, false, true);
			} else if (this.corr.Type__c == 'Anspruchsschreiben') {
				task = Utilities.createTask('Wiedervorlage bzgl. Anspruchsschreiben', null, this.corr, usr, activityDate, false, true);
			} else if (this.corr.Type__c == 'Klageschrift') {
				task = Utilities.createTask('Wiedervorlage bzgl. Klageschrift', null, this.corr, claim.Legal__r, activityDate, false, true);
			} else if (this.corr.Type__c == 'Gerichtskostenrechnung') {
				task = Utilities.createTask('Wiedervorlage bzgl. Gerichtskostenrechnung', null, this.corr, claim.Legal__r, activityDate, false, true);
			} else if (this.corr.Type__c == 'Replik') {
				task = Utilities.createTask('Wiedervorlage bzgl. Replik', null, this.corr, usr, activityDate, false, true);
			} else if (this.corr.Type__c == 'Vollmacht §141 ZPO') {
				task = Utilities.createTask('Wiedervorlage bzgl. Vollmacht §141 ZPO', null, this.corr, usr, activityDate, false, true);
			} else if (this.corr.Type__c == 'Deckungsanfrage für Widerspruch') {
				task = Utilities.createTask('Wiedervorlage bzgl. Deckungsanfrage für Widerspruch', null, this.corr, usr, activityDate, false, true);
			} else if (this.corr.Type__c == 'Deckungsanfrage für Anspruchsschreiben') {
				task = Utilities.createTask('Wiedervorlage bzgl. Deckungsanfrage für Anspruchsschreiben', null, this.corr, usr, activityDate, false, true);
			} else if (this.corr.Type__c == 'Deckungsanfrage für Klage') {
				task = Utilities.createTask('Wiedervorlage bzgl. Deckungsanfrage für Klage', null, this.corr, usr, activityDate, false, true);
			} else if (this.corr.Type__c == 'Deckungsanfrage für Berufung') {
				task = Utilities.createTask('Wiedervorlage bzgl. Deckungsanfrage für Berufung', null, this.corr, usr, activityDate, false, true);
			} else if (this.corr.Type__c == 'Sonstiges') {
				task = Utilities.createTask('Wiedervorlage', null, this.corr, claim.Legal__r, activityDate, false, true);
			} else {
				task = Utilities.createTask('Wiedervorlage', null, this.corr, usr, activityDate, false, true);
			}
			if (task != null) {
				insert task;
			}
		}
		*/

		pageRef = Page.SuccessPage;
		pageRef.setRedirect(true);
		return pageRef;
    }
}