objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for legal process parts.</description>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Legal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Opportunity__r.Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Produkt</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Stages</valueSetName>
        </valueSet>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Produkt</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <businessProcess>Finanzierung</businessProcess>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/SendMail__e.object
<CustomObject>
    <fields>
        <fullName>Is_Recipient_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is_Recipient_Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mail_Id__c</fullName>
        <label>Mail Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mail_Type__c</fullName>
        <description>The Type of Mail which should  be sent</description>
        <label>Mail_Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectId__c</fullName>
        <description>The related Object to which the mail refers</description>
        <label>ObjectId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Adress__c</fullName>
        <label>Recipient_Adress</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>SendMailEvent to decouple VH24MailManager</description>
    <label>SendMail</label>
    <pluralLabel>SendMails</pluralLabel>
</CustomObject>

globalValueSets/Claim_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Entwurf</label>
    </customValue>
    <customValue>
        <fullName>Customers Opposition</fullName>
        <label>Kundenwiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Legal Opposition</fullName>
        <label>Anwaltswiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Claim Letter</fullName>
        <label>Anspruchsschreiben</label>
    </customValue>
    <customValue>
        <fullName>Lawsuit</fullName>
        <label>Klage</label>
    </customValue>
    <customValue>
        <fullName>Class Action</fullName>
        <label>Sammelklage</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
        <label>Abwicklung</label>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
        <label>Abgeschlossen</label>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <label>Warten auf Grundsatzurteil</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>Abbruch</label>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Examination</fullName>
        <isActive>false</isActive>
        <label>Examination</label>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
        <isActive>false</isActive>
        <label>Success</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
        <isActive>false</isActive>
        <label>Failure</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <isActive>false</isActive>
        <label>Open</label>
    </customValue>
    <description>Claim stages.</description>
    <masterLabel>Claim Stages</masterLabel>
</GlobalValueSet>

classes/MandateMailController.cls
public class MandateMailController {
    
    private static boolean isCustomerOpposition;
    
    @AuraEnabled
    public static string init (String claimId){
        Claim__c claim = [Select Stage__c, Opportunity__r.Id, Opportunity__r.Legal__r.Email, Opportunity__r.Product__c
 		FROM Claim__c WHERE Id =: claimId];

        if(isEnabled(claim)){
        	return claim.Opportunity__r.Legal__r.Email;
        } else {
            return 'disabled';
        }
    }
    
    @AuraEnabled
    public static boolean sendMail(String oppId, string mailAddress, String mailId){
        system.debug('----oppId-----' + oppId);  
        system.debug('----mailId-----' + mailId);  
        system.debug('----mailAddress-----' + mailAddress);        
        SendMail__e mailEvent = new SendMail__e(
            Is_Recipient_Address__c = true,
			Mail_Type__c = 'MandateAsMail',
            ObjectId__c = oppId,
         	Recipient_Adress__c = mailAddress,
            Mail_Id__c = mailId
        );
 		Database.SaveResult result = EventBus.publish(mailEvent);
        system.debug('----result-----' + result.isSuccess());
        return true; 
    }
               
    @AuraEnabled
    public static string retrieveMailUuid(){
    	return (String)GUID.Gen(); 
    }
    
    @AuraEnabled
    public static string retrieveOppId(String claimId){
        Claim__c claim = [Select  Opportunity__r.Id FROM Claim__c WHERE Id =: claimId];
        return claim.Opportunity__r.Id;
    }
    
    private static boolean isEnabled(Claim__c claim){
        system.debug('----claim opp producz-----' + claim.Opportunity__r.Product__c);  

        if(claim.Opportunity__r.Product__c == 'Lebensversicherung'
          && claim.Stage__c == 'Legal Opposition') {
        	return true;    
        } else if(claim.Opportunity__r.Product__c == 'Finanzierung'
          && claim.Stage__c == 'Legal Opposition') {
            return true; 
        } else if(claim.Opportunity__r.Product__c == 'Dieselskandal') {
        	return true; 
        }
        return false;
    }

   
}