objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Refund__c</fullName>
        <formula>Opportunity__r.Refund__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Erstattungsbetrag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <formula>Opportunity__r.Test__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Date__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Termine</relationshipLabel>
        <relationshipName>Termine</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Date_Stages</valueSetName>
        </valueSet>
    </fields>
    <label>Termin</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Termine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Bruttosumme</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <description>Invoice number.</description>
        <label>Rechnungsnummer</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Rechnungen</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Invoice_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Uploaded_To_Dropbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hochgeladen</label>
        <type>Checkbox</type>
    </fields>
    <description>Object for storing and managing invoices towards customers.</description>
    <label>Rechnung</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rechnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Has_Legal_Protection_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rechtsschutzversicherung vorhanden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Bearbeitungsnummer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Process_Type__c</fullName>
        <label>Anspruchstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Process_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Refund__c</fullName>
        <label>Erstattungsbetrag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Claim_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Entwurf</label>
    </customValue>
    <customValue>
        <fullName>Customers Opposition</fullName>
        <label>Kundenwiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Legal Opposition</fullName>
        <label>Anwaltswiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Claim Letter</fullName>
        <label>Anspruchsschreiben</label>
    </customValue>
    <customValue>
        <fullName>Lawsuit</fullName>
        <label>Klage</label>
    </customValue>
    <customValue>
        <fullName>Class Action</fullName>
        <label>Sammelklage</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
        <label>Abwicklung</label>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
        <label>Abgeschlossen</label>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <label>Warten auf Grundsatzurteil</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>Abbruch</label>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Examination</fullName>
        <isActive>false</isActive>
        <label>Examination</label>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
        <isActive>false</isActive>
        <label>Success</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
        <isActive>false</isActive>
        <label>Failure</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <isActive>false</isActive>
        <label>Open</label>
    </customValue>
    <description>Claim stages.</description>
    <masterLabel>Claim Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Date_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Open</fullName>
        <default>true</default>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Date Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Invoice_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <description>Invoice stages.</description>
    <masterLabel>Invoice Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Process_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>LV_Opposition</fullName>
        <label>Widerspruch</label>
    </customValue>
    <customValue>
        <fullName>LV_Compensation</fullName>
        <label>Schadenersatz</label>
    </customValue>
    <customValue>
        <fullName>LV_Performance</fullName>
        <label>Erfüllungsanspruch</label>
    </customValue>
    <customValue>
        <fullName>DG_Return</fullName>
        <label>Rückgabe</label>
    </customValue>
    <customValue>
        <fullName>DG_Keep</fullName>
        <label>Behalten</label>
    </customValue>
    <customValue>
        <fullName>DG_Don&apos;t Know</fullName>
        <label>Unentschlossen</label>
    </customValue>
    <masterLabel>Process Types</masterLabel>
</GlobalValueSet>

classes/Invoices.cls
public class Invoices {
    public class InvalidInputException extends Exception {}
    public static Invoice__c build(Claim__c claim, Opportunity opp) {
		Logger.debug('>> Invoices :: build :: opp: ' + opp);
        if (claim == null) {
            throw new InvalidInputException('Claim is mandatory');
        }
        if (opp == null) {
            throw new InvalidInputException('Opportunity is mandatory');
        }

        decimal amount = 0.0;
        if (Opportunities.isDieselskandal(opp.RecordTypeId)) {
            if (opp.Process_Type__c == 'DG_Keep') { // Behalten
                amount = 0.15 * opp.Refund__c;
            } else { // "Rückgabe" "Unentschlossen" "keine Angabe"
                amount = 0.06 * opp.Refund__c;
            }
        } else if (Opportunities.isFinanzierung(opp.RecordTypeId)) {
			amount = 0.17 * opp.Refund__c;
        } else if (Opportunities.isLebensversicherung(opp.RecordTypeId)) {
            if (opp.Has_Legal_Protection_Insurance__c == true) {
                amount = 690; // fix 690 EUR
            } else {
                amount = 0.35 * opp.Refund__c;
            }
        }

        Invoice__c i = new Invoice__c(
        	Opportunity__c = opp.Id,
            Stage__c = 'Draft',
            Date__c = System.today(),
            Amount__c = amount // Bruttosumme
        );

        // Check for duplicates
        for (Invoice__c ei : opp.Invoices__r) {
            /*
            if (ei.Field__c == i.Field__c) {
                // Found duplicate, do not build the object
                return null;
            }
			*/
            return null;
        }

		Logger.debug('<< Invoices :: build :: i: ' + i);
        return i;
    }

    // Legacy code, todo: refactor
    public static void setNumber(Invoice__c[] invoices) {
        Logger.debug('>> Invoices :: setNumber :: invoices: ' + invoices);
        
        List<Invoice__c> oldVhInvoices = [select Number__c from Invoice__c where Opportunity__r.Test__c = false AND CreatedDate = THIS_YEAR AND Number__c LIKE '%IVH' ORDER BY Number__c DESC NULLS LAST LIMIT 1];
        List<Invoice__c> oldVrInvoices = [select Number__c from Invoice__c where Opportunity__r.Test__c = false AND CreatedDate = THIS_YEAR AND Number__c LIKE '%IVR' ORDER BY Number__c DESC NULLS LAST LIMIT 1];

        Integer oldVhInvoicesCount = 0;
        Integer oldVrInvoicesCount = 0;

        if (oldVhInvoices.Size() > 0) {
            oldVhInvoicesCount = Integer.valueOf(oldVhInvoices[0].Number__c.substring(4, 10));
        }
        if (oldVrInvoices.Size() > 0) {
            oldVrInvoicesCount = Integer.valueOf(oldVrInvoices[0].Number__c.substring(4, 10));
        }

        Set<Id> opportunityIds = new Set<Id>();
        for (Invoice__c invoice : invoices) {
            opportunityIds.add(invoice.Opportunity__c);
        }
        Map<Id,Opportunity> opps = new Map<Id,Opportunity>([select Id, Account_Name__c, Test__c from Opportunity where Id IN :opportunityIds]);

        String year = System.now().date().year().format().replace('.', '');
        Integer i = 0;
        for (Invoice__c invoice : invoices) {
            if (invoice.Number__c == null) {
                Opportunity opportunity = opps.get(invoice.Opportunity__c);
                Logger.debug('Opp: ' + opportunity);
                if (opportunity.Test__c == false) {
                    i++;
                }

                Integer VhCount = oldVhInvoicesCount + i;
                Integer VrCount = oldVrInvoicesCount + i;

                if (opportunity.Test__c == true) {
                    invoice.Number__c = year + VrCount.format().replace('.', '').leftPad(6, '0') + '/Test';
                    Logger.debug('Invoices :: setNumber1 :: invoice.Number__c: ' + invoice.Number__c);
                } else if (Opportunities.isVH24(opportunity, false)) {
                    invoice.Number__c = year + VhCount.format().replace('.', '').leftPad(6, '0') + '/IVH';
                    Logger.debug('Invoices :: setNumber2 :: invoice.Number__c: ' + invoice.Number__c);
                } else if (Opportunities.isVR24(opportunity, false)) {
                    invoice.Number__c = year + VrCount.format().replace('.', '').leftPad(6, '0') + '/IVR';
                    Logger.debug('Invoices :: setNumber3 :: invoice.Number__c: ' + invoice.Number__c);
                }
            }
        }
        
        Logger.debug('<< Invoices :: setNumber');
    }
    
	public static void uploadToDropbox(Invoice__c[] invoices, Map<Id,Invoice__c> oldInvoices) {
        List<Id>relatedInvoiceIds = new List<Id>();

        for (Invoice__c invoice : invoices){
            if ((invoice.Stage__c != oldInvoices.get(invoice.Id).Stage__c) && (invoice.Stage__c == 'Sent') && (invoice.Uploaded_To_Dropbox__c == false)){
                relatedInvoiceIds.add(invoice.Id);
            }
        }

        if (relatedInvoiceIds.isEmpty() == false){

            Map<Id, String> paths = new Map<Id, String>{
                    Accounts.VR24ID => '/Accounting/DATEV/VR24/',
                    Accounts.VH24ID => '/Accounting/DATEV/VH24/'
            };

            List<Invoice__c> relatedInvoices = [select Id,Opportunity__r.Account_Id__c,Opportunity__r.Test__c,Date__c from Invoice__c where Id IN :relatedInvoiceIds];
            List<Attachment> attachments = [select Id,ParentId from Attachment where ParentId IN :invoices];

            for (Invoice__c invoice : relatedInvoices){
                for (Attachment attachment : attachments){
                    if (attachment.ParentId == invoice.Id){
                        Date folderDate;
                        if (invoice.Date__c == null) {
                            folderDate = System.now().date();
                        } else {
                            folderDate = invoice.Date__c;
                        }
                        String path;
                        if ((paths.containsKey(invoice.Opportunity__r.Account_Id__c)) && (invoice.Opportunity__r.Test__c == false)) {
                            path = paths.get(invoice.Opportunity__r.Account_Id__c) + folderDate.year() + '/' + folderDate.month() + '/';
                        } else {
                            path = '/Technik/Testdaten/Invoices/' + folderDate.year() + '/' + folderDate.month() + '/';
                        }
                        IntegrateDropbox.uploadFileToDropboxAsync(path, attachment.Id,invoice.Opportunity__r.Account_Id__c);
                    }
                }
            }
        }
	}
}