objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Is_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Kunde ist Eigentümer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for legal process parts.</description>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Legal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Date_Before_Claim_Statement__c</fullName>
        <label>Übermittlung vor Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submitter_Before_Claim_Statement__c</fullName>
        <label>Übermittler vor Klage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Transmitters</valueSetName>
        </valueSet>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Korrespondenzen</relationshipLabel>
        <relationshipName>Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

globalValueSets/Claim_Transmitters.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Kunde</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <masterLabel>Claim Transmitters</masterLabel>
</GlobalValueSet>

classes/ClaimCreateStatement.cls
public class ClaimCreateStatement {
    private final Claim__c claim;

    public ClaimCreateStatement(ApexPages.StandardController stdCtl) {
        this.claim = [
			select Id, Submission_Date_Before_Claim_Statement__c, Legal__c, Legal__r.isActive
            from Claim__c
            WHERE Id = :stdCtl.getId()
        ];
    }

    public PageReference renderPage() {
        PageReference pageRef;

        if (this.claim.Legal__c == null) {
            String errorSubject = 'Fehler!';
            String errorMessage = 'Bitte setzten Sie das Feld Anwalt.';
            pageRef = Errors.page(errorSubject, errorMessage);
            pageRef.setRedirect(true);
            return pageRef;
        }

		Correspondence__c correspondence = Utilities.createCorrespondence(claim, 'Court', 'Klageschrift', 'Draft', null);
		if (correspondence != null) {
			insert correspondence;
		}

		Task task = Utilities.createTask('Klageschrift versenden', null, correspondence, claim.Legal__r, System.today(), true, false);
		if (task != null){
			insert task;
		}

		if (claim.Submission_Date_Before_Claim_Statement__c == null) {
			claim.Submission_Date_Before_Claim_Statement__c = System.today();
			claim.Submitter_Before_Claim_Statement__c = 'System';
			claim.Customer_Is_Owner__c = true;
			update claim;
		}

		pageRef = Page.SuccessPage;
		pageRef.setRedirect(true);
		return pageRef;
    }
}