objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Opportunity__r.Account_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unternehmen</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clerk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sachbearbeiter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Clerk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for legal process parts.</description>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Legal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Ergebnis</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Stages</valueSetName>
        </valueSet>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Korrespondenzen</relationshipLabel>
        <relationshipName>Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Versicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Lebensversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Versicherung)</relationshipLabel>
        <relationshipName>Opportunities_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

globalValueSets/Claim_Results.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accepted</fullName>
        <label>Angenommen</label>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
        <label>Abgelehnt</label>
    </customValue>
    <customValue>
        <fullName>Partial</fullName>
        <label>Teilzahlung</label>
    </customValue>
    <customValue>
        <fullName>Arrangement</fullName>
        <label>Vergleich</label>
    </customValue>
    <customValue>
        <fullName>No Response</fullName>
        <label>Keine Antwort</label>
    </customValue>
    <customValue>
        <fullName>Partially won</fullName>
        <label>Teilweise gewonnen</label>
    </customValue>
    <masterLabel>Claim Results</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Entwurf</label>
    </customValue>
    <customValue>
        <fullName>Customers Opposition</fullName>
        <label>Kundenwiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Legal Opposition</fullName>
        <label>Anwaltswiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Claim Letter</fullName>
        <label>Anspruchsschreiben</label>
    </customValue>
    <customValue>
        <fullName>Lawsuit</fullName>
        <label>Klage</label>
    </customValue>
    <customValue>
        <fullName>Class Action</fullName>
        <label>Sammelklage</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
        <label>Abwicklung</label>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
        <label>Abgeschlossen</label>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <label>Warten auf Grundsatzurteil</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>Abbruch</label>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Examination</fullName>
        <isActive>false</isActive>
        <label>Examination</label>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
        <isActive>false</isActive>
        <label>Success</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
        <isActive>false</isActive>
        <label>Failure</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <isActive>false</isActive>
        <label>Open</label>
    </customValue>
    <description>Claim stages.</description>
    <masterLabel>Claim Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Correspondence_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Correspondence Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Correspondence_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Widerspruch durch Kunden</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Widerspruch</fullName>
    </customValue>
    <customValue>
        <fullName>Widerspruch durch Anwalt</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Anspruchsschreiben</fullName>
    </customValue>
    <customValue>
        <fullName>Anspruchsschreiben</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Klage</fullName>
    </customValue>
    <customValue>
        <fullName>Klageschrift</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungsschrift</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungsbegründung</fullName>
    </customValue>
    <customValue>
        <fullName>Gerichtskostenrechnung</fullName>
    </customValue>
    <customValue>
        <fullName>Replik</fullName>
    </customValue>
    <customValue>
        <fullName>Vollmacht §141 ZPO</fullName>
    </customValue>
    <customValue>
        <fullName>Eingehend</fullName>
    </customValue>
    <customValue>
        <fullName>Fristverlängerung</fullName>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungserwiderung</fullName>
    </customValue>
    <customValue>
        <fullName>Einspruch</fullName>
        <isActive>false</isActive>
        <label>Einspruch</label>
    </customValue>
    <masterLabel>Correspondence Types</masterLabel>
</GlobalValueSet>

classes/ContinueClaimProcessTest.cls
@isTest
public class ContinueClaimProcessTest {
    private static Claim__c createClaim(string record) {
        TriggerConfiguration.allInactive = true;
        Claim__c c;
        System.runAs(TestData.bypassUser()) {
            ClaimTriggerhandler.Deactivate = true;
            Account a = TestData.createAccount();
            a.name = 'VH24';
            a.Type = 'Lebensversicherung';
            insert a;
            User u = TestData.legalUser();
            insert u;
            Opportunity o = TestData.createOpportunity(a.ID, 'On Hold');
            o.Account__c = a.Id;
            o.Backoffice__c = u.Id;
            o.Insurance__c = a.Id;
            RecordType rt = [SELECT Id FROM RecordType WHERE Name = :record AND sObjectType = 'Opportunity'];
            o.RecordTypeId = rt.Id;
            insert o;
            c = new Claim__c(
                Opportunity__c = o.Id,
                Clerk__c = u.Id,
                Legal__c = u.Id
            );
        }
        return c;
    }

    @isTest
    private static void TestDieselSkandalProcessing() {
        Claim__c c = createClaim('Dieselskandal');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Deckungsanfrage Verteidigungsanzeige'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ContinueClaimProcess oe = new ContinueClaimProcess(sc);

        // Act
        PageReference pr = oe.renderPage();

        // test
        Claim__c res = [SELECT Id, Stage__c FROM Claim__c WHERE Id = :c.Id];
        System.assertEquals('Processing', res.Stage__c);
    }

    @isTest
    private static void TestDieselSkandalDeclinedLetter() {
        Claim__c c = createClaim('Dieselskandal');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Result__c = 'Declined';
        c.Stage__c = 'Claim Letter';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Deckungsanfrage Verteidigungsanzeige'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ContinueClaimProcess oe = new ContinueClaimProcess(sc);

        // Act
        PageReference pr = oe.renderPage();

        // test
        Claim__c res = [SELECT Id, Stage__c FROM Claim__c WHERE Id = :c.Id];
        System.assertEquals('Lawsuit', res.Stage__c);
    }

    @isTest
    private static void TestDieselSkandalDeclinedLawsuit() {
        Claim__c c = createClaim('Dieselskandal');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Result__c = 'Declined';
        c.Stage__c = 'Lawsuit';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Deckungsanfrage Verteidigungsanzeige'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ContinueClaimProcess oe = new ContinueClaimProcess(sc);

        // Act
        PageReference pr = oe.renderPage();

        // test
        Claim__c res = [SELECT Id, Stage__c FROM Claim__c WHERE Id = :c.Id];
        System.assertEquals('Appeal', res.Stage__c);
    }

    @isTest
    private static void TestDieselSkandalDeclinedAppeal() {
        Claim__c c = createClaim('Dieselskandal');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Result__c = 'Declined';
        c.Stage__c = 'Appeal';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Deckungsanfrage Verteidigungsanzeige'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ContinueClaimProcess oe = new ContinueClaimProcess(sc);

        // Act
        PageReference pr = oe.renderPage();

        // test
        Claim__c res = [SELECT Id, Stage__c FROM Claim__c WHERE Id = :c.Id];
        System.assertEquals('Processing', res.Stage__c);
    }

    @isTest
    private static void TestLebensVersicherungDeclinedCOpposition() {
        Claim__c c = createClaim('Lebensversicherung');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Result__c = 'Declined';
        c.Stage__c = 'Customers Opposition';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Deckungsanfrage Verteidigungsanzeige'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ContinueClaimProcess oe = new ContinueClaimProcess(sc);

        // Act
        PageReference pr = oe.renderPage();

        // test
        Claim__c res = [SELECT Id, Stage__c FROM Claim__c WHERE Id = :c.Id];
        System.assertEquals('Legal Opposition', res.Stage__c);
    }

    @isTest
    private static void TestLebensVersicherungDeclinedLOpposition() {
        Claim__c c = createClaim('Lebensversicherung');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Result__c = 'Declined';
        c.Stage__c = 'Legal Opposition';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Deckungsanfrage Verteidigungsanzeige'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ContinueClaimProcess oe = new ContinueClaimProcess(sc);

        // Act
        PageReference pr = oe.renderPage();

        // test
		List<Correspondence__c> res = [SELECT Id FROM Correspondence__c WHERE Type__c = 'Widerspruch durch Anwalt'];
        System.assertEquals(1, res.size());
    }

    @isTest
    private static void TestLebensVersicherungDeclinedLOppositionWiderspruch() {
        Claim__c c = createClaim('Lebensversicherung');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Result__c = 'Declined';
        c.Stage__c = 'Legal Opposition';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Widerspruch durch Anwalt'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ContinueClaimProcess oe = new ContinueClaimProcess(sc);

        // TODO: add assertions for task creations:
        //  - create tasks
        //  - count created tasks on claim
        //  - run tests
        //  - count tasks agian and expect all tasks to be closed

        // pre test
        // Task t = Utilities.createTask('Weiterfürung entscheiden', 'foo bar', sObject parentObject, User owner, Date activityDate, Boolean checkExisting, Boolean isFollowUpTask){

        // c.getSObjects('Tasks').size();

        // Act
        PageReference pr = oe.renderPage();

        // test
		// List <Task> res = [SELECT Id FROM Task WHERE Subject = 'Weiterführung entscheiden' AND OwnerId = :c.Id];
        // System.assertEquals(0, res.size());
    }

    @isTest
    private static void TestLebensVersicherungDeclinedLOppositionWiderspruchNoDraft() {
        Claim__c c = createClaim('Lebensversicherung');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Result__c = 'Declined';
        c.Stage__c = 'Legal Opposition';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Widerspruch durch Anwalt',
            Stage__c = 'Sent' // not draft
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ContinueClaimProcess oe = new ContinueClaimProcess(sc);

        // Act
        PageReference pr = oe.renderPage();
    }

    @isTest
    private static void TestLebensVersicherungDeclinedLawsuit() {
        Claim__c c = createClaim('Lebensversicherung');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Result__c = 'Declined';
        c.Stage__c = 'Lawsuit';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Widerspruch durch Anwalt',
            Stage__c = 'Sent' // not draft
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ContinueClaimProcess oe = new ContinueClaimProcess(sc);

        // Act
        PageReference pr = oe.renderPage();
    }

    @isTest
    private static void TestLebensVersicherungDeclinedLawsuitKlage() {
        Claim__c c = createClaim('Lebensversicherung');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Result__c = 'Declined';
        c.Stage__c = 'Lawsuit';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Klageschrift',
            Stage__c = 'Sent' // not draft
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ContinueClaimProcess oe = new ContinueClaimProcess(sc);

        // Act
        PageReference pr = oe.renderPage();
    }

   @isTest
    private static void TestLebensVersicherungDeclinedLawsuitKlageDraft() {
        Claim__c c = createClaim('Lebensversicherung');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Result__c = 'Declined';
        c.Stage__c = 'Lawsuit';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Klageschrift',
            Stage__c = 'Draft'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ContinueClaimProcess oe = new ContinueClaimProcess(sc);

        // Act
        PageReference pr = oe.renderPage();
    }

    //

    @isTest
    private static void TestLebensVersicherungDeclinedAppeal() {
        Claim__c c = createClaim('Lebensversicherung');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Result__c = 'Declined';
        c.Stage__c = 'Appeal';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Widerspruch durch Anwalt',
            Stage__c = 'Sent' // not draft
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ContinueClaimProcess oe = new ContinueClaimProcess(sc);

        // Act
        PageReference pr = oe.renderPage();
    }

    @isTest
    private static void TestLebensVersicherungDeclinedAppealReplik() {
        Claim__c c = createClaim('Lebensversicherung');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Result__c = 'Declined';
        c.Stage__c = 'Appeal';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Replik',
            Stage__c = 'Sent' // not draft
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ContinueClaimProcess oe = new ContinueClaimProcess(sc);

        // Act
        PageReference pr = oe.renderPage();
    }

   @isTest
    private static void TestLebensVersicherungDeclinedAppealReplikDraft() {
        Claim__c c = createClaim('Lebensversicherung');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Result__c = 'Declined';
        c.Stage__c = 'Appeal';
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Replik',
            Stage__c = 'Draft'
        );
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ContinueClaimProcess oe = new ContinueClaimProcess(sc);

        // Act
        PageReference pr = oe.renderPage();
    }

   @isTest
    private static void TestLebensVersicherungArrangement() {
        Claim__c c = createClaim('Lebensversicherung');
        insert c;
        Correspondence__c corr = new Correspondence__c(
            Claim__c = c.Id,
            Type__c = 'Replik'
        );
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        c.recordTypeId = rt.ID;
        c.Result__c = 'Arrangement';
        insert corr;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        ContinueClaimProcess oe = new ContinueClaimProcess(sc);

        // Act
        PageReference pr = oe.renderPage();

        // test
        Claim__c res = [SELECT Id, Stage__c FROM Claim__c WHERE Id = :c.Id];
        System.assertEquals('Processing', res.Stage__c);
    }
}