objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Competent_Court__c</fullName>
        <label>Zuständiges Gericht</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Competent_Courts</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Court_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gericht des Kunden</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Nur Gerichte dürfen hier ausgewählt werden.</errorMessage>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Gericht</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fälle (Gericht des Kunden)</relationshipLabel>
        <relationshipName>Claims_Court_Customer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Court__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Gericht des Gegners</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Nur Gerichte dürfen hier ausgewählt werden.</errorMessage>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Gericht</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fälle (Gericht)</relationshipLabel>
        <relationshipName>Claims_Court</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opposing_Counsel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Korrespondenzanwalt</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Faelle_Korrespondenzanwalt</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <formula>Opportunity__r.Vehicle_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fahrzeughersteller</label>
        <type>Text</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Korrespondenzen</relationshipLabel>
        <relationshipName>Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Partner</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Partners</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Auftragstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assignment_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Kreditinstitut</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Kreditinstitut)</relationshipLabel>
        <relationshipName>Opportunities_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Protection_Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rechtsschutzversicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Rechtsschutzversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Rechtsschutzversicherung)</relationshipLabel>
        <relationshipName>Opportunities_Legal_Protection_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Partner)</relationshipLabel>
        <relationshipName>Opportunities_Partner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fahrzeughersteller</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Fahrzeughersteller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Fahrzeughersteller)</relationshipLabel>
        <relationshipName>Opportunities_Fahrzeughersteller</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
</CustomObject>

globalValueSets/Assignment_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Share</fullName>
    </customValue>
    <customValue>
        <fullName>Direkt</fullName>
    </customValue>
    <customValue>
        <fullName>50%</fullName>
        <isActive>false</isActive>
        <label>50%</label>
    </customValue>
    <customValue>
        <fullName>RSV 20%</fullName>
        <isActive>false</isActive>
        <label>RSV 20%</label>
    </customValue>
    <masterLabel>Assignment Types</masterLabel>
</GlobalValueSet>

globalValueSets/Competent_Courts.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Opponent</fullName>
        <default>true</default>
        <label>Gegner</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
        <label>Kunde</label>
    </customValue>
    <masterLabel>Competent Courts</masterLabel>
</GlobalValueSet>

globalValueSets/Correspondence_Partners.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Insurance</fullName>
        <label>Versicherung</label>
    </customValue>
    <customValue>
        <fullName>Vehicle Brand</fullName>
        <label>Fahrzeughersteller</label>
    </customValue>
    <customValue>
        <fullName>Bank</fullName>
        <label>Kreditinstitut</label>
    </customValue>
    <customValue>
        <fullName>Legal Protection Insurance</fullName>
        <label>Rechtsschutzversicherung</label>
    </customValue>
    <customValue>
        <fullName>Court</fullName>
        <label>Gericht</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
        <label>Kunde</label>
    </customValue>
    <customValue>
        <fullName>Individuell</fullName>
    </customValue>
    <masterLabel>Correspondence Partners</masterLabel>
</GlobalValueSet>

globalValueSets/Correspondence_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Widerspruch durch Kunden</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Widerspruch</fullName>
    </customValue>
    <customValue>
        <fullName>Widerspruch durch Anwalt</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Anspruchsschreiben</fullName>
    </customValue>
    <customValue>
        <fullName>Anspruchsschreiben</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Klage</fullName>
    </customValue>
    <customValue>
        <fullName>Klageschrift</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungsschrift</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungsbegründung</fullName>
    </customValue>
    <customValue>
        <fullName>Gerichtskostenrechnung</fullName>
    </customValue>
    <customValue>
        <fullName>Replik</fullName>
    </customValue>
    <customValue>
        <fullName>Vollmacht §141 ZPO</fullName>
    </customValue>
    <customValue>
        <fullName>Eingehend</fullName>
    </customValue>
    <customValue>
        <fullName>Fristverlängerung</fullName>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungserwiderung</fullName>
    </customValue>
    <customValue>
        <fullName>Einspruch</fullName>
        <isActive>false</isActive>
        <label>Einspruch</label>
    </customValue>
    <masterLabel>Correspondence Types</masterLabel>
</GlobalValueSet>

classes/SendDocViaLetterOrFaxTest.cls
@isTest
public class SendDocViaLetterOrFaxTest {
    private static Opportunity createOpp() {
        Account a = TestData.createAccount();
        a.name = 'Bla';
        insert a;
        Opportunity o = TestData.createOpportunity(a.ID, 'On Hold');
        o.Assignment_Type__c = 'RSV';
        insert o;
		return o;
    }

    @isTest
    private static void testNoCompetetCourtOpponent() {
        Opportunity o = createOpp();
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        claim.Competent_Court__c = 'Opponent';
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Court';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendDocViaLetterOrFax oe = new SendDocViaLetterOrFax(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals('ein Gericht des Gegners auf dem Fall', oe.errorMsg);
    }

    @isTest
    private static void testCompetetCourtOpponentFZ() {
        Account a = TestData.createAccount();
        a.Type = 'Gericht';
        insert a;
        Opportunity o = createOpp();
        o.RecordTypeId = Opportunities.finanzierungRecordType();
        update o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        claim.Competent_Court__c = 'Opponent';
        claim.Court__c = a.Id;
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Court';
        c.Type__c = 'Widerspruch durch Kunden';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendDocViaLetterOrFax oe = new SendDocViaLetterOrFax(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertNotEquals('ein Gericht des Gegners auf dem Fall', oe.errorMsg);
        System.assertEquals('', oe.errorMsg);
        System.assertNotEquals(null, pr);
    }

    @isTest
    private static void testCompetetCourtOpponentFZWithEmailUtilities() {
        Account a = TestData.createAccount();
        a.Type = 'Gericht';
        insert a;
        Opportunity o = createOpp();
        o.RecordTypeId = Opportunities.finanzierungRecordType();
        update o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        claim.Competent_Court__c = 'Opponent';
        claim.Court__c = a.Id;
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Court';
        c.Type__c = 'Widerspruch durch Kunden';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendDocViaLetterOrFax oe = new SendDocViaLetterOrFax(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertNotEquals('ein Gericht des Gegners auf dem Fall', oe.errorMsg);
        System.assertEquals('', oe.errorMsg);
        System.assertNotEquals(null, pr);

        Test.setCurrentPage(pr);
        EmailUtilities eu = new EmailUtilities();
    }

    @isTest
    private static void testNoCompetetCourtCustomer() {
        Opportunity o = createOpp();
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        claim.Competent_Court__c = 'Customer';
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Court';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendDocViaLetterOrFax oe = new SendDocViaLetterOrFax(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals('ein Gericht des Kunden auf dem Fall', oe.errorMsg);
    }

    @isTest
    private static void testCompetetCourtCustomer() {
        Account a = TestData.createAccount();
        a.Type = 'Gericht';
        insert a;
        Opportunity o = createOpp();
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        claim.Competent_Court__c = 'Customer';
        claim.Court_Customer__c = a.Id;
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Court';
        c.Type__c = 'Deckungsanfrage für Widerspruch';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendDocViaLetterOrFax oe = new SendDocViaLetterOrFax(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertNotEquals('ein Gericht des Kunden auf dem Fall', oe.errorMsg);
        System.assertEquals('', oe.errorMsg);
        System.assertNotEquals(null, pr);
    }

    @isTest
    private static void testInsuranceOpposing() {
        Contact con = new Contact(FirstName = 'Foo', LastName = 'Bar');
        insert con;
        Opportunity o = createOpp();
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        claim.Opposing_Counsel__c = con.ID;
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Insurance';
        c.Type__c = 'Widerspruch durch Anwalt';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendDocViaLetterOrFax oe = new SendDocViaLetterOrFax(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertNotEquals('einen Korrespondenzanwalt auf dem Fall', oe.errorMsg);
        System.assertEquals('', oe.errorMsg);
        System.assertNotEquals(null, pr);
    }

    @isTest
    private static void testNoInsuranceOpposing() {
        Opportunity o = createOpp();
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        claim.Opposing_Counsel__c = null;
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Insurance';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendDocViaLetterOrFax oe = new SendDocViaLetterOrFax(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals('einen Korrespondenzanwalt auf dem Fall', oe.errorMsg);
    }

    @isTest
    private static void testVehicle() {
		Account a = TestData.createAccount();
        a.Type = 'Fahrzeughersteller';
        insert a;
        Opportunity o = createOpp();
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Vehicle Brand';
        c.Type__c = 'Deckungsanfrage für Klage';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendDocViaLetterOrFax oe = new SendDocViaLetterOrFax(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertNotEquals('einen Fahrzeughersteller auf dem Fall', oe.errorMsg);
        System.assertEquals('', oe.errorMsg);
        System.assertNotEquals(null, pr);
    }

    @isTest
    private static void testNoVehcile() {
        Opportunity o = createOpp();
        o.Vehicle_Brand__c = null;
        update o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        claim.Opposing_Counsel__c = null;
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Vehicle Brand';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendDocViaLetterOrFax oe = new SendDocViaLetterOrFax(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals('einen Fahrzeughersteller auf dem Fall', oe.errorMsg);
    }

    @isTest
    private static void testBank() {
		Account a = TestData.createAccount();
        insert a;
        Opportunity o = createOpp();
        o.Bank__c = a.Id;
        update o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Bank';
        c.Type__c = 'Klageschrift';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendDocViaLetterOrFax oe = new SendDocViaLetterOrFax(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertNotEquals('ein Kreditinstitut auf der Anfrage', oe.errorMsg);
        System.assertEquals('', oe.errorMsg);
        System.assertNotEquals(null, pr);
        System.assertEquals(true, pr.getUrl().contains('hdl=Klageschrift+versenden.'));
    }

    @isTest
    private static void testNoBank() {
        Opportunity o = createOpp();
        o.Bank__c = null;
        update o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        claim.Opposing_Counsel__c = null;
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Bank';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendDocViaLetterOrFax oe = new SendDocViaLetterOrFax(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals('ein Kreditinstitut auf der Anfrage', oe.errorMsg);
    }

    @isTest
    private static void testRSV() {
		Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert a;
        Opportunity o = createOpp();
        o.Legal_Protection_Insurance__c = a.Id;
        update o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Legal Protection Insurance';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendDocViaLetterOrFax oe = new SendDocViaLetterOrFax(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertNotEquals('eine RSV auf der Anfrage', oe.errorMsg);
        System.assertEquals('', oe.errorMsg);
        System.assertNotEquals(null, pr);
    }

    @isTest
    private static void testNoRSV() {
        Opportunity o = createOpp();
        o.Legal_Protection_Insurance__c = null;
        update o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        claim.Opposing_Counsel__c = null;
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Legal Protection Insurance';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendDocViaLetterOrFax oe = new SendDocViaLetterOrFax(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals('eine RSV auf der Anfrage', oe.errorMsg);
    }

    @isTest
    private static void testCustomer() {
		Contact con = new Contact(FirstName = 'Foo', LastName = 'Bar');
        insert con;
        Opportunity o = createOpp();
        o.contact__c = con.Id;
        update o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Customer';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendDocViaLetterOrFax oe = new SendDocViaLetterOrFax(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertNotEquals('einen Kunden auf der Anfrage', oe.errorMsg);
        System.assertEquals('', oe.errorMsg);
        System.assertNotEquals(null, pr);
    }

    @isTest
    private static void testNoCustomer() {
        Opportunity o = createOpp();
        o.Contact__c = null;
        update o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        claim.Opposing_Counsel__c = null;
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Customer';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendDocViaLetterOrFax oe = new SendDocViaLetterOrFax(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals('einen Kunden auf der Anfrage', oe.errorMsg);
    }

    @isTest
    private static void testIndividuell() {
        Opportunity o = createOpp();
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        claim.Opposing_Counsel__c = null;
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Individuell';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        SendDocViaLetterOrFax oe = new SendDocViaLetterOrFax(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals('den wert "Gericht", "Versicherung", "Fahrzeughersteller", "Kreditinstitut", "Rechtsschutzversicherung" oder "Kunde" als Partner auf der Anfrage', oe.errorMsg);
    }
}