objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for legal process parts.</description>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Legal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Web Form Token</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority_Level__c</fullName>
        <formula>IF(Insurance__c = null,'',CASE(Insurance__r.External_Id__c,'lv001','I','lv002','I','lv104','I','lv003','I','lv106','I','lv032','I','lv039','I','lv031','I','lv046','I','lv071','I','lv047','I','lv053','I','lv008','I','lv005','I','lv067','I', 'lv068','I', 'lv089','I','lv054','I','lv048','I', 'lv049','I', 'lv045','I', 'lv035','I', 'lv098','I', 'lv016','I', 'lv027','I', 'lv078','I', 'lv009','I', 'lv034','I','lv777','I','lv004','II','III'))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prioritätsstufe</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Web form token</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ClaimTriggerHandler.cls
public class ClaimTriggerHandler extends BaseTriggerHandler {
    @testVisible
    private static Boolean deactivate = false;
    
    public override void beforeInsert() {
        Logger.debug('>> ClaimTriggerHandler :: beforeInsert :: claims: ' + Trigger.new);

        // Grab opps related to the Claims and reuse them in all of the Claims' methods
        Claim__c[] cc = Trigger.new;
        Map<ID, Opportunity> oppByID = fetchOpps(cc);
        Claims.setRecordType(cc, oppByID);
        Claims.setUsers(cc, oppByID);
        Claims.setCourt(cc);
        Claims.setStage(cc, (Map<ID, Claim__c>)Trigger.oldMap, oppByID, true);

        setUniqueID(cc);

        Logger.debug('<< ClaimTriggerHandler :: beforeInsert');
    }
    
    public override void afterInsert() {
        Logger.debug('>> ClaimTriggerHandler :: afterInsert :: claims: ' + Trigger.new);

        Claims.createTasks(Trigger.new, (Map<ID, Claim__c>)Trigger.oldMap, Trigger.isInsert);
        Claims.createCorrespondences(Trigger.new, (Map<ID, Claim__c>)Trigger.oldMap);
        
        Logger.debug('<< ClaimTriggerHandler :: afterInsert');
    }

    public override void beforeUpdate() {
        Logger.debug('>> ClaimTriggerHandler :: beforeUpdate :: new claims: ' + Trigger.new + ' old claims: ' + Trigger.old);

        Claim__c[] cc = Trigger.new;
        Map<ID, Opportunity> oppByID = fetchOpps(cc);
        Claims.setUsers(cc, oppByID);
        Claims.setHash(cc, (Map<ID, Claim__c>)Trigger.oldMap);
        Claims.setLastStageChangedAt(Trigger.new, (Map<ID, Claim__c>)Trigger.oldMap);
        Claims.setResponseInsuranceLawsuit(Trigger.new);
        Claims.setCourt(cc);
        Claims.setStage(cc, (Map<ID, Claim__c>)Trigger.oldMap, oppByID, false);

        Logger.debug('<< ClaimTriggerHandler :: beforeUpdate');
    }
    
    public override void afterUpdate() {
        Logger.debug('>> ClaimTriggerHandler :: afterUpdate :: new claims: ' + Trigger.new + ' old claims: ' + Trigger.old);

        Claims.createTasks(Trigger.new, (Map<ID, Claim__c>)Trigger.oldMap, Trigger.isInsert);
        Claims.closeTasks(Trigger.new, (Map<ID, Claim__c>)Trigger.oldMap);
        Claims.autoSendMails(Trigger.new, (Map<ID, Claim__c>)Trigger.oldMap);
        Claims.createCorrespondences(Trigger.new, (Map<ID, Claim__c>)Trigger.oldMap);
        Claims.createCostNotes(Trigger.new, (Map<ID, Claim__c>)Trigger.oldMap);
        Claims.updateOpportunity(Trigger.new, (Map<ID, Claim__c>)Trigger.oldMap);
        Claims.createInvoices(Trigger.new);
        
        Logger.debug('<< ClaimTriggerHandler :: afterUpdate');
    }
    
    protected override Boolean preventFromRunning() { return deactivate; }
    
    private Map<ID, Opportunity> fetchOpps(Claim__c[] cc) {
        ID[] oppIDs = new ID[]{};
        for (Claim__c c: (Claim__c[])Trigger.new) {
            oppIDs.add(c.opportunity__c);
        }
        return new Map<ID, Opportunity>([
            SELECT ID, RecordTypeID, Legal__c, Legal_Account__c, Priority_Level__c
            FROM Opportunity
            WHERE ID IN :oppIDs
        ]);
    }

    private void setUniqueID(Claim__c[] cc) {
        for (Claim__c c : cc) {
            if (c.Token__c != null) {
                continue;
            }
            c.Token__c = GUID.Gen();
        }
    }
}