objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
</CustomObject>

objects/Cost_Note__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipName>Cost_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Betreff</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Kostennote</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostennoten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Note__c</fullName>
        <label>Kostennote</label>
        <referenceTo>Cost_Note__c</referenceTo>
        <relationshipLabel>Kostenpunkte</relationshipLabel>
        <relationshipName>Cost_Note_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Honorar</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Bezeichnung</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Line_Item_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Kostenpunkt</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostenpunkte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
</CustomObject>

globalValueSets/Cost_Note_Line_Item_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Außergerichtlich</fullName>
    </customValue>
    <customValue>
        <fullName>I. Instanz</fullName>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Cost Note Line Item Types</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Außergerichtlich</fullName>
    </customValue>
    <customValue>
        <fullName>I. Instanz</fullName>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Selbstbehalt</fullName>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Abschluss</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Cost Note Types</masterLabel>
</GlobalValueSet>

classes/CreateCreditNoteFromCostNoteTest.cls
@isTest
public class CreateCreditNoteFromCostNoteTest {
    @isTest
    private static void test() {
        Account a = TestData.createAccount();
        insert a;
        Opportunity o = TestData.createOpportunity(a.ID, 'On Hold');
		insert o;
		RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Claim__c'];
        Claim__c cl = new Claim__c(
        	Opportunity__c = o.Id,
            recordTypeId = rt.Id
        );
        insert cl;
        Cost_Note__c c = new Cost_Note__c(
        	Claim__c = cl.Id,
            Subject__c = 'Foo bar',
            Type__c = 'Sonstiges'
        );
        insert c;
        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CreateCreditNoteFromCostNote oe = new CreateCreditNoteFromCostNote(sc);

        // Act
		Cost_Note_Line_Item__c note = new Cost_Note_Line_Item__c(
        	Cost_Note__c = c.Id,
            Price__c = 22,
            Subject__c = 'foo bar',
            Type__c = 'Sonstiges'
        );
        insert note;
        CreateCreditNoteFromCostNote.CCostNoteLineItem cc = new CreateCreditNoteFromCostNote.CCostNoteLineItem(note);
        List<CreateCreditNoteFromCostNote.CCostNoteLineItem> items = new List<CreateCreditNoteFromCostNote.CCostNoteLineItem>{cc};
        oe.parCostNoteLineItems = items;

		oe.parCreditNote.Claim__c = cl.Id;
        PageReference pr = oe.renderPage();
    }
}