objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Opportunity__r.Account_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unternehmen</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Opportunity__r.Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Produkt</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <formula>Opportunity__r.Test__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>notEqual</operation>
                <value>Kunde, Lebensversicherung, Fahrzeughersteller, Rechtsschutzversicherung, Gericht, Kanzlei</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provisionen (Unternehmen)</relationshipLabel>
        <relationshipName>Provisionen</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Dg__c</fullName>
        <label>Betrag Dieselschaden</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Lv__c</fullName>
        <label>Betrag Lebensversicherung</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission_Rate_Dg__c</fullName>
        <label>Provisionssatz Dieselskandal</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Commission_Rate_Lv__c</fullName>
        <label>Provisionssatz Lebensversicherung</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Enddatum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Kanzlei</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provisionen (Kanzlei)</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <defaultValue>'Dieselskandal'</defaultValue>
        <label>Produkt</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Families</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Startdatum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <description>Used to create and store the documents with the commission details</description>
    <label>Provision</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Commission_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unternehmen</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provisionssätze (Unternehmen)</relationshipLabel>
        <relationshipName>Account_Commission_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provisionssätze (Kanzlei)</relationshipLabel>
        <relationshipName>Legal_Account_Commission_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Produkt</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Families</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Satz</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <description>Stores the commission rates which are used to calculate the commission</description>
    <label>Provisionssatz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionssätze</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cost_Note__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Claim__r.Opportunity__r.Account_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unternehmen</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>ROUND(Total_Price__c + Total_VAT__c,2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Summe</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipName>Cost_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <formula>Claim__r.Opportunity__r.Test__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <label>Kostennote</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostennoten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Summe</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provision</label>
        <referenceTo>Commission__c</referenceTo>
        <relationshipLabel>Zahlungseingänge</relationshipLabel>
        <relationshipName>Zahlungseingaenge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost_Note__c</fullName>
        <label>Kostennote</label>
        <referenceTo>Cost_Note__c</referenceTo>
        <relationshipName>Cost_Note_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <formula>Cost_Note__r.Claim__r.Opportunity__r.Test__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <label>Zahlungseingang</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zahlungseingänge</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Date__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Termine</relationshipLabel>
        <relationshipName>Termine</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Termin</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Termine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Rate__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Kurs</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kurse</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Product_Families.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Lebensversicherung</fullName>
        <default>true</default>
        <label>Lebensversicherung</label>
    </customValue>
    <customValue>
        <fullName>Dieselskandal</fullName>
    </customValue>
    <customValue>
        <fullName>Finanzierung</fullName>
    </customValue>
    <masterLabel>Product Families</masterLabel>
</GlobalValueSet>

classes/Commissions.cls
public class Commissions {
	public static void setCommissionRate(Commission__c[] cmm) {
		Commission_Rate__c[] cmrr = [SELECT ID, Account__c, Legal_Account__c, Rate__c, Product__c FROM Commission_Rate__c];
		for (Commission__c cm: cmm) {
			for (Commission_Rate__c cmr : cmrr) {
				if (cmr.account__c == cm.account__c
                    && cmr.legal_Account__c == cm.legal_Account__c
                    && cm.product__c.contains(cmr.product__c)) {
					if (cmr.product__c == 'Dieselskandal') {
						cm.commission_Rate_Dg__c = cmr.rate__c;
					} else if (cmr.Product__c == 'Lebensversicherung') {
						cm.commission_Rate_Lv__c = cmr.rate__c;
					}
				} else {
					cm.addError('Es wurde kein Provisionssatz für diese Provisionskombination gefunden. Bitte erstellen.');
				}
			}
		}
	}

    // Legacy code, todo: refactor
    public static void assignCostNotePayments(List<Commission__c> commissions) {
		List<Cost_Note_Payment__c> costNotePayments = [select Id, Cost_Note__c, Date__c, Cost_Note__r.Claim__r.Opportunity__r.Legal_Account__c, Cost_Note__r.Claim__r.Opportunity__r.Account_Id__c, Cost_Note__r.Claim__r.Opportunity__r.Product__c,Amount__c from Cost_Note_Payment__c where Cost_Note__c != null and Date__c != null and Test__c = false and Commission__c = null];
		// assign cost note payments
		List<Cost_Note_Payment__c> updateCostNotePayments = new List<Cost_Note_Payment__c>();
		List<Commission__c> updateCommissions = new List<Commission__c>();

		for (Commission__c commission : commissions) {
			Decimal amountDg = 0;
			Decimal amountLv = 0;
            for (Cost_Note_Payment__c costNotePayment : costNotePayments) {
                if ((commission.Legal_Account__c == costNotePayment.Cost_Note__r.Claim__r.Opportunity__r.Legal_Account__c) && (String.valueOf(commission.Account__c).substring(0,15) == costNotePayment.Cost_Note__r.Claim__r.Opportunity__r.Account_Id__c) && (commission.Product__c.contains(costNotePayment.Cost_Note__r.Claim__r.Opportunity__r.Product__c))) {
                    if ((commission.Start_Date__c != null) && (commission.End_Date__c != null) && (commission.Start_Date__c <= costNotePayment.Date__c) && (commission.End_Date__c >= costNotePayment.Date__c)) {
                        costNotePayment.Commission__c = commission.Id;
                        updateCostNotePayments.add(costNotePayment);
                        
                        //Add amount for different products
                        if (costNotePayment.Cost_Note__r.Claim__r.Opportunity__r.Product__c == 'Dieselskandal') {
                            amountDg += costNotePayment.Amount__c;
                        } else if (costNotePayment.Cost_Note__r.Claim__r.Opportunity__r.Product__c == 'Lebensversicherung') {
                            amountLv += costNotePayment.Amount__c;
                        }
                    }
                }
            }
			if (amountDg > 0) {
				System.debug(commission.Id);
				System.debug(commission.Product__c);
				System.debug(commission.Commission_Rate_Dg__c);
				updateCommissionAmount(commission.Id, 'Dieselskandal', amountDg * (commission.Commission_Rate_Dg__c/100));
			}
			if (amountLv > 0) {
				updateCommissionAmount(commission.Id, 'Lebensversicherung', amountLv * (commission.Commission_Rate_Lv__c/100));
			}
		}

	// update cost note payments
		if (updateCostNotePayments.isEmpty() == false) {
			update updateCostNotePayments;
		}
	}
    
    // Legacy
    @Future
	public static void updateCommissionAmount(Id commissionId, String product, Decimal amount) {
        if (product != 'Dieselskandal' && product != 'Lebensversicherung') { return; }

		Commission__c commission = [select Id, Product__c, Account__c from Commission__c where Id = :commissionId];
		if (product == 'Dieselskandal') {
			commission.Amount_Dg__c = amount;
		} else if (product == 'Lebensversicherung') {
			commission.Amount_Lv__c = amount;
		}

		update commission;
	}
    
    @future (callout=true)
    public static void autoCreateDocuments(Set<Id> commissions) {
		List<Cost_Note_Payment__c> costNotePayments = [select Id, Commission__c from Cost_Note_Payment__c where Commission__c IN :commissions];

		Set<Id> commissionIds = new Set<Id>();
		for (Cost_Note_Payment__c costNotePayment : costNotePayments) {
			commissionIds.add(costNotePayment.Commission__c);
		}

		for (Id commission : commissions) {
			if (commissionIds.contains(commission)) {
				DocumentCreationAction.autoCreateDocument(commission, false, 'pdf', null, null);
				DocumentCreationAction.autoCreateDocument(commission, false, 'sameAsInput', null, null);
			}
		}
	}
}