objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Clerk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sachbearbeiter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Clerk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Correspondece_Status__c</fullName>
        <label>Korrespondenz Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <formula>Opportunity__r.Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bearbeitungsnummer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Aktenzeichen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Stages</valueSetName>
        </valueSet>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Google_Drive_Id__c</fullName>
        <externalId>true</externalId>
        <label>Google Drive Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Dokumente</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Document_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Dokument</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dokumente</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Bearbeitungsnummer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Aktenzeichen</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <fields>
        <fullName>Email</fullName>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <label>Email</label>
    </recordTypes>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

globalValueSets/Claim_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Entwurf</label>
    </customValue>
    <customValue>
        <fullName>Customers Opposition</fullName>
        <label>Kundenwiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Legal Opposition</fullName>
        <label>Anwaltswiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Claim Letter</fullName>
        <label>Anspruchsschreiben</label>
    </customValue>
    <customValue>
        <fullName>Lawsuit</fullName>
        <label>Klage</label>
    </customValue>
    <customValue>
        <fullName>Class Action</fullName>
        <label>Sammelklage</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
        <label>Abwicklung</label>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
        <label>Abgeschlossen</label>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <label>Warten auf Grundsatzurteil</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>Abbruch</label>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Examination</fullName>
        <isActive>false</isActive>
        <label>Examination</label>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
        <isActive>false</isActive>
        <label>Success</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
        <isActive>false</isActive>
        <label>Failure</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <isActive>false</isActive>
        <label>Open</label>
    </customValue>
    <description>Claim stages.</description>
    <masterLabel>Claim Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Document_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Versicherungsantrag</fullName>
    </customValue>
    <customValue>
        <fullName>Versicherungsvertrag</fullName>
    </customValue>
    <customValue>
        <fullName>Wertstandsmitteilung</fullName>
    </customValue>
    <customValue>
        <fullName>Vollmacht</fullName>
    </customValue>
    <customValue>
        <fullName>DG_Registration</fullName>
        <label>Fahrzeugschein</label>
    </customValue>
    <customValue>
        <fullName>DG_Invoice</fullName>
        <label>Vertrag/Rechnung</label>
    </customValue>
    <customValue>
        <fullName>DG_Authorization_Manufacturer</fullName>
        <label>Vollmacht (Hersteller)</label>
    </customValue>
    <customValue>
        <fullName>DG_Authorization_Dealer</fullName>
        <label>Vollmacht (Autohaus)</label>
    </customValue>
    <customValue>
        <fullName>Vollmacht (Kreditinstitut)</fullName>
    </customValue>
    <customValue>
        <fullName>DG_Update_Confirmation</fullName>
        <label>Bestätigung zum Softwareupdate</label>
    </customValue>
    <customValue>
        <fullName>DG_Legal_Protection_Insurance_Policy</fullName>
        <label>Rechtsschutzversicherungspolice</label>
    </customValue>
    <customValue>
        <fullName>Darlehensvertrag</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <default>true</default>
        <label>Sonstiges</label>
    </customValue>
    <customValue>
        <fullName>Widerspruch</fullName>
    </customValue>
    <customValue>
        <fullName>Allgemeine Vertragsbedingungen</fullName>
    </customValue>
    <description>Document Types</description>
    <masterLabel>Document Types</masterLabel>
</GlobalValueSet>

classes/DocumentEmailHandler.cls
public class DocumentEmailHandler implements Messaging.InboundEmailHandler {
    public static Messaging.InboundEmailResult handleInboundEmail(Messaging.inboundEmail email, Messaging.InboundEnvelope envelop) {
        Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();
        Logger.debug('Handling email with subject: ' + email.subject);
    
        boolean claimIsMonitored = claimIsMonitored(email.subject);
        if(claimIsMonitored) {
            handleMonitoredClaim(email);
        }
        
        Opportunity o = fetchOpportunity(email);
        
        if(o == null) {
            Logger.debug('Could not find opportunity');
            return null;
        }
        
        handleAttachments(email, o.accountId, o.Id);
        if (!String.isBlank(email.htmlBody)) {
            Logger.debug('Attaching email body to opp: ' + o.ID);
            addAsAttachment('email_' + email.fromName + '.html', Blob.valueOf(email.htmlBody), 'text/html', o.ID);
        }
        
        ID uID = o.backoffice__c != null ? o.backoffice__c : o.ownerID;
        User owner = [SELECT ID, IsActive FROM User WHERE ID = :uID];
        
        if(!claimIsMonitored) {
        	createTask(email.subject, o, owner);
        }
        return null;
    }
    
    private static void createTask(String subj, Opportunity o, User owner) {
        if (!owner.IsActive) {
            Logger.debug('Failed to create email task, owner is inactive user');
            return;
        }

        Task t = Tasks.build(subj, '', o, owner, Date.today(), false, false, o.ID);
        insert t;
        Logger.debug('Created email task: ' + t);
    }

    private static void handleAttachments(Messaging.inboundEmail e, id accountId, string oppId) {
        System.debug('handling attachments');
        List<Attachment> atts = new List<Attachment>();
        string n = extractNumber(e.subject);
        
        if (String.isBlank(n)) {
            return;
        }
        
        List<GoogleDriveTypeFile> files = new List<GoogleDriveTypeFile>();
        GoogleDriveUtils u = GoogleDriveUtils.forAccount(accountId);
        
        if (u == null) {
            System.debug('could not find a suitable google drive account for account');
            return;
        }

        if (e.binaryAttachments != null) {
            for (Messaging.InboundEmail.BinaryAttachment b : e.binaryAttachments) {
                files.add(uploadFile(u, n, b.fileName, b.mimeTypeSubType, b.body));
            }
        }
        if (e.textAttachments != null) {
            for (Messaging.InboundEmail.textAttachment b : e.textAttachments) {
                files.add(uploadFile(u, n, b.fileName, b.mimeTypeSubType, Blob.valueOf(b.body)));
            }
        }
        
        System.debug('got: ' + files.size() + ' attachments');
        
        storeGoogleFiles(oppId, files);
    }
    
    private static GoogleDriveTypeFile uploadFile(GoogleDriveUtils u, string n, string fn, string mime, blob body) {
        GoogleDriveFile gdf = u.uploadFile(n + '/' + fn, mime, body);
        
        return new GoogleDriveTypeFile(gdf, 'Other');
    }
    
    private static void storeGoogleFiles(string oppId, List<GoogleDriveTypeFile> files) {
        List<Document__c> docs = new List<Document__c>();
        for (GoogleDriveTypeFile f : files) {
            if (f == null) {
                continue;
            }
            
            Document__c doc = new Document__c(
                Opportunity__c = oppId,
                Link__c = f.file.url,
                Google_Drive_Id__c = f.file.id,
                Name = f.file.filename,
                Type__c = f.typ
            );
            
            System.debug(doc);
            
            docs.add(doc);
        }
        insert docs;
    }

    
    // Bearbeitungsnummer or Aktenzeichenuse
    private static string extractNumber(string s) {
        System.debug('>> DocumentEmailHandler :: extractNumber :: s: ' + s);

        Pattern r = Pattern.compile('(BN\\s*[0-9]+)');
        Matcher m = r.matcher(s);
        if (m.find()) {
            String res = m.group(1).replace(' ', '');
            System.debug('DocumentEmailHandler :: extractNumber :: got: ' + res);
            return res;
        }

        System.debug('Bearbeitungsnummer not found. Look for Aktenzeichen');
        r = Pattern.compile('([0-9]+)');
        m = r.matcher(s);
        if (m.find()) {
            return m.group(1).replace(' ', '');
        }
        
        System.debug('Neither Bearbeitungsnummer not Aktenzeichen found for string: ' + s);
        return null;
    }
    
    private static Opportunity fetchOpportunity(Messaging.inboundEmail e) {
        string n = extractNumber(e.subject);
        
        if (String.isBlank(n)) {
            return null;
        }
        
        System.debug('looking up opp with Bearbeitungsnummer or Aktenzeichen: ' + n);
        
        List<Opportunity> opps = [
            SELECT  ID,
                    AccountId,
                    Owner.ID,
                    Owner.IsActive,
                    Backoffice__c,
                    Backoffice__r.IsActive 
            FROM Opportunity
            WHERE Number__c = :n OR Reference__c = :n
        ];
        
        System.debug(opps);
        
        if (opps.size() == 0) {
            return null;
        }
        
        return opps[0];
    }
    
    private static void addAsAttachment(string filename, blob content, string mime, id parentId) {
        ContentVersion cv = new ContentVersion(
            Title = filename,
            VersionData = content,
            PathOnClient = filename
        );
        insert cv;
        
        cv = [
            SELECT Id, ContentDocumentId
            FROM ContentVersion
            WHERE Id = :cv.Id
        ];
        
        ContentDocumentLink cdl = new ContentDocumentLink(
            LinkedEntityId = parentId,
            ContentDocumentId = cv.ContentDocumentId,
            ShareType = 'V',
            Visibility = 'AllUsers'
        );
        insert cdl;
    }

    @Testvisible
    private static boolean claimIsMonitored(String subject) { 
        List<String> subjectSplitted = subject.split('-');
        for (String item : subjectSplitted) {
            String trimmedItem = item.trim();
            if(trimmedItem.equalsIgnoreCase('monitored')){
                return true;
            }
        }
        return false;
    }
     
    private static void handleMonitoredClaim(Messaging.inboundEmail email) {
        boolean success = false;
        Claim__c claim = retrieveClaim(email.subject);
        if(claim != null) {
        	success =updateClaimStatus(claim, email.subject);
        } else {
            return;
        }    
        if(success) {   
          createReviewSuccessTask(claim, email.subject, email.fromName);
        } else {
          createReviewProblemsTask(claim, email.subject, email.fromName);   
        }
    }
    
    @Testvisible
  	private static Claim__c retrieveClaim(String subject) { 
	    List<String> subjectSplitted = subject.split('-');
        Claim__c  claim = null;
        for (String item : subjectSplitted) {
            String trimmedItem = item.trim();
            String identifier = extractNumber(trimmedItem);
            if(!String.isBlank(identifier)){
                claim = [SELECT Id, Clerk__c, Letzte_Mail_Empfangen_Am__c, Statuskontrolle_Anwalt__c, Correspondece_Status__c, Stage__c, Opportunity__r.backoffice__c, Opportunity__r.Number__c  From Claim__c Where Opportunity_Number__c =: identifier LIMIT 1];
                break;
            }
        }
        return claim;
    }
    
    @Testvisible
    private static boolean updateClaimStatus(Claim__c claim, String subject){
    	List<String> subjectSplitted = subject.split('-');
        String newStatus;
        boolean success = false;
        if( subjectSplitted.size() == 3) {
        	newStatus = subjectSplitted.get(2);
        } else {
        	updateClaim(claim, 'status not clear');
       		return success;   
        }
        success = updateClaim(claim, newStatus);
        if(!success){
        	updateClaim(claim, 'status not clear');
        }
        return success;
    }
    
    private static boolean updateClaim (Claim__c claim, String value) {
    	claim.Statuskontrolle_Anwalt__c	 = value;
        claim.Letzte_Mail_Empfangen_Am__c = date.today();
        try {
      		update claim;
        } catch(DmlException e) {
           	return false;     
        } 
        return true;    
    }
    
    private static void createReviewProblemsTask(Claim__c claim, String subject, String sender) {
        String description = 'Folgende Betreffzeile ist fehlerhaft: ' +
            subject + '.' +
            'Bitte bei zuständiger Kanzlei den Status einholen.';
        Task task = new Task(
            OwnerId = claim.clerk__c,
            Subject = 'Fehler bei Kontrollmail für Fall mit BN: '+ claim.opportunity__r.Number__c,
            ActivityDate = Date.today(),
            Status = 'Open',
            Priority = 'Normal',
            Type = 'KontrolleAnwaltFehler',
            Description = description,
            Follow_Up_Task__c = false,
			whatID = claim.id
        );
		insert task;
    }
    
    private static void createReviewSuccessTask(Claim__c claim, String subject, String sender) {
        String description = 'Bitte das entsprechende Fall-Objekt updaten';
        Task task = new Task(
            OwnerId = claim.clerk__c,
            Subject = 'Neue Kontrollmail für Fall mit BN: '+ claim.opportunity__r.Number__c,
            ActivityDate = Date.today(),
            Status = 'Open',
            Priority = 'Normal',
            Type = 'KontrolleAnwaltErfolg',
            Description = description,
            Follow_Up_Task__c = false,
			whatID = claim.id
        );
		insert task;
    }
        
}