objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Korrespondenzen</relationshipLabel>
        <relationshipName>Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Korrespondenz</relationshipLabel>
        <relationshipName>Opportunity_Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

classes/TaskRelatedOpportunity.cls
public class TaskRelatedOpportunity {
    public static void setOn(Task[] tt) {
        System.debug('>> TaskRelatedOpportunity :: setOn :: tt: ' + tt);

        for (Task t: tt) {
            if (t.whatID == null) {
                System.debug('>> TaskRelatedOpportunity :: setOn :: whatID is null for t: ' + t);
                continue;
            }
            
            if (t.related_Opportunity__c != null) {
                System.debug('>> TaskRelatedOpportunity :: setOn :: related_Opportunity__c is not null for t: ' + t);
                continue;
            }
            
            Schema.SObjectType ot = t.whatID.getSObjectType();
            if (t.whatID.getSObjectType() == Schema.SObjectType.Opportunity.getSObjectType()) {
                t.related_Opportunity__c = t.whatID;
            } else if (t.whatID.getSObjectType() == Schema.SObjectType.Claim__c.getSObjectType()) {
                Claim__c c = [SELECT Opportunity__c FROM Claim__c WHERE ID = :t.whatID];
                t.related_Opportunity__c = c.opportunity__c;
            } else if (t.whatID.getSObjectType() == Schema.SObjectType.Correspondence__c.getSObjectType()) {
                Correspondence__c c = [SELECT Claim__r.Opportunity__c FROM Correspondence__c WHERE ID = :t.whatID];
                t.related_Opportunity__c = c.claim__r.opportunity__c;
            } else if (t.whatID.getSObjectType() == Schema.SObjectType.Opportunity_Correspondence__c.getSObjectType()) {
                Opportunity_Correspondence__c c = [SELECT Opportunity__c FROM Opportunity_Correspondence__c WHERE ID = :t.whatID];
                t.related_Opportunity__c = c.opportunity__c;
            }
            
            System.debug('TaskRelatedOpportunity :: setOn :: did set related_Opportunity__c: ' + t.related_Opportunity__c + ' for t: ' + t);
        }
        
        System.debug('<< TaskRelatedOpportunity :: setOn');
    }
}