objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Canceled_Next_Court_Date__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gerichtstermin abgesagt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Claim_Letter_Insurance_Date__c</fullName>
        <label>Datum Deckungsanfrage Anspruchsschreiben</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Clerk_Appeal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sachbearbeiter Berufung</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Clerk_Appeal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clerk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sachbearbeiter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Clerk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Court__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Gericht des Gegners</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Nur Gerichte dürfen hier ausgewählt werden.</errorMessage>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Gericht</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fälle (Gericht)</relationshipLabel>
        <relationshipName>Claims_Court</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cover_Note_Scope__c</fullName>
        <label>Deckungsumfang</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Cover_Note_Scopes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Is_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Kunde ist Eigentümer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Form_Hash_1__c</fullName>
        <label>Form Hash 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Stage_Change__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Letzter Statuswechsel</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lawsuit_Insurance_Date__c</fullName>
        <label>Datum Deckungsanfrage Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal_Opposition_Insurance_Date__c</fullName>
        <label>Datum Deckungsanfrage Anwaltswiderspruch</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for legal process parts.</description>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Legal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Court_Date__c</fullName>
        <label>Nächster Gerichtstermin</label>
        <summarizedField>Date__c.Date__c</summarizedField>
        <summaryFilterItems>
            <field>Date__c.Type__c</field>
            <operation>equals</operation>
            <value>Gerichtstermin</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Date__c.Stage__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </summaryFilterItems>
        <summaryForeignKey>Date__c.Claim__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Opportunity_Amount_In_Dispute__c</fullName>
        <formula>Opportunity__r.Amount_In_Dispute__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Amount In Dispute</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Record_Type_Id__c</fullName>
        <formula>Opportunity__r.RecordTypeId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Record Type Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Vehicle_Brand_Id__c</fullName>
        <formula>Opportunity__r.Vehicle_Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Vehicle Brand Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response_Insurance_Claim_Letter__c</fullName>
        <label>Antwort Deckungsanfrage Anspruchsschr.</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Insurance_Lawsuit__c</fullName>
        <label>Antwort Deckungsanfrage für Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Insurance_Legal_Opposition__c</fullName>
        <label>Antwort Deckungsanfrage Anwaltswiderspr.</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Ergebnis</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Date_Before_Claim_Statement__c</fullName>
        <label>Übermittlung vor Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submission_Date_Before_Lawsuit_Date__c</fullName>
        <label>Übermittlung vor Gerichtstermin</label>
        <type>Date</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Korrespondenzen</relationshipLabel>
        <relationshipName>Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity_Record_Type_Id__c</fullName>
        <formula>Claim__r.Opportunity__r.RecordTypeId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Record Type Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Vehicle_Brand_Id__c</fullName>
        <formula>Claim__r.Opportunity__r.Vehicle_Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Vehicle Brand Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipName>Cost_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity_Record_Type_Id__c</fullName>
        <formula>Claim__r.Opportunity__r.RecordTypeId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Record Type Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Vehicle_Brand_Id__c</fullName>
        <formula>Claim__r.Opportunity__r.Vehicle_Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Vehicle Brand Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Kostennote</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostennoten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Note__c</fullName>
        <label>Kostennote</label>
        <referenceTo>Cost_Note__c</referenceTo>
        <relationshipLabel>Kostenpunkte</relationshipLabel>
        <relationshipName>Cost_Note_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Line_Item_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Kostenpunkt</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostenpunkte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Rechnungen</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Invoice_Stages</valueSetName>
        </valueSet>
    </fields>
    <description>Object for storing and managing invoices towards customers.</description>
    <label>Rechnung</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rechnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Form_Hash_1__c</fullName>
        <label>Form Hash 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Stage_Change__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Letzter Statuswechsel</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority_Level__c</fullName>
        <formula>IF(Insurance__c = null,'',CASE(Insurance__r.External_Id__c,'lv001','I','lv002','I','lv104','I','lv003','I','lv106','I','lv032','I','lv039','I','lv031','I','lv046','I','lv071','I','lv047','I','lv053','I','lv008','I','lv005','I','lv067','I', 'lv068','I', 'lv089','I','lv054','I','lv048','I', 'lv049','I', 'lv045','I', 'lv035','I', 'lv098','I', 'lv016','I', 'lv027','I', 'lv078','I', 'lv009','I', 'lv034','I','lv777','I','lv004','II','III'))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prioritätsstufe</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <businessProcess>Finanzierung</businessProcess>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

globalValueSets/Claim_Cover_Note_Scopes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Extrajudicial</fullName>
        <label>Außergerichtlich</label>
    </customValue>
    <customValue>
        <fullName>Judicial</fullName>
        <label>Gerichtlich</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Without Appeal</fullName>
        <label>Ohne Berufung</label>
    </customValue>
    <customValue>
        <fullName>Arrangement</fullName>
        <label>Vergleich</label>
    </customValue>
    <masterLabel>Claim Cover Note Scopes</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Results.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accepted</fullName>
        <label>Angenommen</label>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
        <label>Abgelehnt</label>
    </customValue>
    <customValue>
        <fullName>Partial</fullName>
        <label>Teilzahlung</label>
    </customValue>
    <customValue>
        <fullName>Arrangement</fullName>
        <label>Vergleich</label>
    </customValue>
    <customValue>
        <fullName>No Response</fullName>
        <label>Keine Antwort</label>
    </customValue>
    <customValue>
        <fullName>Partially won</fullName>
        <label>Teilweise gewonnen</label>
    </customValue>
    <masterLabel>Claim Results</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Entwurf</label>
    </customValue>
    <customValue>
        <fullName>Customers Opposition</fullName>
        <label>Kundenwiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Legal Opposition</fullName>
        <label>Anwaltswiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Claim Letter</fullName>
        <label>Anspruchsschreiben</label>
    </customValue>
    <customValue>
        <fullName>Lawsuit</fullName>
        <label>Klage</label>
    </customValue>
    <customValue>
        <fullName>Class Action</fullName>
        <label>Sammelklage</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
        <label>Abwicklung</label>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
        <label>Abgeschlossen</label>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <label>Warten auf Grundsatzurteil</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>Abbruch</label>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Examination</fullName>
        <isActive>false</isActive>
        <label>Examination</label>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
        <isActive>false</isActive>
        <label>Success</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
        <isActive>false</isActive>
        <label>Failure</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <isActive>false</isActive>
        <label>Open</label>
    </customValue>
    <description>Claim stages.</description>
    <masterLabel>Claim Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Correspondence_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Correspondence Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Correspondence_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Widerspruch durch Kunden</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Widerspruch</fullName>
    </customValue>
    <customValue>
        <fullName>Widerspruch durch Anwalt</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Anspruchsschreiben</fullName>
    </customValue>
    <customValue>
        <fullName>Anspruchsschreiben</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Klage</fullName>
    </customValue>
    <customValue>
        <fullName>Klageschrift</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage für Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungsschrift</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungsbegründung</fullName>
    </customValue>
    <customValue>
        <fullName>Gerichtskostenrechnung</fullName>
    </customValue>
    <customValue>
        <fullName>Replik</fullName>
    </customValue>
    <customValue>
        <fullName>Vollmacht §141 ZPO</fullName>
    </customValue>
    <customValue>
        <fullName>Eingehend</fullName>
    </customValue>
    <customValue>
        <fullName>Fristverlängerung</fullName>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Deckungsanfrage Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <customValue>
        <fullName>Berufungserwiderung</fullName>
    </customValue>
    <customValue>
        <fullName>Einspruch</fullName>
        <isActive>false</isActive>
        <label>Einspruch</label>
    </customValue>
    <masterLabel>Correspondence Types</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Line_Item_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Außergerichtlich</fullName>
    </customValue>
    <customValue>
        <fullName>I. Instanz</fullName>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Cost Note Line Item Types</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Replaced</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Cost Note Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Außergerichtlich</fullName>
    </customValue>
    <customValue>
        <fullName>I. Instanz</fullName>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Selbstbehalt</fullName>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Abschluss</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Cost Note Types</masterLabel>
</GlobalValueSet>

globalValueSets/Invoice_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <description>Invoice stages.</description>
    <masterLabel>Invoice Stages</masterLabel>
</GlobalValueSet>

classes/Claims.cls
public class Claims {
    // Record types
    private static String dkRtName = 'Dieselskandal';
    private static String fzRtName = 'Finanzierung';
    private static String lvRtName = 'Lebensversicherung';
    private static ID dkRtID;
    private static ID fzRtID;
    private static ID lvRtID;
    static {
        RecordType[] rts = [
            SELECT ID, DeveloperName
            FROM RecordType
            WHERE (DeveloperName = :dkRtName
                OR DeveloperName = :fzRtName
                OR DeveloperName = :lvRtName)
                AND SObjectType = 'Claim__c'
        ];
        for (RecordType rt : rts) {
            if (rt.developerName == dkRtName) {
                dkRtID = rt.ID;
                continue;
            }
            if (rt.developerName == fzRtName) {
                fzRtID = rt.ID;
                continue;
            }
            if (rt.developerName == lvRtName) {
                lvRtID = rt.ID;
                continue;
            }
        }
    }

    public static Id dieselSkandalRecordType() {
        return dkRtID;
    }

    public static Boolean isDieselSkandal(ID claimRecordTypeID) {
        if (claimRecordTypeID == null) {
            return false;
        }
        return claimRecordTypeID == dkRtID;
    }
    
    public static Id finanzierungRecordType() {
        return fzRtID;
    }
    
    public static Boolean isFinanzierung(ID claimRecordTypeID) {
        if (claimRecordTypeID == null) {
            return false;
        }
        return claimRecordTypeID == fzRtID;
    }

    public static Id lebensversicherungRecordType() {
        return lvRtID;
    }
    
    public static Boolean isLebensversicherung(ID claimRecordTypeID) {
        if (claimRecordTypeID == null) {
            return false;
        }
        return claimRecordTypeID == lvRtID;
    }
    // --

    // cc must contain Opportunity__c, and oppByID is a map of Opportunity IDs to Opportunity,
    // with all the Opportunities related to the Claims in cc.
    // Opportunity must contain RecordTypeID
    public static void setRecordType(Claim__c[] cc, Map<ID, Opportunity> oppByID) {
        Logger.debug('>> Claims :: setRecordType :: cc: ' + cc +  ' oppByID: ' + oppByID);

        for (Claim__c c: cc) {
            Opportunity o = oppByID.get(c.opportunity__c);
            if (o == null) {
                continue;
            }

            if (Opportunities.isDieselSkandal(o.recordTypeID)) {
                c.recordTypeId = Claims.dieselSkandalRecordType();
                continue;
            }
            
            if (Opportunities.isFinanzierung(o.recordTypeID)) {
                c.recordTypeId = Claims.finanzierungRecordType();
                continue;
            }
            
            if (Opportunities.isLebensversicherung(o.recordTypeID)) {
                c.recordTypeId = Claims.lebensversicherungRecordType();
                continue;
            }
        }
        
        Logger.debug('<< Claims :: setRecordType');
    }
    
    // cc must contain Opportunity__c, and oppByID is a map of Opportunity IDs to Opportunity,
    // with all the Opportunities related to the Claims in cc.
    // Opportunity must contain Legal__c and Legal_Account__c
    public static void setUsers(Claim__c[] cc, Map<ID, Opportunity> oppByID) {
        Logger.debug('>> Claims :: setUsers :: cc: ' + cc +  ' oppByID: ' + oppByID);

        for (Claim__c c: cc) {
            Opportunity o = oppByID.get(c.opportunity__c);
            if (o == null) {
                continue;
            }

            if (c.legal__c == null) {
                c.legal__c = o.legal__c;
            }

            if (c.clerk__c == null) {
                if (Accounts.isCLLBLegal(o.legal_Account__c)) {
                    // Kainz, nur Partnerprozess
                    c.clerk__c = Users.cllbClerk();
                }
            }

            if (c.clerk_Appeal__c == null && c.stage__c == 'Appeal') {
                c.clerk_Appeal__c = Users.clerkAppeal();
            }
            
            Logger.debug('Claims :: setUsers :: legal:' + c.legal__c + ' clerk: ' + c.clerk__c);
        }
        
        Logger.debug('<< Claims :: setUsers');
    }
    
    // cc must contain Opportunity__c, RecordTypeID, Lawsuit_Insurance_Date__c, Court__c, and Opportunity_Vehicle_Brand_Id__c.
    public static void setCourt(Claim__c[] cc) {
        Logger.debug('>> Claims :: setCourt :: cc: ' + cc);

        for (Claim__c c: cc) {
            Logger.debug('Claims :: setCourt :: c: ' + c);

            if (!Claims.isDieselSkandal(c.recordTypeId)
                || c.lawsuit_Insurance_Date__c != null
                || c.court__c != null
                || c.opportunity_Vehicle_Brand_Id__c == null) {
                Logger.debug('Claims :: setCourt :: criteria did not match, exiting');
                continue;
            }
            
            if (VehicleBrands.isDaimlerAG(c.opportunity_Vehicle_Brand_Id__c)
                || VehicleBrands.isPorscheAG(c.opportunity_Vehicle_Brand_Id__c)) {
                c.court__c = useCountyCourt(c) ? Courts.stuttgartAmtsgerichtID : Courts.stuttgartLandgerichtID;
                Logger.debug('Claims :: setCourt :: 1');
                return;
            }
            
            if (VehicleBrands.isAudiAG(c.opportunity_Vehicle_Brand_Id__c)) {
                c.court__c = useCountyCourt(c) ? Courts.ingolstadtAmtsgerichtID : Courts.ingolstadtLandgerichtID;
                Logger.debug('Claims :: setCourt :: 2');
                return;
            }
            
            if (VehicleBrands.isOpelAutomobileGmbH(c.opportunity_Vehicle_Brand_Id__c)) {
                c.court__c = useCountyCourt(c) ? Courts.darmstadtAmtsgerichtID : Courts.darmstadtLandgerichtID;
                Logger.debug('Claims :: setCourt :: 3');
                return;
            }
            
            if (VehicleBrands.isVolkswagenAG(c.opportunity_Vehicle_Brand_Id__c)) {
                c.court__c = useCountyCourt(c) ? Courts.wolfsburgAmtsgerichtID : Courts.braunschweigLandgerichtID;
                Logger.debug('Claims :: setCourt :: 4');
                return;
            }
        }
        
        Logger.debug('<< Claims :: setCourt :: no court set');
    }

    private static Boolean useCountyCourt(Claim__c c) {
        return c.opportunity_Amount_In_Dispute__c <= 5000;
    }

    // cc must contain Opportunity__c, RecordTypeID, and Stage__c.
    // oppByID is a map of Opportunity IDs to Opportunity,
    // with all the Opportunities related to the Claims in cc.
    // Opportunity must contain Priority_Level__c.
    public static void setStage(Claim__c[] cc, Map<ID, Claim__c> oldCc, Map<ID, Opportunity> oppByID, boolean isInsert) {
        Logger.debug('>> Claims :: setStage :: cc: ' + cc +  ' oppByID: ' + oppByID);
		ClaimStage.setStage(cc, oldCc, oppByID, isInsert);
        Logger.debug('<< Claims :: setStage');
    }
    
    // cc must contain Form_Hash_1__c, Submission_Date_Before_Claim_Statement__c, and Submission_Date_Before_Lawsuit_Date__c.
    // oldCc is a map of Claims which got updated, where cc is the list of the updated version.
    // oldCc must contain Submission_Date_Before_Claim_Statement__c and Submission_Date_Before_Lawsuit_Date__c.
    public static void setHash(Claim__c[] cc, Map<ID, Claim__c> oldCc) {
        Logger.debug('>> Claims :: setHash :: cc: ' + cc + ' oldCc: ' + oldCc);

        for (Claim__c c: cc) {
            if (c.form_Hash_1__c == null 
                || (c.submission_Date_Before_Claim_Statement__c != null && c.submission_Date_Before_Claim_Statement__c != oldCc.get(c.Id).submission_Date_Before_Claim_Statement__c)
                || (c.submission_Date_Before_Lawsuit_Date__c != null && c.submission_Date_Before_Lawsuit_Date__c != oldCc.get(c.Id).submission_Date_Before_Lawsuit_Date__c)) {
                c.Form_Hash_1__c = GUID.Gen();
                Logger.debug('Claims :: setHash :: hash set: ' + c.Form_Hash_1__c);
                continue;
            }
        }
        
        Logger.debug('<< Claims :: setHash');
    }

    // cc must contain Stage__c.
    // oldCc is a map of Claims which got updated, where cc is the list of the updated version.
    // oldCc must contain Stage__c.
    public static void setLastStageChangedAt(Claim__c[] cc, Map<ID, Claim__c> oldCc) {
        Logger.debug('>> Claims :: setLastStageChangedAt :: cc: ' + cc + ' oldCc: ' + oldCc);

        for (Claim__c c: cc) {
            if (c.Stage__c != oldCc.get(c.Id).Stage__c){
                c.last_Stage_Change__c = System.now();
                Logger.debug('Claims :: setLastStageChangedAt :: to: ' + c.last_Stage_Change__c);
            }
        }
        
        Logger.debug('<< Claims :: setLastStageChangedAt');
    }

    // Legacy note: in the case of a cover note for the claim that has already been made,
    // the process is automatically continued after conversion to "claim".
    // cc must contain cover_Note_Scope__c, opportunity_Record_Type_Id__c, lawsuit_Insurance_Date__c, claim_Letter_Insurance_Date__c,
    // legal_Opposition_Insurance_Date__c, response_Insurance_Lawsuit__c, response_Insurance_Claim_Letter__c, and response_Insurance_Legal_Opposition__c.
    public static void setResponseInsuranceLawsuit(Claim__c[] cc) {
        Logger.debug('>> Claims :: setResponseInsuranceLawsuit :: cc: ' + cc);

        for (Claim__c c: cc) {
            if (c.cover_Note_Scope__c == null || !c.cover_Note_Scope__c.contains('Judicial')) {
                Logger.debug('Claims :: setResponseInsuranceLawsuit :: criteria not met, exit');
                continue;
            }

            if (c.lawsuit_Insurance_Date__c == null) {
                c.lawsuit_Insurance_Date__c = Opportunities.isDieselSkandal(c.opportunity_Record_Type_Id__c)
                    ? c.claim_Letter_Insurance_Date__c
                    : c.legal_Opposition_Insurance_Date__c;
            }

            if (c.response_Insurance_Lawsuit__c == null) {
                c.response_Insurance_Lawsuit__c = Opportunities.isDieselSkandal(c.opportunity_Record_Type_Id__c)
                    ? c.response_Insurance_Claim_Letter__c
                    : c.response_Insurance_Legal_Opposition__c;
            }
        }

        Logger.debug('<< Claims :: setResponseInsuranceLawsuit');
    }

    public static void createInvoices(Claim__c[] cc) {
        Logger.debug('>> Claims :: createInvoices :: cc: ' + cc);
        List<Invoice__c> insertInvoices = ClaimInvoices.create(cc);
        Logger.debug('<< Claims :: createInvoices :: created: ' + insertInvoices);
    }

    public static void createTasks(Claim__c[] cc, Map<ID, Claim__c> oldCc, Boolean isInsertingClaim) {
        Logger.debug('>> Claims :: createTasks :: cc: ' + cc + ' oldCc: ' + oldCc + ' isInsertingClaim: ' + isInsertingClaim);
		List<Task> tt = ClaimTasks.create(cc, oldCc, isInsertingClaim);
        Logger.debug('<< Claims :: createTasks :: created: ' + tt);
    }

    public static void closeTasks(Claim__c[] cc, Map<ID, Claim__c> oldCc) {
        Logger.debug('>> Claims :: closeTasks :: cc: ' + cc + ' oldCc: ' + oldCc);

        cc = [
            SELECT  ID,
                    Next_Court_Date__c,
                    Stage__c,
                    Canceled_Next_Court_Date__c,
                    (SELECT ID FROM Correspondencies__r),
                    (SELECT ID, Status, Subject FROM Tasks)
            FROM Claim__c
            WHERE ID IN :cc
        ];
        Correspondence__c[] crr = [
            SELECT  ID,
                    Claim__c,
                    Stage__c,
                    Type__c,
                    (SELECT ID, Status, Subject FROM Tasks) FROM Correspondence__c WHERE Claim__c IN :cc
        ];

        Task[] tt = new Task[]{};
        for (Claim__c c: cc) {            
            if (c.stage__c != oldCc.get(c.Id).stage__c) {
                tt.addAll(Tasks.markAsClosed('Wiedervorlage', c));
                tt.addAll(Tasks.markAsClosed('Ergebnis', c));
                tt.addAll(Tasks.markAsClosed('Weiterführung entscheiden', c));
                for (Correspondence__c cr: crr) {
                    if (cr.claim__c == c.Id) {
                        tt.addAll(Tasks.markAsClosed('Wiedervorlage', cr));
                    }
                }
            }

            if (c.next_Court_Date__c != null && c.next_Court_Date__c != oldCc.get(c.Id).next_Court_Date__c) {
                tt.addAll(Tasks.markAsClosed('Wiedervorlage zu Klage', c));
                tt.addAll(Tasks.markAsClosed('Gerichtstermin vereinbaren', c));
                tt.addAll(Tasks.markAsClosed('Gerichtstermin für Klage hinterlegen', c));
                tt.addAll(Tasks.markAsClosed('Gerichtstermin für Berufung hinterlegen', c));
            }

            if (c.stage__c == 'Finished'){
                tt.addAll(Tasks.markAsClosed('abgeschlossen markieren', c));
            }

            if (c.canceled_Next_Court_Date__c){
                tt.addAll(Tasks.markAsClosed('Gerichtstermin absagen', c));
            }
        }

        if (tt.size() > 0) {
            update tt;
        }

        Logger.debug('<< Claims :: closeTasks :: closed: ' + tt);
    }
    
    public static void createCorrespondences(Claim__c[] cc, Map<ID, Claim__c> oldCc) {
        Logger.debug('>> Claims :: createCorrespondences :: cc: ' + cc);
        Correspondence__c[] crr = ClaimCorrespondences.create(cc, OldCc);
        Logger.debug('<< Claims :: createCorrespondences :: inserted: ' + crr);
    }

    public static void createCostNotes(Claim__c[] cc, Map<ID, Claim__c> oldClaims) {
        Logger.debug('>> Claims :: createCostNotes :: cc: ' + cc + ' oldClaims: ' + oldClaims);
		Map<Cost_Note__c,List<Cost_Note_Line_Item__c>> insertCostNotes = ClaimCostNotes.create(cc, oldClaims);
        Logger.debug('<< Claims :: createCostNotes :: sent costnotes to queue: ' + insertCostNotes); // ' updated costnotes: ' + updateCostNotes);
    }
    
    public static void updateOpportunity(Claim__c[] cc, Map<ID, Claim__c> oldCc) {
        Logger.debug('>> Claims :: updateOpportunity :: cc: ' + cc + ' oldCc: ' + oldCc);

        cc = [
            SELECT  ID,
                    Stage__c,
                    Result__c,
                    Customer_Is_Owner__c,
                    Submission_Date_Before_Lawsuit_Date__c,
                    Submission_Date_Before_Claim_Statement__c,
                    Opportunity__r.StageName,
                    Opportunity__r.Process_Type__c,
                    Opportunity__r.Assignment_Type__c,
                    Opportunity__c
            FROM Claim__c
            WHERE ID IN :cc
        ];

        Opportunity[] oo = new Opportunity[]{};
        Correspondence__c[] crr = new Correspondence__c[]{};
        for (Claim__c c: cc) {
            if (c.stage__c != 'Finished' && c.stage__c != 'Lawsuit') {
                continue;
            }

            if (c.stage__c == 'Finished') {
                if (c.result__c == 'Declined'){
                    if (c.opportunity__r.stageName != 'Lost') {
                        c.opportunity__r.stageName = 'Lost';
                        c.opportunity__r.reason_For_Loss__c = 'Sonstige Gründe (ohne Mail)';
                        oo.add(c.opportunity__r);
                    }
                    
                    continue;
                }
                
                if (c.opportunity__r.stageName != 'Finished') {
                    c.opportunity__r.stageName = 'Finished';
                    oo.add(c.opportunity__r);
                }

                continue;
            } 

            if (c.stage__c == 'Lawsuit') {
                if (!c.customer_Is_Owner__c
                    && ((c.submission_Date_Before_Claim_Statement__c != null
                        && c.submission_Date_Before_Claim_Statement__c != oldCc.get(c.ID).submission_Date_Before_Claim_Statement__c)
                      || (c.submission_Date_Before_Lawsuit_Date__c != null
                        && c.submission_Date_Before_Lawsuit_Date__c != oldCc.get(c.ID).submission_Date_Before_Lawsuit_Date__c))) {
                    if (c.opportunity__r.assignment_Type__c == 'RSV'){
                        Correspondence__c cr = Correspondences.build(c, 'Court', 'Sonstiges', 'Draft', 'NurSchadensersatz');
                        if (cr != null) {
                            crr.add(cr);
                        }
                    } else if (c.opportunity__r.stageName != 'Lost') {
                        c.opportunity__r.stageName = 'Lost';
                        c.opportunity__r.reason_For_Loss__c = 'Kunde nicht Käufer';
                        oo.add(c.opportunity__r);
                    }
                }
            }
        }

        if (!oo.isEmpty()) {
            update oo;
        }

        if (!crr.isEmpty()) {
            insert crr;
        }
        
        Logger.debug('<< Claims :: updateOpportunity :: updated oo: ' + oo + ' inserted crr: ' + crr);
    }

    public static void autoSendMails(Claim__c[] cc, Map<ID, Claim__c> oldClaims) {
        Logger.debug('>> Claims :: autoSendMails :: cc: ' + cc + ' oldClaims: ' + oldClaims);
        ClaimMail.send(cc, oldClaims);
        Logger.debug('<< Claims :: autoSendMails');
    }
}