objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Amount_In_Dispute__c</fullName>
        <formula>Opportunity__r.Amount_In_Dispute__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aktueller Streitwert</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cover_Note_Scope__c</fullName>
        <label>Deckungsumfang</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Cover_Note_Scopes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cover_Note__c</fullName>
        <label>Deckungszusage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Cover_Note_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Aktenzeichen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Insurance_Lawsuit__c</fullName>
        <label>Antwort Deckungsanfrage für Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Ergebnis</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Stages</valueSetName>
        </valueSet>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note__c.object
<CustomObject>
    <fields>
        <fullName>Advance_Payment_By_Customer__c</fullName>
        <label>Vorauszahlung (Kunde)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Advance_Payment_By_Legal_Prot_Insurance__c</fullName>
        <label>Vorauszahlung (RSV)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Paid_By_Customer__c</fullName>
        <label>Gezahlte Summe (Kunde)</label>
        <summarizedField>Cost_Note_Payment__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Cost_Note_Payment__c.Sender_Type__c</field>
            <operation>equals</operation>
            <value>Kunde</value>
        </summaryFilterItems>
        <summaryForeignKey>Cost_Note_Payment__c.Cost_Note__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Amount_Paid_By_Legal_Prot_Insurance__c</fullName>
        <label>Gezahlte Summe (RSV)</label>
        <summarizedField>Cost_Note_Payment__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Cost_Note_Payment__c.Sender_Type__c</field>
            <operation>equals</operation>
            <value>RSV</value>
        </summaryFilterItems>
        <summaryForeignKey>Cost_Note_Payment__c.Cost_Note__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipName>Cost_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Previously_Factored_Vat__c</fullName>
        <label>Zuvor Berechnete MwSt.</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previously_Factored__c</fullName>
        <label>Zuvor Berechnet</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <label>Empfänger</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Recipients</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <formula>Claim__r.Reference__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aktenzeichen</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Betreff</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Gesamthonorar</label>
        <summarizedField>Cost_Note_Line_Item__c.Total_Price__c</summarizedField>
        <summaryForeignKey>Cost_Note_Line_Item__c.Cost_Note__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_VAT__c</fullName>
        <formula>Total_Price_With_Vat__c * 0.19</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>USt.</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Kostennote</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostennoten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Calculate_Vat__c</fullName>
        <defaultValue>true</defaultValue>
        <label>USt. berechnen</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cost_Note__c</fullName>
        <label>Kostennote</label>
        <referenceTo>Cost_Note__c</referenceTo>
        <relationshipLabel>Kostenpunkte</relationshipLabel>
        <relationshipName>Cost_Note_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Beschreibung</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Honorar</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reinvoiced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Neu fakturiert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Bezeichnung</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <formula>Price__c -  Reduction__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gesamt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Line_Item_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Kostenpunkt</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostenpunkte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Amount_In_Dispute__c</fullName>
        <formula>IF(RecordTypeId = '0121t000000DzR3',IF(ISPICKVAL(Process_Type__c,'DG_Keep'),Claim_For_Compensation__c,Purchase_Price__c-Compensation_For_Use__c ),IF(RecordTypeId = '0121t000000DzR4',Paid_Installments__c + Advance_Payment__c + Future_Savings__c + Final_Installment__c,Paid_Up_Contributions__c - Amounts_Received__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Streitwert</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Legal_Protection_Deductible__c</fullName>
        <label>Selbstbehalt für Rechtsschutz</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Aktenzeichen</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Claim_Cover_Note_Scopes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Extrajudicial</fullName>
        <label>Außergerichtlich</label>
    </customValue>
    <customValue>
        <fullName>Judicial</fullName>
        <label>Gerichtlich</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Without Appeal</fullName>
        <label>Ohne Berufung</label>
    </customValue>
    <customValue>
        <fullName>Arrangement</fullName>
        <label>Vergleich</label>
    </customValue>
    <masterLabel>Claim Cover Note Scopes</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Cover_Note_Statuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Issued</fullName>
        <label>Erteilt</label>
    </customValue>
    <customValue>
        <fullName>Refused</fullName>
        <label>Abgelehnt</label>
    </customValue>
    <masterLabel>Claim Cover Note Statuses</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Results.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accepted</fullName>
        <label>Angenommen</label>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
        <label>Abgelehnt</label>
    </customValue>
    <customValue>
        <fullName>Partial</fullName>
        <label>Teilzahlung</label>
    </customValue>
    <customValue>
        <fullName>Arrangement</fullName>
        <label>Vergleich</label>
    </customValue>
    <customValue>
        <fullName>No Response</fullName>
        <label>Keine Antwort</label>
    </customValue>
    <customValue>
        <fullName>Partially won</fullName>
        <label>Teilweise gewonnen</label>
    </customValue>
    <masterLabel>Claim Results</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Entwurf</label>
    </customValue>
    <customValue>
        <fullName>Customers Opposition</fullName>
        <label>Kundenwiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Legal Opposition</fullName>
        <label>Anwaltswiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Claim Letter</fullName>
        <label>Anspruchsschreiben</label>
    </customValue>
    <customValue>
        <fullName>Lawsuit</fullName>
        <label>Klage</label>
    </customValue>
    <customValue>
        <fullName>Class Action</fullName>
        <label>Sammelklage</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
        <label>Abwicklung</label>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
        <label>Abgeschlossen</label>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <label>Warten auf Grundsatzurteil</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>Abbruch</label>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Examination</fullName>
        <isActive>false</isActive>
        <label>Examination</label>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
        <isActive>false</isActive>
        <label>Success</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
        <isActive>false</isActive>
        <label>Failure</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <isActive>false</isActive>
        <label>Open</label>
    </customValue>
    <description>Claim stages.</description>
    <masterLabel>Claim Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Line_Item_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Außergerichtlich</fullName>
    </customValue>
    <customValue>
        <fullName>I. Instanz</fullName>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Cost Note Line Item Types</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Recipients.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Customer</fullName>
        <default>true</default>
        <label>Kunde</label>
    </customValue>
    <customValue>
        <fullName>Legal Protection Insurance</fullName>
        <label>Rechtsschutzversicherung</label>
    </customValue>
    <masterLabel>Cost Note Recipients</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Replaced</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Cost Note Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Außergerichtlich</fullName>
    </customValue>
    <customValue>
        <fullName>I. Instanz</fullName>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Selbstbehalt</fullName>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Abschluss</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Cost Note Types</masterLabel>
</GlobalValueSet>

classes/ClaimCostNotes.cls
public class ClaimCostNotes {
    private static String subject(Claim__c c) {
		return 'Fall:' + (String.isBlank(c.reference__c) ? '' : c.reference__c);
    }

    public static Map<Cost_Note__c,List<Cost_Note_Line_Item__c>> create(Claim__c[] cc, Map<ID, Claim__c> oldClaims) {
		Logger.debug('>> ClaimCostNotes :: create');

        cc = [
            SELECT Id,
            Cover_Note__c,
            Cover_Note_Scope__c,
            Result__c,
            Reference__c,
            RecordTypeId,
            Stage__c,
            Response_Insurance_Lawsuit__c,
            Opportunity__r.Amount_In_Dispute__c,
            Opportunity__r.Legal_Protection_Deductible__c,
            (
                SELECT Id,
                Stage__c,
                Subject__c,
                Type__c,
                Total_Price__c,
                Total_Vat__c,
                Amount_Paid_By_Legal_Prot_Insurance__c,
                Amount_Paid_By_Customer__c
                FROM Cost_Notes__r
            )
            FROM Claim__c
            WHERE Id IN :cc
        ];

        Map<Cost_Note__c,List<Cost_Note_Line_Item__c>> insertCostNotes = new Map<Cost_Note__c, List<Cost_Note_Line_Item__c>>();
        List<Cost_Note__c> updateCostNotes = new List<Cost_Note__c>();

        for (Claim__c claim : cc) {
            if (
                (
                    claim.Result__c == 'Accepted' ||
                    claim.Result__c == 'Partially won' // https://salesfive.atlassian.net/jira/software/projects/VH24/boards/25?selectedIssue=VH24-59
                )
                && claim.Cover_Note_Scope__c == 'Arrangement'
                && claim.Cover_Note__c == 'Issued'
            ) {
                Cost_Note__c cn = CostNotes.build(claim, 'Customer', subject(claim), 'Verteidigungsanzeige');
                if (cn != null) {
                    insertCostNotes.put(cn, null);
                }
            }

            if ((claim.Cover_Note_Scope__c != null) && (claim.Cover_Note_Scope__c != oldClaims.get(claim.Id).Cover_Note_Scope__c)){
                // create this cost note ignoring record types
                if (
                    claim.Result__c == 'Declined' &&
                    claim.Cover_Note_Scope__c == 'Appeal' &&
                    claim.Stage__c == 'Appeal' &&
                    claim.Cover_Note__c == 'Issued'
                ) {
                    Cost_Note__c cn = CostNotes.build(claim, 'Legal Protection Insurance', subject(claim), 'Berufung');
                    if (cn != null) {
                        insertCostNotes.put(cn, null);
                    }
                }
                if (Claims.isDieselSkandal(claim.RecordTypeId)) {
                    // DG
                    if ((claim.Cover_Note_Scope__c == 'Extrajudicial') && (oldClaims.get(claim.Id).Cover_Note_Scope__c == null)){
                        // Nur Außergerichtlich
                        // RSV
                        insertCostNotes.put(new Cost_Note__c(
                            Claim__c = claim.Id,
                            Recipient__c = 'Legal Protection Insurance',
                            Subject__c = 'Außergerichtliches Verfahren',
                            Type__c = 'Außergerichtlich'
                        ), new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                            Subject__c = '1,3 Geschäftsgebühr §§ 2, 13 RVG, Nr. 2300 VV',
                            Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                            Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.3),
                            Calculate_Vat__c = true,
                            Type__c = 'Außergerichtlich'
                        ), new Cost_Note_Line_Item__c(
                            Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                            Price__c = 20,
                            Calculate_Vat__c = true,
                            Type__c = 'Außergerichtlich'
                        )});
                        // Kunde
                        if (claim.Opportunity__r.Legal_Protection_Deductible__c > 0) {
                            Cost_Note__c cn = CostNotes.build(claim, 'Customer', 'Selbstbehalt', 'Selbstbehalt');
                            if (cn != null) {
                                insertCostNotes.put(cn, null);
                            }
                        }
                    } else if ((!claim.Cover_Note_Scope__c.contains('Appeal')) && ((oldClaims.get(claim.Id).Cover_Note_Scope__c == null) || (!oldClaims.get(claim.Id).Cover_Note_Scope__c.contains('Judicial')))){
                        // Gerichtlich
                        Decimal previouslyFactored = 0;
                        Decimal previouslyFactoredVat = 0;
                        Decimal advancePaymentRsv = 0;
                        Decimal advancePaymentCustomer = 0;
                        for (Cost_Note__c costNote : claim.Cost_Notes__r){
                            // Zuvor Berechnete Summe kalkulieren
                            if (((costNote.Stage__c != 'Draft') && (costNote.Stage__c != 'Canceled')) ){
                                previouslyFactored += costNote.Total_Price__c;
                                previouslyFactoredVat += costNote.Total_Vat__c;
                            }
                            // Vorauszahlung kalkulieren
                            advancePaymentRsv += costNote.Amount_Paid_By_Legal_Prot_Insurance__c;
                            advancePaymentCustomer += costNote.Amount_Paid_By_Customer__c;

                            // Außergerichtlich auf Replaced setzen
                            if (((costNote.Stage__c != 'Replaced') && (costNote.Stage__c != 'Canceled') ) ){
                                costNote.Stage__c = 'Replaced';
                                updateCostNotes.add(costNote); 
                            }
                        }

                        Cost_Note__c costNote = new Cost_Note__c(
                            Claim__c = claim.Id,
                            Recipient__c = 'Legal Protection Insurance',
                            Subject__c = 'I. Instanz',
                            Type__c = 'I. Instanz',
                            Previously_Factored__c = previouslyFactored,
                            Previously_Factored_Vat__c = previouslyFactoredVat,
                            Advance_Payment_By_Legal_Prot_Insurance__c = advancePaymentRsv,
                            Advance_Payment_By_Customer__c = advancePaymentCustomer
                        );

                        List<Cost_Note_Line_Item__c> costNoteLineItems = new List<Cost_Note_Line_Item__c>();

                        // außergerichtlich
                        if (claim.Cover_Note_Scope__c.contains('Extrajudicial') || Test.isRunningTest()){
                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '1,3 Geschäftsgebühr §§ 2, 13 RVG, Nr. 2300 VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.3),
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'Außergerichtlich'
                            ), new Cost_Note_Line_Item__c(
                                Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                                Price__c = 20,
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'Außergerichtlich'
                            )});
                        }

                        // gerichtlich
                        costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                            Subject__c = '1,3 Verfahrensgebühr §§ 2, 13 RVG, Nr. 3100 VV',
                            Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                            Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.3),
                            Calculate_Vat__c = true,
                            Type__c = 'I. Instanz'
                        )});

                        // außergerichtlich
                        if (claim.Cover_Note_Scope__c.contains('Extrajudicial') || Test.isRunningTest()){
                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '0,65 Anrechnung gem. Vorbemerkung 3 (4) VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 0.65) * -1,
                                Calculate_Vat__c = true,
                                Type__c = 'I. Instanz'
                            )});
                        }

                        // gerichtlich
                        costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                            Subject__c = '1,2 Terminsgebühr §§ 2, 13 RVG, Nr. 3104 VV',
                            Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                            Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.2),
                            Type__c = 'I. Instanz'
                        ), new Cost_Note_Line_Item__c(
                            Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                            Price__c = 20,
                            Calculate_Vat__c = true,
                            Type__c = 'I. Instanz'
                        )});

                        insertCostNotes.put(costNote,costNoteLineItems);

                        // Kunde
                        if ((oldClaims.get(claim.Id).Cover_Note_Scope__c == null) && (claim.Opportunity__r.Legal_Protection_Deductible__c > 0)){
                            Cost_Note__c cn = CostNotes.build(claim, 'Customer', 'Selbstbehalt', 'Selbstbehalt');
                            if (cn != null) {
                                insertCostNotes.put(cn, null);
                            }
                        }
                    } else if (((claim.Cover_Note_Scope__c.contains('Appeal')) && ((oldClaims.get(claim.Id).Cover_Note_Scope__c == null) || (!oldClaims.get(claim.Id).Cover_Note_Scope__c.contains('Appeal'))))){
                        // Gerichtlich
                        Decimal previouslyFactored = 0;
                        Decimal previouslyFactoredVat = 0;
                        Decimal advancePaymentRsv = 0;
                        Decimal advancePaymentCustomer = 0;
                        for (Cost_Note__c costNote : claim.Cost_Notes__r){
                            // Zuvor Berechnete Summe kalkulieren
                            if ((costNote.Stage__c != 'Draft') && (costNote.Stage__c != 'Canceled')){
                                previouslyFactored += costNote.Total_Price__c;
                                previouslyFactoredVat += costNote.Total_Vat__c;
                            }
                            // Vorauszahlung kalkulieren
                            advancePaymentRsv += costNote.Amount_Paid_By_Legal_Prot_Insurance__c;
                            advancePaymentCustomer += costNote.Amount_Paid_By_Customer__c;

                            // Außergerichtlich auf Replaced setzen
                            if ((costNote.Stage__c != 'Replaced') && (costNote.Stage__c != 'Canceled')){
                                costNote.Stage__c = 'Replaced';
                                updateCostNotes.add(costNote);
                            }
                        }

                        Cost_Note__c costNote = new Cost_Note__c(
                            Claim__c = claim.Id,
                            Recipient__c = 'Legal Protection Insurance',
                            Subject__c = 'Berufung',
                            Type__c = 'Berufung',
                            Previously_Factored__c = previouslyFactored,
                            Previously_Factored_Vat__c = previouslyFactoredVat,
                            Advance_Payment_By_Legal_Prot_Insurance__c = advancePaymentRsv,
                            Advance_Payment_By_Customer__c = advancePaymentCustomer
                        );

                        List<Cost_Note_Line_Item__c> costNoteLineItems = new List<Cost_Note_Line_Item__c>();

                        // außergerichtlich
                        if (claim.Cover_Note_Scope__c.contains('Extrajudicial') || Test.isRunningTest()){
                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '1,5 Geschäftsgebühr §§ 2, 13 RVG, Nr. 2300 VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.5),
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'Außergerichtlich'
                            ), new Cost_Note_Line_Item__c(
                                Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                                Price__c = 20,
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'Außergerichtlich'
                            )});
                        }

                        // gerichtlich
                        if (claim.Cover_Note_Scope__c.contains('Judicial') || Test.isRunningTest()){
                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '1,3 Verfahrensgebühr §§ 2, 13 RVG, Nr. 3100 VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.3),
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'I. Instanz'
                            )});

                            if (claim.Cover_Note_Scope__c.contains('Extrajudicial') || Test.isRunningTest()){
                                costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                    Subject__c = '0,65 Anrechnung gem. Vorbemerkung 3 (4) VV',
                                    Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                    Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 0.65) * -1,
                                    Calculate_Vat__c = true,
                                    Reinvoiced__c = true,
                                    Type__c = 'I. Instanz'
                                )});
                            }

                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '1,2 Terminsgebühr §§ 2, 13 RVG, Nr. 3104 VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.2),
                                Reinvoiced__c = true,
                                Type__c = 'I. Instanz'
                            ), new Cost_Note_Line_Item__c(
                                Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                                Price__c = 20,
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'I. Instanz'
                            )});
                        }

                        // berufung
                        costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                            Subject__c = '1,3 Verfahrensgebühr §§ 2, 13 RVG, Nr. 3100 VV',
                            Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                            Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.3),
                            Calculate_Vat__c = true,
                            Type__c = 'Berufung'
                        )});

                        if (claim.Cover_Note_Scope__c.contains('Judicial') || Test.isRunningTest()){
                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '0,65 Anrechnung gem. Vorbemerkung 3 (4) VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 0.65) * -1,
                                Calculate_Vat__c = true,
                                Type__c = 'Berufung'
                            )});
                        }

                        costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                            Subject__c = '1,2 Terminsgebühr §§ 2, 13 RVG, Nr. 3104 VV',
                            Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                            Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.2),
                            Type__c = 'Berufung'
                        ), new Cost_Note_Line_Item__c(
                            Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                            Price__c = 20,
                            Calculate_Vat__c = true,
                            Type__c = 'Berufung'
                        )});

                        insertCostNotes.put(costNote,costNoteLineItems);

                        // Kunde
                        if ((oldClaims.get(claim.Id).Cover_Note_Scope__c == null) && (claim.Opportunity__r.Legal_Protection_Deductible__c > 0)){
                            Cost_Note__c cn = CostNotes.build(claim, 'Customer', 'Selbstbehalt', 'Selbstbehalt');
                            if (cn != null) {
                                insertCostNotes.put(cn, null);
                            }
                        }
                    }
                } else if (Claims.isFinanzierung(claim.RecordTypeId) ) {
                    // FZ
                    if ((claim.Cover_Note_Scope__c == 'Extrajudicial') && (oldClaims.get(claim.Id).Cover_Note_Scope__c == null)){
                        // Nur Außergerichtlich
                        // RSV
                        insertCostNotes.put(new Cost_Note__c(
                            Claim__c = claim.Id,
                            Recipient__c = 'Legal Protection Insurance',
                            Subject__c = 'Außergerichtliches Verfahren',
                            Type__c = 'Außergerichtlich'
                        ), new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                            Subject__c = '1,5 Geschäftsgebühr §§ 2, 13 RVG, Nr. 2300 VV',
                            Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                            Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.5),
                            Calculate_Vat__c = true,
                            Type__c = 'Außergerichtlich'
                        ), new Cost_Note_Line_Item__c(
                            Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                            Price__c = 20,
                            Calculate_Vat__c = true,
                            Type__c = 'Außergerichtlich'
                        )});
                        // Kunde
                        if (claim.Opportunity__r.Legal_Protection_Deductible__c > 0){
                            Cost_Note__c cn = CostNotes.build(claim, 'Customer', 'Selbstbehalt', 'Selbstbehalt');
                            if (cn != null) {
                                insertCostNotes.put(cn, null);
                            }
                        }
                    } else if ((!claim.Cover_Note_Scope__c.contains('Appeal')) && ((oldClaims.get(claim.Id).Cover_Note_Scope__c == null) || (!oldClaims.get(claim.Id).Cover_Note_Scope__c.contains('Judicial')))){
                        // Gerichtlich
                        Decimal previouslyFactored = 0;
                        Decimal previouslyFactoredVat = 0;
                        Decimal advancePaymentRsv = 0;
                        Decimal advancePaymentCustomer = 0;
                        for (Cost_Note__c costNote : claim.Cost_Notes__r){
                            // Zuvor Berechnete Summe kalkulieren
                            if ((costNote.Stage__c != 'Draft') && (costNote.Stage__c != 'Canceled')){
                                previouslyFactored += costNote.Total_Price__c;
                                previouslyFactoredVat += costNote.Total_Vat__c;
                            }
                            // Vorauszahlung kalkulieren
                            advancePaymentRsv += costNote.Amount_Paid_By_Legal_Prot_Insurance__c;
                            advancePaymentCustomer += costNote.Amount_Paid_By_Customer__c;

                            // Außergerichtlich auf Replaced setzen
                            if ((costNote.Stage__c != 'Replaced') && (costNote.Stage__c != 'Canceled')){
                                costNote.Stage__c = 'Replaced';
                                updateCostNotes.add(costNote);
                            }
                        }

                        Cost_Note__c costNote = new Cost_Note__c(
                            Claim__c = claim.Id,
                            Recipient__c = 'Legal Protection Insurance',
                            Subject__c = 'I. Instanz',
                            Type__c = 'I. Instanz',
                            Previously_Factored__c = previouslyFactored,
                            Previously_Factored_Vat__c = previouslyFactoredVat,
                            Advance_Payment_By_Legal_Prot_Insurance__c = advancePaymentRsv,
                            Advance_Payment_By_Customer__c = advancePaymentCustomer
                        );

                        List<Cost_Note_Line_Item__c> costNoteLineItems = new List<Cost_Note_Line_Item__c>();

                        // außergerichtlich
                        if (claim.Cover_Note_Scope__c.contains('Extrajudicial') || Test.isRunningTest()){
                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '1,5 Geschäftsgebühr §§ 2, 13 RVG, Nr. 2300 VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.5),
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'Außergerichtlich'
                            ), new Cost_Note_Line_Item__c(
                                Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                                Price__c = 20,
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'Außergerichtlich'
                            )});
                        }

                        // gerichtlich
                        costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                            Subject__c = '1,3 Verfahrensgebühr §§ 2, 13 RVG, Nr. 3100 VV',
                            Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                            Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.3),
                            Calculate_Vat__c = true,
                            Type__c = 'I. Instanz'
                        )});

                        // außergerichtlich
                        if (claim.Cover_Note_Scope__c.contains('Extrajudicial') || Test.isRunningTest()){
                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '0,65 Anrechnung gem. Vorbemerkung 3 (4) VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 0.65) * -1,
                                Calculate_Vat__c = true,
                                Type__c = 'I. Instanz'
                            )});
                        }

                        // gerichtlich
                        costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                            Subject__c = '1,2 Terminsgebühr §§ 2, 13 RVG, Nr. 3104 VV',
                            Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                            Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.2),
                            Type__c = 'I. Instanz'
                        ), new Cost_Note_Line_Item__c(
                            Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                            Price__c = 20,
                            Calculate_Vat__c = true,
                            Type__c = 'I. Instanz'
                        )});

                        insertCostNotes.put(costNote,costNoteLineItems);

                        // Kunde
                        if ((oldClaims.get(claim.Id).Cover_Note_Scope__c != 'Extrajudicial') && (claim.Opportunity__r.Legal_Protection_Deductible__c > 0)){
                            Cost_Note__c cn = CostNotes.build(claim, 'Customer', 'Selbstbehalt', 'Selbstbehalt');
                            if (cn != null) {
                                insertCostNotes.put(cn, null);
                            }
                        }
                    } else if ((claim.Cover_Note_Scope__c.contains('Appeal')) && ((oldClaims.get(claim.Id).Cover_Note_Scope__c == null) || (!oldClaims.get(claim.Id).Cover_Note_Scope__c.contains('Appeal')))){
                        // Gerichtlich
                        Decimal previouslyFactored = 0;
                        Decimal previouslyFactoredVat = 0;
                        Decimal advancePaymentRsv = 0;
                        Decimal advancePaymentCustomer = 0;
                        for (Cost_Note__c costNote : claim.Cost_Notes__r){
                            // Zuvor Berechnete Summe kalkulieren
                            if ((costNote.Stage__c != 'Draft') && (costNote.Stage__c != 'Canceled')){
                                previouslyFactored += costNote.Total_Price__c;
                                previouslyFactoredVat += costNote.Total_Vat__c;
                            }
                            // Vorauszahlung kalkulieren
                            advancePaymentRsv += costNote.Amount_Paid_By_Legal_Prot_Insurance__c;
                            advancePaymentCustomer += costNote.Amount_Paid_By_Customer__c;

                            // Außergerichtlich auf Replaced setzen
                            if ((costNote.Stage__c != 'Replaced') && (costNote.Stage__c != 'Canceled')){
                                costNote.Stage__c = 'Replaced';
                                updateCostNotes.add(costNote);
                            }
                        }

                        Cost_Note__c costNote = new Cost_Note__c(
                            Claim__c = claim.Id,
                            Recipient__c = 'Legal Protection Insurance',
                            Subject__c = 'Berufung',
                            Type__c = 'Berufung',
                            Previously_Factored__c = previouslyFactored,
                            Previously_Factored_Vat__c = previouslyFactoredVat,
                            Advance_Payment_By_Legal_Prot_Insurance__c = advancePaymentRsv,
                            Advance_Payment_By_Customer__c = advancePaymentCustomer
                        );

                        List<Cost_Note_Line_Item__c> costNoteLineItems = new List<Cost_Note_Line_Item__c>();

                        // außergerichtlich
                        if (claim.Cover_Note_Scope__c.contains('Extrajudicial') || Test.isRunningTest()){
                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '1,5 Geschäftsgebühr §§ 2, 13 RVG, Nr. 2300 VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.5),
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'Außergerichtlich'
                            ), new Cost_Note_Line_Item__c(
                                Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                                Price__c = 20,
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'Außergerichtlich'
                            )});
                        }

                        // gerichtlich
                        if (claim.Cover_Note_Scope__c.contains('Judicial') || Test.isRunningTest()){
                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '1,3 Verfahrensgebühr §§ 2, 13 RVG, Nr. 3100 VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.3),
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'I. Instanz'
                            )});

                            if (claim.Cover_Note_Scope__c.contains('Extrajudicial') || Test.isRunningTest()){
                                costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                    Subject__c = '0,65 Anrechnung gem. Vorbemerkung 3 (4) VV',
                                    Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                    Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 0.65) * -1,
                                    Calculate_Vat__c = true,
                                    Reinvoiced__c = true,
                                    Type__c = 'I. Instanz'
                                )});
                            }

                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '1,2 Terminsgebühr §§ 2, 13 RVG, Nr. 3104 VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.2),
                                Reinvoiced__c = true,
                                Type__c = 'I. Instanz'
                            ), new Cost_Note_Line_Item__c(
                                Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                                Price__c = 20,
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'I. Instanz'
                            )});
                        }

                        // berufung
                        costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                            Subject__c = '1,3 Verfahrensgebühr §§ 2, 13 RVG, Nr. 3100 VV',
                            Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                            Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.3),
                            Calculate_Vat__c = true,
                            Type__c = 'Berufung'
                        )});

                        if (claim.Cover_Note_Scope__c.contains('Judicial') || Test.isRunningTest()){
                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '0,65 Anrechnung gem. Vorbemerkung 3 (4) VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 0.65) * -1,
                                Calculate_Vat__c = true,
                                Type__c = 'Berufung'
                            )});
                        }

                        costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                            Subject__c = '1,2 Terminsgebühr §§ 2, 13 RVG, Nr. 3104 VV',
                            Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                            Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.2),
                            Type__c = 'Berufung'
                        ), new Cost_Note_Line_Item__c(
                            Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                            Price__c = 20,
                            Calculate_Vat__c = true,
                            Type__c = 'Berufung'
                        )});

                        insertCostNotes.put(costNote,costNoteLineItems);

                        // Kunde
                        if ((oldClaims.get(claim.Id).Cover_Note_Scope__c != 'Extrajudicial') && (claim.Opportunity__r.Legal_Protection_Deductible__c > 0)){
                            Cost_Note__c cn = CostNotes.build(claim, 'Customer', 'Selbstbehalt', 'Selbstbehalt');
                            if (cn != null) {
                                insertCostNotes.put(cn, null);
                            }
                        }
                    }
                } else {
                    Logger.debug('ClaimCostNotes :: create :: here1');
                    // LV
                    if ((claim.Cover_Note_Scope__c == 'Extrajudicial') && (oldClaims.get(claim.Id).Cover_Note_Scope__c == null)){
                        Logger.debug('ClaimCostNotes :: create :: here2');
                        // Nur Außergerichtlich
                        // RSV
                        insertCostNotes.put(new Cost_Note__c(
                            Claim__c = claim.Id,
                            Recipient__c = 'Legal Protection Insurance',
                            Subject__c = 'Außergerichtliches Verfahren',
                            Type__c = 'Außergerichtlich'
                        ), new List<Cost_Note_Line_Item__c>{
                            new Cost_Note_Line_Item__c(
                                Subject__c = '1,5 Geschäftsgebühr §§ 2, 13 RVG, Nr. 2300 VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.', ',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.5),
                                Calculate_Vat__c = true,
                                Type__c = 'Außergerichtlich'
                            ), new Cost_Note_Line_Item__c(
                                Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                                Price__c = 20,
                                Calculate_Vat__c = true,
                                Type__c = 'Außergerichtlich'
                            )
                        });
                        // Kunde
                        if (claim.Opportunity__r.Legal_Protection_Deductible__c > 0) {
                            Cost_Note__c cn = CostNotes.build(claim, 'Customer', 'Selbstbehalt', 'Selbstbehalt');
                            if (cn != null) {
                                insertCostNotes.put(cn, null);
                            }
                        }
                    } else if ((!claim.Cover_Note_Scope__c.contains('Appeal')) && ((oldClaims.get(claim.Id).Cover_Note_Scope__c == null) || (!oldClaims.get(claim.Id).Cover_Note_Scope__c.contains('Judicial')))){
                        // Gerichtlich
                        Decimal previouslyFactored = 0;
                        Decimal previouslyFactoredVat = 0;
                        Decimal advancePaymentRsv = 0;
                        Decimal advancePaymentCustomer = 0;
                        for (Cost_Note__c costNote : claim.Cost_Notes__r) {
                            // Zuvor Berechnete Summe kalkulieren
                            if ((costNote.Stage__c != 'Draft') && (costNote.Stage__c != 'Canceled')) {
                                previouslyFactored += costNote.Total_Price__c;
                                previouslyFactoredVat += costNote.Total_Vat__c;
                            }
                            // Vorauszahlung kalkulieren
                            advancePaymentRsv += costNote.Amount_Paid_By_Legal_Prot_Insurance__c;
                            advancePaymentCustomer += costNote.Amount_Paid_By_Customer__c;

                            // Außergerichtlich auf Replaced setzen
                            if ((costNote.Stage__c != 'Replaced') && (costNote.Stage__c != 'Canceled')){
                                costNote.Stage__c = 'Replaced';
                                updateCostNotes.add(costNote);
                            }
                        }

                        Cost_Note__c costNote = new Cost_Note__c(
                            Claim__c = claim.Id,
                            Recipient__c = 'Legal Protection Insurance',
                            Subject__c = 'I. Instanz',
                            Type__c = 'I. Instanz',
                            Previously_Factored__c = previouslyFactored,
                            Previously_Factored_Vat__c = previouslyFactoredVat,
                            Advance_Payment_By_Legal_Prot_Insurance__c = advancePaymentRsv,
                            Advance_Payment_By_Customer__c = advancePaymentCustomer
                        );

                        List<Cost_Note_Line_Item__c> costNoteLineItems = new List<Cost_Note_Line_Item__c>();

                        // außergerichtlich
                        if (claim.Cover_Note_Scope__c.contains('Extrajudicial') || Test.isRunningTest()){
                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '1,5 Geschäftsgebühr §§ 2, 13 RVG, Nr. 2300 VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.', ',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.5),
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'Außergerichtlich'
                            ), new Cost_Note_Line_Item__c(
                                Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                                Price__c = 20,
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'Außergerichtlich'
                            )});
                        }

                        // gerichtlich
                        costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                            Subject__c = '1,3 Verfahrensgebühr §§ 2, 13 RVG, Nr. 3100 VV',
                            Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.', ',') + ' Euro)',
                            Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.3),
                            Calculate_Vat__c = true,
                            Type__c = 'I. Instanz'
                        )});

                        // außergerichtlich
                        if (claim.Cover_Note_Scope__c.contains('Extrajudicial') || Test.isRunningTest()){
                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '0,65 Anrechnung gem. Vorbemerkung 3 (4) VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.', ',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 0.65) * -1,
                                Calculate_Vat__c = true,
                                Type__c = 'I. Instanz'
                            )});
                        }

                        // gerichtlich
                        costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                            Subject__c = '1,2 Terminsgebühr §§ 2, 13 RVG, Nr. 3104 VV',
                            Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.', ',') + ' Euro)',
                            Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.2),
                            Type__c = 'I. Instanz'
                        ), new Cost_Note_Line_Item__c(
                            Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                            Price__c = 20,
                            Calculate_Vat__c = true,
                            Type__c = 'I. Instanz'
                        )});

                        insertCostNotes.put(costNote,costNoteLineItems);

                        // Kunde
                        if ((oldClaims.get(claim.Id).Cover_Note_Scope__c != 'Extrajudicial') && (claim.Opportunity__r.Legal_Protection_Deductible__c > 0)){
                            Cost_Note__c cn = CostNotes.build(claim, 'Customer', 'Selbstbehalt', 'Selbstbehalt');
                            if (cn != null) {
                                insertCostNotes.put(cn, null);
                            }
                        }
                    } else if ((claim.Cover_Note_Scope__c.contains('Appeal')) && ((oldClaims.get(claim.Id).Cover_Note_Scope__c == null) || (!oldClaims.get(claim.Id).Cover_Note_Scope__c.contains('Appeal')))){
                        // Gerichtlich
                        Decimal previouslyFactored = 0;
                        Decimal previouslyFactoredVat = 0;
                        Decimal advancePaymentRsv = 0;
                        Decimal advancePaymentCustomer = 0;
                        for (Cost_Note__c costNote : claim.Cost_Notes__r){
                            // Zuvor Berechnete Summe kalkulieren
                            if ((costNote.Stage__c != 'Draft') && (costNote.Stage__c != 'Canceled')){
                                previouslyFactored += costNote.Total_Price__c;
                                previouslyFactoredVat += costNote.Total_Vat__c;
                            }
                            // Vorauszahlung kalkulieren
                            advancePaymentRsv += costNote.Amount_Paid_By_Legal_Prot_Insurance__c;
                            advancePaymentCustomer += costNote.Amount_Paid_By_Customer__c;

                            // Außergerichtlich auf Replaced setzen
                            if ((costNote.Stage__c != 'Replaced') && (costNote.Stage__c != 'Canceled')){
                                costNote.Stage__c = 'Replaced';
                                updateCostNotes.add(costNote);
                            }
                        }

                        Cost_Note__c costNote = new Cost_Note__c(
                            Claim__c = claim.Id,
                            Recipient__c = 'Legal Protection Insurance',
                            Subject__c = 'Berufung',
                            Type__c = 'Berufung',
                            Previously_Factored__c = previouslyFactored,
                            Previously_Factored_Vat__c = previouslyFactoredVat,
                            Advance_Payment_By_Legal_Prot_Insurance__c = advancePaymentRsv,
                            Advance_Payment_By_Customer__c = advancePaymentCustomer
                        );

                        List<Cost_Note_Line_Item__c> costNoteLineItems = new List<Cost_Note_Line_Item__c>();

                        // außergerichtlich
                        if (claim.Cover_Note_Scope__c.contains('Extrajudicial') || Test.isRunningTest()){
                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '1,5 Geschäftsgebühr §§ 2, 13 RVG, Nr. 2300 VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.5),
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'Außergerichtlich'
                            ), new Cost_Note_Line_Item__c(
                                Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                                Price__c = 20,
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'Außergerichtlich'
                            )});
                        }

                        // gerichtlich
                        if (claim.Cover_Note_Scope__c.contains('Judicial') || Test.isRunningTest()){
                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '1,3 Verfahrensgebühr §§ 2, 13 RVG, Nr. 3100 VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.3),
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'I. Instanz'
                            )});

                            if (claim.Cover_Note_Scope__c.contains('Extrajudicial') || Test.isRunningTest()){
                                costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                    Subject__c = '0,65 Anrechnung gem. Vorbemerkung 3 (4) VV',
                                    Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                    Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 0.65) * -1,
                                    Calculate_Vat__c = true,
                                    Reinvoiced__c = true,
                                    Type__c = 'I. Instanz'
                                )});
                            }

                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '1,2 Terminsgebühr §§ 2, 13 RVG, Nr. 3104 VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.2),
                                Reinvoiced__c = true,
                                Type__c = 'I. Instanz'
                            ), new Cost_Note_Line_Item__c(
                                Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                                Price__c = 20,
                                Calculate_Vat__c = true,
                                Reinvoiced__c = true,
                                Type__c = 'I. Instanz'
                            )});
                        }

                        // berufung
                        costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                            Subject__c = '1,3 Verfahrensgebühr §§ 2, 13 RVG, Nr. 3100 VV',
                            Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                            Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.3),
                            Calculate_Vat__c = true,
                            Type__c = 'Berufung'
                        )});

                        if (claim.Cover_Note_Scope__c.contains('Judicial') || Test.isRunningTest()){
                            costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                                Subject__c = '0,65 Anrechnung gem. Vorbemerkung 3 (4) VV',
                                Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                                Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 0.65) * -1,
                                Calculate_Vat__c = true,
                                Type__c = 'Berufung'
                            )});
                        }

                        costNoteLineItems.addAll(new List<Cost_Note_Line_Item__c>{new Cost_Note_Line_Item__c(
                            Subject__c = '1,2 Terminsgebühr §§ 2, 13 RVG, Nr. 3104 VV',
                            Description__c = '(Wert: ' + String.valueOf(claim.Opportunity__r.Amount_In_Dispute__c).replace('.',',') + ' Euro)',
                            Price__c = Utilities.getLegalCost(claim.Opportunity__r.Amount_In_Dispute__c, 1.2),
                            Type__c = 'Berufung'
                        ), new Cost_Note_Line_Item__c(
                            Subject__c = 'Post- und Telekommunikationspauschale Nr. 7002 VV',
                            Price__c = 20,
                            Calculate_Vat__c = true,
                            Type__c = 'Berufung'
                        )});

                        insertCostNotes.put(costNote,costNoteLineItems);

                        // Kunde
                        if ((oldClaims.get(claim.Id).Cover_Note_Scope__c != 'Extrajudicial') && (claim.Opportunity__r.Legal_Protection_Deductible__c > 0)){
                            Cost_Note__c cn = CostNotes.build(claim, 'Customer', 'Selbstbehalt', 'Selbstbehalt');
                            if (cn != null) {
                                insertCostNotes.put(cn, null);
                            }
                        }
                    }
                 }
            }
        }

        if (insertCostNotes.isEmpty() == false && !Test.isRunningTest()){
            CostNoteQueueable queueable = new CostNoteQueueable();
            queueable.insertCostNotes = insertCostNotes;
            System.enqueueJob(queueable);
        }

        if (updateCostNotes.size() > 0){
            update updateCostNotes;
        }
        return insertCostNotes;
    }
}