objects/Claim__c.object
<CustomObject>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lawsuit_Package__c.object
<CustomObject>
    <label>Klagepaket</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Klagepakete</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lawsuit_Package_Reference__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Klagepakete</relationshipLabel>
        <relationshipName>Lawsuit_Package_Referencies</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lawsuit_Package__c</fullName>
        <label>Klagepaket</label>
        <referenceTo>Lawsuit_Package__c</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Lawsuit_Package_Referencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Klagepaketreferenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Klagepaketreferenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreateLawsuitPackage.cls
public class CreateLawsuitPackage {
    private final List<Claim__c> claims;
    private List<SObject> objects;
    public Lawsuit_Package__c parLawsuitPackage{get; set;}
    
    public CreateLawsuitPackage(ApexPages.StandardSetController stdSetController) {
        
        parLawsuitPackage = new Lawsuit_Package__c();
        
        objects = stdSetController.getRecords().clone();
        while (stdSetController.getHasNext()) {
            stdSetController.next();
            objects.addAll(stdSetController.getRecords().clone());
        }
        
        this.claims = [
            
            select Id, CreatedDate 
            from Claim__c 
            where Id IN :objects    
        ];
    }
    
    public PageReference renderPage() {
        
        PageReference pageRef;
        
        Lawsuit_Package__c insertLawsuitPackage = parLawsuitPackage;
        insert insertLawsuitPackage;
        
        List<Lawsuit_Package_Reference__c> insertLawsuitPackageReferencies = new List<Lawsuit_Package_Reference__c>();
        
        for (Claim__c claim : claims){
            insertLawsuitPackageReferencies.add(new Lawsuit_Package_Reference__c(
                Claim__c = claim.Id,
                Lawsuit_Package__c = insertLawsuitPackage.Id
            ));
        }
        
        if (insertLawsuitPackageReferencies.size() > 0) {
            insert insertLawsuitPackageReferencies;
            System.debug('Successfully inserted ' + insertLawsuitPackageReferencies.size() + ' new lawsuit package referencies.');
        }
        
        pageRef = new PageReference('/' + insertLawsuitPackage.Id);
        pageRef.setRedirect(true);
        return pageRef;
    }
}