objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Clerk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sachbearbeiter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Clerk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Competent_Court__c</fullName>
        <label>Zuständiges Gericht</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Competent_Courts</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Court_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gericht des Kunden</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Nur Gerichte dürfen hier ausgewählt werden.</errorMessage>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Gericht</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fälle (Gericht des Kunden)</relationshipLabel>
        <relationshipName>Claims_Court_Customer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Court__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Gericht des Gegners</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Nur Gerichte dürfen hier ausgewählt werden.</errorMessage>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Gericht</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fälle (Gericht)</relationshipLabel>
        <relationshipName>Claims_Court</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opposing_Counsel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Korrespondenzanwalt</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Faelle_Korrespondenzanwalt</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <formula>TEXT(Opportunity__r.Sales_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vertriebstyp</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <formula>Opportunity__r.Vehicle_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fahrzeughersteller</label>
        <type>Text</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Auto_Follow_up_Count__c</fullName>
        <label>Anzahl Auto-Follow-ups</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Korrespondenzen</relationshipLabel>
        <relationshipName>Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Partner</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Partners</valueSetName>
        </valueSet>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Auftragstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assignment_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auto_Follow_up_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Anzahl Auto-Follow-ups</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Kreditinstitut</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Kreditinstitut)</relationshipLabel>
        <relationshipName>Opportunities_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Has_Legal_Protection_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rechtsschutzversicherung vorhanden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Versicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Lebensversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Versicherung)</relationshipLabel>
        <relationshipName>Opportunities_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Protection_Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rechtsschutzversicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Rechtsschutzversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Rechtsschutzversicherung)</relationshipLabel>
        <relationshipName>Opportunities_Legal_Protection_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Partner)</relationshipLabel>
        <relationshipName>Opportunities_Partner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <defaultValue>"Online"</defaultValue>
        <label>Vertriebstyp</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sales_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fahrzeughersteller</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Fahrzeughersteller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Fahrzeughersteller)</relationshipLabel>
        <relationshipName>Opportunities_Fahrzeughersteller</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Bank__c</fullName>
        <label>Bank</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Assignment_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Share</fullName>
    </customValue>
    <customValue>
        <fullName>Direkt</fullName>
    </customValue>
    <customValue>
        <fullName>50%</fullName>
        <isActive>false</isActive>
        <label>50%</label>
    </customValue>
    <customValue>
        <fullName>RSV 20%</fullName>
        <isActive>false</isActive>
        <label>RSV 20%</label>
    </customValue>
    <masterLabel>Assignment Types</masterLabel>
</GlobalValueSet>

globalValueSets/Competent_Courts.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Opponent</fullName>
        <default>true</default>
        <label>Gegner</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
        <label>Kunde</label>
    </customValue>
    <masterLabel>Competent Courts</masterLabel>
</GlobalValueSet>

globalValueSets/Correspondence_Partners.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Insurance</fullName>
        <label>Versicherung</label>
    </customValue>
    <customValue>
        <fullName>Vehicle Brand</fullName>
        <label>Fahrzeughersteller</label>
    </customValue>
    <customValue>
        <fullName>Bank</fullName>
        <label>Kreditinstitut</label>
    </customValue>
    <customValue>
        <fullName>Legal Protection Insurance</fullName>
        <label>Rechtsschutzversicherung</label>
    </customValue>
    <customValue>
        <fullName>Court</fullName>
        <label>Gericht</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
        <label>Kunde</label>
    </customValue>
    <customValue>
        <fullName>Individuell</fullName>
    </customValue>
    <masterLabel>Correspondence Partners</masterLabel>
</GlobalValueSet>

globalValueSets/Sales_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
        <default>true</default>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <masterLabel>Sales Types</masterLabel>
</GlobalValueSet>

classes/CorrSendDocToPartnerTest.cls
@isTest
public class CorrSendDocToPartnerTest {
    public static Opportunity createOpp(Id accountId, String stageName) {
        Account vehicleBrand = new Account(
            Name = 'TestVehicleBrand',
            Type = 'Fahrzeughersteller'
        );
        insert vehicleBrand;
        Opportunity opp = new Opportunity(
            Name = 'TestOpportunity',
            AccountId = accountId,
            CloseDate = System.today(),
            StageName = stageName,
            Sent_Mail_Flag_1__c = true,
            Sent_Mail_Flag_2__c = true,
            Assignment_Type__c = 'RSV',
            Has_Legal_Protection_Insurance__c = true,
            Auto_Follow_up_Count__c = 0,
            Sales_Type__c = 'Online',
            Vehicle_Brand__c = vehicleBrand.Id
        );
        return opp;
    }

    @isTest
    private static void testRecCourt() {
        ClaimTriggerhandler.Deactivate = true;
        Account a = TestData.createAccount();
        a.Type = 'Gericht';
        insert a;
        Opportunity o = createOpp(a.ID, 'On Hold');
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        User u = TestData.createUser();
        insert u;
        claim.Clerk__c = u.Id;
        claim.Court__c = a.Id;
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Court';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrSendDocToPartner oe = new CorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(true, pr.getUrl().contains(a.Id));
    }

    @isTest
    private static void testRecCourtCustomer() {
        ClaimTriggerhandler.Deactivate = true;
        Account a = TestData.createAccount();
        a.Type = 'Gericht';
        insert a;
        Opportunity o = createOpp(a.ID, 'On Hold');
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        User u = TestData.createUser();
        insert u;
        claim.Clerk__c = u.Id;
        claim.Court_Customer__c = a.Id;
        claim.Competent_Court__c = 'Customer';
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Court';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrSendDocToPartner oe = new CorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.debug('url:' + pr.getUrl());
        System.assertEquals(true, pr.getUrl().contains(a.Id));
    }

    @isTest
    private static void testInsuranceOpposing() {
        ClaimTriggerhandler.Deactivate = true;
        Account a = TestData.createAccount();
        a.Type = 'Lebensversicherung';
        insert a;
        Opportunity o = createOpp(a.ID, 'On Hold');
        o.Insurance__c = a.Id;
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        User u = TestData.createUser();
        insert u;
        Contact con = new Contact(LastName = 'bar');
        insert con;
        claim.Clerk__c = u.Id;
        claim.Competent_Court__c = 'Customer';
        claim.Opposing_Counsel__c = con.Id;
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Insurance';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrSendDocToPartner oe = new CorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
		System.assertEquals(true, pr.getUrl().contains(con.Id));
    }

    @isTest
    private static void testInsurance() {
        ClaimTriggerhandler.Deactivate = true;
        Account a = TestData.createAccount();
        a.Type = 'Lebensversicherung';
        insert a;
        Opportunity o = createOpp(a.ID, 'On Hold');
        o.Insurance__c = a.Id;
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        User u = TestData.createUser();
        insert u;
        claim.Clerk__c = u.Id;
        claim.Competent_Court__c = 'Customer';
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Insurance';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrSendDocToPartner oe = new CorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
		System.assertEquals(true, pr.getUrl().contains(a.Id));
    }

    @isTest
    private static void testNoInsurance() {
        ClaimTriggerhandler.Deactivate = true;
        Account a = TestData.createAccount();
        a.Type = 'Lebensversicherung';
        insert a;
        Opportunity o = createOpp(a.ID, 'On Hold');
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        User u = TestData.createUser();
        insert u;
        claim.Clerk__c = u.Id;
        claim.Competent_Court__c = 'Customer';
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Insurance';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrSendDocToPartner oe = new CorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
		System.assertEquals(Errors.page('Empfänger nicht gefunden.', 'Bitte tragen Sie eine "Versicherung" auf der Anfrage oder ein "Korrespondenzanwalt" auf dem Fall ein.').getUrl(), pr.getUrl());
    }

    @isTest
    private static void testVehicleBrandOpposing() {
        ClaimTriggerhandler.Deactivate = true;
        Account a = TestData.createAccount();
        a.Type = 'Lebensversicherung';
        insert a;
        Opportunity o = createOpp(a.ID, 'On Hold');
        o.Insurance__c = a.Id;
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        User u = TestData.createUser();
        insert u;
        Contact con = new Contact(LastName = 'bar');
        insert con;
        claim.Clerk__c = u.Id;
        claim.Competent_Court__c = 'Customer';
        claim.Opposing_Counsel__c = con.Id;
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Vehicle Brand';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrSendDocToPartner oe = new CorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
		System.assertEquals(true, pr.getUrl().contains(con.Id));
    }

    @isTest
    private static void testVehicleBrand() {
        ClaimTriggerhandler.Deactivate = true;
        Account a = TestData.createAccount();
        a.Type = 'Lebensversicherung';
        insert a;
        Account VehicleAcc = TestData.createAccount();
        VehicleAcc.Type = 'Fahrzeughersteller';
        insert VehicleAcc;
        Opportunity o = createOpp(a.ID, 'On Hold');
        o.Insurance__c = a.Id;
        o.Vehicle_Brand__c = VehicleAcc.Id;
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        User u = TestData.createUser();
        insert u;
        Contact con = new Contact(LastName = 'bar');
        insert con;
        claim.Clerk__c = u.Id;
        claim.Competent_Court__c = 'Customer';
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Vehicle Brand';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrSendDocToPartner oe = new CorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
		System.assertEquals(true, pr.getUrl().contains(VehicleAcc.Id));
    }

    @isTest
    private static void testBank() {
        ClaimTriggerhandler.Deactivate = true;
        Account a = TestData.createAccount();
        insert a;
        Opportunity o = createOpp(a.ID, 'On Hold');
        o.Bank__c = a.Id;
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        User u = TestData.createUser();
        insert u;
        claim.Clerk__c = u.Id;
        claim.Competent_Court__c = 'Customer';
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Bank';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrSendDocToPartner oe = new CorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
		System.assertEquals(true, pr.getUrl().contains(a.Id));
    }

    @isTest
    private static void testMissingCourt() {
        ClaimTriggerhandler.Deactivate = true;
        Account a = TestData.createAccount();
        insert a;
        Opportunity o = createOpp(a.ID, 'On Hold');
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        User u = TestData.createUser();
        insert u;
        claim.Clerk__c = u.Id;
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Court';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrSendDocToPartner oe = new CorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.debug('url: ' + pr.getUrl());
        System.assertEquals(Errors.page('Empfänger nicht gefunden.', 'Bitte tragen Sie ein "Gericht des Gegners" ein.').getUrl(), pr.getUrl());
        // System.assertEquals(null, oe.getRecipient());
    }

    @isTest
    private static void testMissingCourtCustomer() {
        ClaimTriggerhandler.Deactivate = true;
        Account a = TestData.createAccount();
        insert a;
        Opportunity o = createOpp(a.ID, 'On Hold');
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        User u = TestData.createUser();
        insert u;
        claim.Clerk__c = u.Id;
        claim.Competent_Court__c = 'Customer';
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Court';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrSendDocToPartner oe = new CorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(Errors.page('Empfänger nicht gefunden.', 'Bitte tragen Sie ein "Gericht des Kunden" ein.').getUrl(), pr.getUrl());
    }

    @isTest
    private static void testMissingBank() {
        ClaimTriggerhandler.Deactivate = true;
        Account a = TestData.createAccount();
        insert a;
        Opportunity o = createOpp(a.ID, 'On Hold');
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        User u = TestData.createUser();
        insert u;
        claim.Clerk__c = u.Id;
        claim.Competent_Court__c = 'Customer';
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Bank';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrSendDocToPartner oe = new CorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(Errors.page('Empfänger nicht gefunden.', 'Bitte hinterlegen Sie ein "Kreditinstitut" auf der Anfrage ein.').getUrl(), pr.getUrl());
    }

    @isTest
    private static void testLegal() {
        ClaimTriggerhandler.Deactivate = true;
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert a;
        Opportunity o = createOpp(a.ID, 'On Hold');
        o.Legal_Protection_Insurance__c = a.Id;
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        User u = TestData.createUser();
        insert u;
        claim.Clerk__c = u.Id;
        claim.Competent_Court__c = 'Customer';
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Legal Protection Insurance';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrSendDocToPartner oe = new CorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(true, pr.getUrl().contains(a.Id));
    }

    @isTest
    private static void testMissingLegal() {
        ClaimTriggerhandler.Deactivate = true;
        Account a = TestData.createAccount();
        insert a;
        Opportunity o = createOpp(a.ID, 'On Hold');
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        User u = TestData.createUser();
        insert u;
        claim.Clerk__c = u.Id;
        claim.Competent_Court__c = 'Customer';
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Legal Protection Insurance';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrSendDocToPartner oe = new CorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(Errors.page('Empfänger nicht gefunden.', 'Bitte hinterlegen Sie eine "Rechtsschutzversicherung" auf der Anfrage.').getUrl(), pr.getUrl());
    }

    @isTest
    private static void testCustomer() {
        ClaimTriggerhandler.Deactivate = true;
        Account a = TestData.createAccount();
        insert a;
        Contact con = new Contact(FirstName = 'Foo', LastName = 'Bar');
        insert con;
        Opportunity o = createOpp(a.ID, 'On Hold');
        o.Contact__c = con.Id;
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        User u = TestData.createUser();
        insert u;
        claim.Clerk__c = u.Id;
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrSendDocToPartner oe = new CorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(true, pr.getUrl().contains(con.Id));
    }

    @isTest
    private static void testMissingCustomer() {
        ClaimTriggerhandler.Deactivate = true;
        Account a = TestData.createAccount();
        insert a;
        Opportunity o = createOpp(a.ID, 'On Hold');
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        User u = TestData.createUser();
        insert u;
        claim.Clerk__c = u.Id;
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrSendDocToPartner oe = new CorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(Errors.page('Empfänger nicht gefunden.', 'Bitte tragen Sie einen "Kunden" auf der Anfrage ein.').getUrl(), pr.getUrl());
    }

    @isTest
    private static void testElseError() {
        ClaimTriggerhandler.Deactivate = true;
        Account a = TestData.createAccount();
        insert a;
        Opportunity o = createOpp(a.ID, 'On Hold');
        insert o;
        Claim__c claim = new Claim__c(Opportunity__c = o.Id);
        User u = TestData.createUser();
        insert u;
        claim.Clerk__c = u.Id;
        insert claim;
        Correspondence__c c = TestData.createCorrespondence(claim.Id, 'Customer', 'Sonstiges', 'Sent');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name = 'Anspruchsschreiben (Dieselskandal)' AND sObjectType = 'Correspondence__c'];
        c.recordTypeId = rt.ID;
        c.Partner__c = 'Individuell';
        insert c;

        Apexpages.StandardController sc = new Apexpages.standardController(c);
        CorrSendDocToPartner oe = new CorrSendDocToPartner(sc);

        // Act
        PageReference pr = oe.renderPage();
        System.assertEquals(Errors.page('Empfänger nicht gefunden.', 'Es wurde kein Empfänger gefunden.').getUrl(), pr.getUrl());
    }
}