objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Clerk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sachbearbeiter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Clerk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Korrespondenzen</relationshipLabel>
        <relationshipName>Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Insurance_Status__c</fullName>
        <formula>IF(Termination_Date__c &lt; Today(),"bereits gekündigt",IF(Expiration_Date__c &lt; Today(),"regulär abgelaufen",IF(Active_Non_contributory_Periods__c &gt; 0,"beitragsfrei gestellt","noch aktiv")))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Versicherungsstatus</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority_Level__c</fullName>
        <formula>IF(Insurance__c = null,'',CASE(Insurance__r.External_Id__c,'lv001','I','lv002','I','lv104','I','lv003','I','lv106','I','lv032','I','lv039','I','lv031','I','lv046','I','lv071','I','lv047','I','lv053','I','lv008','I','lv005','I','lv067','I', 'lv068','I', 'lv089','I','lv054','I','lv048','I', 'lv049','I', 'lv045','I', 'lv035','I', 'lv098','I', 'lv016','I', 'lv027','I', 'lv078','I', 'lv009','I', 'lv034','I','lv777','I','lv004','II','III'))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prioritätsstufe</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

classes/ClaimSendTemplateToCustomer.cls
// Claim__c "Vorlage an Kunden versenden" Button
// Fall "Vorlage an Kunden versenden" Button
public class ClaimSendTemplateToCustomer {
    private final Claim__c claim;
    private final Opportunity opp;
    private string errorMessage = null;
    
    public ClaimSendTemplateToCustomer(ApexPages.StandardController stdCtl) {
        this.claim = [
            SELECT ID,
            Opportunity__c,
            RecordTypeId,
            Clerk__c,
            Clerk__r.Id,
            Clerk__r.isActive
            FROM Claim__c
            WHERE ID = :stdCtl.getId()
        ];
        this.opp = [
            SELECT ID,
            Priority_Level__c,
            RecordTypeId,
            Insurance_Status__c
            FROM Opportunity
            WHERE ID = :this.claim.Opportunity__c
        ];
        
        
    }
    public string getErrorMessage() {
        return this.errorMessage;
    }

    public PageReference renderPage() {
        if (!Claims.isLebensversicherung(this.claim.RecordTypeId)) {
            this.errorMessage = 'Die Sparte muss Lebensversicherung sein!';
            return null;
        }
        
        if (this.opp.Priority_Level__c != 'III') {
            this.errorMessage = 'Die Anfrage muss die Prioritätsstufe III haben';
            return null;
        }
        
        if (this.opp.Insurance_Status__c != 'noch aktiv' && this.opp.Insurance_Status__c != 'beitragsfrei gestellt') {
			this.errorMessage = 'Der Versicherungsstatus muss "noch aktiv" oder "beitragsfrei gestellt" sein.';            
            return null;
        }
        
        if (this.claim.Clerk__c == null) {
            this.errorMessage = 'Es muss ein Sachbearbeiter auf dem Fall hinterlegt sein!';
            return null;
        }
        
        Correspondence__c cr = Correspondences.build(this.claim, 'Insurance', 'Widerspruch durch Kunden', 'Draft', null);
        if (cr != null) {
            insert cr;
        }
        
        /*
        // created by process or trigger already so reacreating it is useless since no duplicates will always filter it
        Task t = Tasks.build(
            'Widerspruchsvorlage an Kunden versenden', // subject
            null, // description
            cr, // parentObj
            this.claim.Clerk__r, // owner
            System.today(), // activityDate
            true, // noDuplicates
            false // isFollowUpTask
		);
        if (t != null) {
            t.Status = 'Open';
            t.Priority = 'Normal';
            insert t;
        }
		*/
        return Page.SuccessPage;
    }
}