objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Amount_In_Dispute_Claim_Letter__c</fullName>
        <label>Streitwert Außergerichtlich</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_In_Dispute_Lawsuit__c</fullName>
        <label>Streitwert Gerichtlich</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_In_Dispute__c</fullName>
        <formula>Opportunity__r.Amount_In_Dispute__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aktueller Streitwert</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Clerk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sachbearbeiter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Clerk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Extrajudicial_Cost_Note_Number__c</fullName>
        <label>Nummer der ag. Kostennote</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Legal_Account_Id__c</fullName>
        <formula>Opportunity__r.Legal_Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Legal Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <formula>Opportunity__r.Test__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note__c.object
<CustomObject>
    <fields>
        <fullName>Accounting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accounting</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Kostennoten</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Open__c</fullName>
        <formula>Amount__c - Cost_Note_Payment_Sum__c - Advance_Payment_By_Legal_Prot_Insurance__c - Advance_Payment_By_Customer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Offene Summe</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipName>Cost_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Nummer</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <label>Empfänger</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Recipients</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Betreff</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <formula>Claim__r.Opportunity__r.Test__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Uploaded_To_Dropbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hochgeladen</label>
        <type>Checkbox</type>
    </fields>
    <label>Kostennote</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostennoten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note_Reminder__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Note__c</fullName>
        <label>Kostennote</label>
        <referenceTo>Cost_Note__c</referenceTo>
        <relationshipLabel>Mahnungen</relationshipLabel>
        <relationshipName>Cost_Note_Reminders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <label>Empfänger</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Recipients</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reminder_Stages</valueSetName>
        </valueSet>
    </fields>
    <label>Mahnung</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mahnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Date__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Termine</relationshipLabel>
        <relationshipName>Termine</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Date_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Bezeichnung</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Date_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Termin</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Termine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount_In_Dispute__c</fullName>
        <formula>IF(RecordTypeId = '0121t000000DzR3',IF(ISPICKVAL(Process_Type__c,'DG_Keep'),Claim_For_Compensation__c,Purchase_Price__c-Compensation_For_Use__c ),IF(RecordTypeId = '0121t000000DzR4',Paid_Installments__c + Advance_Payment__c + Future_Savings__c + Final_Installment__c,Paid_Up_Contributions__c - Amounts_Received__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Streitwert</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Bearbeitungsnummer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Claim_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Entwurf</label>
    </customValue>
    <customValue>
        <fullName>Customers Opposition</fullName>
        <label>Kundenwiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Legal Opposition</fullName>
        <label>Anwaltswiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Claim Letter</fullName>
        <label>Anspruchsschreiben</label>
    </customValue>
    <customValue>
        <fullName>Lawsuit</fullName>
        <label>Klage</label>
    </customValue>
    <customValue>
        <fullName>Class Action</fullName>
        <label>Sammelklage</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
        <label>Abwicklung</label>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
        <label>Abgeschlossen</label>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <label>Warten auf Grundsatzurteil</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>Abbruch</label>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Examination</fullName>
        <isActive>false</isActive>
        <label>Examination</label>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
        <isActive>false</isActive>
        <label>Success</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
        <isActive>false</isActive>
        <label>Failure</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <isActive>false</isActive>
        <label>Open</label>
    </customValue>
    <description>Claim stages.</description>
    <masterLabel>Claim Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Recipients.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Customer</fullName>
        <default>true</default>
        <label>Kunde</label>
    </customValue>
    <customValue>
        <fullName>Legal Protection Insurance</fullName>
        <label>Rechtsschutzversicherung</label>
    </customValue>
    <masterLabel>Cost Note Recipients</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Replaced</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Cost Note Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Außergerichtlich</fullName>
    </customValue>
    <customValue>
        <fullName>I. Instanz</fullName>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Selbstbehalt</fullName>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Abschluss</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Cost Note Types</masterLabel>
</GlobalValueSet>

globalValueSets/Date_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Open</fullName>
        <default>true</default>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Date Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Date_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Gerichtstermin</fullName>
        <default>true</default>
        <label>Gerichtstermin</label>
    </customValue>
    <customValue>
        <fullName>Berufung</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Date Types</masterLabel>
</GlobalValueSet>

globalValueSets/Reminder_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Reminder Stages</masterLabel>
</GlobalValueSet>

classes/CostNotes.cls
public class CostNotes {
    public class InvalidInputException extends Exception {}
    public static Cost_Note__c build(Claim__c claim, string rec, string sub, string typ) {
        Logger.debug('>> Costnotes :: build :: claim: ' + claim);
        if (claim == null) {
            throw new InvalidInputException('Claim is mandatory');
        }
        
        if (sub == null) {
            throw new InvalidInputException('Subject is mandatory');
        }

        Cost_Note__c cn = new Cost_Note__c(
            Claim__c = claim.Id,
            Recipient__c = rec,
            Subject__c = sub,
            Type__c = typ
        );

        // Check for duplicates
        for (Cost_Note__c ecn : claim.Cost_Notes__r) {
            if (cn.type__c == ecn.type__c && cn.Subject__c == ecn.Subject__c) {
                // Found duplicate, do not build the object
                return null;
            }
        }

        Logger.debug('<< Costnotes :: build :: cn: ' + cn);
        return cn;
    }

    // Legacy code
    public static void setNumber(List<Cost_Note__c> cnn, Map<Id,Cost_Note__c> oldCostNotes, Boolean isInsert) {
        Logger.debug('>> CostNotes :: setNumber :: cnn: ' + cnn);
        Set<Id> claimIds = new Set<Id>();
        for (Cost_Note__c cn: cnn) {
            claimIds.add(cn.claim__c);
        }

        Map<ID, Claim__c> claims = new Map<ID, Claim__c>([
            SELECT ID,
            Opportunity__r.Legal_Account__c,
            Opportunity__r.RecordTypeId,
            Opportunity__r.Account_Id__c
            FROM Claim__c
            WHERE ID IN :claimIds
        ]);
        
        Set<String> postfixes = new Set<String>();
        for (Claim__c claim : claims.values()){
            if (Opportunities.isDieselSkandal(claim.Opportunity__r.RecordTypeId)) {
                // DG
                if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) {
                    // Jäger
                    if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) {
                        // VH24
                        postfixes.add('JVH');
                    } else {
                        // VR24
                        postfixes.add('JDG');
                    }
                } else if (Accounts.isCLLBLegal(claim.Opportunity__r.Legal_Account__c)) {
                    // Kainz
                    if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) {
                        // VH24
                        postfixes.add('CVH');
                    } else {
                        // VR24
                        postfixes.add('CVR');
                    }
                } else if (Accounts.isLegal21(claim.Opportunity__r.Legal_Account__c)) {
                    // 21Legal
                    if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) {
                        // VH24
                        postfixes.add('21VH');
                    } else {
                        // VR24
                        postfixes.add('21DG');
                    }
                } else {
                    // Lachmair
                    if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) {
                        // VH24
                        postfixes.add('VH');
                    } else {
                        // VR24
                        postfixes.add('DG');
                    }
                }
            } else if (Opportunities.isFinanzierung(claim.Opportunity__r.RecordTypeId)) {
                // FZ
                if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) {
                    // Jäger
                    if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)){
                        // VH24
                        postfixes.add('JVHFZ');
                    } else {
                        // VR24
                        postfixes.add('JVRFZ');
                    }
                } else {
                    // Kainz
                    if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) {
                        // VH24
                        postfixes.add('CVHFZ');
                    } else {
                        // VR24
                        postfixes.add('CVRFZ');
                    }
                }
            } else {
                // LV
                if (Accounts.isJCLegalLv(claim.Opportunity__r.Legal_Account__c)){
                    // Jäger
                    if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)){
                        // VH24
                        postfixes.add('JVHLV');
                    } else {
                        // VR24
                        postfixes.add('JVRLV');
                    }
                } else {
                    // 21Legal
                    if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)){
                        // VH24
                        postfixes.add('21VHLV');
                    } else {
                        // VR24
                        postfixes.add('21VRLV');
                    }
                }
            }
        }

        System.debug('postfixes' + postfixes);
        Map<String,Cost_Note__c> lastCostNotes = new Map<String,Cost_Note__c>();
        // Gets existing costnotes from this year matching the postfix
        for (String postfix : postfixes){
            if (lastCostNotes.get(postfix) == null){
                List<Cost_Note__c> queriedCostNotes = Database.query('SELECT Id,Number__c FROM Cost_Note__c where Recipient__c != \'Customer\' AND Test__c = false AND Date__c = THIS_YEAR AND Number__c LIKE \'%/' + postfix + '\' ORDER BY Number__c DESC NULLS LAST LIMIT 1');
                if (queriedCostNotes.size() > 0){
                    lastCostNotes.put(postfix,queriedCostNotes[0]);
                }
            }
        }

        Map<String,Integer> lastCostNoteCount = new Map<String,Integer>();
        Map<String,Integer> thisCostNoteCount = new Map<String,Integer>();
        for (String postfix : postfixes) {
            Integer count = 0;
            if (lastCostNotes.get(postfix) != null) {
                count = Integer.valueOf(lastCostNotes.get(postfix).Number__c.substring(4,10));
            }
            lastCostNoteCount.put(postfix,count);
            thisCostNoteCount.put(postfix,1);
        }

        for (Cost_Note__c costNote : cnn) {
            if (costNote.Recipient__c != 'Customer' && costNote.Number__c == null && costNote.Date__c != null && (isInsert == true || (costNote.Date__c != oldCostNotes.get(costNote.Id).Date__c && costNote.Number__c == oldCostNotes.get(costNote.Id).Number__c))) {
                Logger.debug('here');
                Claim__c claim = claims.get(costNote.Claim__c);
                String postfix;
    
                if (Opportunities.isDieselSkandal(claim.Opportunity__r.RecordTypeId)) { // 0120Y000000W0CY
                    // DG
                    if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) { // 0010Y000011MYHW
                        // Jäger
                        if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) { // 0010Y00000eCUS9
                            // VH24
                            postfix = 'JVH';
                        } else {
                            // VR24
                            postfix = 'JDG';
                        }
                    } else if (Accounts.isCLLBLegal(claim.Opportunity__r.Legal_Account__c)) { // 0010Y000010COcm
                        // Kainz
                        if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) { // 0010Y00000eCUS9
                            // VH24
                            postfix = 'CVH';
                        } else {
                            // VR24
                            postfix = 'CVR';
                        }
                    } else if (Accounts.isLegal21(claim.Opportunity__r.Legal_Account__c)) { // 0010Y000013yLnP
                        // 21Legal
                        if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) { // 0010Y00000eCUS9
                            // VH24
                            postfix = '21VH';
                        } else {
                            // VR24
                            postfix = '21DG';
                        }
                    } else {
                        // Lachmair
                        if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) { // 0010Y00000eCUS9
                            // VH24
                            postfix = 'VH';
                        } else {
                            // VR24
                            postfix = 'DG';
                        }
                    }
                } else if (Opportunities.isFinanzierung(claim.Opportunity__r.RecordTypeId)) { // 0120Y000000KnMH
                    // FZ
                    if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) { // 0010Y000011MYHW
                        // Jäger
                        if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) { // 0010Y00000eCUS9
                            // VH24
                            postfix = 'JVHFZ';
                        } else {
                            // VR24
                            postfix = 'JVRFZ';
                        }
                    } else {
                        // Kainz
                        if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) { // 0010Y00000eCUS9
                            // VH24
                            postfix = 'CVHFZ';
                        } else {
                            // VR24
                            postfix = 'CVRFZ';
                        }
                    }
                } else {
                    // LV
                    if (Accounts.isJCLegalLv(claim.Opportunity__r.Legal_Account__c)) { // 0010Y000010BXGZ
                        // Jäger
                        if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) { // 0010Y00000eCUS9
                            // VH24
                            postfix = 'JVHLV';
                        } else {
                            // VR24
                            postfix = 'JVRLV';
                        }
                    } else {
                        // 21Legal
                        if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) { // 0010Y00000eCUS9
                            // VH24
                            postfix = '21VHLV';
                        } else {
                            // VR24
                            postfix = '21VRLV';
                        }
                    }
                    System.debug('fixpsot: ' + postfix);
                }
                Integer count = lastCostNoteCount.get(postfix) + thisCostNoteCount.get(postfix);
                String year = System.now().date().year().format().replace('.','');
    
                if (costNote.Test__c == true){
                    costNote.Number__c = year + count.format().replace('.','').leftPad(6,'0') + '/Test';
                } else {
                    costNote.Number__c = year + count.format().replace('.','').leftPad(6,'0') + '/' + postfix;
                    thisCostNoteCount.put(postfix,thisCostNoteCount.get(postfix) + 1);
                }
            }
        }
        Logger.debug('<< CostNotes :: setNumber');
    }

    // todo: refactor, part of the CostNote Hack on DocumentCreationAction
    public static String computeNumber(Cost_Note__c costNote) {
        Logger.debug('>> CostNotes :: computeNumber :: cn: ' + costNote);
        
        Claim__c[] cc = [
            SELECT ID,
            Opportunity__r.Legal_Account__c,
            Opportunity__r.RecordTypeId,
            Opportunity__r.Account_Id__c
            FROM Claim__c
            WHERE ID = :costNote.claim__c
        ];
        if (cc.size() == 0) {
            Logger.debug('CostNotes :: computeNumber :: no claims for costnote: ' + costNote.ID);
            return null;
        }

        Claim__c claim = cc[0];
        Set<String> postfixes = new Set<String>();
        if (Opportunities.isDieselSkandal(claim.Opportunity__r.RecordTypeId)) {
            // DG
            if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) {
                // Jäger
                if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) {
                    // VH24
                    postfixes.add('JVH');
                } else {
                    // VR24
                    postfixes.add('JDG');
                }
            } else if (Accounts.isCLLBLegal(claim.Opportunity__r.Legal_Account__c)) {
                // Kainz
                if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) {
                    // VH24
                    postfixes.add('CVH');
                } else {
                    // VR24
                    postfixes.add('CVR');
                }
            } else if (Accounts.isLegal21(claim.Opportunity__r.Legal_Account__c)) {
                // 21Legal
                if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) {
                    // VH24
                    postfixes.add('21VH');
                } else {
                    // VR24
                    postfixes.add('21DG');
                }
            } else {
                // Lachmair
                if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) {
                    // VH24
                    postfixes.add('VH');
                } else {
                    // VR24
                    postfixes.add('DG');
                }
            }
        } else if (Opportunities.isFinanzierung(claim.Opportunity__r.RecordTypeId)) {
            // FZ
            if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) {
                // Jäger
                if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)){
                    // VH24
                    postfixes.add('JVHFZ');
                } else {
                    // VR24
                    postfixes.add('JVRFZ');
                }
            } else {
                // Kainz
                if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) {
                    // VH24
                    postfixes.add('CVHFZ');
                } else {
                    // VR24
                    postfixes.add('CVRFZ');
                }
            }
        } else {
            // LV
            if (Accounts.isJCLegalLv(claim.Opportunity__r.Legal_Account__c)){
                // Jäger
                if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)){
                    // VH24
                    postfixes.add('JVHLV');
                } else {
                    // VR24
                    postfixes.add('JVRLV');
                }
            } else {
                // 21Legal
                if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)){
                    // VH24
                    postfixes.add('21VHLV');
                } else {
                    // VR24
                    postfixes.add('21VRLV');
                }
            }
        }

        System.debug('postfixes' + postfixes);
        Map<String,Cost_Note__c> lastCostNotes = new Map<String,Cost_Note__c>();
        for (String postfix : postfixes){
            if (lastCostNotes.get(postfix) == null){
                List<Cost_Note__c> queriedCostNotes = Database.query('SELECT Id,Number__c FROM Cost_Note__c where Recipient__c != \'Customer\' AND Test__c = false AND Date__c = THIS_YEAR AND Number__c LIKE \'%/' + postfix + '\' ORDER BY Number__c DESC NULLS LAST LIMIT 1');
                if (queriedCostNotes.size() > 0){
                    lastCostNotes.put(postfix,queriedCostNotes[0]);
                }
            }
        }

        Map<String,Integer> lastCostNoteCount = new Map<String,Integer>();
        Map<String,Integer> thisCostNoteCount = new Map<String,Integer>();
        for (String postfix : postfixes) {
            Integer count = 0;
            if (lastCostNotes.get(postfix) != null) {
                count = Integer.valueOf(lastCostNotes.get(postfix).Number__c.substring(4,10));
            }
            lastCostNoteCount.put(postfix,count);
            thisCostNoteCount.put(postfix,1);
        }

        if (costNote.Recipient__c == 'Customer') {
            Logger.debug('recipient is customer');
            return null;
        }
        
        if (costNote.Date__c == null) {
            Logger.debug('date is null');
            return null;
        }
        
        String postfix;
        if (Opportunities.isDieselSkandal(claim.Opportunity__r.RecordTypeId)) { // 0120Y000000W0CY
            // DG
            if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) { // 0010Y000011MYHW
                // Jäger
                if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) { // 0010Y00000eCUS9
                    // VH24
                    postfix = 'JVH';
                } else {
                    // VR24
                    postfix = 'JDG';
                }
            } else if (Accounts.isCLLBLegal(claim.Opportunity__r.Legal_Account__c)) { // 0010Y000010COcm
                // Kainz
                if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) { // 0010Y00000eCUS9
                    // VH24
                    postfix = 'CVH';
                } else {
                    // VR24
                    postfix = 'CVR';
                }
            } else if (Accounts.isLegal21(claim.Opportunity__r.Legal_Account__c)) { // 0010Y000013yLnP
                // 21Legal
                if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) { // 0010Y00000eCUS9
                    // VH24
                    postfix = '21VH';
                } else {
                    // VR24
                    postfix = '21DG';
                }
            } else {
                // Lachmair
                if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) { // 0010Y00000eCUS9
                    // VH24
                    postfix = 'VH';
                } else {
                    // VR24
                    postfix = 'DG';
                }
            }
        } else if (Opportunities.isFinanzierung(claim.Opportunity__r.RecordTypeId)) { // 0120Y000000KnMH
            // FZ
            if (Accounts.isJCLegal(claim.Opportunity__r.Legal_Account__c)) { // 0010Y000011MYHW
                // Jäger
                if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) { // 0010Y00000eCUS9
                    // VH24
                    postfix = 'JVHFZ';
                } else {
                    // VR24
                    postfix = 'JVRFZ';
                }
            } else {
                // Kainz
                if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) { // 0010Y00000eCUS9
                    // VH24
                    postfix = 'CVHFZ';
                } else {
                    // VR24
                    postfix = 'CVRFZ';
                }
            }
        } else {
            // LV
            if (Accounts.isJCLegalLv(claim.Opportunity__r.Legal_Account__c)) { // 0010Y000010BXGZ
                // Jäger
                if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) { // 0010Y00000eCUS9
                    // VH24
                    postfix = 'JVHLV';
                } else {
                    // VR24
                    postfix = 'JVRLV';
                }
            } else {
                // 21Legal
                if (Accounts.isVH24(claim.Opportunity__r.Account_Id__c)) { // 0010Y00000eCUS9
                    // VH24
                    postfix = '21VHLV';
                } else {
                    // VR24
                    postfix = '21VRLV';
                }
            }
        }
        Integer count = lastCostNoteCount.get(postfix) + thisCostNoteCount.get(postfix);
        String year = System.now().date().year().format().replace('.','');
        
        if (costNote.Test__c == true){
            costNote.Number__c = year + count.format().replace('.','').leftPad(6,'0') + '/Test';
        } else {
            costNote.Number__c = year + count.format().replace('.','').leftPad(6,'0') + '/' + postfix;
            thisCostNoteCount.put(postfix,thisCostNoteCount.get(postfix) + 1);
        }
        //update costNote;

        Logger.debug('<< CostNotes :: computeNumber: ' + costNote.number__c);
        
        return costNote.number__c;
    }
    
    // Legacy code
    public static void setUser(List<Cost_Note__c> cnn) {
        Logger.debug('>> CostNotes :: setUser :: cnn: ' + cnn);
        Set<Id> claimIds = new Set<Id>();
        for (Cost_Note__c costNote : cnn){
            claimIds.add(costNote.Claim__c);
        }
        Map<Id,Claim__c> claims = new Map<Id,Claim__c>([select Id, Opportunity_Legal_Account_Id__c, Clerk__c from Claim__c where Id IN :claimIds]);
        for (Cost_Note__c costNote : cnn){
            Claim__c claim = claims.get(costNote.Claim__c);
            if (costNote.Accounting__c == null) {
                if (Accounts.isJCLegal(claim.Opportunity_Legal_Account_Id__c)) {
                    // Bei H. Jäger Maria Gorzna setzen
                    costNote.Accounting__c = Users.MariaGorzna();
                } else {
                    // Rest
                    costNote.Accounting__c = claim.Clerk__c;
                }
            }
        }
        Logger.debug('<< CostNotes :: setUser');
    }

    public static void setRemindersCanceled(Cost_Note__c[] cnn, Map<ID, Cost_Note__c> oldCnn) {
        cnn = [
            SELECT  ID,
            Stage__c,
            Amount_Open__c,
            (SELECT ID, Stage__c FROM Cost_Note_Reminders__r)
            FROM Cost_Note__c
            WHERE ID IN: cnn
        ];

        Cost_Note_Reminder__c[] cnnrToUpdate = new Cost_Note_Reminder__c[]{};
        for (Cost_Note__c cn: cnn) {
            if (cn.stage__c != 'Paid' || oldCnn.get(cn.ID).stage__c != 'Sent') {
                continue;
            }
            for (Cost_Note_Reminder__c cnr : cn.cost_Note_Reminders__r) {
                if (cnr.Stage__c == 'Draft') {
                    cnr.Stage__c = 'Canceled';
                    cnnrToUpdate.add(cnr);
                }
            }
        }
        update cnnrToUpdate;
    }

    public static void setClaimAmountInDispute(List<Cost_Note__c> costNotes, Map<Id,Cost_Note__c> oldCostNotes) {
        costNotes = [
            SELECT Id,
            Type__c,
            Stage__c,
            Claim__c,
            Claim__r.Amount_In_Dispute__c,
            Claim__r.Amount_In_Dispute_Claim_Letter__c,
            Claim__r.Amount_In_Dispute_Lawsuit__c
            FROM Cost_Note__c
            WHERE Id IN :costNotes
        ];
        List<Claim__c> updateClaims = new List<Claim__c>();

        for (Cost_Note__c costNote : costNotes) {
            if ((costNote.Stage__c == 'Sent') && (costNote.Stage__c != oldCostNotes.get(costNote.Id).Stage__c)) {
                if (costNote.Type__c == 'Außergerichtlich') {
                    // Außergerichtlich
                    costNote.Claim__r.Amount_In_Dispute_Claim_Letter__c = costNote.Claim__r.Amount_In_Dispute__c;
                } else {
                    // Gerichtlich
                    costNote.Claim__r.Amount_In_Dispute_Lawsuit__c = costNote.Claim__r.Amount_In_Dispute__c;
                }
                updateClaims.add(costNote.Claim__r);
            }
        }
        if (!updateClaims.isEmpty()) {
            update updateClaims;
        }
    }

    public static void setClaimExtrajudicialCostNoteNumber(Cost_Note__c[] cnn, Map<ID, Cost_Note__c> oldCnn) {
        cnn = [
            SELECT  ID,
            Type__c,
            Stage__c,
            Number__c,
            Claim__c,
            Claim__r.Extrajudicial_Cost_Note_Number__c
            FROM Cost_Note__c
            WHERE ID IN :cnn
        ];

        Claim__c[] claimsToUpdate = new Claim__c[]{};
        for (Cost_Note__c cn: cnn) {
            if (cn.stage__c != 'Sent' || cn.stage__c == oldCnn.get(cn.ID).stage__c) {
                continue;
            }
            if (cn.type__c == 'Außergerichtlich') {
                cn.claim__r.Extrajudicial_Cost_Note_Number__c = cn.number__c;
                claimsToUpdate.add(cn.claim__r);
            }
        }
        update claimsToUpdate;
    }
 
    public static void uploadToDropbox(List<Cost_Note__c> costNotes, Map<Id,Cost_Note__c> oldCostNotes) {
        List<Id>relatedCostNoteIds = new List<Id>();

        for (Cost_Note__c costNote : costNotes){
            if ((costNote.Stage__c != oldCostNotes.get(costNote.Id).Stage__c) && (costNote.Stage__c == 'Sent') && (costNote.Uploaded_To_Dropbox__c == false)){
                relatedCostNoteIds.add(costNote.Id);
            }
        }

        if (relatedCostNoteIds.isEmpty() == false){

            Map<Id, String> paths = new Map<Id, String>{
                    Accounts.CLLBLegalID => '/CLLB/Kostennoten/',
                    Accounts.JCLegalLvID => '/Jäger/Kostennoten/',
                    Accounts.JCLegalID => '/Accounting/DATEV/Jäger/',
                    Accounts.LegalLachmairID => '/Lachmair/Kostennoten/',
                    Accounts.LegalVortmannID => '/Vortmann/Kostennoten/',
                    Accounts.Legal21ID => '/21Legal/Kostennoten/'
            };

            List<Cost_Note__c> relatedCostNotes = [select Id,Stage__c,Claim__r.Opportunity__r.Legal_Account__c,Claim__r.Test__c,Date__c from Cost_Note__c where Id IN :relatedCostNoteIds];
            List<Attachment> attachments = [select Id,ParentId from Attachment where ParentId IN :costNotes];

            for (Cost_Note__c costNote : relatedCostNotes){
                for (Attachment attachment : attachments){
                    if (attachment.ParentId == costNote.Id){
                        Date folderDate;                        
                        if (costNote.Date__c == null) {
                            folderDate = System.now().date();
                        } else {
                            folderDate = costNote.Date__c;
                        }
                        String path;
                        if ((paths.containsKey(costNote.Claim__r.Opportunity__r.Legal_Account__c)) && (costNote.Claim__r.Test__c == false)) {
                            path = paths.get(costNote.Claim__r.Opportunity__r.Legal_Account__c) + folderDate.year() + '/' + folderDate.month() + '/';
                        } else {
                            path = '/Technik/Testdaten/Cost Notes/' + folderDate.year() + '/' + folderDate.month() + '/';
                        }
                        IntegrateDropbox.uploadFileToDropboxAsync(path, attachment.Id,costNote.Claim__r.Opportunity__r.Legal_Account__c);
                    }
                }
            }
        }
    }
}