objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Opportunity__r.Account_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unternehmen</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Canceled_Next_Court_Date__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gerichtstermin abgesagt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Claim_Letter_Insurance_Date__c</fullName>
        <label>Datum Deckungsanfrage Anspruchsschreiben</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Clerk_Appeal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sachbearbeiter Berufung</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Clerk_Appeal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clerk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sachbearbeiter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Clerk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Court__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Gericht des Gegners</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Nur Gerichte dürfen hier ausgewählt werden.</errorMessage>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Gericht</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fälle (Gericht)</relationshipLabel>
        <relationshipName>Claims_Court</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cover_Note_Scope__c</fullName>
        <label>Deckungsumfang</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Cover_Note_Scopes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cover_Note__c</fullName>
        <label>Deckungszusage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Cover_Note_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Is_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Kunde ist Eigentümer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Form_Hash_1__c</fullName>
        <label>Form Hash 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Stage_Change__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Letzter Statuswechsel</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lawsuit_Date__c</fullName>
        <label>Datum Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lawsuit_Insurance_Date__c</fullName>
        <label>Datum Deckungsanfrage Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for legal process parts.</description>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims_Legal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Amount_In_Dispute__c</fullName>
        <formula>Opportunity__r.Amount_In_Dispute__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Amount In Dispute</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Vehicle_Brand_Id__c</fullName>
        <formula>Opportunity__r.Vehicle_Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Vehicle Brand Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fälle</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response_Insurance_Claim_Letter__c</fullName>
        <label>Antwort Deckungsanfrage Anspruchsschr.</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Insurance_Lawsuit__c</fullName>
        <label>Antwort Deckungsanfrage für Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Ergebnis</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Results</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Claim_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Date_Before_Claim_Statement__c</fullName>
        <label>Übermittlung vor Klage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submission_Date_Before_Lawsuit_Date__c</fullName>
        <label>Übermittlung vor Gerichtstermin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <formula>Opportunity__r.Vehicle_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fahrzeughersteller</label>
        <type>Text</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Korrespondenzen</relationshipLabel>
        <relationshipName>Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity_Vehicle_Brand_Id__c</fullName>
        <formula>Claim__r.Opportunity__r.Vehicle_Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Vehicle Brand Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Correspondence_Stages</valueSetName>
        </valueSet>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Note__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Claim__r.Opportunity__r.Account_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unternehmen</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipName>Cost_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity_Vehicle_Brand_Id__c</fullName>
        <formula>Claim__r.Opportunity__r.Vehicle_Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Vehicle Brand Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Cost_Note_Stages</valueSetName>
        </valueSet>
    </fields>
    <label>Kostennote</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kostennoten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Form_Hash_1__c</fullName>
        <label>Form Hash 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Stage_Change__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Letzter Statuswechsel</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority_Level__c</fullName>
        <formula>IF(Insurance__c = null,'',CASE(Insurance__r.External_Id__c,'lv001','I','lv002','I','lv104','I','lv003','I','lv106','I','lv032','I','lv039','I','lv031','I','lv046','I','lv071','I','lv047','I','lv053','I','lv008','I','lv005','I','lv067','I', 'lv068','I', 'lv089','I','lv054','I','lv048','I', 'lv049','I', 'lv045','I', 'lv035','I', 'lv098','I', 'lv016','I', 'lv027','I', 'lv078','I', 'lv009','I', 'lv034','I','lv777','I','lv004','II','III'))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prioritätsstufe</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fahrzeughersteller</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Fahrzeughersteller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Fahrzeughersteller)</relationshipLabel>
        <relationshipName>Opportunities_Fahrzeughersteller</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <businessProcess>Finanzierung</businessProcess>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Bypass_process_builder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass process builder</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Claim_Cover_Note_Scopes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Extrajudicial</fullName>
        <label>Außergerichtlich</label>
    </customValue>
    <customValue>
        <fullName>Judicial</fullName>
        <label>Gerichtlich</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Without Appeal</fullName>
        <label>Ohne Berufung</label>
    </customValue>
    <customValue>
        <fullName>Arrangement</fullName>
        <label>Vergleich</label>
    </customValue>
    <masterLabel>Claim Cover Note Scopes</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Cover_Note_Statuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Issued</fullName>
        <label>Erteilt</label>
    </customValue>
    <customValue>
        <fullName>Refused</fullName>
        <label>Abgelehnt</label>
    </customValue>
    <masterLabel>Claim Cover Note Statuses</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Results.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accepted</fullName>
        <label>Angenommen</label>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
        <label>Abgelehnt</label>
    </customValue>
    <customValue>
        <fullName>Partial</fullName>
        <label>Teilzahlung</label>
    </customValue>
    <customValue>
        <fullName>Arrangement</fullName>
        <label>Vergleich</label>
    </customValue>
    <customValue>
        <fullName>No Response</fullName>
        <label>Keine Antwort</label>
    </customValue>
    <customValue>
        <fullName>Partially won</fullName>
        <label>Teilweise gewonnen</label>
    </customValue>
    <masterLabel>Claim Results</masterLabel>
</GlobalValueSet>

globalValueSets/Claim_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Entwurf</label>
    </customValue>
    <customValue>
        <fullName>Customers Opposition</fullName>
        <label>Kundenwiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Legal Opposition</fullName>
        <label>Anwaltswiderspruch</label>
    </customValue>
    <customValue>
        <fullName>Claim Letter</fullName>
        <label>Anspruchsschreiben</label>
    </customValue>
    <customValue>
        <fullName>Lawsuit</fullName>
        <label>Klage</label>
    </customValue>
    <customValue>
        <fullName>Class Action</fullName>
        <label>Sammelklage</label>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
        <label>Berufung</label>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
        <label>Abwicklung</label>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
        <label>Abgeschlossen</label>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <label>Warten auf Grundsatzurteil</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>Abbruch</label>
    </customValue>
    <customValue>
        <fullName>Verteidigungsanzeige</fullName>
    </customValue>
    <customValue>
        <fullName>Examination</fullName>
        <isActive>false</isActive>
        <label>Examination</label>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
        <isActive>false</isActive>
        <label>Success</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
        <isActive>false</isActive>
        <label>Failure</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <isActive>false</isActive>
        <label>Open</label>
    </customValue>
    <description>Claim stages.</description>
    <masterLabel>Claim Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Correspondence_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Correspondence Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Cost_Note_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Replaced</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Cost Note Stages</masterLabel>
</GlobalValueSet>

classes/ClaimsTests.cls
@isTest
public class ClaimsTests { 
    @isTest
    private static void testRecordTypeOnInsert() {
        ClaimTriggerhandler.Deactivate = true;

        User u = TestData.legalUser();
        Claim__c c = buildClaim(u, null, 0, null, null);

        Test.startTest();
        insert c;
        Test.stopTest();

        Opportunity o = [SELECT RecordTypeID FROM Opportunity];
        
        // DieselSkandal
        c = [SELECT RecordTypeID FROM Claim__c];
        System.assertNotEquals(null, c);
        
        //System.assert(Claims.isDieselSkandal(c.recordTypeID));

        // Finanzierung
        o.recordTypeID = Opportunities.finanzierungRecordType();
        update o;

        c = TestData.createClaim(o.ID, 'Draft');
        c.legal__c = u.ID;
        c.clerk__c = u.ID;
        insert c;

        c = [SELECT RecordTypeID FROM Claim__c WHERE ID = :c.ID];
        System.assertNotEquals(null, c);        
       // System.assert(Claims.isFinanzierung(c.recordTypeID));
        
        // Lebensversicherung
        o.recordTypeID = Opportunities.lebensversicherungRecordType();
        update o;

        c = TestData.createClaim(o.ID, 'Draft');
        c.legal__c = u.ID;
        c.clerk__c = u.ID;
        insert c;

        c = [SELECT RecordTypeID FROM Claim__c WHERE ID = :c.ID];
        System.assertNotEquals(null, c);        
        //System.assert(Claims.isLebensversicherung(c.recordTypeID));
    }

    @isTest
    private static void testUsersOnInsertAndUpdate() {
        Account a = TestData.createAccount();
        Account vh24 = TestData.createVH24Account();
        Account legal = TestData.createCLLBLegal();
        insert new Account[]{a, vh24, legal};
        
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;    
        }

        Opportunity o = TestData.createOpportunity(a.ID, 'On Hold');
        o.recordTypeID = Opportunities.dieselSkandalRecordType();
        o.account__c = vh24.Id;
        o.backoffice__c = u.Id;
        o.legal__c = u.ID;
        o.legal_Account__c = legal.ID;
        insert o;

        Claim__c c = TestData.createClaim(o.ID, 'Appeal');
        c.legal__c = null;
        c.clerk__c = null;
        c.clerk_Appeal__c = null;

        o = [SELECT Legal__c, Legal_Account__c FROM Opportunity];
        
        Test.startTest();
        insert c;
        Test.stopTest();
        
        c = [SELECT Legal__c, Clerk__c, Clerk_Appeal__c FROM Claim__c];
        System.assertNotEquals(null, c);
        System.assertEquals(o.legal__c, c.legal__c);
        System.assertEquals(Users.cllbClerk(), c.clerk__c);
        System.assertEquals(Users.clerkAppeal(), c.clerk_Appeal__c);
        
        // Update
        c.legal__c = null;
        update c;
        c = [SELECT Legal__c FROM Claim__c];
        System.assertEquals(o.legal__c, c.legal__c);
    }

    @isTest
    private static void testCourtOnInsertAndUpdate() { 
        Account daimler = TestData.createDaimlerBrand();
        Account opel = TestData.createPorscheBrand();
        Account stutCourt = TestData.createStuttgartAmtsgerichtCourt();
        Account darmstadtCourt = TestData.createDarmstadtAmtsgerichtCourt();
        
        insert new Account[]{daimler, opel, stutCourt, darmstadtCourt};

        User u = TestData.legalUser();
        Claim__c c = buildClaim(u, daimler, 2000, null, null); // Goes to Stuttgart county court
        
        Test.startTest();
        insert c;
        Test.stopTest();

        c = [SELECT Court__c, Opportunity_Amount_In_Dispute__c, Opportunity__c FROM Claim__c];
        System.assertNotEquals(null, c);
        System.assertNotEquals(null, c.court__c);
        System.assert(c.opportunity_Amount_In_Dispute__c <= 5000 ? Courts.isStuttgartAmtsgericht(c.court__c) : Courts.isStuttgartLandgericht(c.court__c));
        
        ID oldCourt = c.court__c;
        // Update
        c.court__c = null;
        c.lawsuit_Insurance_Date__c = null;
        update c;
        
        c = [SELECT Court__c, Opportunity_Amount_In_Dispute__c, Opportunity__r.Vehicle_Brand__c, Opportunity_Vehicle_Brand_Id__c FROM Claim__c];
        System.assertNotEquals(null, c);
        System.assertEquals(oldCourt, c.court__c);
    }
    
    @isTest
    private static void testStageOnInsertAndUpdate() {
        ClaimTriggerhandler.Deactivate = true;
        Account daimler = TestData.createDaimlerBrand();
        insert daimler;

        User u = TestData.legalUser();
        Claim__c cDG = buildClaim(u, daimler, null, null, Opportunities.dieselSkandalRecordType());
        Claim__c cFZ = buildClaim(u, daimler, null, 'I', Opportunities.finanzierungRecordType());
        Claim__c cLV = buildClaim(u, daimler, null, 'II', Opportunities.finanzierungRecordType());
        Claim__c cLV2 = buildClaim(u, daimler, null, null, Opportunities.finanzierungRecordType());

        Test.startTest();
        insert new Claim__c[]{cDG, cFZ, cLV, cLV2};
        Test.stopTest();

        Claim__c[] cc = [SELECT RecordTypeID, RecordType.name, Stage__c, Opportunity__r.Priority_Level__c FROM Claim__c];
        System.assert(!cc.isEmpty());
        for (Claim__c c: cc) {
            System.assertNotEquals(null, c);
            System.assertNotEquals(null, c.stage__c);
            if (Claims.isDieselSkandal(c.recordTypeId)) {
                System.assertEquals('Claim Letter', c.stage__c);
                continue;
            }
            
            if (Claims.isFinanzierung(c.recordTypeId) || Claims.isLebensversicherung(c.recordTypeId)) {
                if (c.opportunity__r.priority_Level__c == 'I' || c.opportunity__r.priority_Level__c == 'II') {
                    //System.assertEquals('Legal Opposition', c.stage__c);
                } else {
                    System.assertEquals('Customers Opposition', c.stage__c);
                }
                continue;
            }
        }
        
        // Update
        cFZ.recordTypeId = Claims.dieselSkandalRecordType();
        update cFZ;
        cFZ = [SELECT Stage__c FROM Claim__c WHERE ID = :cFZ.ID];
        System.assertEquals('Customers Opposition', cFZ.stage__c);
    }

    @isTest
    private static void testHashOnUpdate() {
        User u = TestData.legalUser();
        Claim__c c = buildClaim(u, null, null, null, Opportunities.dieselSkandalRecordType());
        insert c;
        
        Test.startTest();
        c.submission_Date_Before_Claim_Statement__c = Date.today();
        c.Submission_Date_Before_Lawsuit_Date__c = Date.today();
        update c;
        Test.stopTest();

        Claim__c[] cc = [SELECT Form_Hash_1__c FROM Claim__c];
        System.assert(!cc.isEmpty());
        System.assert(String.isNotBlank(cc[0].form_Hash_1__c));
    }
    
    @isTest
    private static void testLastStageChangedAtOnUpdate() {
        User u = TestData.legalUser();
        Claim__c c = buildClaim(u, null, null, null, Opportunities.dieselSkandalRecordType());
        insert c;
        
        Test.startTest();
        c.stage__c = 'Appeal';
        update c;
        DateTime dt = DateTime.now();
        Test.stopTest();

        Claim__c[] cc = [SELECT Last_Stage_Change__c FROM Claim__c];
        System.assert(!cc.isEmpty());
        //System.assertEquals(dt.minute(), cc[0].last_Stage_Change__c.minute()); // if this failed just rerun the test you might get unlucky
    }
    
    @isTest
    private static void testResponseInsuranceLawsuitOnUpdate() {
        User u = TestData.legalUser();
        Claim__c c = buildClaim(u, null, null, null, Opportunities.dieselSkandalRecordType());
        insert c;
        
        Test.startTest();
        c.cover_Note_Scope__c = 'Judicial';
        c.claim_Letter_Insurance_Date__c = Date.today();
        c.response_Insurance_Claim_Letter__c = Date.today();
        update c;
        Test.stopTest();

        Claim__c[] cc = [
            SELECT  Lawsuit_Insurance_Date__c, Response_Insurance_Lawsuit__c,
                    Claim_Letter_Insurance_Date__c, Response_Insurance_Claim_Letter__c
            FROM Claim__c
        ];
        System.assert(!cc.isEmpty());
        System.assertEquals(cc[0].claim_Letter_Insurance_Date__c, cc[0].lawsuit_Insurance_Date__c);
        System.assertEquals(cc[0].response_Insurance_Claim_Letter__c, cc[0].response_Insurance_Lawsuit__c);
    }
    
    /*@isTest
    private static void testCreateTasksOnInsertAndUpdate() {
        User u = TestData.legalUser();
        u.bypass_process_builder__c = true;
        System.runAs(u) {
            testCreateTasksOnInsertAndUpdateAsUser(u);
        }
    }*/
    
    private static void testCreateTasksOnInsertAndUpdateAsUser(User u) {
        //User u = TestData.legalUser();
        ClaimTriggerhandler.Deactivate = true;
        Claim__c c = buildClaim(u, null, null, null, Opportunities.dieselSkandalRecordType());
        c.result__c = 'Partial';

        Test.startTest();
        insert c;        
        Test.stopTest();

        Task[] tt = [
            SELECT Subject
            FROM Task
            WHERE WhatID = :c.ID
        ];
        System.assertEquals(1, tt.size());
        System.assertEquals('Teilerstattungsbetrag hinterlegen', tt[0].subject);

        c.stage__c = 'Processing';
        c.result__c = 'Declined';
        update c;
        tt = [
            SELECT Subject
            FROM Task
            WHERE WhatID = :c.ID
        ];
        System.assertEquals(2, tt.size());
        System.assert(tt[0].subject == 'Teilerstattungsbetrag hinterlegen' || tt[0].subject == 'Als abgeschlossen markieren');
        System.assert(tt[1].subject == 'Teilerstattungsbetrag hinterlegen' || tt[1].subject == 'Als abgeschlossen markieren');
        System.assertNotEquals(tt[0].subject, tt[1].subject);
        
        c.result__c = 'Arrangement';
        update c;
        tt = [
            SELECT Subject
            FROM Task
            WHERE WhatID = :c.ID
        ];
        System.assertEquals(3, tt.size());
        System.assertNotEquals(tt[0].subject, tt[1].subject);
        System.assertNotEquals(tt[1].subject, tt[2].subject);
        System.assertNotEquals(tt[0].subject, tt[2].subject);
        
        // todo: fix 101 error from pb on correspondence.
        // Trigger recursion stopper ignored since it's a test.

        // Test correspondences as well
        /*Correspondence__c cr = TestData.createCorrespondence(c.ID, 'Court', 'Klageschrift', 'Draft');
        insert cr;

        c.stage__c = 'Lawsuit';
        c.customer_Is_Owner__c = true;
        c.canceled_Next_Court_Date__c = true;
        c.response_Insurance_Lawsuit__c = Date.today();
        c.cover_Note__c = 'Issued';
        c.cover_Note_Scope__c = 'Judicial';
        c.submission_Date_Before_Claim_Statement__c = Date.today();
        c.lawsuit_Date__c = null;
        update c;
        tt = [
            SELECT Subject
            FROM Task
            WHERE WhatID = :c.ID
        ];
        System.assertEquals(5, tt.size());
        */
    }
    
    @isTest
    private static void testCloseTasksOnUpdate() {
        // todo:
    }

    @testVisible
    private static Claim__c buildClaim(User u,
                                       Account vehicleBrand,
                                       Decimal amountInDispute,
                                       String oppPriorityLevel,
                                       ID oppRecordType) {
        Account a = TestData.createAccount();
        Account vh24 = TestData.createVH24Account();
        insert new Account[]{a, vh24};

        User[] uu = [SELECT ID FROM User WHERE Username = :u.username];
        if (uu.isEmpty()) {
            System.runAs(TestData.bypassUser()) {
                insert u;
            }
        } else {
            u = uu[0];
        }

        Opportunity o = TestData.createOpportunity(a.ID, 'On Hold');
        o.recordTypeID = oppRecordType != null ? oppRecordType : Opportunities.dieselSkandalRecordType();
        o.account__c = vh24.Id;
        o.backoffice__c = u.Id;
        if (vehicleBrand != null) {
            o.vehicle_Brand__c = vehicleBrand.ID;    
        }
        
        Account insurance;
        if (oppPriorityLevel == 'I') {
            insurance = TestData.createInsurance('lvXX1');
        } else if (oppPriorityLevel == 'II') {
            insurance = TestData.createInsurance('lv004');
        } else if (String.isNotBlank(oppPriorityLevel)) {
            insurance = TestData.createInsurance('aksjkj');
        }
        if (insurance != null) {
            insert insurance;
            o.insurance__c = insurance.ID;
        }
        insert o;

        Claim__c c = TestData.createClaim(o.ID, 'Draft');
        c.legal__c = u.ID;
        c.clerk__c = u.ID;
        return c;
    }

    @isTest
    private static void testDuplicateCostNote() {
        User u = TestData.legalUser();
        Claim__c c = buildClaim(u, null, null, null, Opportunities.dieselSkandalRecordType());
        insert c;
        Cost_Note__C cn = CostNotes.build(c, 'Customer', 'Selbstbehalt', 'Selbstbehalt');
        insert cn;

        Test.startTest();
        c.cover_Note_Scope__c = 'Extrajudicial';
        c.claim_Letter_Insurance_Date__c = Date.today();
        c.response_Insurance_Claim_Letter__c = Date.today();
        c.cover_Note_Scope__c = 'Extrajudicial';
        update c; // should not create the same costnote agian
        Test.stopTest();

        List<Cost_Note__c> cns = [SELECT Id FROM Cost_Note__c WHERE Subject__c = 'Selbstbehalt'];
        System.assertEquals(1, cns.size());
    }

    /*
    // should work idk what is wrong here
    @isTest
    private static void testSingleCostNote() {
        User u = TestData.legalUser();
        Claim__c c = buildClaim(u, null, null, null, Opportunities.dieselSkandalRecordType());
        insert c;
        
        Test.startTest();
        c.cover_Note_Scope__c = 'Extrajudicial';
        c.claim_Letter_Insurance_Date__c = Date.today();
        c.response_Insurance_Claim_Letter__c = Date.today();
        update c; // should create a costnote
        c.cover_Note_Scope__c = null;
        update c;
        Test.stopTest();

        List<Cost_Note__c> cns = [SELECT Id FROM Cost_Note__c WHERE Subject__c = 'Selbstbehalt'];
        System.assertEquals(1, cns.size());
    }
    */
}