objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Is_Not_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Kunde ist nicht Eigentümer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Is_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Kunde ist Eigentümer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ownership_Request_Date__c</fullName>
        <label>Datum Eigentümerrückfrage</label>
        <type>Date</type>
    </fields>
    <description>Object for managing legal claim process.</description>
    <label>Fall</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fälle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Fall</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Korrespondenzen</relationshipLabel>
        <relationshipName>Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Link_Ownership__c</fullName>
        <label>Versanddatum Rückfrage Eigentümerschaft</label>
        <type>Date</type>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UpdateVehicleOwnership.cls
global class UpdateVehicleOwnership implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(
            'SELECT Id, Date_Link_Ownership__c, Claim__r.Customer_Is_Owner__c, Claim__r.Customer_Is_Not_Owner__c ' +
            'FROM Correspondence__c'
        );
    }

    global void execute(Database.BatchableContext BC, List<Correspondence__c> scope) {
        List<Claim__c> claims = new List<Claim__c>();
        for (Correspondence__c corr : scope) {
            if (corr.Date_Link_Ownership__c == null || corr.Date_Link_Ownership__c.daysBetween(System.today()) <= 2) {
                continue;
            }
            if (corr.Claim__r.Customer_Is_Owner__c == true || corr.Claim__r.Customer_Is_Not_Owner__c == true) {
                continue;
            }
            corr.Claim__r.Customer_Is_Owner__c = true;
            corr.Claim__r.Ownership_Request_Date__c = System.today();
            claims.add(corr.Claim__r);
        }
        update claims;
    }

    global void finish(Database.BatchableContext BC) {
    }
}