objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Commission_Rate_Dg__c</fullName>
        <label>Provisionssatz Dieselskandal</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Commission_Rate_Lv__c</fullName>
        <label>Provisionssatz Lebensversicherung</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <description>Used to create and store the documents with the commission details</description>
    <label>Provision</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Commission_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Satz</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <description>Stores the commission rates which are used to calculate the commission</description>
    <label>Provisionssatz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionssätze</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Rate__c.object
<CustomObject>
    <label>Kurs</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kurse</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CommissionsTests.cls
@isTest
public class CommissionsTests {
	@isTest
	static void testCommissionRate() {
		TriggerConfiguration.allInactive = true;

		Account account = TestData.createAccount();
		insert account;
		Account legalAccount = TestData.createAccount();
		insert legalAccount;
		Commission_Rate__c commissionRate1 = TestData.createCommissionRate(account.Id, legalAccount.Id, 'Lebensversicherung', 50);
		insert commissionRate1;
		Commission_Rate__c commissionRate2 = TestData.createCommissionRate(account.Id, legalAccount.Id, 'Dieselskandal', 50);
		insert commissionRate2;
		Commission__c commission = TestData.createCommission(account.Id,legalAccount.Id,null,null,System.today()-1,System.today()+1);

		TriggerConfiguration.allInactive = false;

		Test.startTest();
		insert commission;
		Test.stopTest();

		Commission__c updatedCommission = [select Id, Commission_Rate_Dg__c, Commission_Rate_Lv__c from Commission__c where Id = :commission.Id];
		System.assert(updatedCommission.Commission_Rate_Lv__c == commissionRate1.Rate__c);
		System.assert(updatedCommission.Commission_Rate_Dg__c == commissionRate2.Rate__c);
	}
}