objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Auto_Follow_up_Count__c</fullName>
        <label>Anzahl Auto-Follow-ups</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Auto_Follow_up_Date__c</fullName>
        <label>Nächstes Auto-Follow-up</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Autostart_Auto_Follow_up_Journeys__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Follow-up Journeys automatisch starten</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Started_Auto_Follow_up_Journey_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Started Auto-Follow-up Journey 1</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Auto_Follow_up_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Anzahl Auto-Follow-ups</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Auto_Follow_up_Date__c</fullName>
        <label>Nächstes Auto-Follow-up</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Autostart_Auto_Follow_up_Journeys__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Follow-up Journeys automatisch starten</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Form_Hash_1__c</fullName>
        <label>Form Hash 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Started_Auto_Follow_up_Journey_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Started Auto-Follow-up Journey 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Web form token</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <fields>
        <fullName>Email</fullName>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <label>Email</label>
    </recordTypes>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Follow_up_Count__c</fullName>
        <label>Anzahl Auto-Follow-ups</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Auto_Follow_up_Date__c</fullName>
        <label>Nächstes Auto-Follow-up</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Autostart_Auto_Follow_up_Journeys__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Follow-up Journeys automatisch starten</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Form_Hash_1__c</fullName>
        <label>Form Hash 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Hash_2__c</fullName>
        <label>Form Hash 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Started_Auto_Follow_up_Journey_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Started Auto-Follow-up Journey 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Test_Case_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Web Form Token</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>Musterfeststellungsklage</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Musterfeststellungsklagen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Test_Case_Statuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Test Case Statuses</masterLabel>
</GlobalValueSet>

classes/TestCaseTriggerHandlerTests.cls
@isTest
public class TestCaseTriggerHandlerTests {
	@isTest
	static void testSetToken(){
		// Testsetup
		TriggerConfiguration.allInactive = true;

		Opportunity opportunity = TestData.createOpportunity(null, 'New');
		insert opportunity;
		Test_Case__c testCase = TestData.createTestCase(opportunity.Id);

		TriggerConfiguration.allInactive = false;

		// Test
		Test.startTest();
		insert testCase;
		Test.stopTest();

		// Assertion
		testCase = [SELECT Id, Token__c FROM Test_Case__c WHERE Id = :testCase.Id];
		System.assertNotEquals(null, testCase.Token__c);
	}

	@isTest
	static void testSetHash(){
		// Testsetup
		TriggerConfiguration.allInactive = true;

		Opportunity opportunity = TestData.createOpportunity(null, 'New');
		insert opportunity;
		Test_Case__c testCase = TestData.createTestCase(opportunity.Id);

		TriggerConfiguration.allInactive = false;

		// Test
		Test.startTest();

		insert testCase;

		Test.stopTest();

		// Assertion
		testCase = [select Id, Form_Hash_1__c, Form_Hash_2__c from Test_Case__c where Id = :testCase.Id];
		System.assert(testCase.Form_Hash_1__c != null);
		System.assert(testCase.Form_Hash_2__c != null);
	}
    
    @isTest
	static void testAutoJourney(){
		// Testsetup
		TriggerConfiguration.allInactive = true;

		Opportunity opportunity = TestData.createOpportunity(null, 'New');
		insert opportunity;
		Test_Case__c testCase = TestData.createTestCase(opportunity.Id);
		testCase.Status__c = 'Finished';
		testCase.Auto_Follow_up_Count__c = 4;
		testCase.Autostart_Auto_Follow_up_Journeys__c = true;

		TriggerConfiguration.allInactive = false;

		// Test
		Test.startTest();

		insert testCase;

		Test.stopTest();

		// Assertion
		testCase = [select Id, Auto_Follow_up_Date__c, Auto_Follow_up_Count__c, Started_Auto_Follow_up_Journey_1__c from Test_Case__c where Id = :testCase.Id];
		System.assertNotEquals(null,testCase.Auto_Follow_up_Date__c);
		System.assertEquals(0, testCase.Auto_Follow_up_Count__c);
		System.assertEquals(true, testCase.Started_Auto_Follow_up_Journey_1__c);
	}

	@isTest
	static void testAutoSendFinished(){
		// Testsetup
		TriggerConfiguration.allInactive = true;

		Account account = TestData.createAccount();
		insert account;
		Contact contact = TestData.createContact(account.Id);
		insert contact;
		Opportunity opportunity = TestData.createOpportunity(account.Id,'New');
		opportunity.Contact__c = contact.Id;
		insert opportunity;
		Test_Case__c testCase = TestData.createTestCase(opportunity.Id);
		insert testCase;

		TriggerConfiguration.allInactive = false;

		// Test
		Test.startTest();

		testCase.Status__c = 'Finished'; 
		update testCase;

		Test.stopTest();

		// Assertion - todo: what to assert?
		//List<Task> tasks = [select Id from Task where Subject LIKE 'Email:%' AND WhatId = :testCase.Id];
		//System.assertEquals(1,tasks.size());
	}
}