objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>Follow_up_Period__c</fullName>
        <defaultValue>3</defaultValue>
        <label>Zeit bis Follow-up</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Verträge</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contract_Stages</valueSetName>
        </valueSet>
    </fields>
    <description>Object for storing contract with customer.</description>
    <label>Vertrag</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verträge</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Follow_up_Period__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Zeit bis Follow-up</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

globalValueSets/Contract_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Signed</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <description>Contract stages.</description>
    <masterLabel>Contract Stages</masterLabel>
</GlobalValueSet>

classes/DidNotReceiveContract.cls
// Vertrag "Unterschrift nicht erhalten" Button
// Contract__c "Unterschrift nicht erhalten" Button
public class DidNotReceiveContract {
    private final Contract__c contract;
    private final Opportunity opp;

    public DidNotReceiveContract(ApexPages.StandardController stdCtl) {
        this.contract = [
            SELECT Id,
            Stage__c,
            Follow_up_Period__c,
            Opportunity__c,
            Opportunity__r.Account_Id__c,
            Opportunity__r.Contact__c,
            (SELECT Id, Status, Subject, IsClosed FROM Tasks)
            FROM Contract__c
            WHERE Id = :stdCtl.getId()
        ];
    }

    public PageReference renderPage() {
        PageReference pageRef;
        if (contract.Opportunity__r.Contact__c == null) {
            return Errors.page('Bitte hinterlegen Sie einen Kontakt auf dem Feld "Kunde" auf der Anfrage.');
        }

		// Send mail
		Id templateId;
		if (Accounts.isVH24(this.contract.Opportunity__r.Account_Id__c)) { // 0010Y00000eCUS9
			// VH24
			templateId = EmailTemplates.idOf(EmailTemplates.name.LvCallcenterDidNotReceiveContractVh24);
		} else {
			// VR24
			templateId = EmailTemplates.idOf(EmailTemplates.name.LvCallcenterDidNotReceiveContractVr24);
		}
		EmailUtilities emailUtilities = new EmailUtilities(contract.Id, contract.Opportunity__r.Contact__c, templateId, UserInfo.getUserId());
		String result = emailUtilities.send();
	    System.debug('Sent automatic mail with result: ' + result);

		// Update task
		for (Task task : this.contract.Tasks) {
			if ((task.Subject == 'Unterschriebenen Vertrag hochladen und Erhalt bestätigen') && (task.isClosed == false)){
				task.ActivityDate = System.today() +  Integer.valueOf(this.contract.Follow_up_Period__c);
				update task;
			}
		}

        pageRef = Page.SuccessPage;
        pageRef.setRedirect(true);
        return pageRef;
    }
}