objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Salutation__c</fullName>
        <formula>IF(Title = "Herr" || TEXT(Salutation) = "Herr","Sehr geehrter Herr " + LastName,IF(Title = "Frau"|| TEXT(Salutation) = "Frau","Sehr geehrte Frau " + LastName,"Hallo " + FirstName + " " + LastName))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Salutation</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EMailMapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Attachment__c</fullName>
        <label>Attachment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsEnabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <label>Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UniqueName__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>UniqueName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>EMailMapping</label>
    <pluralLabel>EMailMappings</pluralLabel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Number__c</fullName>
        <label>Bearbeitungsnummer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <formula>Contact__r.Salutation__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Salutation</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

classes/LVSendAGBDelegation.cls
public class LVSendAGBDelegation implements iVH24MailDelegation {
    
    private EmailTemplate template;
    private Id templateId;
    private EMailMapping__mdt  eMailMapping;
    private Attachment attachment;
    private Messaging.EmailFileAttachment fileAttachment;
    private Contact contact;
    private string body;
    private string htmlBody;
    private Id parentId;
    private Id UserId;
    private Id senderAdressId;
    private string subject;
    private Map<String,String> mergeMappings;
    private String bn;

    public LVSendAGBDelegation(String bn,Contact contact) {
        this.bn = bn;
        this.contact = contact;
    }
    
    public LVSendAGBDelegation(VH24MailData data) {
        this.bn = data.bn;
        mapIdToContact(data.objectId);  
    }
    
    private void  mapIdToContact(Id contactId) {
        this.contact = [Select EMail,Id,Salutation__c FROM Contact WHERE Id =: contactId];
    }
    
    public void prepareMail() {
        this.userId = Users.vh24Lv();
        this.eMailMapping = fetchConfig();
        this.template = fetchTemplate();
        this.attachment = fetchAndMapAttachment();
        fileAttachment = mapToFile();
        this.subject = buildSubject();
        buildBody();
        buildHtmlBody();
        prepareMergeMappings();
        mergeFields();
        getSenderAdress();
    }
    
    public string getPlainTextBody(){
        return body;
    }
    
    
    public string getHtmlBody(){
		return htmlBody;
    }
    
    public list<string> getAddresses() {
    	return new list<string> {contact.EMail};
    }
    
    public string getSubject(){
    	return this.subject;    
    }

    public Messaging.EmailFileAttachment[] getAttachments() {
        return new Messaging.EmailFileAttachment[]{this.fileAttachment};
    } 
    
    public EMailTemplate getMailTemplate() {
        return this.template;
    }
    
    public Id getSenderId() {
        return senderAdressId;
    }
    
    public string getRecipientAddress() {
        return contact.Email;
    }
    
    public boolean isEnabled(){
        return eMailMapping.isEnabled__c;
    }
    
    public void processResult(Messaging.SendEmailResult [] r) {
        
    }
        
    public void processError(String message) {
            
    }
    
    private EMailMapping__mdt fetchConfig(){
       return [Select Attachment__c, 
                              Template__c, 
                              UniqueName__c,
               				  IsEnabled__c
                              FROM  EMailMapping__mdt 
                              WHERE UniqueName__c = 'LVLeadOppConversion' LIMIT 1];
    }
    
    private EmailTemplate fetchTemplate(){
        return [SELECT Id,
                         Subject,
                         Body,
                         Name,
                         HtmlValue 
                         FROM EmailTemplate 
                         WHERE DeveloperName =: eMailMapping.Template__c];
        
    } 
    
    private Attachment fetchAndMapAttachment(){
     		 return [select Id,
                                Name,
                                Body,
                                BodyLength FROM Attachment where ParentId =: this.template.id LIMIT 1];            
    }
      
    private Messaging.Emailfileattachment mapToFile() {
        this.fileAttachment = new Messaging.Emailfileattachment();
        this.fileAttachment.setFileName(this.attachment.Name);
        this.fileAttachment.setBody(this.attachment.Body);
        return this.fileAttachment;
        //attachmentSize += attachment.BodyLength;
    }
    
    private void buildBody() {
         Id recipientId = contact.Id;
         Id parentId = template.Id;
         this.body = template.Body;
     }
    
    private void buildHtmlBody() {
        Id recipientId = contact.Id;
        Id parentId = template.Id;
        this.htmlBody = template.HtmlValue.replace('{text_body}',body.replace('\n','<br/>'));
    }
    
    private string buildSubject(){
        Id recipientId = contact.Id;
        Id parentId = template.Id;
        return template.subject;
    }
    
    private void getSenderAdress(){
    	OrgWideEmailAddress orgWideEmailAddresses = [select Id, 
                                                     Address 
                                                     from OrgWideEmailAddress 
                                                     Where Address = 'lebensversicherung@verbraucherhilfe24.de' LIMIT 1];
        senderAdressId = (Id)orgWideEmailAddresses.Id;
    }
    
    private void prepareMergeMappings(){
        this.mergeMappings = new Map<String,String>();
        this.mergeMappings.put('{!Opportunity.Number__c}',this.bn);
        if(Contact.Salutation__c != null) {
        	this.mergeMappings.put('{!Contact.Salutation__c}',Contact.Salutation__c);  
        } else {
          	this.mergeMappings.put('{!Contact.Salutation__c}',''); 
        }    
    }
    
    private void mergeFields(){
        for (String key : this.mergeMappings.keySet()) {
            this.htmlBody = this.htmlBody.replace(key,this.mergeMappings.get(key));
            this.body = this.body.replace(key,this.mergeMappings.get(key));
            this.subject = this.subject.replace(key,this.mergeMappings.get(key));            
		}
    }
    
    public void processResult(){
        
    }
    
}