objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <formula>TEXT(Last_Opportunity__r.StageName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Date__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Termine</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Date_Stages</valueSetName>
        </valueSet>
    </fields>
    <label>Termin</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Termine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Partner)</relationshipLabel>
        <relationshipName>Opportunities_Partner</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Autocreate_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Autocreate Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Autosend_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Autosend Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Korrespondenz</relationshipLabel>
        <relationshipName>Opportunity_Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Partner</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Opportunity_Correspondence_Partners</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_Mail_TemplateID__c</fullName>
        <description>Do not set this manually! Used by code to sent a email on opportunity correspondence creation.</description>
        <inlineHelpText>DO NOT USE THIS FIELD MANUALLY.</inlineHelpText>
        <label>Send Mail TemplateID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Opportunity_Correspondence_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Text_Modules__c</fullName>
        <label>Textbausteine</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Opportunity_Correspondence_Text_Modules</valueSetName>
        </valueSet>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Date_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Open</fullName>
        <default>true</default>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Date Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Opportunity_Correspondence_Partners.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Insurance</fullName>
        <label>Versicherung</label>
    </customValue>
    <customValue>
        <fullName>Vehicle Brand</fullName>
        <label>Fahrzeughersteller</label>
    </customValue>
    <customValue>
        <fullName>Bank</fullName>
        <label>Kreditinstitut</label>
    </customValue>
    <customValue>
        <fullName>Legal Protection Insurance</fullName>
        <label>Rechtsschutzversicherung</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
        <label>Kunde</label>
    </customValue>
    <customValue>
        <fullName>Individuell</fullName>
    </customValue>
    <masterLabel>Opportunity Correspondence Partners</masterLabel>
</GlobalValueSet>

globalValueSets/Opportunity_Correspondence_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Opportunity Correspondence Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Opportunity_Correspondence_Text_Modules.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AnforderungVertrag</fullName>
        <label>Anforderung Vertrag</label>
    </customValue>
    <masterLabel>Opportunity Correspondence Text Modules</masterLabel>
</GlobalValueSet>

classes/DGen_DocumentCreatedWebhookTest.cls
// TODO: !
@isTest
public class DGen_DocumentCreatedWebhookTest {
    @isTest
    public static void hackCoverage() {
        DGen_DocumentCreatedWebhook.hackCoverage();
    }

    /*
    @isTest
    public static void testSendMail() {
        // doesnt work :c
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.addHeader('httpMethod', 'POST');
        req.requestUri = '/services/apexrest/docgen/documents';       
        String postData = '{}';
        String JsonMsg = JSON.serialize(postData);
        req.requestBody = Blob.valueof(JsonMsg);
        RestContext.request = req; 
        RestContext.response= res;


        TriggerConfiguration.allInactive = true;
        Account a = new Account(
            name = 'VH24'
        );
        insert a;
        Contact con = new Contact(
            LastName = 'bar',
            Email = 'foo@bar.baz'
        );
        insert con;
        Opportunity opp = TestData.createOpportunity(a.Id, 'On Hold');
        User ul = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert ul;
        }
        opp.Legal__c = ul.Id;
        opp.Contact__c = con.Id;
        insert opp; 
        TriggerConfiguration.allInactive = false;
        Opportunity_Correspondence__c oppCorr = new Opportunity_Correspondence__c(
            Opportunity__c = opp.Id,
            Date__c = System.today(),
            Stage__c = 'Draft',
            Partner__c = 'Bank',
            Autocreate_Document__c = true,
            Autosend_Email__c = true,
            Text_Modules__c = 'AnforderungVertrag',
            Send_Mail_TemplateID__c = EmailTemplates.idOf(EmailTemplates.name.FzLeComLegalAnfrageKorrespondenz)
        );
        Test.startTest();
        insert oppCorr;
        Test.stopTest();
    }
    */
}