objects/Date__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Termine</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Date_Stages</valueSetName>
        </valueSet>
    </fields>
    <label>Termin</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Termine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Insurance_Status__c</fullName>
        <formula>IF(Termination_Date__c &lt; Today(),"bereits gekündigt",IF(Expiration_Date__c &lt; Today(),"regulär abgelaufen",IF(Active_Non_contributory_Periods__c &gt; 0,"beitragsfrei gestellt","noch aktiv")))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Versicherungsstatus</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Partner)</relationshipLabel>
        <relationshipName>Opportunities_Partner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority_Level__c</fullName>
        <formula>IF(Insurance__c = null,'',CASE(Insurance__r.External_Id__c,'lv001','I','lv002','I','lv104','I','lv003','I','lv106','I','lv032','I','lv039','I','lv031','I','lv046','I','lv071','I','lv047','I','lv053','I','lv008','I','lv005','I','lv067','I', 'lv068','I', 'lv089','I','lv054','I','lv048','I', 'lv049','I', 'lv045','I', 'lv035','I', 'lv098','I', 'lv016','I', 'lv027','I', 'lv078','I', 'lv009','I', 'lv034','I','lv777','I','lv004','II','III'))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prioritätsstufe</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Autocreate_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Autocreate Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Autosend_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Autosend Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Korrespondenz</relationshipLabel>
        <relationshipName>Opportunity_Correspondencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Partner</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Opportunity_Correspondence_Partners</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_Mail_TemplateID__c</fullName>
        <description>Do not set this manually! Used by code to sent a email on opportunity correspondence creation.</description>
        <inlineHelpText>DO NOT USE THIS FIELD MANUALLY.</inlineHelpText>
        <label>Send Mail TemplateID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Opportunity_Correspondence_Stages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Text_Modules__c</fullName>
        <label>Textbausteine</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Opportunity_Correspondence_Text_Modules</valueSetName>
        </valueSet>
    </fields>
    <label>Korrespondenz</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Korrespondenzen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <fields>
        <fullName>Email</fullName>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <label>Email</label>
    </recordTypes>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

globalValueSets/Date_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Open</fullName>
        <default>true</default>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Date Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Opportunity_Correspondence_Partners.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Insurance</fullName>
        <label>Versicherung</label>
    </customValue>
    <customValue>
        <fullName>Vehicle Brand</fullName>
        <label>Fahrzeughersteller</label>
    </customValue>
    <customValue>
        <fullName>Bank</fullName>
        <label>Kreditinstitut</label>
    </customValue>
    <customValue>
        <fullName>Legal Protection Insurance</fullName>
        <label>Rechtsschutzversicherung</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
        <label>Kunde</label>
    </customValue>
    <customValue>
        <fullName>Individuell</fullName>
    </customValue>
    <masterLabel>Opportunity Correspondence Partners</masterLabel>
</GlobalValueSet>

globalValueSets/Opportunity_Correspondence_Stages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Opportunity Correspondence Stages</masterLabel>
</GlobalValueSet>

globalValueSets/Opportunity_Correspondence_Text_Modules.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AnforderungVertrag</fullName>
        <label>Anforderung Vertrag</label>
    </customValue>
    <masterLabel>Opportunity Correspondence Text Modules</masterLabel>
</GlobalValueSet>

classes/OppRequestContract.cls
// Opportunity__c "Vertrag anfordern" Button
// Anfrage "Vertrag anfordern" Button
public class OppRequestContract {
    private final Opportunity opp;

    public OppRequestContract(ApexPages.StandardController stdCtl) {
        this.opp = [
            SELECT ID,
            RecordTypeId,
            StageName,
            Legal__c,
            Legal_Account__c,
            Contact__c,
            Priority_Level__c,
            Insurance_Status__c,
            Backoffice__c,
            Backoffice__r.isActive
            FROM Opportunity
            WHERE ID = :stdCtl.getId()
        ];
    }

    private string getTemplate() {
        if (Opportunities.isLebensversicherung(this.opp.RecordTypeId)) {
            if (Accounts.isJCLegalLv(this.opp.Legal_Account__c)) {
                return EmailTemplates.idOf(EmailTemplates.name.LvJaegerLegalAnfrageKorrespondenz);
            } else if (Accounts.isLegalLeCom(this.opp.Legal_Account__c)) {
                return EmailTemplates.idOf(EmailTemplates.name.LvLeComLegalAnfrageKorrespondenz);
            } else if (Accounts.isCLLBLegal(this.opp.Legal_Account__c)) {
                return EmailTemplates.idOf(EmailTemplates.name.LvKainzLegalAnfrageKorrespondenz);
            }
        } else if (Opportunities.isDieselskandal(this.opp.RecordTypeId)) {
            if (Accounts.isJCLegal(this.opp.Legal_Account__c)) {
                return EmailTemplates.idOf(EmailTemplates.name.DieselJaegerLegalAnfrageKorrespondenz);
            } else if (Accounts.isLegalLeCom(this.opp.Legal_Account__c)) {
                return EmailTemplates.idOf(EmailTemplates.name.DieselLeComLegalAnfrageKorrespondenz);
            } else if (Accounts.isCLLBLegal(this.opp.Legal_Account__c)) {
                return EmailTemplates.idOf(EmailTemplates.name.DieselKainzLegalAnfrageKorrespondenz);
            }
        } else if (Opportunities.isFinanzierung(this.opp.RecordTypeId)) {
            if (Accounts.isJCLegal(this.opp.Legal_Account__c)) {
                return EmailTemplates.idOf(EmailTemplates.name.FzJaegerLegalAnfrageKorrespondenz);
            } else if (Accounts.isLegalLeCom(this.opp.Legal_Account__c)) {
                return EmailTemplates.idOf(EmailTemplates.name.FzLeComLegalAnfrageKorrespondenz);
            } else if (Accounts.isCLLBLegal(this.opp.Legal_Account__c)) {
                return EmailTemplates.idOf(EmailTemplates.name.FzKainzLegalAnfrageKorrespondenz);
            }
        } else {
            System.debug('OppRequestContract :: getTemplate: error invalid recordtype=' + this.opp.RecordTypeId);
            return null;
        }
        System.debug('OppRequestContract :: getTemplate: error invalid legal account');
        return null;
    }

    private void sendEmail(Opportunity_Correspondence__c oppCorr) {
        string templateId = getTemplate();
        if (templateId == null) {
            System.debug('OppRequestContract :: sendMail: error templateId is null');
            return;
        } else if (templateId == '') {
            System.debug('OppRequestContract :: sendMail: error templateId is empty');
            return;
        }
        System.debug('OppRequestContract :: sendMail: setting templateID=' + templateID);
        oppCorr.Send_Mail_TemplateID__c = templateId; // sends a mail after oppcorr attachement insert
        /*
        List<attachment> atts = [select Id from Attachment where ParentId = :oppCorr.Id];
        List<id> attsIds = new List<Id>();
        for (attachment a : atts) {
            attsIds.add(a.Id);
            System.debug('OppRequestContract :: sendMail: found attachment id=' + a.Id);
        }
        EmailUtilities emailUtilities = new EmailUtilities(oppCorr.ID, this.opp.Contact__c, templateId, this.opp.Legal__c);
        emailUtilities.createFollowUp = true;
        if (atts.size() > 0) {
            emailUtilities.additionalAttachmentIds.addAll(attsIds);
            System.debug('OppRequestContract :: sendMail: attaching atts=' + atts);
        } else {
            System.debug('OppRequestContract :: sendMail: warning no attachments found for oppcorr=' + oppCorr.Id);
        }
        String result = emailUtilities.send();
        System.debug('Sent automatic mail with result: ' + result + ' templateID: ' + templateId);
        */
    }

    public PageReference renderPage() {
        PageReference pageRef;

        if (this.opp.Contact__c == null) {
            return Errors.page('Bitte tragen Sie ein Kontakt auf dem Feld "Kunde" ein.');
        } else if (this.opp.Backoffice__c == null || this.opp.Backoffice__r.isActive == false) {
            return Errors.page('Bitte tragen Sie einen aktiven Backoffice Mitarbeiter auf der Anfrage ein.');
        }
        String partner;
        if (Opportunities.isDieselSkandal(this.opp.RecordTypeId)) { // 0120Y000000W0CY
            partner = 'Bank';
        } else if (Opportunities.isFinanzierung(this.opp.RecordTypeId)) { // 0120Y000000KnMH
            partner = 'Bank';
            /*
            // commented this task out again and use the code in emailutilities:
            // https://trello.com/c/2bC3rqlQ/339-anfrage-vertrag-anfordern-button-feedback
            // added this task here:
            // https://trello.com/c/Ob5aJmfP/311-create-task-wiedervorlage-bzgl-darlehensvertrag
            Task t = Tasks.build(
                'Wiedervorlage bzgl. Darlehensvertrag', // subject
                null, // description
                this.opp,
                this.opp.Backoffice__r,
                Date.today().addDays(14), // ActivityDate
                true, // no duplicates
                false // followup
            );
            if (t != null) {
                insert t;
            }
            */
        } else { // if (Opportunities.isLebensversicherung(this.opp.RecordTypeId)) {
            partner = 'Insurance';
            /*
            // commented this task out again and use the code in emailutilities:
            // https://trello.com/c/2bC3rqlQ/339-anfrage-vertrag-anfordern-button-feedback
            if ((opp.Priority_Level__c == 'I') || (opp.Priority_Level__c == 'II')) {
                if ((opp.Insurance_Status__c == 'beitragsfrei gestellt') || (opp.Insurance_Status__c == 'noch aktiv')) {
                    Task t = Tasks.build('Wiedervorlage bzgl. Vertrag', null, this.opp, this.opp.Backoffice__r, Date.today()+14, true, false);
                    if (t != null) {
                        insert t;
                    }
                }
            }
            */
        }

        Opportunity_Correspondence__c oppCorr = new Opportunity_Correspondence__c(
            Opportunity__c = this.opp.Id,
            Date__c = System.today(),
            Stage__c = 'Draft',
            Partner__c = partner,
            Autocreate_Document__c = true,
            Autosend_Email__c = true,
            Text_Modules__c = 'AnforderungVertrag'
        );
        // send automatic email: https://trello.com/c/2bC3rqlQ/339-anfrage-vertrag-anfordern-button-feedback
        sendEmail(oppCorr);
        insert oppCorr;
        // System.debug('OppRequestContract :: created Opportunity_Correspondence__c=' + oppCorr.Id);

        pageRef = Page.SuccessPage;
        pageRef.setRedirect(true);
        return pageRef;
    }
}