objects/Date__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Web form token</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Termin</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Termine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TerminTriggerHandler.cls
// DateTriggerHandler ( TerminTriggerHandler )
public class TerminTriggerHandler extends BaseTriggerHandler {
    @testVisible
    private static Boolean deactivate = false;

    public override void beforeInsert() {
        Logger.debug('>> TerminTriggerHandler :: beforeInsert :: termins: ' + Trigger.new);

        Date__c[] tt = Trigger.new;
        setUniqueID(tt);

        Logger.debug('<< TerminTriggerHandler :: beforeInsert');
    }

    protected override Boolean preventFromRunning() { return deactivate; }

    private void setUniqueID(Date__c[] tt) {
        for (Date__c t : tt) {
            if (t.Token__c != null) {
                continue;
            }
            t.Token__c = GUID.Gen();
        }
    }
}