objects/Date__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Datum</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Termin bestätigt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Representative_Confirmation_Date__c</fullName>
        <label>Bestätigungsdatum des Terminsvertreters</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Web form token</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Termin</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Termine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ConfirmAppointmentController.cls
public class ConfirmAppointmentController {
    private Date__c app;
    public boolean isError {get; set;}
    public string errorMsg {get; set;}
    public PageReference init() {
        isError = false;
        errorMsg = '';
        app = getAppointment();
        if (this.app == null) {
            errorMsg = 'Der Termin wurde nicht gefunden.';
        }
        if (this.app.Date_confirmed__c == true) {
            errorMsg = 'Der Termin wurde bereits bestätigt.';
        }
        if (errorMsg != '') {
            isError = true;
            return null;
        }
        ConfirmApp();
        return null;
    }

    public void ConfirmApp() {
		this.app.Date_confirmed__c = true;
		this.app.Representative_Confirmation_Date__c = Datetime.now();
		update this.app;
    }

    private Date__c getAppointment() {
        string appId = getToken();
        if (appId == null) {
            return null;
        }
        List<Date__c> apps = [
            SELECT Id,
            Token__c,
            Date_confirmed__c
            FROM Date__c
            WHERE Token__c = :appId
        ];
        if (apps.size() != 1) {
            return null;
        }
        return apps[0];
    }

    private string getToken() {
        return ApexPages.currentPage().getParameters().get('token');
    }
}