objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Dokumente</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Quelle</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Document_Sources</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Typ</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Document_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Dokument</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dokumente</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Auto_Follow_up_Date__c</fullName>
        <label>Nächstes Auto-Follow-up</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <formula>CASE((AdWords_Source__c ), 
"kwanko", "Kwanko",
"taboola", "Taboola",
" ")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quelle</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

globalValueSets/Document_Sources.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Email attachment</fullName>
    </customValue>
    <customValue>
        <fullName>Upload</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <default>true</default>
        <label>Sonstiges</label>
    </customValue>
    <description>Document Sources</description>
    <masterLabel>Document Sources</masterLabel>
</GlobalValueSet>

globalValueSets/Document_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Versicherungsantrag</fullName>
    </customValue>
    <customValue>
        <fullName>Versicherungsvertrag</fullName>
    </customValue>
    <customValue>
        <fullName>Wertstandsmitteilung</fullName>
    </customValue>
    <customValue>
        <fullName>Vollmacht</fullName>
    </customValue>
    <customValue>
        <fullName>DG_Registration</fullName>
        <label>Fahrzeugschein</label>
    </customValue>
    <customValue>
        <fullName>DG_Invoice</fullName>
        <label>Vertrag/Rechnung</label>
    </customValue>
    <customValue>
        <fullName>DG_Authorization_Manufacturer</fullName>
        <label>Vollmacht (Hersteller)</label>
    </customValue>
    <customValue>
        <fullName>DG_Authorization_Dealer</fullName>
        <label>Vollmacht (Autohaus)</label>
    </customValue>
    <customValue>
        <fullName>Vollmacht (Kreditinstitut)</fullName>
    </customValue>
    <customValue>
        <fullName>DG_Update_Confirmation</fullName>
        <label>Bestätigung zum Softwareupdate</label>
    </customValue>
    <customValue>
        <fullName>DG_Legal_Protection_Insurance_Policy</fullName>
        <label>Rechtsschutzversicherungspolice</label>
    </customValue>
    <customValue>
        <fullName>Darlehensvertrag</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <default>true</default>
        <label>Sonstiges</label>
    </customValue>
    <customValue>
        <fullName>Widerspruch</fullName>
    </customValue>
    <customValue>
        <fullName>Allgemeine Vertragsbedingungen</fullName>
    </customValue>
    <description>Document Types</description>
    <masterLabel>Document Types</masterLabel>
</GlobalValueSet>

classes/DocumentTriggerHandlerTest.cls
@isTest
public class DocumentTriggerHandlerTest {
    @isTest
    public static void testDeactivateJourney() {
        Account a = TestData.createAccount();
        insert a;
        Opportunity o = TestData.createOpportunity(a.Id, 'On Hold');
        User u = TestData.createUser();
        insert u;
        o.Backoffice__c = u.Id;
        o.Auto_Follow_up_Date__c = System.today();
        insert o;
        Document__c document = new Document__c(
            Opportunity__c = o.Id,
            Name = 'TestName',
            Type__c = 'Other',
            Source__c = 'Other',
            Link__c = 'http://foo.bar'
        );
        Test.startTest();
        insert document;
        update document;
        Test.stopTest();

        o = [SELECT Id, Auto_Follow_up_Date__c FROM Opportunity WHERE Id = :o.Id];
        System.assertEquals(null, o.Auto_Follow_up_Date__c);
    }

    @isTest
    public static void testCreateTask() {
        Account a = TestData.createAccount();
        insert a;
        Opportunity o = TestData.createOpportunity(a.Id, 'On Hold');
        User u = TestData.createUser();
        insert u;
        o.Backoffice__c = u.Id;
        o.Auto_Follow_up_Date__c = System.today();
        insert o;
        Document__c document = new Document__c(
            Opportunity__c = o.Id,
            Name = 'TestName',
            Type__c = 'Other',
            Source__c = 'Other',
            Link__c = 'http://foo.bar'
        );

		List<Task> ts = [SELECT ID FROM Task WHERE Subject = 'Neue Unterlagen'];
        System.assertEquals(0, ts.size());

        Test.startTest();
        insert document;
        Test.stopTest();

        ts = [SELECT ID FROM Task WHERE Subject = 'Neue Unterlagen'];
        System.assertEquals(1, ts.size());
    }
}