objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Dokumente</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dokument</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dokumente</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <label>Dieselskandal</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Auftragstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assignment_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Callcenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for call center process parts.</description>
        <label>Callcenter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Callcenter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dokumente_unvollst_ndig__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dokumente unvollständig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dokumente_vollst_ndig__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dokumente vollständig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Engine_Type__c</fullName>
        <label>Motortyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Engine_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Has_Legal_Protection_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rechtsschutzversicherung vorhanden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legal_Protection_Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rechtsschutzversicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Rechtsschutzversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Rechtsschutzversicherung)</relationshipLabel>
        <relationshipName>Opportunities_Legal_Protection_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_For_Loss__c</fullName>
        <label>Absagegrund</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reasons_For_Loss</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Assignment_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Share</fullName>
    </customValue>
    <customValue>
        <fullName>Direkt</fullName>
    </customValue>
    <customValue>
        <fullName>50%</fullName>
        <isActive>false</isActive>
        <label>50%</label>
    </customValue>
    <customValue>
        <fullName>RSV 20%</fullName>
        <isActive>false</isActive>
        <label>RSV 20%</label>
    </customValue>
    <masterLabel>Assignment Types</masterLabel>
</GlobalValueSet>

globalValueSets/Engine_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>OM640</fullName>
    </customValue>
    <customValue>
        <fullName>OM642</fullName>
    </customValue>
    <customValue>
        <fullName>OM 607</fullName>
    </customValue>
    <customValue>
        <fullName>OM651</fullName>
    </customValue>
    <customValue>
        <fullName>3.0</fullName>
    </customValue>
    <customValue>
        <fullName>4.2</fullName>
    </customValue>
    <customValue>
        <fullName>EA189</fullName>
    </customValue>
    <customValue>
        <fullName>EA288</fullName>
    </customValue>
    <customValue>
        <fullName>EA189 ohne Rückruf</fullName>
    </customValue>
    <customValue>
        <fullName>ENS</fullName>
    </customValue>
    <customValue>
        <fullName>EA897</fullName>
    </customValue>
    <customValue>
        <fullName>OM622</fullName>
    </customValue>
    <customValue>
        <fullName>Anderer Motortyp</fullName>
    </customValue>
    <customValue>
        <fullName>OM626</fullName>
    </customValue>
    <customValue>
        <fullName>OM 646.811</fullName>
    </customValue>
    <customValue>
        <fullName>OM 646.812</fullName>
    </customValue>
    <masterLabel>Engine Types</masterLabel>
</GlobalValueSet>

globalValueSets/Reasons_For_Loss.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Nicht im Zeitraum</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde möchte nicht wegen Preis</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde will nicht</fullName>
    </customValue>
    <customValue>
        <fullName>Widerruf nicht angreifbar</fullName>
    </customValue>
    <customValue>
        <fullName>Potential zu gering</fullName>
    </customValue>
    <customValue>
        <fullName>Kein wirtschaftliches Potential</fullName>
    </customValue>
    <customValue>
        <fullName>Dokumente nicht geschickt</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde hat widerrufen</fullName>
    </customValue>
    <customValue>
        <fullName>Auto verkauft</fullName>
    </customValue>
    <customValue>
        <fullName>Fahrzeug nicht betroffen</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde nicht Käufer</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde nicht erreichbar</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde verstorben</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde hat keine RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Leasing Vertrag</fullName>
    </customValue>
    <customValue>
        <fullName>Keine Widerrufsbelehrung</fullName>
    </customValue>
    <customValue>
        <fullName>BMW EZ nach 01.06.2014</fullName>
    </customValue>
    <customValue>
        <fullName>Darlehensvertrag älter als 2 Jahre</fullName>
    </customValue>
    <customValue>
        <fullName>Nutzungsanteil zu gering</fullName>
    </customValue>
    <customValue>
        <fullName>Kapital zu gering</fullName>
    </customValue>
    <customValue>
        <fullName>Österreich/Schweiz kleiner Motor</fullName>
    </customValue>
    <customValue>
        <fullName>Umrüstung erfolgt</fullName>
    </customValue>
    <customValue>
        <fullName>Mfk nicht bestätigt</fullName>
    </customValue>
    <customValue>
        <fullName>Effektiver Jahreszins 0,00%</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstige Gründe</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstige Gründe (ohne Mail)</fullName>
    </customValue>
    <customValue>
        <fullName>Aussortiert</fullName>
    </customValue>
    <customValue>
        <fullName>Absage wegen Kenntnis</fullName>
    </customValue>
    <masterLabel>Reasons For Loss</masterLabel>
</GlobalValueSet>

classes/OppDocsExtensionTests.cls
@isTest
public class OppDocsExtensionTests {
    /*
    private static void testErrorCases(Boolean docsComplete) {
        // Arrange
        PageReference p = docsComplete ? Page.OppDocsComplete : Page.OppDocsIncomplete;
        Test.setCurrentPage(p);
        
        Account vh24 = TestData.createVH24Account();
        Account vr24 = TestData.createVR24Account();
        Account a = TestData.createAccount();
        insert new Account[]{vh24, vr24, a};

        Opportunity o = TestData.createOpportunity(a.ID, 'On Hold');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        // o.Account__c = vh24.Id;
        insert o;

		// o = [SELECT Id, account_Id__c FROM Opportunity WHERE Id = :o.Id];
        // System.assertNotEquals(null, o.account_Id__c);

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        OppDocsExtension oe = new OppDocsExtension(sc);
        
        // Act
        PageReference pr = docsComplete ? oe.complete() : oe.incomplete();

        // Assert that no field is set when not LV record type
        o = [
            SELECT  StageName,
            		Dokumente_vollst_ndig__c,
                    Dokumente_unvollst_ndig__c,
            		Has_Legal_Protection_Insurance__c,
            		Assignment_Type__c,
            		Engine_Type__c
            		
            FROM Opportunity
        ];
        System.assertEquals('On Hold', o.stageName);
        System.assertEquals(false, o.dokumente_vollst_ndig__c);
        System.assertEquals(false, o.dokumente_unvollst_ndig__c);
        System.assert(pr.getUrl().containsIgnoreCase(Page.Error.getUrl()));

        rt = [SELECT ID FROM RecordType WHERE Name='DieselSkandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        o.assignment_Type__c = null;
        o.legal__c = null;
        update o;
        oe = new OppDocsExtension(sc);
        pr = docsComplete ? oe.complete() : oe.incomplete();

    	// Assert that it fails when no assignment_Type__c or legal__c
        String noParamsErrUrl1 = pr.getUrl();
        System.debug('noParamsErrUrl1 ' + noParamsErrUrl1);
        System.assert(noParamsErrUrl1.containsIgnoreCase(Page.Error.getUrl()));
        //--
        o.assignment_Type__c = 'Share';
        o.has_Legal_Protection_Insurance__c = false;

        UserRole ur = [SELECT ID FROM UserRole WHERE Name = 'Management'];
        User u = [SELECT ID FROM User WHERE UserRole.Name = 'Management' LIMIT 1];
        u.userRoleId = ur.ID;
        o.legal__c = u.ID;

        o.engine_Type__c = 'EA189';
        update o;

        oe = new OppDocsExtension(sc);
        pr = docsComplete ? oe.complete() : oe.incomplete();
        
        // Assert that it fails with a different error msg if there's assignment_Type__c and legal__c,
        // but engine_Type__c is 'EA189', Opp record type is 'Dieselskandal', and assignment_Type__c is not 'RSV'.
        String noParamsErrUrl2 = pr.getUrl();
        System.debug('noParamsErrUrl2 ' + noParamsErrUrl2);
        System.assert(noParamsErrUrl2.containsIgnoreCase(Page.Error.getUrl()));
        System.assertNotEquals(noParamsErrUrl1, noParamsErrUrl2);
        
        //--
        o.Backoffice__c = u.Id;
        o.assignment_Type__c = 'RSV';
        o.has_Legal_Protection_Insurance__c = false;
        o.StageName = 'Lost';
        o.Reason_For_Loss__c = 'Aussortiert';
        update o;
        
        oe = new OppDocsExtension(sc);
        pr = docsComplete ? oe.complete() : oe.incomplete();
        
        // Assert that it fails with a different error msg if there's if has_Legal_Protection_Insurance__c is false.
        String noParamsErrUrl3 = pr.getUrl();
        System.assert(noParamsErrUrl3.containsIgnoreCase(Page.Error.getUrl()));
        System.assertNotEquals(noParamsErrUrl1, noParamsErrUrl3);
        System.assertNotEquals(noParamsErrUrl2, noParamsErrUrl3);
        
        //--
        o.has_Legal_Protection_Insurance__c = true;
        update o;
        
        oe = new OppDocsExtension(sc);
        pr = docsComplete ? oe.complete() : oe.incomplete();

        // Assert that it fails with a different error msg if Backoffice__c is not filled.
        String noParamsErrUrl4 = pr.getUrl();
        System.assert(noParamsErrUrl4.containsIgnoreCase(Page.Error.getUrl()));
        System.assertNotEquals(noParamsErrUrl1, noParamsErrUrl4);
        System.assertNotEquals(noParamsErrUrl2, noParamsErrUrl4);
        System.assertNotEquals(noParamsErrUrl3, noParamsErrUrl4);

        //--
        o.backoffice__c = u.ID;
        update o;
        
        oe = new OppDocsExtension(sc);
        pr = docsComplete ? oe.complete() : oe.incomplete();

        // Assert that it fails with a different error msg if the opp is not linked to a vh24 or vr24 account
        System.assert(pr.getUrl().containsIgnoreCase(Page.Error.getUrl()));
        System.assertNotEquals(noParamsErrUrl1, pr.getUrl());
        System.assertNotEquals(noParamsErrUrl2, pr.getUrl());
        System.assertNotEquals(noParamsErrUrl3, pr.getUrl());
        System.assertNotEquals(noParamsErrUrl4, pr.getUrl());
    }

    @isTest
    private static void testErrorCasesForComplete() {
        TriggerConfiguration.allInactive = true;
        testErrorCases(true);
    }

    @isTest
    private static void testErrorCasesForIncomplete() {
        TriggerConfiguration.allInactive = true;
        testErrorCases(false);
    }
	*/

    @isTest
    private static void testErrorClaimAlready() {
        // Arrange
        PageReference p = Page.OppDocsComplete;
        Test.setCurrentPage(p);

        Account vh24 = TestData.createVH24Account();
        Account vr24 = TestData.createVR24Account();
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert new Account[]{vh24, vr24, a};

		Opportunity o = buildOpp(a.ID, vr24.ID);
        o.Assignment_Type__c = 'Direkt';
        o.stageName = 'Claim';
        o.assignment_Type__c = 'RSV';
        o.Legal_Protection_Insurance__c = a.Id;
        o.has_Legal_Protection_Insurance__c = true;
        o.RecordTypeId = Opportunities.dieselSkandalRecordType();
        insert o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        OppDocsExtension oe = new OppDocsExtension(sc);

        // Act
        PageReference pr = oe.incomplete();

        System.assertEquals(Errors.page('Die Anfrage befindet sich bereits im Fall Status. Es muss keine Aktion ausgeführt werden.').getUrl(), pr.getUrl());
    }

    @isTest
    private static void testErrorNoContact() {
        // Arrange
        PageReference p = Page.OppDocsComplete;
        Test.setCurrentPage(p);

        Account vh24 = TestData.createVH24Account();
        Account vr24 = TestData.createVR24Account();
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert new Account[]{vh24, vr24, a};

		Opportunity o = buildOpp(a.ID, vr24.ID);
        o.Contact__c = null;
        o.Assignment_Type__c = 'Direkt';
        o.stageName = 'Check';
        o.assignment_Type__c = 'RSV';
        o.Legal_Protection_Insurance__c = a.Id;
        o.has_Legal_Protection_Insurance__c = true;
        o.RecordTypeId = Opportunities.dieselSkandalRecordType();
        insert o;
        Document__c doc = new Document__c(
            Opportunity__c = o.Id
        );
        insert doc;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        OppDocsExtension oe = new OppDocsExtension(sc);

        // Act
        PageReference pr = oe.complete();

        System.assertEquals(Errors.page('Bitte hinterlegen Sie einen Kontakt auf dem Feld "Kunde" der Anfrage.').getUrl(), pr.getUrl());
    }

    @isTest
    private static void testErrorNotEnoughDocs() {
        // Arrange
        PageReference p = Page.OppDocsComplete;
        Test.setCurrentPage(p);

        Account vh24 = TestData.createVH24Account();
        Account vr24 = TestData.createVR24Account();
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert new Account[]{vh24, vr24, a};

		Opportunity o = buildOpp(a.ID, vr24.ID);
        o.Assignment_Type__c = 'Direkt';
        o.stageName = 'Check';
        o.assignment_Type__c = 'RSV';
        o.Legal_Protection_Insurance__c = a.Id;
        o.has_Legal_Protection_Insurance__c = true;
        o.RecordTypeId = Opportunities.dieselSkandalRecordType();
        insert o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        OppDocsExtension oe = new OppDocsExtension(sc);

        // Act
        PageReference pr = oe.complete();

        System.assertEquals(Errors.page('Zu dieser Anfrage wurden noch keine Dokumente hochgeladen!').getUrl(), pr.getUrl());
    }

    @isTest
    private static void testDocsCompleteVR() {
        // Arrange
        PageReference p = Page.OppDocsComplete;
        Test.setCurrentPage(p);

        Account vh24 = TestData.createVH24Account();
        Account vr24 = TestData.createVR24Account();
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert new Account[]{vh24, vr24, a};

		Opportunity o = buildOpp(a.ID, vr24.ID);
        o.Assignment_Type__c = 'Direkt';
        o.stageName = 'Check';
        o.assignment_Type__c = 'RSV';
        o.Legal_Protection_Insurance__c = a.Id;
        o.has_Legal_Protection_Insurance__c = true;
        o.RecordTypeId = Opportunities.dieselSkandalRecordType();
        insert o;
        Document__c doc = new Document__c(
            Opportunity__c = o.Id
        );
        insert doc;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        OppDocsExtension oe = new OppDocsExtension(sc);

        // Act
        PageReference pr = oe.complete();

        o = [
            SELECT  ID,
            StageName,
            Dokumente_vollst_ndig__c,
            Dokumente_unvollst_ndig__c
            FROM Opportunity
        ];

        // Assert that when Account is VH24 or VR24 we don't return an error,
        // and opp fields are set.
        System.assertEquals('Claim', o.stageName);
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.DocumentsComplete.LVCallcenterDocumentsCompleteVr24)));
        System.assertEquals(true, o.dokumente_vollst_ndig__c);
        System.assertEquals(false, o.dokumente_unvollst_ndig__c);
    }

    @isTest
    private static void testDocsCompleteVH() {
        // Arrange
        PageReference p = Page.OppDocsComplete;
        Test.setCurrentPage(p);

        Account vh24 = TestData.createVH24Account();
        Account vr24 = TestData.createVR24Account();
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert new Account[]{vh24, vr24, a};

		Opportunity o = buildOpp(a.ID, vh24.ID);
        o.Assignment_Type__c = 'Direkt';
        o.stageName = 'Check';
        o.assignment_Type__c = 'RSV';
        o.Legal_Protection_Insurance__c = a.Id;
        o.has_Legal_Protection_Insurance__c = true;
        o.RecordTypeId = Opportunities.dieselSkandalRecordType();
        insert o;
        Document__c doc = new Document__c(
            Opportunity__c = o.Id
        );
        insert doc;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        OppDocsExtension oe = new OppDocsExtension(sc);

        // Act
        PageReference pr = oe.complete();

        o = [
            SELECT  ID,
            StageName,
            Dokumente_vollst_ndig__c,
            Dokumente_unvollst_ndig__c
            FROM Opportunity
        ];

        // Assert that when Account is VH24 or VR24 we don't return an error,
        // and opp fields are set.
        System.assertEquals('Claim', o.stageName);
        System.assertEquals(true, pr.getUrl().contains(EmailTemplates.idOf(EmailTemplates.DocumentsComplete.LVCallcenterDocumentsCompleteVh24)));
        System.assertEquals(true, o.dokumente_vollst_ndig__c);
        System.assertEquals(false, o.dokumente_unvollst_ndig__c);
    }

    @isTest
    private static void testDocsIncompleteVHcoverFZ() {
        // Arrange
        PageReference p = Page.OppDocsComplete;
        Test.setCurrentPage(p);
        
        Account vh24 = TestData.createVH24Account();
        Account vr24 = TestData.createVR24Account();
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert new Account[]{vh24, vr24, a};
        
        Opportunity o = buildOpp(a.ID, vh24.ID);
        o.Assignment_Type__c = 'Direkt';
        o.stageName = 'Check';
        o.Legal_Protection_Insurance__c = a.Id;
        o.has_Legal_Protection_Insurance__c = true;
        o.recordtypeid = Opportunities.finanzierungRecordType();
        insert o;
        Document__c doc = new Document__c(
            Opportunity__c = o.Id
        );
        insert doc;
        
        Apexpages.StandardController sc = new Apexpages.standardController(o);
        OppDocsExtension oe = new OppDocsExtension(sc);
        
        // Act
        PageReference pr = oe.incomplete();
    }

    @isTest
    private static void testDocsIncompleteVH() {
        // Arrange
        PageReference p = Page.OppDocsComplete;
        Test.setCurrentPage(p);
        
        Account vh24 = TestData.createVH24Account();
        Account vr24 = TestData.createVR24Account();
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert new Account[]{vh24, vr24, a};
        
        Opportunity o = buildOpp(a.ID, vh24.ID);
        o.Assignment_Type__c = 'Direkt';
        o.stageName = 'Check';
        o.Legal_Protection_Insurance__c = a.Id;
        o.has_Legal_Protection_Insurance__c = true;
        insert o;
        Document__c doc = new Document__c(
            Opportunity__c = o.Id
        );
        insert doc;
        
        Apexpages.StandardController sc = new Apexpages.standardController(o);
        OppDocsExtension oe = new OppDocsExtension(sc);
        
        // Act
        PageReference pr = oe.incomplete();

        o = [
            SELECT  ID,
            		StageName,
            		Dokumente_vollst_ndig__c,
                    Dokumente_unvollst_ndig__c
            FROM Opportunity
        ];

        // Assert that when Account is VH24 or VR24 we don't return an error,
        // and opp fields are set.
        System.assertNotEquals('Claim', o.stageName);
        System.assert(pr.getUrl().containsIgnoreCase(o.ID));
        System.assertEquals(false, o.dokumente_vollst_ndig__c);
        System.assertEquals(true, o.dokumente_unvollst_ndig__c);
    }

    @isTest
    private static void testDocsIncompleteVR() {
        // Arrange
        PageReference p = Page.OppDocsComplete;
        Test.setCurrentPage(p);
        
        Account vh24 = TestData.createVH24Account();
        Account vr24 = TestData.createVR24Account();
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert new Account[]{vh24, vr24, a};
        
        Opportunity o = buildOpp(a.ID, vr24.ID);
        o.Assignment_Type__c = 'Direkt';
        o.stageName = 'Check';
        o.Legal_Protection_Insurance__c = a.Id;
        o.has_Legal_Protection_Insurance__c = true;
        insert o;
        Document__c doc = new Document__c(
            Opportunity__c = o.Id
        );
        insert doc;
        
        Apexpages.StandardController sc = new Apexpages.standardController(o);
        OppDocsExtension oe = new OppDocsExtension(sc);
        
        // Act
        PageReference pr = oe.incomplete();

        o = [
            SELECT  ID,
            		StageName,
            		Dokumente_vollst_ndig__c,
                    Dokumente_unvollst_ndig__c
            FROM Opportunity
        ];

        // Assert that when Account is VH24 or VR24 we don't return an error,
        // and opp fields are set.
        System.assertNotEquals('Claim', o.stageName);
        System.assert(pr.getUrl().containsIgnoreCase(o.ID));
        System.assertEquals(false, o.dokumente_vollst_ndig__c);
        System.assertEquals(true, o.dokumente_unvollst_ndig__c);
    }

   @isTest
    private static void testLebensversicherung() {
        TriggerConfiguration.allInactive = true;
        // Arrange
        PageReference p = Page.OppDocsComplete;
        Test.setCurrentPage(p);
        
        Account vh24 = TestData.createVH24Account();
        Account vr24 = TestData.createVR24Account();
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert new Account[]{vh24, vr24, a};
        
        Opportunity o = buildOpp(a.ID, vr24.ID);
        o.recordTypeId = Opportunities.lebensversicherungRecordType();
        o.assignment_Type__c = 'Direkt';
        o.stageName = 'Check';
        o.legal_Protection_Insurance__c = a.Id;
        o.has_Legal_Protection_Insurance__c = true;
        
        User u = TestData.createUser();
		insert u;
        o.callcenter__c = u.ID;
	    insert o;

        Document__c doc = new Document__c(
            Opportunity__c = o.Id
        );
        insert doc;
        
        Apexpages.StandardController sc = new Apexpages.standardController(o);
        OppDocsExtension oe = new OppDocsExtension(sc);
        
        // Act
        PageReference pr = oe.incomplete();

        o = [
            SELECT  ID,
            		StageName,
            		Dokumente_vollst_ndig__c,
                    Dokumente_unvollst_ndig__c
            FROM Opportunity
        ];

        // Assert that when Account is VH24 or VR24, and LV, we don't return an error
        // but we also don't take the user to the email sending page.
        // Opp fields shoudl still be set, though.
        System.assertNotEquals('Claim', o.stageName);
        System.assert(pr.getUrl().endsWith('/' + o.ID));
        System.assertEquals(false, o.dokumente_vollst_ndig__c);
        System.assertEquals(true, o.dokumente_unvollst_ndig__c);
    }
    
    private static Opportunity buildOpp(ID accID, ID vhOrVrAcc) {
        TriggerConfiguration.allInactive = true;
        Opportunity o = TestData.createOpportunity(accID, 'On Hold');
        Contact con = new Contact(LastName = 'foo', Email = 'bar@baz.de');
        insert con;
        o.Contact__c = con.id;
        o.account__c = vhOrVrAcc;
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        o.has_Legal_Protection_Insurance__c = true;
        o.assignment_Type__c = 'Share';
		// UserRole ur = [SELECT ID FROM UserRole WHERE Name = 'Management'];
        // User u = [SELECT ID FROM User WHERE UserRole.Name = 'Management' LIMIT 1];
        // u.userRoleId = ur.ID;
        User u = TestData.legalUser();
        System.runAs(TestData.bypassUser()) {
            insert u;
        }
        o.legal__c = u.ID;
        o.backoffice__c = u.ID;
        return o;
    }
}