objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Dokumente</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dokument</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dokumente</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

classes/DocumentActionTest.cls
@isTest
public class DocumentActionTest {
    @isTest
    public static void testCreateTask() {
        TriggerConfiguration.allInactive = true;
        Account a = new Account(Name = 'VH24');
        insert a;
        Opportunity o = TestData.createOpportunity(a.Id, 'On Hold');
        User u = TestData.createUser();
        insert u;
        o.Backoffice__c = u.Id;
        insert o;
        Document__c doc = new Document__c(
            Opportunity__c = o.Id
        );
        insert doc;
        List<Document__c> docs = new List<Document__c>();
        docs.add(doc);

        List<Task> ts;
        ts = [SELECT Id FROM Task WHERE Subject = 'Neue Unterlagen'];
        System.assertEquals(0, ts.size());

        DocumentAction.createTasks(docs);

        ts = [SELECT Id FROM Task WHERE Subject = 'Neue Unterlagen'];
        System.assertEquals(1, ts.size());

        DocumentAction.createTasks(docs);

        ts = [SELECT Id FROM Task WHERE Subject = 'Neue Unterlagen'];
        System.assertEquals(1, ts.size(), 'unexpected duplication');
    }

    @isTest
    public static void hackCoverage() {
        TriggerConfiguration.allInactive = true;
        Account a = new Account(Name = 'VH24');
        insert a;
        Opportunity o = TestData.createOpportunity(a.Id, 'On Hold');
        User u = TestData.createUser();
        insert u;
        o.Backoffice__c = u.Id;
        insert o;
        Document__c doc = new Document__c(
            Opportunity__c = o.Id
        );
        insert doc;
        List<Document__c> docs = new List<Document__c>();
        docs.add(doc);

        DocumentAction.deactivateFollowUpJourneys(docs);
        DocumentAction.setRecordType(docs);
    }
}