objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Dokumente</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dokument</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dokumente</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Auto_Follow_up_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Anzahl Auto-Follow-ups</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Auto_Follow_up_Date__c</fullName>
        <label>Nächstes Auto-Follow-up</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

classes/DocumentAction.cls
public class DocumentAction {
    public static void createTasks(List<Document__c> documents){
        documents = [
            SELECT Id,
            Opportunity__c,
            (SELECT Id,Status,Subject from Tasks)
            FROM Document__c
            WHERE Id IN :documents
        ];
        Set<Id> opportunityIds = new Set<Id>();
        for (Document__c document : documents) {
            opportunityIds.add(document.Opportunity__c);
        }
        Map<Id,Opportunity> opportunities = new Map<Id,Opportunity>([
            SELECT Id,
            Backoffice__c,
            Backoffice__r.isActive,
            (SELECT Id,Status,Subject FROM Tasks)
            FROM Opportunity
            WHERE Id IN :opportunityIds
        ]);
        List<Task> ts = new List<Task>();
        List<Task> newTasks = new List<Task>();
        for (Document__c document : documents){
            Opportunity opportunity = opportunities.get(document.Opportunity__c);
            if (opportunity.Backoffice__r == null || opportunity.Backoffice__r.isActive == false) {
                Logger.debug('DocumentAction :: createTasks :: error: backoffice inactive or null (opportunity=' + opportunity.id + ').');
                continue;
            }
            ts.add(Tasks.build(
                'Neue Unterlagen', // subject
                null, // description
                opportunity, // parent object
                opportunity.Backoffice__r, // owner
                System.today(), // due date
                true, // no duplicates
                false, // followup
                opportunity.ID
            ));
        }
        for (Task task : ts){
            if (task != null){
                newTasks.add(task);
            }
        }
        if (newTasks.size() > 0) {
            insert newTasks;
        }
    }

    public static void deactivateFollowUpJourneys(List<Document__c> documents){
        Set<Id> opportunityIds = new Set<Id>();
        for (Document__c document : documents) {
            opportunityIds.add(document.Opportunity__c);
        }
        Map<Id,Opportunity> opportunities = new Map<Id,Opportunity>([
            SELECT Id,
            Auto_Follow_up_Count__c,
            Auto_Follow_up_Date__c,
            Backoffice__c,
            Backoffice__r.isActive,
            (SELECT Id, Status, Subject FROM Tasks)
            FROM Opportunity
            WHERE Id IN :opportunityIds
        ]);
        List<Opportunity> updateOpportunities = new List<Opportunity>();
        for (Document__c document : documents){
            Opportunity opportunity = opportunities.get(document.Opportunity__c);
            Boolean updateOpportunity = false;
            if (opportunity.Auto_Follow_up_Count__c != 0){
                opportunity.Auto_Follow_up_Count__c = 0;
                updateOpportunity = true;
            }
            if (opportunity.Auto_Follow_up_Date__c != null){
                opportunity.Auto_Follow_up_Date__c = null;
                updateOpportunity = true;
            }
            if (updateOpportunity == true){
                updateOpportunities.add(opportunity);
            }
        }
        if (!updateOpportunities.isEmpty()){
            update updateOpportunities;
        }
    }

    public static void setRecordType(List<Document__c> docs){
        Set<Id> opportunityIds = new Set<Id>();
        for (Document__c document : docs){
            opportunityIds.add(document.Opportunity__c);
        }
        Map<Id,Opportunity> opps = new Map<Id,Opportunity>([SELECT Id, RecordTypeId FROM Opportunity WHERE Id IN :opportunityIds]);
        for (Document__c document : docs) {
            Opportunity opportunity = opps.get(document.Opportunity__c);
            if (Opportunities.isDieselSkandal(opportunity.RecordTypeId)) { // 0120Y000000W0CY
                document.RecordTypeId = Documents.dieselSkandalRecordType(); // 0120Y000000W0t2
            } else if (Opportunities.isFinanzierung(opportunity.RecordTypeId)) { // 0120Y000000KnMH
                document.RecordTypeId = Documents.finanzierungRecordType(); // 0120Y000000KnMM
            } else {
                document.RecordTypeId = Documents.lebensversicherungRecordType(); // 0120Y000000W0sx
            }
        }
    }
}