objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Anfrage</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Dokumente</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dokument</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dokumente</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Auftragstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assignment_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Automatisches_Follow_up_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Automatisches Follow-up 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Callcenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for call center process parts.</description>
        <label>Callcenter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Callcenter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dokumente_unvollst_ndig__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dokumente unvollständig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dokumente_vollst_ndig__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dokumente vollständig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Engine_Type__c</fullName>
        <label>Motortyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Engine_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Has_Legal_Protection_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rechtsschutzversicherung vorhanden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

globalValueSets/Assignment_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Share</fullName>
    </customValue>
    <customValue>
        <fullName>Direkt</fullName>
    </customValue>
    <customValue>
        <fullName>50%</fullName>
        <isActive>false</isActive>
        <label>50%</label>
    </customValue>
    <customValue>
        <fullName>RSV 20%</fullName>
        <isActive>false</isActive>
        <label>RSV 20%</label>
    </customValue>
    <masterLabel>Assignment Types</masterLabel>
</GlobalValueSet>

globalValueSets/Engine_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>OM640</fullName>
    </customValue>
    <customValue>
        <fullName>OM642</fullName>
    </customValue>
    <customValue>
        <fullName>OM 607</fullName>
    </customValue>
    <customValue>
        <fullName>OM651</fullName>
    </customValue>
    <customValue>
        <fullName>3.0</fullName>
    </customValue>
    <customValue>
        <fullName>4.2</fullName>
    </customValue>
    <customValue>
        <fullName>EA189</fullName>
    </customValue>
    <customValue>
        <fullName>EA288</fullName>
    </customValue>
    <customValue>
        <fullName>EA189 ohne Rückruf</fullName>
    </customValue>
    <customValue>
        <fullName>ENS</fullName>
    </customValue>
    <customValue>
        <fullName>EA897</fullName>
    </customValue>
    <customValue>
        <fullName>OM622</fullName>
    </customValue>
    <customValue>
        <fullName>Anderer Motortyp</fullName>
    </customValue>
    <customValue>
        <fullName>OM626</fullName>
    </customValue>
    <customValue>
        <fullName>OM 646.811</fullName>
    </customValue>
    <customValue>
        <fullName>OM 646.812</fullName>
    </customValue>
    <masterLabel>Engine Types</masterLabel>
</GlobalValueSet>

classes/OppDocsExtension.cls
// Anfrage "Dokumente unvollständig" Button
// Anfrage "Dokumente vollständig" Button

// Opportunity "Dokumente unvollständig" Button
// Opportunity "Dokumente vollständig" Button
/*
OppDocsExtension is a visualforce controller extension to provide the business logic
for when an Opportunity has completed all the necessary documents or not.
An automated email is sent on either case, and a few variables are set on the Opportunity.
*/
public class OppDocsExtension {
    private final Opportunity opp;
    public OppDocsExtension(ApexPages.StandardController stdCtl) {
        this.opp = fetchOpp(stdCtl.getId());
    }

    public PageReference complete() {
        Logger.debug('>> OppDocsExtension :: complete :: opp: ' + this.opp);
        Logger.debug('<< OppDocsExtension :: complete');

        if (this.opp.Documents__r.size() < 1) {
            return Errors.page('Zu dieser Anfrage wurden noch keine Dokumente hochgeladen!');
        }

        return process(true, this.opp.account_Id__c, this.opp.recordTypeId);
    }

    public PageReference incomplete() {
        Logger.debug('>> OppDocsExtension :: incomplete :: opp: ' + this.opp);
        Logger.debug('<< OppDocsExtension :: incomplete');
        return process(false, this.opp.account_Id__c, this.opp.recordTypeId);
    }

    private PageReference process(Boolean docsComplete, ID acc, ID oppRecordType) {
        if (this.opp.stageName == 'Claim') {
            // Already in Claim stage, nothing to be done.
            return Errors.page('Die Anfrage befindet sich bereits im Fall Status. Es muss keine Aktion ausgeführt werden.');
        }

        if (this.opp.stageName != 'Check') { // no lawayer needed in stage check
            if (this.opp.assignment_Type__c == null || opp.legal__c == null) {
                return Errors.page('Daten unvollständig für diese Aktion: Auftragstyp, Anwalt. Bitte ergänzen und erneut versuchen.');
            }
        }

        if (this.opp.Contact__c == null) {
            return Errors.page('Bitte hinterlegen Sie einen Kontakt auf dem Feld "Kunde" der Anfrage.');
        }

        if (Opportunities.isDieselSkandal(opp.recordTypeId)
            && this.opp.assignment_Type__c != 'RSV'
            && this.opp.engine_Type__c == 'EA189') {
            return Errors.page('Fehler bei Übergabe des Prozesses.',
                               'Anfragen ohne Rechtsschutzversicherung und Motortyp EA189 können nicht an Anwalt oder Finanzierungsprozess übergeben werden.');
        }

        /*
        // should be covered by validation rules now
        if (this.opp.has_Legal_Protection_Insurance__c == null || !this.opp.has_Legal_Protection_Insurance__c) {
            return Errors.page('Es muss eine Rechtsschutzversicherung vorhanden sein.',
                               'Bevor die Stage auf "Claim" gestezt werden kann muss "RSV vorhanden" gecheckt sein.');
        }

        if (this.opp.backoffice__c == null) {
            return Errors.page('Bitte tragen Sie einen Backoffice Mitarbeiter ein.',
                               'Bevor die Stage auf "Claim" gestezt werden kann muss ein Backoffice Mitarbeiter eingetragen werden.');
        }
		*/

        if (Opportunities.isDieselSkandal(oppRecordType) && docsComplete) {
            this.opp.stageName = 'Claim';
        }

        this.opp.dokumente_vollst_ndig__c = docsComplete;
        this.opp.dokumente_unvollst_ndig__c = !docsComplete;
        update this.opp;

        // https://salesfive.atlassian.net/browse/VH24-146
        if (Opportunities.isLebensversicherung(this.opp.recordTypeId)) {
            Logger.debug('OppDocsExtension :: complete :: is LV. No email sent');
            return new PageReference('/' + this.opp.ID);
        }

        String templID = templateID(docsComplete);
        if (String.isBlank(templID)) {
            String errMsg = 'Unable to get email template for related account. No email sent.';
            Logger.error('OppDocsExtension :: complete :: ' + errMsg);
            return Errors.page(null, errMsg);
        }

        Logger.debug('OppDocsExtension :: complete :: sending email with template id: ' + templID);
        string url = page.sendMail.getUrl() + createUrl(templID);
        System.debug('url: ' +  url);
        Logger.debug('<< OppDocsExtension :: toClaim');
        return new PageReference(url);
    }

    private string createUrl(string tpl) {
        return
            '?id=' + opp.Id +
            '&tpl=' + tpl +
            '&recipient=' + opp.Contact__c +
            '&noprtatt=true' +
            '&hdl="Anfrage für fehlende Dokumente versenden."' +
            '&showAuthorizationsList=true';
    }
 
    private string getTplIncomplete() {
        if (Opportunities.isDieselSkandal(this.opp.RecordTypeId)) { // 0120Y000000W0CY
            if (Accounts.isJCLegal(this.opp.Legal_Account__c)) { // 0010Y000011MYHW
                return EmailTemplates.idOf(EmailTemplates.DocumentsIncomplete.DieselskandalBackofficeDocumentsIncompleteJaeger);
            }
            if (Accounts.isVH24(this.opp.Account__c)) { // 0010Y00000eCUS9
                return EmailTemplates.idOf(EmailTemplates.DocumentsIncomplete.DieselskandalBackofficeDocumentsIncompleteVh24);
            }
            return EmailTemplates.idOf(EmailTemplates.DocumentsIncomplete.DieselskandalBackofficeDocumentsIncompleteVr24);
        }
        if (Opportunities.isFinanzierung(this.opp.RecordTypeId)) { // 0120Y000000KnMH
            if (Accounts.isJCLegal(this.opp.Legal_Account__c)) { // 0010Y000011MYHW
                return EmailTemplates.idOf(EmailTemplates.DocumentsIncomplete.FzBackofficeDocumentsIncompleteJaeger);
            }
            if (Accounts.isVH24(this.opp.Account__c)) { // 0010Y00000eCUS9
                return EmailTemplates.idOf(EmailTemplates.DocumentsIncomplete.FzBackofficeDocumentsIncompleteVh24);
            }
            return EmailTemplates.idOf(EmailTemplates.DocumentsIncomplete.FzBackofficeDocumentsIncompleteVr24);
        }
        if (Accounts.isVH24(this.opp.Account__c)) { // 0010Y00000eCUS9
            return EmailTemplates.idOf(EmailTemplates.DocumentsIncomplete.LvCallcenterDocumentsIncompleteVh24);
        }
        return EmailTemplates.idOf(EmailTemplates.DocumentsIncomplete.LvCallcenterDocumentsIncompleteVr24);
    }

    private string getTplComplete() {
        if (Accounts.isVH24(this.opp.Account__c)) {
            return EmailTemplates.idOf(EmailTemplates.DocumentsComplete.LVCallcenterDocumentsCompleteVh24);
        }
        if (Accounts.isVR24(this.opp.Account__c)) {
            return EmailTemplates.idOf(EmailTemplates.DocumentsComplete.LVCallcenterDocumentsCompleteVr24);
        }
        return '';
    }

    private String templateID(Boolean docsComplete) {
        return docsComplete
            ? getTplComplete()
            : getTplIncomplete();
		/*
        if (Accounts.isVH24(accID)) {
            return docsComplete 
                ? EmailTemplates.idOf(EmailTemplates.DocumentsComplete.LVCallcenterDocumentsCompleteVh24)
                : EmailTemplates.idOf(EmailTemplates.Name.LvCallcenterDidNotReceiveDocumentsVh24);
        }
        if (Accounts.isVR24(accID)) {
            return docsComplete 
                ? EmailTemplates.idOf(EmailTemplates.DocumentsComplete.LVCallcenterDocumentsCompleteVr24)
                : EmailTemplates.idOf(EmailTemplates.Name.LvCallcenterDidNotReceiveDocumentsVr24);
        }
        return null;
		*/
    }

    private PageReference notLebensversicherungError() {
        String errMsg = 'Diese Funktionalität ist nur für die Sparte "Lebensversicherung" verfügbar.';
        Logger.error('OppDocsExtension :: ' + errMsg);
        return Errors.page(null, errMsg);
    }

    private Opportunity fetchOpp(ID oppID) {
        return [
            SELECT ID,
            RecordTypeId,
            Account_Id__c,
            Account__c,
            Legal_Account__c,
            Assignment_Type__c,
            Engine_Type__c,
            StageName,
            Legal__c,
            Has_Legal_Protection_Insurance__c,
            Backoffice__c,
            Contact__c,
            Callcenter__c,
            Dokumente_vollst_ndig__c,
            Dokumente_unvollst_ndig__c,
            Automatisches_Follow_up_2__c,
            (SELECT Id FROM Documents__r)
            FROM Opportunity
            WHERE ID = :oppID
        ];
    } 
}