objects/FinAPI_Log__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>Logs of the FinAPI importing process.</description>
    <label>FinAPI Log</label>
    <nameField>
        <label>FinAPI_Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FinAPI_Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FinAPILogger.cls
public class FinAPILogger implements Log { // Logger is taken
    // todo: batch without losing timestamp
    private void log(String type, String msg) {
		FinAPI_Log__c l = new FinAPI_Log__c();
		l.type__c = type;
        l.message__c = msg;
        insert l;
        Logger.debug('inserted log: ' + l);
    }

	public void error(String msg) {
        log('err', msg);
    }
    
    public void debug(String msg) {
        log('debug', msg);
    }
}