objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Abschluss_zwischen_1991_2007__c</fullName>
        <label>Abschluss zwischen 1991 und 2007</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Abschluss_zwischen_1991_und_2007</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>VH24 or VR24</description>
        <inlineHelpText>VH24 oder VR24</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Account Name)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bestandteil_betriebl_Altersvorsorge__c</fullName>
        <label>Bestandteil betriebl. Altersvorsorge</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bestandteil_betriebl_Altersvorsorge</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Has_Legal_Protection_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rechtsschutzversicherung vorhanden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legal_Protection_Insurance__c</fullName>
        <label>Rechtsschutzversicherung</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Web form token</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Versicherung_LV_RV__c</fullName>
        <label>Versicherung (LV/RV)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Versicherungen_LV_RV</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zufriedenheit_Renditenentwicklung__c</fullName>
        <label>Zufriedenheit Renditenentwicklung</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Zufriedenheit_Renditenentwicklung</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lead Process</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

globalValueSets/Abschluss_zwischen_1991_und_2007.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ja</fullName>
    </customValue>
    <customValue>
        <fullName>Nein</fullName>
    </customValue>
    <masterLabel>Abschluss zwischen 1991 und 2007</masterLabel>
</GlobalValueSet>

globalValueSets/Bestandteil_betriebl_Altersvorsorge.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ja</fullName>
    </customValue>
    <customValue>
        <fullName>Nein</fullName>
    </customValue>
    <masterLabel>Bestandteil betriebl. Altersvorsorge</masterLabel>
</GlobalValueSet>

globalValueSets/Zufriedenheit_Renditenentwicklung.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ja</fullName>
    </customValue>
    <customValue>
        <fullName>Nein</fullName>
    </customValue>
    <customValue>
        <fullName>Kann ich nicht beurteilen</fullName>
    </customValue>
    <masterLabel>Zufriedenheit Renditenentwicklung</masterLabel>
</GlobalValueSet>

classes/LebensversicherungLeadController.cls
public class LebensversicherungLeadController {
    public string satisfaction { get; set; }
    public string insuranceDate { get; set; }
    public string companyRetirementPlan { get; set; }
    public string insuranceCompany { get; set; }
    public string hasLegalInsurance { get; set; }
    public string legalInsuranceCompany { get; set; }

    public LebensversicherungLeadController() {
    }

    public PageReference ensureLeadExists() {
        if (fetchLeadFromToken() == null) {
            return new PageReference('/NotFound');
        }
        return null;
    }

    public List<SelectOption> getSatisfactionOptions() {
        return SObjectIntrospection.getUnsortedSelectOptions(new Lead(), 'Zufriedenheit_Renditenentwicklung__c');
    }

    public List<SelectOption> getInsuranceDateOptions() {
        return SObjectIntrospection.getSelectOptions(new Lead(), 'Abschluss_zwischen_1991_2007__c');
    }

    public List<SelectOption> getCompanyRetirementPlanOptions() {
        return SObjectIntrospection.getSelectOptions(new Lead(), 'Bestandteil_betriebl_Altersvorsorge__c');
    }

    public List<SelectOption> getInsuranceCompanyOptions() {
        return SObjectIntrospection.getSelectOptions(new Lead(RecordTypeId = getRecordTypeId()), 'Versicherung_LV_RV__c');
    }

    public List<SelectOption> getLegalInsuranceOptions() {
        List<SelectOption> o = new List<SelectOption>();
        o.add(new SelectOption('Ja', 'Ja'));
        o.add(new SelectOption('Nein', 'Nein'));
        return o;
    }

    private Lead fetchLeadFromToken() {
        string token = getToken();
        if (token == null || token == '') {
            return null;
        }
        List<Lead> leads = [
            SELECT Name
            FROM Lead
            WHERE Token__c = :token
        ];
        if (leads.size() == 0) {
            return null;
        }
        return leads[0];
    }

    private id getRecordTypeId() {
        RecordType rt = [
            SELECT Id
            FROM RecordType
            WHERE Name = 'Lebensversicherung'
            AND SObjectType = 'Lead'
        ];
        return rt.Id;
    }

    public PageReference createLead() {
        Lead l = new Lead(
            Company = 	'WebformLV still Unknown',
            FirstName = 'WebformLV still Unknown',
            LastName = 	'WebformLV still Unknown',
            Account__c = Accounts.VH24ID,
            LeadSource = 'Webform',
            RecordTypeId = getRecordTypeId(),
            Zufriedenheit_Renditenentwicklung__c = this.satisfaction,
            Abschluss_zwischen_1991_2007__c = this.insuranceDate,
            Bestandteil_betriebl_Altersvorsorge__c = this.companyRetirementPlan,
            Versicherung_LV_RV__c = this.insuranceCompany,
            Has_Legal_Protection_Insurance__c = (this.hasLegalInsurance == 'Ja'),
            Legal_Protection_Insurance__c = this.legalInsuranceCompany
        );
        l = UrlUtils.setLeadFields(l);
        insert l;
        l = [SELECT id, Token__c FROM Lead WHERE Id = :l.Id];
        return new PageReference('/LebensversicherungZwischenseite?token=' + l.Token__c);
    }

    public string getToken() {
        return ApexPages.currentPage().getParameters().get('token');
    }
}