objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>VH24 or VR24</description>
        <inlineHelpText>VH24 oder VR24</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Account Name)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AdWords_Campaign__c</fullName>
        <label>AdWords Campaign</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AdWords_Content__c</fullName>
        <label>AdWords Content</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AdWords_Medium__c</fullName>
        <label>AdWords Medium</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AdWords_Source__c</fullName>
        <label>AdWords Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AdWords_Term__c</fullName>
        <label>AdWords Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Kampagne</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Confirmed_Authorization__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Vollmacht bestätigt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Financing_Type__c</fullName>
        <label>Finanzierungsart</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Financing_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Form_Id__c</fullName>
        <label>Formular Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Has_Legal_Protection_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rechtsschutzversicherung vorhanden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <label>Referrer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Web form token</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <label>Unique Id</label>
        <length>62</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Type__c</fullName>
        <label>Fahrzeugtyp</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Lead Process</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
</CustomObject>

globalValueSets/Financing_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Leasing</fullName>
    </customValue>
    <customValue>
        <fullName>Finanzierung</fullName>
    </customValue>
    <customValue>
        <fullName>Eigenkapital</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Financing Types</masterLabel>
</GlobalValueSet>

classes/DieselLeadControllerTests.cls
@isTest
public class DieselLeadControllerTests {
    @isTest
    public static void TestPage1() {
        PageReference p = Page.Dieselskandal;
        Test.setCurrentPage(p);
        ApexPages.currentPage().getParameters().put('utm_Source',	'1');
        ApexPages.currentPage().getParameters().put('utm_Medium',	'2');
        ApexPages.currentPage().getParameters().put('utm_Campaign',	'3');
        ApexPages.currentPage().getParameters().put('utm_Term',		'4');
        ApexPages.currentPage().getParameters().put('utm_Content',	'5');
        ApexPages.currentPage().getParameters().put('UniqueId',		'6');
        ApexPages.currentPage().getParameters().put('FormularId',	'7');
        ApexPages.currentPage().getParameters().put('Kampagne',		'8');
        ApexPages.currentPage().getParameters().put('Referrer',		'9');
        DieselLeadController c = new DieselLeadController();

        c.legal_insurance = 'Ja';
        c.vehicleType = 'ada';
        c.FinancingType = 'Leasing';

        PageReference nextPage = c.createLead();
        List<Lead> leads = [
            SELECT Id, Has_Legal_Protection_Insurance__c, Vehicle_Type__c,
            Confirmed_Authorization__c, Account__c, Financing_Type__c,
            Company, FirstName, LastName, Token__c,
            AdWords_Source__c, AdWords_Medium__c, AdWords_Campaign__c, AdWords_Term__c, AdWords_Content__c,
            Unique_Id__c, Form_Id__c, Campaign__c, Referrer__c
            FROM Lead
        ];

        System.assertEquals(1, leads.size());
        Lead l = leads[0];

        System.assertEquals('WebformDG still Unknown', l.Company);
        System.assertEquals('WebformDG still Unknown', l.FirstName);
        System.assertEquals('WebformDG still Unknown', l.LastName);
        System.assertEquals('Leasing', l.Financing_Type__c);
        System.assertEquals('ada', l.Vehicle_Type__c);
        System.assertEquals(Accounts.VH24ID, l.Account__c);
        System.assertEquals(true, l.Has_Legal_Protection_Insurance__c);
        System.assertEquals('/DieselskandalZwischenseite?token=' + l.Token__c, nextPage.getUrl());
        System.assertEquals('1', l.AdWords_Source__c);
        System.assertEquals('2', l.AdWords_Medium__c);
        System.assertEquals('3', l.AdWords_Campaign__c);
        System.assertEquals('4', l.AdWords_Term__c);
        System.assertEquals('5', l.AdWords_Content__c);
        System.assertEquals('6', l.Unique_Id__c);
        System.assertEquals('7', l.Form_Id__c);
        System.assertEquals('8', l.Campaign__c);
        System.assertEquals('9', l.Referrer__c);
    }

    @isTest
    public static void TestLegalInsuranceOptions() {
        new DieselLeadController().getLegalInsuranceOptions();
    }

    @isTest
    public static void TestBrandOptions() {
        new DieselLeadController().getBrandOptions();
    }
    
    @isTest
    static void hackCoverage() {
        DieselLeadController.hackCoverage();
    }
}