objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>VH24 or VR24</description>
        <inlineHelpText>VH24 oder VR24</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Account Name)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AdWords_Campaign__c</fullName>
        <label>AdWords Campaign</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AdWords_Medium__c</fullName>
        <label>AdWords Medium</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AdWords_Source__c</fullName>
        <label>AdWords Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/API_Finanzen.cls
@RestResource(urlMapping='/vh/finanzen')
global class API_Finanzen extends API_Base {
    public class Input {
        public string sex;
        public string firstname;
        public string lastname;
        public string adresse;
        public string postalCode;
        public string city;
        public string dateOfBirth;
        public string email;
        public string phone;
        public integer occupationGroupId;
        public string occupationGroupName;
        public string leadtype;
        public integer leadid;
        // public string translated;
        public integer campaign;
        public string derivation;
        public integer tarif;
        public integer behandlung;
        public integer selbstbeteiligung;
        public integer zahnbehandlung;
        public string tagegeld_betrag;
    }

    @HttpPost
    global static void createLead() {
        Input i = (Input)loadRequest(Input.class);

        Lead l = new Lead(
            RecordTypeId = Leads.dkRtID,
            Account__c = Accounts.VH24ID,
            FirstName = i.firstname,
            LastName = i.lastname,
            Country = 'Deutschland',
            CountryCode = 'DE',
            Street = i.adresse,
            City = i.city,
            PostalCode = i.postalCode,
            Phone = i.phone,
            Email = i.email,
            Company = i.firstname + ' ' + i.lastname,
            AdWords_Medium__c = i.leadtype,
            AdWords_Campaign__c = i.derivation,
            Adwords_Source__c = 'Finanzen.de'
        );

        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true;
        dml.DuplicateRuleHeader.runAsCurrentUser = true;
        Database.SaveResult sr = Database.insert(l, dml);

        if (sr.isSuccess()) {
            System.debug('lead created');
        } else {
            string errors = '';
            for(Database.Error e : sr.getErrors()) {
                errors += e.getMessage();
            }

            throw new API_Exception('failed to create lead: ' + errors);
        }
    }
}