objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>VH24 or VR24</description>
        <inlineHelpText>VH24 oder VR24</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Account Name)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Lead Process</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <businessProcess>Lead Process</businessProcess>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lead Process</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <businessProcess>Finanzierung</businessProcess>
        <label>Finanzierung</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lebensversicherung</fullName>
        <active>true</active>
        <businessProcess>Lebensversicherung</businessProcess>
        <label>Lebensversicherung</label>
    </recordTypes>
</CustomObject>

classes/SendExampleCalcLead.cls
// Lead "Beispielrechnung versenden" Button
public class SendExampleCalcLead {
    private final Lead lead;

    public SendExampleCalcLead(ApexPages.StandardController stdCtl) {
        this.lead = [
            SELECT ID, RecordTypeId, Account__r.Id, Email
            FROM Lead
            WHERE ID = :stdCtl.getId()
        ];
    }

    public PageReference renderPage() {
        string url = page.sendMail.getUrl() + createUrl();
        System.debug('url: ' +  url);
        return new PageReference(url);
    }

    public EmailTemplates.name getEmailTemplateName() {
        boolean vh24 = Accounts.isVH24(this.lead.Account__r.Id);
        id rtid = this.lead.RecordTypeId;
        // Dieselskandal
        if (Leads.isDieselSkandal(rtId)) { // 0120Y000000W0CY
            if (vh24) { // 0010Y00000eCUS9
                return EmailTemplates.name.DieselskandalBackofficeExampleCalcLeadVh24; // 00X0Y000000m5bW
            }
            return EmailTemplates.name.DieselskandalBackofficeExampleCalcLeadVr24; // 00X0Y000000dk3U
        }
        // Finanzierung
        if (Leads.isFinanzierung(rtId)) {
            if (vh24) { // 0010Y00000eCUS9
                return EmailTemplates.name.FzBackofficeExampleCalcLeadVh24; // 00X1v000000SMwB
            }
            return EmailTemplates.name.FzBackofficeExampleCalcLeadVr24; // 00X1v000000SMwG
        }
        // Lebensversicherung
        if (vh24) { // 0010Y00000eCUS9
            return EmailTemplates.name.LvBackofficeExampleCalcLeadVh24; // 00X1v000000OTLI
        }
        return EmailTemplates.name.LvBackofficeExampleCalcLeadVr24; // 00X1v000000OTLN
    }

    private string getTpl() {
        return EmailTemplates.idOf(getEmailTemplateName());
    }

    private string createUrl() {
        return
            '?id=' + lead.Id +
            '&tpl=' + getTpl() +
            '&recipient=' + lead.Id +
            '&islead=true' +
            '&noprtatt=true' +
            '&hdl=Beispielrechnung versenden.';
    }
}

// /apex/SendMail?id={!Opportunity.Id}
// &tpl={!IF(Opportunity.RecordTypeId = '0120Y000000W0CY',IF(Opportunity.Account_Id__c = '0010Y00000eCUS9','00X0Y000000m5bW','00X0Y000000dk3U'),IF(Opportunity.RecordTypeId = '0120Y000000KnMH',IF(Opportunity.Account_Id__c = '0010Y00000eCUS9','00X1v000000SMwB','00X1v000000SMwG'),IF(Opportunity.Account_Id__c = '0010Y00000eCUS9','00X1v000000OTLI','00X1v000000OTLN')))}
// &recipient={!Opportunity.ContactId__c}
// &noprtatt=true
// &hdl="Beispielrechnung versenden."