objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Callcenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Callcenter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Confirmed_Terms_And_Conditions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AGB bestätigt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Reached__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Kunde erreicht</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_interaction_notes__c</fullName>
        <inlineHelpText>Dieses Feld zeigt nur die Notizen des letzten Telefonats.
Für alle Notizen bitte die History besuchen.</inlineHelpText>
        <label>Kurznotiz zum Telefonat</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Follow_up_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Follow-up Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Follow_up_Period__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Follow-up Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_follow_up_task__c</fullName>
        <description>Used for the automatic follow up task creation in the AGB process (Used in apex scheduler).</description>
        <label>Last follow up task</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

classes/TasksCreate.cls
global class TasksCreate implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(
            'SELECT Id, ' +
            'customer_Reached__c, ' +
            'Callcenter__c, ' +
            'Callcenter__r.ID, ' +
            'Callcenter__r.IsActive, ' +
            'customer_interaction_notes__c, ' +
            'Last_follow_up_task__c, ' +
            'Follow_up_Count__c, ' +
            'follow_Up_Period__c ' +
            'FROM Lead ' +
            'WHERE Confirmed_Terms_And_Conditions__c = false ' +
            'AND follow_up_Count__c > 1 AND follow_up_Count__c < 4 '
        );
    }

    global void execute(Database.BatchableContext BC, List<Lead> scope) {
        List<Task> ts = new List<Task>();
        List<Lead> updateLeads = new List<Lead>();
        for (Lead l : scope) {
            Integer delay = l.Customer_Reached__c ? 5 : 3;
            if (l.Last_follow_up_task__c > System.today().addDays(-delay)) {
                continue;
            }
            String subject = l.customer_Reached__c ? 'AGB/Kunde erreicht #' : 'AGB/Kunde nicht erreicht #';
            Task t = Tasks.build(
                subject + l.follow_up_Count__c,
                l.customer_interaction_notes__c,
                l,
                l.callcenter__r,
                l.follow_up_Period__c > 0 ? Date.today() + Integer.valueOf(l.follow_Up_Period__c) : Date.today(),
                true,	// no duplicates
                true // follow up l.follow_up_Count__c > 0
            );
            l.Follow_up_Count__c = l.Follow_up_Count__c + 1;
            updateLeads.add(l);
            if (t != null) {
                ts.add(t);
            }
        }
        update updateLeads;
        insert ts;
    }

    global void finish(Database.BatchableContext BC) {
    }
}