objects/Legal_Assignment_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Aktiv</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JC_Legal__c</fullName>
        <defaultValue>0.0</defaultValue>
        <label>Anwälte Jäger</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>JH_Legal__c</fullName>
        <defaultValue>0.0</defaultValue>
        <label>H. Jäger</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>JHeinrich_Legal__c</fullName>
        <defaultValue>0.0</defaultValue>
        <label>Heinrich Jäger</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Kainz_Legal__c</fullName>
        <defaultValue>0.0</defaultValue>
        <label>A. Kainz</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Krutisch_Legal__c</fullName>
        <defaultValue>0.0</defaultValue>
        <label>Dominic Krutisch</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Lachmair_Legal__c</fullName>
        <defaultValue>0.0</defaultValue>
        <label>Wilhelm Lachmair</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <label>Legal Account</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>VH24</fullName>
                    <default>true</default>
                    <label>VH24</label>
                </value>
                <value>
                    <fullName>VR24</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dieselskandal</fullName>
                    <default>true</default>
                    <label>Dieselskandal</label>
                </value>
                <value>
                    <fullName>Lebensversicherung</fullName>
                </value>
                <value>
                    <fullName>Finanzierung</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>todo</description>
    <label>Legal Assignment Setting</label>
    <pluralLabel>Legal Assignment Settings</pluralLabel>
</CustomObject>

classes/OpportunitiesLegalSettings.cls
public inherited sharing class OpportunitiesLegalSettings {
    public class SettingsException extends Exception {}

    public static List<OpportunitiesLegal.Config> CONFIGS;
    private static Integer MAX_SETTINGS;
    static {
        CONFIGS = new List<OpportunitiesLegal.Config>();
        MAX_SETTINGS = 6;
        if (Test.isRunningTest()) {
           return;
        }

        Legal_Assignment_Setting__mdt[] setts = [
            SELECT
            Legal_Account__c,
            Record_Type__c,
            JC_Legal__c,
            JH_Legal__c,
            JHeinrich_Legal__c,
            Kainz_Legal__c,
            Krutisch_Legal__c,
            Lachmair_Legal__c
            FROM Legal_Assignment_Setting__mdt  
            WHERE Is_Active__c = true
        ];
        if (setts.size() == 0) {
           throw new OpportunitiesLegalSettings.SettingsException('No settings found. Please create them in Setup -> Custom Metadata Types -> Legal Assignment Setting -> Manage Records');
        }
        if (setts.size() > MAX_SETTINGS) {
           throw new OpportunitiesLegalSettings.SettingsException('More than ' + MAX_SETTINGS + ' active settings found. Please set ' + MAX_SETTINGS + ' records as active in Setup -> Custom Metadata Types -> Legal Assignment Setting -> Manage Records');
        }
        if (setts.size() < MAX_SETTINGS) {
           throw new OpportunitiesLegalSettings.SettingsException('Less than ' + MAX_SETTINGS + ' active settings found. Please set ' + MAX_SETTINGS + ' records as active in Setup -> Custom Metadata Types -> Legal Assignment Setting -> Manage Records');
        }

        for (Legal_Assignment_Setting__mdt s : setts) {
            Map<string, decimal> cfg = new Map<string, decimal>();
            // TODO: replace it with hardcoded lawyer names
            cfg.put(Schema.getGlobalDescribe().get('Legal_Assignment_Setting__mdt').getDescribe().fields.getMap().get('JC_Legal__c').getDescribe().getLabel(),			s.JC_Legal__c * 0.01);
            cfg.put(Schema.getGlobalDescribe().get('Legal_Assignment_Setting__mdt').getDescribe().fields.getMap().get('JH_Legal__c').getDescribe().getLabel(),			s.JH_Legal__c * 0.01);
            cfg.put(Schema.getGlobalDescribe().get('Legal_Assignment_Setting__mdt').getDescribe().fields.getMap().get('JHeinrich_Legal__c').getDescribe().getLabel(),	s.JHeinrich_Legal__c * 0.01);
            cfg.put(Schema.getGlobalDescribe().get('Legal_Assignment_Setting__mdt').getDescribe().fields.getMap().get('Kainz_Legal__c').getDescribe().getLabel(),		s.Kainz_Legal__c * 0.01);
            cfg.put(Schema.getGlobalDescribe().get('Legal_Assignment_Setting__mdt').getDescribe().fields.getMap().get('Krutisch_Legal__c').getDescribe().getLabel(),	s.Krutisch_Legal__c * 0.01);
            cfg.put(Schema.getGlobalDescribe().get('Legal_Assignment_Setting__mdt').getDescribe().fields.getMap().get('Lachmair_Legal__c').getDescribe().getLabel(),	s.Lachmair_Legal__c * 0.01);

            OpportunitiesLegal.Config completeConf = new OpportunitiesLegal.Config(s.Record_Type__c, s.Legal_Account__c, cfg);
            CONFIGS.add(completeConf);
        }
    }
}