objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Callcenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for call center process parts.</description>
        <label>Callcenter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Callcenter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

classes/DidNotRecieveDocumentsTest.cls
@isTest
public class DidNotRecieveDocumentsTest {
    private static Opportunity createOpp(string accname, boolean isCallcenter, boolean isContact) {
        PageReference p = Page.DidNotRecieveDocuments;
        Test.setCurrentPage(p);

        User u = TestData.createUser();
        Account a = TestData.createAccount();
        a.name = accname;
        insert a;
        insert u;
        Opportunity o = TestData.createOpportunity(a.ID, 'On Hold');
        o.Account__c = a.ID;
        o.Backoffice__c = u.Id;
        insert o;
        Task t = Utilities.createTask('Foo task', 'foo desc', o, u, System.today(), false, false);
        t.Type = 'Q&A';
        insert t;
        if (isCallcenter == true) {
            o.Callcenter__c = u.Id;
            o.Callcenter__r = u;
        }
        if (isContact == true) {
            Contact c = new Contact(FirstName = 'foo', LastName = 'bar');
            insert c;
            o.Contact__c = c.Id;
        }
        return o;
    }

    @isTest
    private static void testVH24() {
        Opportunity o = createOpp('VH24', true, true);
        System.debug('testcallcenter: ' + o.Callcenter__r);
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        update o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        DidNotRecieveDocuments oe = new DidNotRecieveDocuments(sc);

        // Act
        oe.parDescription = 'Foo bar';
        PageReference pr = oe.renderPage();
    }

    @isTest
    private static void testVR24() {
        Opportunity o = createOpp('VR24', true, true);
        System.debug('testcallcenter: ' + o.Callcenter__r);
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        update o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        DidNotRecieveDocuments oe = new DidNotRecieveDocuments(sc);

        // Act
        oe.parDescription = 'Foo bar';
        PageReference pr = oe.renderPage();
    }

    @isTest
    private static void testNoCallcenter() {
        Opportunity o = createOpp('VH24', false, false);
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        update o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        DidNotRecieveDocuments oe = new DidNotRecieveDocuments(sc);

        // Act
        oe.parDescription = 'Foo bar';
        PageReference pr = oe.renderPage();
    }

    @isTest
    private static void testNoContact() {
        Opportunity o = createOpp('VH24', true, false);
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        update o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        DidNotRecieveDocuments oe = new DidNotRecieveDocuments(sc);

        // Act
        oe.parDescription = 'Foo bar';
        PageReference pr = oe.renderPage();
    }
}