objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Token__c</fullName>
        <label>Web form token</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Revocation_Date__c</fullName>
        <label>Datum Abtretungswiderruf</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Musterfeststellungsklagen</relationshipLabel>
        <relationshipName>Test_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Test_Case_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Web Form Token</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>Musterfeststellungsklage</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Musterfeststellungsklagen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Test_Case_Statuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Finished</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>Test Case Statuses</masterLabel>
</GlobalValueSet>

classes/AbtretungslinkControllerTest.cls
@isTest
public class AbtretungslinkControllerTest {
    @isTest
    public static void TestNotFound() {
        ApexPages.currentPage().getParameters().put('token', '123');
        AbtretungslinkController c = new AbtretungslinkController();
        c.init();
    }

    @isTest
    public static void TestSetDate() {
        Account a = TestData.createAccount();
        insert a;
        Opportunity o = TestData.createOpportunity(a.Id, 'On Hold');
        insert o;
        Test_Case__c tc = new Test_Case__c(
            Opportunity__c = o.Id,
            Status__c = 'Draft'
        );
        insert tc;
        tc = [SELECT Id, Token__c FROM Test_Case__c WHERE Id = :tc.Id];

        ApexPages.currentPage().getParameters().put('token', tc.Token__c);
        AbtretungslinkController c = new AbtretungslinkController();
        c.init();

        tc = [SELECT ID, Assignment_Revocation_Date__c FROM Test_Case__c WHERE Id = :tc.Id];
        Datetime tcDate = tc.Assignment_Revocation_Date__c;
        Datetime nowDate = Datetime.now();
        System.assertEquals(nowDate.year(), tcDate.year());
        System.assertEquals(nowDate.month(), tcDate.month());
        System.assertEquals(nowDate.day(), tcDate.day());
        System.assertEquals(nowDate.hour(), tcDate.hour());
    }
}