objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SendSwornStatement.cls
// Anfrage "Eidesstattliche Erklärung" Button
// Opportunity "Eidesstattliche Erklärung" Button
public class SendSwornStatement {
    private final Opportunity opp;
    public boolean errorContact {get; set;}

    public SendSwornStatement(ApexPages.StandardController stdCtl) {
        errorContact = false;
        this.opp = [
            SELECT ID,
            AccountId,
            Contact__c,
            Legal_Account__c,
            Account_Id__c,
            RecordTypeId,
            Account__c
            FROM Opportunity
            WHERE ID = :stdCtl.getId()
        ];
    }

    public PageReference renderPage() {
        if (opp.Contact__c == null) {
            errorContact = true;
            return null;
        }

        string url = page.sendMail.getUrl() + createUrl();
        System.debug('url: ' +  url);
        return new PageReference(url);
    }

    private string getTpl() {
        if (Opportunities.isDieselSkandal(this.opp.RecordTypeId)) { // 0120Y000000W0CY
            if (Accounts.isVH24(this.opp.Legal_Account__c)) { // 0010Y000011MYHW
                return EmailTemplates.idOf(EmailTemplates.name.DieselskandalBackofficeSwornStatementJaeger);  // 00X0Y000001awe3
            }
            if (Accounts.isVH24(this.opp.Account__c)) { // 0010Y00000eCUS9
                return EmailTemplates.idOf(EmailTemplates.name.DieselskandalBackofficeSwornStatementVh24);  // 00X0Y000000mC6Z
            }
            return EmailTemplates.idOf(EmailTemplates.name.DieselskandalBackofficeSwornStatementVr24);  // 00X0Y000000mC6e
        }
        if (Accounts.isVH24(this.opp.Legal_Account__c)) { // 0010Y000011MYHW
            return EmailTemplates.idOf(EmailTemplates.name.FzBackofficeSwornStatementJaeger);  // 00X1v000000SMxE
        }
        if (Accounts.isVH24(this.opp.Account__c)) { // 0010Y00000eCUS9
            return EmailTemplates.idOf(EmailTemplates.name.FzBackofficeSwornStatementVh24);  // 00X1v000000SMvw
        }
        return EmailTemplates.idOf(EmailTemplates.name.FzBackofficeSwornStatementVr24);  // 00X1v000000SMw1
    }

    private string createUrl() {
        return
            '?id=' + opp.Id +
            '&tpl=' + getTpl() +
            '&recipient=' + opp.Contact__c +
            '&noprtatt=true' +
            '&hdl=Eidesstattliche Erklärung anfordern.' +
            '&tplatt=true' + 
            '&eidesstattlicheversicherung=true';
    }
}

// /apex/SendMail?id={!Opportunity.Id}
// &tpl={!IF(Opportunity.RecordTypeId = '0120Y000000W0CY',IF(Opportunity.Legal_AccountId__c = '0010Y000011MYHW','00X0Y000001awe3',IF(Opportunity.Account__c = '0010Y00000eCUS9','00X0Y000000mC6Z','00X0Y000000mC6e')),IF(Opportunity.Legal_AccountId__c = '0010Y000011MYHW','00X1v000000SMxE',IF(Opportunity.Account__c = '0010Y00000eCUS9','00X1v000000SMvw','00X1v000000SMw1')))}
// &recipient={!Opportunity.ContactId__c}
// &noprtatt=true
// &hdl="Eidesstattliche Erklärung anfordern."
// &tplatt=true