objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MFK__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MFK</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Musterfeststellungsklagen</relationshipLabel>
        <relationshipName>Test_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Musterfeststellungsklage</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Musterfeststellungsklagen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OppCreateTestCase.cls
// Opportunity "Übergabe zu MFK" Button
public class OppCreateTestCase {
    private final Opportunity opp;

    public OppCreateTestCase(ApexPages.StandardController stdCtl) {
        this.opp = [
            SELECT Id, StageName
            FROM Opportunity
            WHERE ID = :stdCtl.getId()
        ];
    }

    public PageReference renderPage() {
        Savepoint sp = Database.setSavepoint();
        this.opp.MFK__c = true;
        update this.opp;
        if (this.opp.StageName != 'Claim') {
            this.opp.StageName = 'Claim';
            string err = ValidationCatch.updateObj(this.opp, sp);
            if (err != '') {
                return Errors.page(err);
            }
        }
        Test_Case__c testCase = new Test_Case__c(
            Opportunity__c = this.opp.Id
        );
        insert testCase;
        return new PageReference('/' + this.opp.Id);
    }
}