objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>VH24 oder VR24.</inlineHelpText>
        <label>Unternehmen</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
            <errorMessage>Das Unternehmen muss VH24, VR24, Testkunde, Test KT oder Test sein.</errorMessage>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VH24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>VR24</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>testkunde</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test KT</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Martin Test Hahn Test</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>Klaus Schreimel, Volkswagen AG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Unternehmen)</relationshipLabel>
        <relationshipName>Opportunities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <defaultValue>"Online"</defaultValue>
        <label>Vertriebstyp</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sales_Types</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

globalValueSets/Sales_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
        <default>true</default>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <masterLabel>Sales Types</masterLabel>
</GlobalValueSet>

classes/FinishedLegalCheckTest.cls
@isTest
public class FinishedLegalCheckTest {
    private static Opportunity createOpp(string accname, string salestype) {
        PageReference p = Page.FinishedLegalCheck;
        Test.setCurrentPage(p);

        Account a = TestData.createAccount();
        a.name = accname;
        insert a;
        Opportunity o = TestData.createOpportunity(a.ID, 'On Hold');
        o.Account__c = a.ID;
        o.Sales_Type__c = salestype;
        return o;
    }

    @isTest
    private static void testCreateTask() {
        Opportunity o = createOpp('VR24', 'Online');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        insert o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        FinishedLegalCheck oe = new FinishedLegalCheck(sc);

		List<Task> ts = [SELECT ID FROM Task WHERE Subject = 'Potential prüfen'];
        System.assertEquals(0, ts.size());

        PageReference pr = oe.renderPage();

        ts = [SELECT ID FROM Task WHERE Subject = 'Potential prüfen'];
        System.assertEquals(1, ts.size());
    }

    @isTest
    private static void testVH24() {
        Opportunity o = createOpp('VH24', 'Online');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        insert o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        FinishedLegalCheck oe = new FinishedLegalCheck(sc);

        // Act
        PageReference pr = oe.renderPage();
    }

    @isTest
    private static void testVH24Partner() {
        Opportunity o = createOpp('VH24', 'Partner');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        insert o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        FinishedLegalCheck oe = new FinishedLegalCheck(sc);

        // Act
        PageReference pr = oe.renderPage();
    }
    
    @isTest
    private static void testVR24() {
        Opportunity o = createOpp('VR24', 'Online');
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        insert o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        FinishedLegalCheck oe = new FinishedLegalCheck(sc);

        // Act
        PageReference pr = oe.renderPage();
    }
}