objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Auftragstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assignment_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auto_Follow_up_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Anzahl Auto-Follow-ups</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Kreditinstitut</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Kreditinstitut)</relationshipLabel>
        <relationshipName>Opportunities_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Contract_Numbe__c</fullName>
        <label>Kreditvertragsnummer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Engine_Type__c</fullName>
        <label>Motortyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Engine_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Financing_Contract_Date__c</fullName>
        <label>Finanzierungsvertragsdatum</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Finanzierungsvertrag_Gesamtbetrag__c</fullName>
        <label>Finanzierungsvertrag Gesamtbetrag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Has_Legal_Protection_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rechtsschutzversicherung vorhanden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legal_Protection_Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rechtsschutzversicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Rechtsschutzversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Rechtsschutzversicherung)</relationshipLabel>
        <relationshipName>Opportunities_Legal_Protection_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Rate__c</fullName>
        <label>Monatliche Raten</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Paid_Installments__c</fullName>
        <label>Bisher geleistete Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Aktenzeichen</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <defaultValue>"Online"</defaultValue>
        <label>Vertriebstyp</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sales_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sent_Mail_Flag_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent Mail Flag 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fahrzeughersteller</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Fahrzeughersteller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Fahrzeughersteller)</relationshipLabel>
        <relationshipName>Opportunities_Fahrzeughersteller</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Dieselskandal</fullName>
        <active>true</active>
        <businessProcess>Dieselskandal</businessProcess>
        <label>Dieselskandal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <businessProcess>Finanzierung</businessProcess>
        <label>Finanzierung</label>
    </recordTypes>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Bank__c</fullName>
        <label>Bank</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Assignment_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Share</fullName>
    </customValue>
    <customValue>
        <fullName>Direkt</fullName>
    </customValue>
    <customValue>
        <fullName>50%</fullName>
        <isActive>false</isActive>
        <label>50%</label>
    </customValue>
    <customValue>
        <fullName>RSV 20%</fullName>
        <isActive>false</isActive>
        <label>RSV 20%</label>
    </customValue>
    <masterLabel>Assignment Types</masterLabel>
</GlobalValueSet>

globalValueSets/Engine_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>OM640</fullName>
    </customValue>
    <customValue>
        <fullName>OM642</fullName>
    </customValue>
    <customValue>
        <fullName>OM 607</fullName>
    </customValue>
    <customValue>
        <fullName>OM651</fullName>
    </customValue>
    <customValue>
        <fullName>3.0</fullName>
    </customValue>
    <customValue>
        <fullName>4.2</fullName>
    </customValue>
    <customValue>
        <fullName>EA189</fullName>
    </customValue>
    <customValue>
        <fullName>EA288</fullName>
    </customValue>
    <customValue>
        <fullName>EA189 ohne Rückruf</fullName>
    </customValue>
    <customValue>
        <fullName>ENS</fullName>
    </customValue>
    <customValue>
        <fullName>EA897</fullName>
    </customValue>
    <customValue>
        <fullName>OM622</fullName>
    </customValue>
    <customValue>
        <fullName>Anderer Motortyp</fullName>
    </customValue>
    <customValue>
        <fullName>OM626</fullName>
    </customValue>
    <customValue>
        <fullName>OM 646.811</fullName>
    </customValue>
    <customValue>
        <fullName>OM 646.812</fullName>
    </customValue>
    <masterLabel>Engine Types</masterLabel>
</GlobalValueSet>

globalValueSets/Sales_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
        <default>true</default>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <masterLabel>Sales Types</masterLabel>
</GlobalValueSet>

classes/SetOppRecordTypeTest.cls
@isTest
public class SetOppRecordTypeTest {
    private static Opportunity createOpp() {
        PageReference p = Page.SetOppRecordType;
        Test.setCurrentPage(p);

        Account a = TestData.createAccount();
        a.name = 'Bla';
        insert a;
        Account vehicleBrand = new Account(
            Name = 'TestVehicleBrand',
            Type = 'Fahrzeughersteller'
        );
        insert vehicleBrand;
        Opportunity o = new Opportunity(
            Name = 'TestOpportunity',
            AccountId = a.Id,
            CloseDate = System.today(),
            StageName = 'On Hold',
            Sent_Mail_Flag_1__c = true,
            Sent_Mail_Flag_2__c = true,
            Assignment_Type__c = 'RSV',
            Has_Legal_Protection_Insurance__c = true,
            Auto_Follow_up_Count__c = 0,
            Sales_Type__c = 'Online',
            Vehicle_Brand__c = vehicleBrand.Id
        );
        return o;
    }

    @isTest
    private static void testErrorFinanzierung() {
        Opportunity o = createOpp();
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Finanzierung' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        User u = TestData.createUser();
        insert u;
        Account a = TestData.createAccount();
        // a.Type = 'Rechtsschutzversicherung';
        insert a;
        o.Backoffice__c = u.Id;
        insert o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        SetOppRecordType oe = new SetOppRecordType(sc);

        // Act
        PageReference pr = oe.renderPage();

        System.debug('url: ' + pr.getUrl());
        System.assertEquals(true, pr.getUrl().contains('Finanzierung'));
    }

    @isTest
    private static void testErrorEngine() {
        Opportunity o = createOpp();
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        o.Engine_Type__c = 'EA189';
        o.Assignment_Type__c = 'Direkt'; // 'Share';
        User u = TestData.createUser();
        insert u;
        Account a = TestData.createAccount();
        // a.Type = 'Rechtsschutzversicherung';
        insert a;
        o.Backoffice__c = u.Id;
        o.Has_Legal_Protection_Insurance__c = false;
        // o.Legal_Protection_Insurance__c = a.Id;
        o.Financing_Contract_Date__c = System.today();
        o.Bank__c = a.Id;
        o.Finanzierungsvertrag_Gesamtbetrag__c = 2;
        o.Paid_Installments__c = 2;
        o.Monthly_Rate__c = 2;
        o.Credit_Contract_Numbe__c = '4242';
        insert o;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        SetOppRecordType oe = new SetOppRecordType(sc);

        // Act
        PageReference pr = oe.renderPage();

        System.debug('url: ' + pr.getUrl());
        System.assertEquals(true, pr.getUrl().contains('Anfragen+ohne+Rechtsschutzversicherung+und+Motortyp+EA189'));
    }

    @isTest
    private static void testErrorBackoffice() {
        Opportunity o = createOpp();
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert a;
        o.Legal_Protection_Insurance__c = a.Id;
        o.Financing_Contract_Date__c = System.today();
        o.Bank__c = a.Id;
        o.Finanzierungsvertrag_Gesamtbetrag__c = 2;
        o.Paid_Installments__c = 2;
        o.Monthly_Rate__c = 2;
        o.Credit_Contract_Numbe__c = '4242';
        insert o;
        Id oppID = o.Id;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        SetOppRecordType oe = new SetOppRecordType(sc);

        // Act
        PageReference pr = oe.renderPage();

        System.assertEquals(true, pr.getUrl().contains('Backoffice'));
    }

    /*
    @isTest
    private static void testErrorProtInsurance() {
        Opportunity o = createOpp();
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert a;
        User u = TestData.createUser();
        insert u;
        o.Backoffice__c = u.Id;
        o.Financing_Contract_Date__c = System.today();
        o.Bank__c = a.Id;
        o.Finanzierungsvertrag_Gesamtbetrag__c = 2;
        o.Paid_Installments__c = 2;
        o.Monthly_Rate__c = 2;
        o.Credit_Contract_Numbe__c = '4242';
        insert o;
        Id oppID = o.Id;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        SetOppRecordType oe = new SetOppRecordType(sc);

        // Act
        PageReference pr = oe.renderPage();

        System.assertEquals(true, pr.getUrl().contains('Rechtsschutzversicherung'));
    }
	*/
    /*
    @isTest
    private static void testErrorBank() {
        Opportunity o = createOpp();
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert a;
        User u = TestData.createUser();
        insert u;
        o.Backoffice__c = u.Id;
        o.Legal_Protection_Insurance__c = a.Id;
        o.Financing_Contract_Date__c = System.today();
        o.Finanzierungsvertrag_Gesamtbetrag__c = 2;
        o.Paid_Installments__c = 2;
        o.Monthly_Rate__c = 2;
        o.Credit_Contract_Numbe__c = '4242';
        insert o;
        Id oppID = o.Id;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        SetOppRecordType oe = new SetOppRecordType(sc);

        // Act
        PageReference pr = oe.renderPage();

        System.assertEquals(true, pr.getUrl().contains('Kreditinstitut'));
    }
	*/
    /*
    @isTest
    private static void testErrorConDate() {
        Opportunity o = createOpp();
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert a;
        User u = TestData.createUser();
        insert u;
        o.Backoffice__c = u.Id;
        o.Legal_Protection_Insurance__c = a.Id;
        o.Bank__c = a.Id;
        o.Finanzierungsvertrag_Gesamtbetrag__c = 2;
        o.Paid_Installments__c = 2;
        o.Monthly_Rate__c = 2;
        o.Credit_Contract_Numbe__c = '4242';
        insert o;
        Id oppID = o.Id;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        SetOppRecordType oe = new SetOppRecordType(sc);

        // Act
        PageReference pr = oe.renderPage();

        System.assertEquals(true, pr.getUrl().contains('Finanzierungsvertragsdatum'));
    }
	*/
    /*
    @isTest
    private static void testErrorFianceTotal() {
        Opportunity o = createOpp();
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert a;
        User u = TestData.createUser();
        insert u;
        o.Backoffice__c = u.Id;
        o.Legal_Protection_Insurance__c = a.Id;
        o.Financing_Contract_Date__c = System.today();
        o.Bank__c = a.Id;
        o.Paid_Installments__c = 2;
        o.Monthly_Rate__c = 2;
        o.Credit_Contract_Numbe__c = '4242';
        insert o;
        Id oppID = o.Id;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        SetOppRecordType oe = new SetOppRecordType(sc);

        // Act
        PageReference pr = oe.renderPage();

        System.assertEquals(true, pr.getUrl().contains('Finanzierungsvertrag+Gesamtbetrag'));
    }
	*/
    /*
    @isTest
    private static void testErrorPaidInstall() {
        Opportunity o = createOpp();
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert a;
        User u = TestData.createUser();
        insert u;
        o.Backoffice__c = u.Id;
        o.Legal_Protection_Insurance__c = a.Id;
        o.Financing_Contract_Date__c = System.today();
        o.Bank__c = a.Id;
        o.Finanzierungsvertrag_Gesamtbetrag__c = 2;
        o.Monthly_Rate__c = 2;
        o.Credit_Contract_Numbe__c = '4242';
        insert o;
        Id oppID = o.Id;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        SetOppRecordType oe = new SetOppRecordType(sc);

        // Act
        PageReference pr = oe.renderPage();

        System.assertEquals(true, pr.getUrl().contains('Bisher+geleistete+Rate'));
    }
	*/
    /*
    @isTest
    private static void testErrorMonthlyRate() {
        Opportunity o = createOpp();
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert a;
        User u = TestData.createUser();
        insert u;
        o.Backoffice__c = u.Id;
        o.Legal_Protection_Insurance__c = a.Id;
        o.Financing_Contract_Date__c = System.today();
        o.Bank__c = a.Id;
        o.Finanzierungsvertrag_Gesamtbetrag__c = 2;
        o.Paid_Installments__c = 2;
        o.Credit_Contract_Numbe__c = '4242';
        insert o;
        Id oppID = o.Id;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        SetOppRecordType oe = new SetOppRecordType(sc);

        // Act
        PageReference pr = oe.renderPage();

        System.assertEquals(true, pr.getUrl().contains('Monatliche+Raten'));
    }
	*/
    /*
    @isTest
    private static void testErrorCreditContract() {
        Opportunity o = createOpp();
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert a;
        User u = TestData.createUser();
        insert u;
        o.Backoffice__c = u.Id;
        o.Legal_Protection_Insurance__c = a.Id;
        o.Financing_Contract_Date__c = System.today();
        o.Bank__c = a.Id;
        o.Finanzierungsvertrag_Gesamtbetrag__c = 2;
        o.Paid_Installments__c = 2;
        o.Monthly_Rate__c = 2;
        insert o;
        Id oppID = o.Id;

        Apexpages.StandardController sc = new Apexpages.standardController(o);
        SetOppRecordType oe = new SetOppRecordType(sc);

        // Act
        PageReference pr = oe.renderPage();

        System.assertEquals(true, pr.getUrl().contains('Kreditvertragsnummer'));
    }
	*/
    @isTest
    private static void testErrorReference() {
        Opportunity o = createOpp();
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert a;
        User u = TestData.createUser();
        insert u;
        o.Backoffice__c = u.Id;
        o.Legal_Protection_Insurance__c = a.Id;
        o.Financing_Contract_Date__c = System.today();
        o.Bank__c = a.Id;
        o.Finanzierungsvertrag_Gesamtbetrag__c = 2;
        o.Paid_Installments__c = 2;
        o.Monthly_Rate__c = 2;
        o.Credit_Contract_Numbe__c = 'gha9wd89w';
        insert o;
        Id oppID = o.Id;
        Apexpages.StandardController sc = new Apexpages.standardController(o);
        SetOppRecordType oe = new SetOppRecordType(sc);

        // Act
        PageReference pr = oe.renderPage();

        System.assertEquals(true, pr.getUrl().contains('Aktenzeichen'));
    }

    @isTest
    private static void testSuccess() {
	TriggerConfiguration.allInactive = true;
        Opportunity o = createOpp();
        RecordType rt = [SELECT ID FROM RecordType WHERE Name='Dieselskandal' AND sObjectType = 'Opportunity'];
        o.recordTypeId = rt.ID;
        Account a = TestData.createAccount();
        a.Type = 'Rechtsschutzversicherung';
        insert a;
        User u = TestData.createUser();
        insert u;
        o.Backoffice__c = u.Id;
        o.Legal_Protection_Insurance__c = a.Id;
        o.Financing_Contract_Date__c = System.today();
        o.Bank__c = a.Id;
        o.Finanzierungsvertrag_Gesamtbetrag__c = 2;
        o.Paid_Installments__c = 2;
        o.Monthly_Rate__c = 2;
        o.Credit_Contract_Numbe__c = '4242';
        o.Reference__c = 'foo';
        insert o;
	TriggerConfiguration.allInactive = false;
        Id oppID = o.Id;
		System.debug('Id of recently inserted opp is ' + oppID);
        Apexpages.StandardController sc = new Apexpages.standardController(o);
        SetOppRecordType oe = new SetOppRecordType(sc);

        // Act
        PageReference pr = oe.renderPage();

        Opportunity res = [SELECT Id, StageName FROM Opportunity WHERE Id = :oppID];
        System.assertEquals('Claim', res.StageName);
    }
}