objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Auftragstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assignment_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Kreditinstitut</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Kreditinstitut)</relationshipLabel>
        <relationshipName>Opportunities_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Contract_Numbe__c</fullName>
        <label>Kreditvertragsnummer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Engine_Type__c</fullName>
        <label>Motortyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Engine_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Financing_Contract_Date__c</fullName>
        <label>Finanzierungsvertragsdatum</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Finanzierungsvertrag_Gesamtbetrag__c</fullName>
        <label>Finanzierungsvertrag Gesamtbetrag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Legal_Protection_Insurance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rechtsschutzversicherung</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Rechtsschutzversicherung</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Rechtsschutzversicherung)</relationshipLabel>
        <relationshipName>Opportunities_Legal_Protection_Insurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Rate__c</fullName>
        <label>Monatliche Raten</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Paid_Installments__c</fullName>
        <label>Bisher geleistete Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Aktenzeichen</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Finanzierung</fullName>
        <active>true</active>
        <businessProcess>Finanzierung</businessProcess>
        <label>Finanzierung</label>
    </recordTypes>
</CustomObject>

globalValueSets/Assignment_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Share</fullName>
    </customValue>
    <customValue>
        <fullName>Direkt</fullName>
    </customValue>
    <customValue>
        <fullName>50%</fullName>
        <isActive>false</isActive>
        <label>50%</label>
    </customValue>
    <customValue>
        <fullName>RSV 20%</fullName>
        <isActive>false</isActive>
        <label>RSV 20%</label>
    </customValue>
    <masterLabel>Assignment Types</masterLabel>
</GlobalValueSet>

globalValueSets/Engine_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>OM640</fullName>
    </customValue>
    <customValue>
        <fullName>OM642</fullName>
    </customValue>
    <customValue>
        <fullName>OM 607</fullName>
    </customValue>
    <customValue>
        <fullName>OM651</fullName>
    </customValue>
    <customValue>
        <fullName>3.0</fullName>
    </customValue>
    <customValue>
        <fullName>4.2</fullName>
    </customValue>
    <customValue>
        <fullName>EA189</fullName>
    </customValue>
    <customValue>
        <fullName>EA288</fullName>
    </customValue>
    <customValue>
        <fullName>EA189 ohne Rückruf</fullName>
    </customValue>
    <customValue>
        <fullName>ENS</fullName>
    </customValue>
    <customValue>
        <fullName>EA897</fullName>
    </customValue>
    <customValue>
        <fullName>OM622</fullName>
    </customValue>
    <customValue>
        <fullName>Anderer Motortyp</fullName>
    </customValue>
    <customValue>
        <fullName>OM626</fullName>
    </customValue>
    <customValue>
        <fullName>OM 646.811</fullName>
    </customValue>
    <customValue>
        <fullName>OM 646.812</fullName>
    </customValue>
    <masterLabel>Engine Types</masterLabel>
</GlobalValueSet>

classes/SetOppRecordType.cls
// Opportunity "Übergabe zu Finanzierung" Button
public class SetOppRecordType {
    private final Opportunity opp;

    public SetOppRecordType(ApexPages.StandardController stdCtl) {
        this.opp = [
            SELECT
            	Id,
            	RecordTypeId,
            	Assignment_Type__c,
            	Engine_Type__c,
            	Backoffice__c,
            	Legal_Protection_Insurance__c,
            	Bank__c, Financing_Contract_Date__c,
            	Finanzierungsvertrag_Gesamtbetrag__c,
            	Paid_Installments__c,
            	Monthly_Rate__c,
            	Credit_Contract_Numbe__c,
            	Reference__c
            FROM Opportunity
            WHERE Id = :stdCtl.getId()
        ];
    }

    public PageReference renderPage() {
		PageReference pageRef;

		// Set RecordType
		if (Opportunities.isFinanzierung(this.opp.RecordTypeId)) {
            return Errors.page('Die Anfrage darf nicht vom RecordType Finanzierung sein.');
        }

        if (Opportunities.isDieselSkandal(this.opp.RecordTypeId) && (this.opp.Assignment_Type__c != 'RSV') && (this.opp.Engine_Type__c == 'EA189')) {
            String errorSubject = 'Fehler bei Übergabe des Prozesses.';
            String errorMessage = 'Anfragen ohne Rechtsschutzversicherung und Motortyp EA189 können nicht an Anwalt oder Finanzierungsprozess übergeben werden.';
            // pageRef = new PageReference('/apex/errorpage?errorSubject=' + errorSubject + '&errorMessage=' + errorMessage);
            pageRef = Errors.page(errorSubject, errorMessage);
        } else if (this.opp.Backoffice__c == null) {
            pageRef = Errors.page('Fehler bei Übergabe des Prozesses.', 'Bitte tragen Sie einen Backoffice Mitarbeiter ein.');
        } /* else if (this.opp.Legal_Protection_Insurance__c == null) {
            pageRef = Errors.page('Fehler bei Übergabe des Prozesses.', 'Bitte wählen Sie eine Rechtsschutzversicherung aus.');
        } else if (this.opp.Bank__c == null) {
            pageRef = Errors.page('Benötigtes Feld', 'Bitte tragen Sie einen Wert in das Kreditinstitut Feld ein.');
        } else if (this.opp.Financing_Contract_Date__c == null) {
            pageRef = Errors.page('Benötigtes Feld', 'Bitte tragen Sie einen Wert in das Finanzierungsvertragsdatum Feld ein.');
        } else if (this.opp.Finanzierungsvertrag_Gesamtbetrag__c == null) {
            pageRef = Errors.page('Benötigtes Feld', 'Bitte tragen Sie einen Wert in das Finanzierungsvertrag Gesamtbetrag Feld ein.');
        } else if (this.opp.Paid_Installments__c == null) {
            pageRef = Errors.page('Benötigtes Feld', 'Bitte tragen Sie einen Wert in das Bisher geleistete Rate Feld ein.');
        } else if (this.opp.Monthly_Rate__c == null) {
            pageRef = Errors.page('Benötigtes Feld', 'Bitte tragen Sie einen Wert in das Monatliche Raten Feld ein.');
        } else if (this.opp.Credit_Contract_Numbe__c == null) {
            pageRef = Errors.page('Benötigtes Feld', 'Bitte tragen Sie einen Wert in das Kreditvertragsnummer Feld ein.');
        } */else if (this.opp.Reference__c == null) {
            pageRef = Errors.page('Benötigtes Feld', 'Bitte tragen Sie einen Wert in das Aktenzeichen Feld ein.');
        } else {
            //System.debug('Id of recently updated opp is ' + opp.Id);
            this.opp.StageName = 'Claim';
            this.opp.RecordTypeId = Opportunities.finanzierungRecordType();
            //System.debug('Id of recordtypeID is ' + Opportunities.finanzierungRecordType());
            this.opp.Legal__c = Users.JCLegal(); // 0050Y000004hLE3
         	update this.opp;
            pageRef = Page.SuccessPage;
        }


		// Return page reference
		pageRef.setRedirect(true);
		return pageRef;
    }
}