objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lawsuit_Type__c</fullName>
        <label>Klagemodell</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Antragsmodell</fullName>
                </value>
                <value>
                    <fullName>Policenmodell</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <defaultValue>"Online"</defaultValue>
        <label>Vertriebstyp</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sales_Types</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <fields>
        <fullName>Email</fullName>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <label>Email</label>
    </recordTypes>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Sales_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
        <default>true</default>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <masterLabel>Sales Types</masterLabel>
</GlobalValueSet>

classes/FinishedLegalCheck.cls
public class FinishedLegalCheck {
    private final Opportunity opp;
    public Opportunity parOpportunity {get; set;}

    public FinishedLegalCheck(ApexPages.StandardController stdCtl) {
        parOpportunity = new Opportunity();
        this.opp = [
            SELECT ID, RecordTypeID, Sales_Type__c, Account_Id__c, Contact__c, Backoffice__c, Backoffice__r.isActive, (SELECT ID, Status, Subject, IsClosed FROM Tasks)
            FROM Opportunity
            WHERE ID = :stdCtl.getId()
        ];
    }

    public PageReference renderPage() {
        PageReference pageRef;
		
        if (!Opportunities.isLebensversicherung(this.opp.RecordTypeId)) {
        	// Send mail if not LV
            Id templateId;
            Id userId;
            if (Accounts.isVH24(this.opp.Account_Id__c)) { // 0010Y00000eCUS9
                // VH24
                templateId = EmailTemplates.idOf(EmailTemplates.name.LvBackofficeFinishedLegalCheckVh24); // 00X0Y000000m4um
                if (this.opp.Sales_Type__c == 'Online') {
                    // Online
                    userId = this.opp.Backoffice__c;
                } else {
                    //Partner
                    userId = Users.vh24Lv(); // 0050Y000003848T
                }
            } else {
                // VR24
                templateId = EmailTemplates.idOf(EmailTemplates.name.LvBackofficeFinishedLegalCheckVr24); // 00X0Y000000dmum
                userId = this.opp.Backoffice__c;
            }
    
            EmailUtilities emailUtilities = new EmailUtilities(this.opp.Id, this.opp.Contact__c, templateId, userId);
            emailUtilities.noAttachment = true;
            String result = emailUtilities.send();
            System.debug('Sent automatic mail with result: ' + result);   
        } else {
            Logger.debug('FinishedLegalCheck :: renderPage :: is LV. No email sent');
        }

        // Close task
        update Tasks.markAsClosed('Juristische Prüfung', this.opp);

        // Update opportunity
        this.opp.Lawsuit_Type__c = parOpportunity.Lawsuit_Type__c;
        update this.opp;

        // Create task
        User user = [SELECT Id, isActive FROM User WHERE Id = :Users.potentialCheck() ]; // Martin Braun
        // Task task = Tasks.build('Potential prüfen', null, this.opp, user, System.today(), true, false);
        Task task = Tasks.build('Potential prüfen', null, this.opp, user, System.today(), true, false, this.opp.ID);

        if (task != null) {
            insert task;
        }

        return new PageReference('/' + this.opp.ID);
    }
}