objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Aktenzeichen</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tag__c</fullName>
        <externalId>true</externalId>
        <label>Tag</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BatchSetTag.cls
global class BatchSetTag implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        // collect the batches of records or objects to be passed to execute
        String query = 'SELECT Id, Reference__c FROM Opportunity WHERE Tag__c = null';
        return Database.getQueryLocator(query);
    }
    
    // Go through all revenue schedules and update the closing priority based on the Opportunity Info.
    global void execute(Database.BatchableContext BC, List<Opportunity> opps) {  
        
        For(Opportunity o : opps) {
            o.Tag__c = o.Reference__c.substringBeforeLast('-');
        }
        
        update opps;
    }   
    
    global void finish(Database.BatchableContext BC) {
        // execute any post-processing operations
    }
}