objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Auftragstyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assignment_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Backoffice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person in charge for backoffice process parts.</description>
        <label>Backoffice</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Backoffice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Mileage__c</fullName>
        <label>Aktueller Kilometerstand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Engine_Type__c</fullName>
        <label>Motortyp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Engine_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expected_Mileage__c</fullName>
        <defaultValue>500000</defaultValue>
        <label>Voraussichtliche Kilometer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Financing_Type__c</fullName>
        <label>Finanzierungsart</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Financing_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Has_Legal_Protection_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rechtsschutzversicherung vorhanden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anwalt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Legal</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mileage_On_Purchase__c</fullName>
        <label>Kilometerstand bei Kauf</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Purchase_Date__c</fullName>
        <label>Kaufdatum</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Purchase_Price__c</fullName>
        <label>Kaufpreis</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Aktenzeichen</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Date__c</fullName>
        <label>Zulassungsdatum</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand_Name__c</fullName>
        <label>Fahrzeugmarke</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fahrzeughersteller</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Fahrzeughersteller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Fahrzeughersteller)</relationshipLabel>
        <relationshipName>Opportunities_Fahrzeughersteller</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Identification_Number__c</fullName>
        <label>Fahrzeug Identifizierungsnummer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Assignment_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Share</fullName>
    </customValue>
    <customValue>
        <fullName>Direkt</fullName>
    </customValue>
    <customValue>
        <fullName>50%</fullName>
        <isActive>false</isActive>
        <label>50%</label>
    </customValue>
    <customValue>
        <fullName>RSV 20%</fullName>
        <isActive>false</isActive>
        <label>RSV 20%</label>
    </customValue>
    <masterLabel>Assignment Types</masterLabel>
</GlobalValueSet>

globalValueSets/Engine_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>OM640</fullName>
    </customValue>
    <customValue>
        <fullName>OM642</fullName>
    </customValue>
    <customValue>
        <fullName>OM 607</fullName>
    </customValue>
    <customValue>
        <fullName>OM651</fullName>
    </customValue>
    <customValue>
        <fullName>3.0</fullName>
    </customValue>
    <customValue>
        <fullName>4.2</fullName>
    </customValue>
    <customValue>
        <fullName>EA189</fullName>
    </customValue>
    <customValue>
        <fullName>EA288</fullName>
    </customValue>
    <customValue>
        <fullName>EA189 ohne Rückruf</fullName>
    </customValue>
    <customValue>
        <fullName>ENS</fullName>
    </customValue>
    <customValue>
        <fullName>EA897</fullName>
    </customValue>
    <customValue>
        <fullName>OM622</fullName>
    </customValue>
    <customValue>
        <fullName>Anderer Motortyp</fullName>
    </customValue>
    <customValue>
        <fullName>OM626</fullName>
    </customValue>
    <customValue>
        <fullName>OM 646.811</fullName>
    </customValue>
    <customValue>
        <fullName>OM 646.812</fullName>
    </customValue>
    <masterLabel>Engine Types</masterLabel>
</GlobalValueSet>

globalValueSets/Financing_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Leasing</fullName>
    </customValue>
    <customValue>
        <fullName>Finanzierung</fullName>
    </customValue>
    <customValue>
        <fullName>Eigenkapital</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstiges</fullName>
    </customValue>
    <masterLabel>Financing Types</masterLabel>
</GlobalValueSet>

classes/SetOppClaimPotential.cls
// Anfrage "Potential auslösen" Button
// Opportunity "Potential auslösen" Button
public class SetOppClaimPotential {
    private final Opportunity opp;

    public SetOppClaimPotential(ApexPages.StandardController stdCtl) {
        this.opp = [
            SELECT Id,
            RecordTypeId,
            Assignment_Type__c,
            Engine_Type__c,
            StageName,
            Legal__c,
            Backoffice__c,
            Vehicle_Brand__c,
            Vehicle_Brand_Name__c,
            Vehicle_Identification_Number__c,
            Registration_Date__c,
            Financing_Type__c,
            Purchase_Date__c,
            Purchase_Price__c,
            Mileage_On_Purchase__c,
            Current_Mileage__c,
            Expected_Mileage__c,
            Legal_Account__c,
            Reference__c,
            Has_Legal_Protection_Insurance__c
            FROM Opportunity
            WHERE ID = :stdCtl.getId()
        ];
    }

    public PageReference renderPage() {
        if ((Opportunities.isDieselSkandal(this.opp.RecordTypeId)) && (this.opp.Assignment_Type__c != 'RSV') && (this.opp.Engine_Type__c == 'EA189')) {
            String errorSubject = 'Fehler bei Übergabe des Prozesses.';
            String errorMessage = 'Anfragen ohne Rechtsschutzversicherung und Motortyp EA189 können nicht an Anwalt oder Finanzierungsprozess übergeben werden.';
            return Errors.page(errorSubject, errorMessage);
        }
        if (this.opp.Backoffice__c == null) {
            return Errors.page('Bitte tragen Sie einen Backoffice Mitarbeiter ein.');
        }
        this.opp.StageName = 'Claim';
        update this.opp;
        return new PageReference('/' + opp.ID);
    }
}