objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kunde</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Anfragen</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kanzlei</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Anfragen (Kanzlei)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_For_Loss__c</fullName>
        <label>Absagegrund</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reasons_For_Loss</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <defaultValue>"Online"</defaultValue>
        <label>Vertriebstyp</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sales_Types</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Reasons_For_Loss.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Nicht im Zeitraum</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde möchte nicht wegen Preis</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde will nicht</fullName>
    </customValue>
    <customValue>
        <fullName>Widerruf nicht angreifbar</fullName>
    </customValue>
    <customValue>
        <fullName>Potential zu gering</fullName>
    </customValue>
    <customValue>
        <fullName>Kein wirtschaftliches Potential</fullName>
    </customValue>
    <customValue>
        <fullName>Dokumente nicht geschickt</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde hat widerrufen</fullName>
    </customValue>
    <customValue>
        <fullName>Auto verkauft</fullName>
    </customValue>
    <customValue>
        <fullName>Fahrzeug nicht betroffen</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde nicht Käufer</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde nicht erreichbar</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde verstorben</fullName>
    </customValue>
    <customValue>
        <fullName>Kunde hat keine RSV</fullName>
    </customValue>
    <customValue>
        <fullName>Leasing Vertrag</fullName>
    </customValue>
    <customValue>
        <fullName>Keine Widerrufsbelehrung</fullName>
    </customValue>
    <customValue>
        <fullName>BMW EZ nach 01.06.2014</fullName>
    </customValue>
    <customValue>
        <fullName>Darlehensvertrag älter als 2 Jahre</fullName>
    </customValue>
    <customValue>
        <fullName>Nutzungsanteil zu gering</fullName>
    </customValue>
    <customValue>
        <fullName>Kapital zu gering</fullName>
    </customValue>
    <customValue>
        <fullName>Österreich/Schweiz kleiner Motor</fullName>
    </customValue>
    <customValue>
        <fullName>Umrüstung erfolgt</fullName>
    </customValue>
    <customValue>
        <fullName>Mfk nicht bestätigt</fullName>
    </customValue>
    <customValue>
        <fullName>Effektiver Jahreszins 0,00%</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstige Gründe</fullName>
    </customValue>
    <customValue>
        <fullName>Sonstige Gründe (ohne Mail)</fullName>
    </customValue>
    <customValue>
        <fullName>Aussortiert</fullName>
    </customValue>
    <customValue>
        <fullName>Absage wegen Kenntnis</fullName>
    </customValue>
    <masterLabel>Reasons For Loss</masterLabel>
</GlobalValueSet>

globalValueSets/Sales_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
        <default>true</default>
        <label>Online</label>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <masterLabel>Sales Types</masterLabel>
</GlobalValueSet>

classes/OpportunityEmailsTests.cls
@isTest
public class OpportunityEmailsTests {
    @isTest
    public static void hackCoverage() {
        OpportunityEmails.hackCoverage();
    }

    @isTest
    public static void testDGupdateOnHoldCllb() {
        TriggerConfiguration.allInactive = true;
        List<Opportunity> oo = new List<Opportunity>();
        Map<Id, Opportunity> oldOo = new Map<Id, Opportunity>();
        Account a = new Account(
            Name = 'CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB'
        );
        insert a;
        Contact con = new Contact(
            LastName = 'foo',
            Email = 'bar@baz.com'
        );
        insert con;
        Opportunity o = TestData.createOpportunity(a.Id, 'On Hold');
        o.Legal_Account__c = a.Id;
        o.Contact__c = con.ID;
		o.Sales_Type__c = 'Online';
        o.RecordTypeId = Opportunities.dieselskandalRecordType();
        insert o;
        oo.add(o);
        oldOo.put(o.Id, o);
		OpportunityEmails.autoSend(oo, oldOo, false);
    }

    @isTest
    public static void testDGupdateNewCllb() {
        TriggerConfiguration.allInactive = true;
        List<Opportunity> oo = new List<Opportunity>();
        Map<Id, Opportunity> oldOo = new Map<Id, Opportunity>();
        Account a = new Account(
            Name = 'CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB'
        );
        insert a;
        Contact con = new Contact(
            LastName = 'foo',
            Email = 'bar@baz.com'
        );
        insert con;
        Opportunity o = TestData.createOpportunity(a.Id, 'New');
        o.Legal_Account__c = a.Id;
        o.Contact__c = con.ID;
		o.Sales_Type__c = 'Online';
        o.RecordTypeId = Opportunities.dieselskandalRecordType();
        insert o;
        oo.add(o);
        oldOo.put(o.Id, o);
		OpportunityEmails.autoSend(oo, oldOo, false);
    }

    @isTest
    public static void testDGupdateLostCllb() {
        TriggerConfiguration.allInactive = true;
        List<Opportunity> oo = new List<Opportunity>();
        Map<Id, Opportunity> oldOo = new Map<Id, Opportunity>();
        Account a = new Account(
            Name = 'CLLB Rechtsanwälte Cocron, Liebl, Leitz, Braun, Kainz, Sittner Partnerschaft mbB'
        );
        insert a;
        Contact con = new Contact(
            LastName = 'foo',
            Email = 'bar@baz.com'
        );
        insert con;
        Opportunity o = TestData.createOpportunity(a.Id, 'Lost');
        o.Reason_For_Loss__c = 'Nicht im Zeitraum';
        o.Legal_Account__c = a.Id;
        o.Contact__c = con.ID;
		o.Sales_Type__c = 'Online';
        o.RecordTypeId = Opportunities.dieselskandalRecordType();
        insert o;
        oo.add(o);
        oldOo.put(o.Id, o);
		OpportunityEmails.autoSend(oo, oldOo, false);
    }
}