objects/SendMail__e.object
<CustomObject>
    <fields>
        <fullName>Is_Recipient_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is_Recipient_Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mail_Id__c</fullName>
        <label>Mail Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mail_Type__c</fullName>
        <description>The Type of Mail which should  be sent</description>
        <label>Mail_Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectId__c</fullName>
        <description>The related Object to which the mail refers</description>
        <label>ObjectId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Adress__c</fullName>
        <label>Recipient_Adress</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>SendMailEvent to decouple VH24MailManager</description>
    <label>SendMail</label>
    <pluralLabel>SendMails</pluralLabel>
</CustomObject>

classes/SendMailTriggerTest.cls
@isTest
public class SendMailTriggerTest {
   
    @isTest
    private static void testTriggerEvent(){  
        Test.startTest();
        SendMail__e mailEvent = new SendMail__e(
            Is_Recipient_Address__c = true,
			Mail_Type__c = 'MandateAsMail',
            ObjectId__c = '1234567',
         	Recipient_Adress__c = 'test@test.com',
            Mail_Id__c = 'testtest'
        );
 		Database.SaveResult result = EventBus.publish(mailEvent);
        Test.getEventBus().deliver();
    	List<EventBusSubscriber> subscribers = [SELECT Name, Position, Retries, LastError 
			FROM EventBusSubscriber WHERE Topic='SendMail__e' AND Type='ApexTrigger'];
       
        System.assertNotEquals(null, subscribers);
        Test.stopTest();
    }
}